"""Recipes 216-219: Caprese Salad, Lasagna, Salade Niçoise, Beef Stroganoff."""

RECIPES = []

# ── 216. Caprese Salad ────────────────────────────────────────────────
RECIPES.append({
    'id': 216, 'tipType': 'salad', 'pairingsType': 'italian',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Caprese_salad.jpg/330px-Caprese_salad.jpg',
    'name': {
        'ro':"Salată Caprese",'en':"Caprese Salad",'es':"Ensalada Caprese",'fr':"Salade Caprese",
        'de':"Caprese-Salat",'pt':"Salada Caprese",'ru':"Капрезе",'ar':"سلطة كابريزي",
        'zh':"卡普雷塞沙拉",'ja':"カプレーゼ",'hi':"कैप्रेज़ सलाद",'tr':"Caprese salatası",
        'it':"Insalata Caprese",'ko':"카프레제 샐러드",
    },
    'origin': {
        'ro':"Italia",'en':"Italy",'es':"Italia",'fr':"Italie",'de':"Italien",'pt':"Itália",
        'ru':"Италия",'ar':"إيطاليا",'zh':"意大利",'ja':"イタリア",'hi':"इटली",'tr':"İtalya",
        'it':"Italia",'ko':"이탈리아",
    },
    'category': {
        'ro':"Salate",'en':"Salad",'es':"Ensalada",'fr':"Salade",'de':"Salat",'pt':"Salada",
        'ru':"Салат",'ar':"سلطة",'zh':"沙拉",'ja':"サラダ",'hi':"सलाद",'tr':"Salata",
        'it':"Insalata",'ko':"샐러드",
    },
    'ingredients': {
        'ro':["3 roșii coapte, tăiate felii","250 g mozzarella di bufala","frunze de busuioc proaspăt","ulei de măsline extravirgin","sare grunjoasă","piper negru proaspăt măcinat","oțet balsamic (opțional)"],
        'en':["3 ripe tomatoes, sliced","250 g buffalo mozzarella","fresh basil leaves","extra-virgin olive oil","coarse salt","freshly ground black pepper","balsamic vinegar (optional)"],
        'es':["3 tomates maduros en rodajas","250 g de mozzarella de búfala","hojas de albahaca fresca","aceite de oliva virgen extra","sal gruesa","pimienta negra recién molida","vinagre balsámico (opcional)"],
        'fr':["3 tomates mûres en tranches","250 g de mozzarella di bufala","feuilles de basilic frais","huile d'olive extra vierge","sel grossier","poivre noir fraîchement moulu","vinaigre balsamique (facultatif)"],
        'de':["3 reife Tomaten, in Scheiben","250 g Büffelmozzarella","frische Basilikumblätter","natives Olivenöl extra","grobes Salz","frisch gemahlener schwarzer Pfeffer","Balsamico-Essig (optional)"],
        'pt':["3 tomates maduros às rodelas","250 g de mozzarella de búfala","folhas de manjericão fresco","azeite virgem extra","sal grosso","pimenta preta moída na hora","vinagre balsâmico (opcional)"],
        'ru':["3 спелых помидора, кружочками","250 г моцареллы из буйволиного молока","свежий базилик","оливковое масло экстра вирджин","крупная соль","свежемолотый чёрный перец","бальзамический уксус (по желанию)"],
        'ar':["3 حبات طماطم ناضجة بشرائح","250 غ موزاريلا الجاموس","أوراق ريحان طازج","زيت زيتون بكر ممتاز","ملح خشن","فلفل أسود مطحون طازج","خل بلسمي (اختياري)"],
        'zh':["熟番茄3个，切片","水牛奶马苏里拉250克","新鲜罗勒叶","特级初榨橄榄油","粗盐","现磨黑胡椒","巴萨米克醋（可选）"],
        'ja':["完熟トマト3個（薄切り）","水牛モッツァレラ250g","フレッシュバジルの葉","エクストラバージンオリーブオイル","粗塩","挽きたて黒こしょう","バルサミコ酢（お好みで）"],
        'hi':["3 पके टमाटर, टुकड़ों में","250 ग्राम बफ़ेलो मोज़रेला","ताज़ी तुलसी की पत्तियाँ","एक्स्ट्रा-वर्जिन ज़ैतून तेल","मोटा नमक","ताज़ी पिसी काली मिर्च","बाल्समिक सिरका (वैकल्पिक)"],
        'tr':["3 olgun domates, dilim","250 g manda mozzarella","taze fesleğen yaprakları","sızma zeytinyağı","iri tane tuz","taze çekilmiş karabiber","balsamik sirke (isteğe bağlı)"],
        'it':["3 pomodori maturi a fette","250 g di mozzarella di bufala","foglie di basilico fresco","olio d'oliva extravergine","sale grosso","pepe nero macinato fresco","aceto balsamico (facoltativo)"],
        'ko':["잘 익은 토마토 3개, 슬라이스","버팔로 모차렐라 250g","신선한 바질 잎","엑스트라 버진 올리브 오일","굵은 소금","갓 갈은 흑후추","발사믹 식초(선택)"],
    },
    'howIsMade': {
        'ro':"Alternează pe o farfurie felii de roșie cu felii de mozzarella, intercalând frunze de busuioc. Stropește cu ulei de măsline, presară sare și piper. Servește la temperatura camerei, niciodată rece din frigider — mozzarella își pierde cremositatea.",
        'en':"On a plate, alternate slices of tomato and mozzarella, tucking basil leaves between. Drizzle with olive oil, season with salt and pepper. Serve at room temperature — straight from the fridge the mozzarella loses its creaminess.",
        'es':"En un plato, alterna rodajas de tomate y mozzarella intercalando hojas de albahaca. Riega con aceite, sazona con sal y pimienta. Sirve a temperatura ambiente — fría pierde su cremosidad.",
        'fr':"Sur une assiette, alternez tranches de tomate et de mozzarella en intercalant des feuilles de basilic. Arrosez d'huile d'olive, salez et poivrez. Servez à température ambiante — sortie du frigo, la mozzarella perd son crémeux.",
        'de':"Auf einem Teller Tomaten- und Mozzarellascheiben abwechselnd auflegen und Basilikumblätter dazwischen stecken. Mit Olivenöl beträufeln, mit Salz und Pfeffer würzen. Bei Zimmertemperatur servieren — kalt verliert der Mozzarella seine Cremigkeit.",
        'pt':"Num prato, alterne fatias de tomate e mozzarella intercalando folhas de manjericão. Regue com azeite, tempere com sal e pimenta. Sirva à temperatura ambiente — fria, a mozzarella perde a cremosidade.",
        'ru':"На тарелке чередуйте ломтики помидора и моцареллы, прокладывая листьями базилика. Сбрызните оливковым маслом, посолите и поперчите. Подавайте при комнатной температуре — холодная моцарелла теряет кремовость.",
        'ar':"رصّي على طبق شرائح الطماطم والموزاريلا بالتناوب وضعي بينها أوراق الريحان. اسكبي زيت الزيتون، تبّلي بالملح والفلفل. قدّمي بحرارة الغرفة — من الثلاجة تفقد الموزاريلا قوامها الكريمي.",
        'zh':"在盘中将番茄片和马苏里拉片交错摆放，中间夹入罗勒叶。淋上橄榄油，撒盐和胡椒。室温享用——冰箱拿出马苏里拉会失去奶香质感。",
        'ja':"皿にトマトとモッツァレラのスライスを交互に並べ、間にバジルの葉を挟む。オリーブオイルを回しかけ、塩こしょうで味付け。室温で食べる — 冷蔵庫から出したてではモッツァレラのクリーミーさが消える。",
        'hi':"प्लेट पर टमाटर और मोज़रेला के टुकड़े बारी-बारी रखें, बीच में तुलसी की पत्तियाँ डालें। जैतून तेल छिड़कें, नमक और काली मिर्च डालें। कमरे के तापमान पर परोसें — फ्रिज से सीधा निकालने पर मोज़रेला अपनी क्रीमी बनावट खो देता है।",
        'tr':"Tabağa domates ve mozzarella dilimlerini sırayla dizin, aralara fesleğen yaprağı koyun. Zeytinyağı gezdirin, tuz ve karabiber serpin. Oda sıcaklığında servis edin — buzdolabından çıkar çıkmaz mozzarella kremamsı dokusunu kaybeder.",
        'it':"Su un piatto, alterna fette di pomodoro e mozzarella infilando foglie di basilico. Irrora con olio d'oliva, sala e pepa. Servi a temperatura ambiente — fredda di frigo, la mozzarella perde la cremosità.",
        'ko':"접시에 토마토와 모차렐라 슬라이스를 번갈아 놓고 사이사이 바질 잎을 끼웁니다. 올리브 오일을 두르고 소금과 후추로 간합니다. 냉장고에서 막 꺼낸 차가운 상태가 아니라 실온에서 제공해야 모차렐라의 크리미함이 살아납니다.",
    },
    'originText': {
        'ro':"Insalata Caprese poartă numele insulei Capri, unde a fost creată în anii 1920 ca simbol al tricolorului italian — roșu, alb și verde — din roșii dulci, mozzarella di bufala și busuioc proaspăt.",
        'en':"Insalata Caprese takes its name from the island of Capri, where it was created in the 1920s as a tribute to the Italian flag — red, white and green — from sweet tomatoes, buffalo mozzarella and fresh basil.",
        'es':"La insalata Caprese debe su nombre a la isla de Capri, donde fue creada en los años veinte como homenaje a la bandera italiana — rojo, blanco y verde — con tomates dulces, mozzarella de búfala y albahaca fresca.",
        'fr':"L'insalata Caprese tient son nom de l'île de Capri, où elle a été créée dans les années 1920 en hommage au drapeau italien — rouge, blanc, vert — avec des tomates sucrées, de la mozzarella di bufala et du basilic frais.",
        'de':"Die Insalata Caprese verdankt ihren Namen der Insel Capri, wo sie in den 1920er Jahren als Hommage an die italienische Flagge entstand — rot, weiß, grün — aus süßen Tomaten, Büffelmozzarella und frischem Basilikum.",
        'pt':"A insalata Caprese deve o nome à ilha de Capri, onde foi criada nos anos 20 como homenagem à bandeira italiana — vermelho, branco e verde — com tomates doces, mozzarella de búfala e manjericão fresco.",
        'ru':"Капрезе названа в честь острова Капри, где появилась в 1920-х как дань итальянскому флагу — красный, белый, зелёный — из сладких помидоров, моцареллы из буйволиного молока и свежего базилика.",
        'ar':"سلطة كابريزي تأخذ اسمها من جزيرة كابري الإيطالية، حيث وُلدت في عشرينات القرن الماضي تكريماً لألوان العلم الإيطالي — الأحمر والأبيض والأخضر — من طماطم حلوة وموزاريلا الجاموس وريحان طازج.",
        'zh':"Insalata Caprese 得名于卡普里岛，1920年代诞生于此，以红白绿三色致敬意大利国旗——成熟番茄、水牛奶马苏里拉与新鲜罗勒。",
        'ja':"インサラータ・カプレーゼはカプリ島から名前を取った料理で、1920年代にイタリア国旗の赤・白・緑に敬意を表して生まれた — 甘いトマト、水牛モッツァレラ、フレッシュバジル。",
        'hi':"इन्सलाता कैप्रेज़े का नाम कैप्री द्वीप से आता है — 1920 के दशक में इटली के झंडे के रंगों (लाल, सफ़ेद, हरा) के सम्मान में बनाई गई थी, मीठे टमाटर, बफ़ेलो मोज़रेला और ताज़ी तुलसी से।",
        'tr':"Insalata Caprese adını Capri adasından alır; 1920'lerde İtalyan bayrağının kırmızı-beyaz-yeşil renklerine saygı niyetiyle tatlı domates, manda mozzarellası ve taze fesleğenle yaratıldı.",
        'it':"L'insalata Caprese prende il nome dall'isola di Capri, dove nacque negli anni Venti come omaggio alla bandiera italiana — rosso, bianco e verde — con pomodori dolci, mozzarella di bufala e basilico fresco.",
        'ko':"인살라타 카프레제는 1920년대 카프리섬에서 이탈리아 국기의 빨강·하양·초록을 기리며 탄생했다 — 달콤한 토마토, 버팔로 모차렐라, 신선한 바질로 만든다.",
    },
})

# ── 217. Lasagna ──────────────────────────────────────────────────────
RECIPES.append({
    'id': 217, 'tipType': 'pasta', 'pairingsType': 'italian',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Lasagne_-_stonesoup.jpg/330px-Lasagne_-_stonesoup.jpg',
    'name': {
        'ro':"Lasagna",'en':"Lasagna",'es':"Lasaña",'fr':"Lasagnes",'de':"Lasagne",'pt':"Lasanha",
        'ru':"Лазанья",'ar':"لازانيا",'zh':"千层面",'ja':"ラザニア",'hi':"लज़ानिए",'tr':"Lazanya",
        'it':"Lasagne",'ko':"라자냐",
    },
    'origin': {
        'ro':"Italia",'en':"Italy",'es':"Italia",'fr':"Italie",'de':"Italien",'pt':"Itália",
        'ru':"Италия",'ar':"إيطاليا",'zh':"意大利",'ja':"イタリア",'hi':"इटली",'tr':"İtalya",
        'it':"Italia",'ko':"이탈리아",
    },
    'category': {
        'ro':"Paste",'en':"Pasta",'es':"Pasta",'fr':"Pâtes",'de':"Pasta",'pt':"Massa",
        'ru':"Паста",'ar':"معكرونة",'zh':"意面",'ja':"パスタ",'hi':"पास्ता",'tr':"Makarna",
        'it':"Pasta",'ko':"파스타",
    },
    'ingredients': {
        'ro':["300 g foi de lasagna","500 g vită tocată","1 ceapă","2 căței usturoi","400 g sos de roșii","300 ml sos béchamel","150 g Parmigiano ras","150 g mozzarella","sare, piper, ulei de măsline"],
        'en':["300 g lasagna sheets","500 g beef mince","1 onion","2 garlic cloves","400 g tomato sauce","300 ml béchamel sauce","150 g Parmigiano grated","150 g mozzarella","salt, pepper, olive oil"],
        'es':["300 g de láminas de lasaña","500 g de ternera picada","1 cebolla","2 dientes de ajo","400 g de salsa de tomate","300 ml de bechamel","150 g de Parmigiano rallado","150 g de mozzarella","sal, pimienta, aceite de oliva"],
        'fr':["300 g de feuilles de lasagnes","500 g de bœuf haché","1 oignon","2 gousses d'ail","400 g de sauce tomate","300 ml de béchamel","150 g de Parmigiano râpé","150 g de mozzarella","sel, poivre, huile d'olive"],
        'de':["300 g Lasagneblätter","500 g Rinderhack","1 Zwiebel","2 Knoblauchzehen","400 g Tomatensauce","300 ml Béchamel","150 g Parmigiano gerieben","150 g Mozzarella","Salz, Pfeffer, Olivenöl"],
        'pt':["300 g de placas de lasanha","500 g de carne picada","1 cebola","2 dentes de alho","400 g de molho de tomate","300 ml de béchamel","150 g de Parmigiano ralado","150 g de mozzarella","sal, pimenta, azeite"],
        'ru':["300 г листов лазаньи","500 г говяжьего фарша","1 луковица","2 зубчика чеснока","400 г томатного соуса","300 мл соуса бешамель","150 г тёртого Пармиджано","150 г моцареллы","соль, перец, оливковое масло"],
        'ar':["300 غ ألواح لازانيا","500 غ لحم بقري مفروم","1 بصلة","2 فصوص ثوم","400 غ صلصة طماطم","300 مل صلصة بشاميل","150 غ بارميجانو مبشور","150 غ موزاريلا","ملح، فلفل، زيت زيتون"],
        'zh':["千层面皮300克","牛肉末500克","洋葱1个","大蒜2瓣","番茄酱400克","贝夏梅酱300毫升","Parmigiano磨碎150克","马苏里拉150克","盐、胡椒、橄榄油"],
        'ja':["ラザニアシート300g","牛ひき肉500g","玉ねぎ1個","にんにく2片","トマトソース400g","ベシャメルソース300ml","パルミジャーノおろし150g","モッツァレラ150g","塩、こしょう、オリーブオイル"],
        'hi':["300 ग्राम लज़ानिए शीट्स","500 ग्राम बीफ़ कीमा","1 प्याज़","2 लहसुन की कलियाँ","400 ग्राम टमाटर सॉस","300 मिली बेशामेल सॉस","150 ग्राम कद्दूकस Parmigiano","150 ग्राम मोज़रेला","नमक, काली मिर्च, ज़ैतून तेल"],
        'tr':["300 g lazanya yaprağı","500 g dana kıyma","1 soğan","2 diş sarımsak","400 g domates sosu","300 ml beşamel sos","150 g rendelenmiş Parmigiano","150 g mozzarella","tuz, karabiber, zeytinyağı"],
        'it':["300 g di lasagne secche","500 g di macinato di manzo","1 cipolla","2 spicchi d'aglio","400 g di salsa di pomodoro","300 ml di besciamella","150 g di Parmigiano grattugiato","150 g di mozzarella","sale, pepe, olio d'oliva"],
        'ko':["라자냐 시트 300g","다진 소고기 500g","양파 1개","마늘 2쪽","토마토 소스 400g","베샤멜 소스 300ml","갈아 놓은 파르미지아노 150g","모차렐라 150g","소금, 후추, 올리브유"],
    },
    'howIsMade': {
        'ro':"Călește ceapa și usturoiul, adaugă carnea tocată și rumenește bine. Toarnă sosul de roșii, condimentează și fierbe 30 min. Într-un vas, alternează straturi: sos de carne, foi de lasagna, béchamel, mozzarella, Parmigiano. Repetă terminând cu un strat gros de béchamel și Parmigiano. Coace la 180°C 35 min până se rumenește.",
        'en':"Sauté onion and garlic, add the mince and brown well. Pour in tomato sauce, season and simmer 30 minutes. In a baking dish, layer: meat sauce, lasagna sheets, béchamel, mozzarella, Parmigiano. Repeat, finishing with a thick layer of béchamel and Parmigiano. Bake at 180°C for 35 minutes until golden.",
        'es':"Sofríe cebolla y ajo, añade la carne y dora bien. Vierte el tomate, salpimenta y cuece 30 min. En una fuente, intercala capas: salsa de carne, láminas, bechamel, mozzarella, Parmigiano. Repite acabando con bechamel y Parmigiano. Hornea a 180°C 35 min hasta dorar.",
        'fr':"Faites suer oignon et ail, ajoutez la viande et faites-la bien dorer. Versez la sauce tomate, assaisonnez et laissez mijoter 30 min. Dans un plat, alternez : sauce viande, feuilles, béchamel, mozzarella, Parmigiano. Répétez en terminant par béchamel et Parmigiano. Enfournez à 180°C 35 min jusqu'à dorure.",
        'de':"Zwiebel und Knoblauch andünsten, das Hackfleisch zugeben und scharf anbraten. Tomatensauce angießen, würzen und 30 Min. köcheln. In einer Auflaufform schichten: Fleischsauce, Lasagneblätter, Béchamel, Mozzarella, Parmigiano. Wiederholen, mit Béchamel und Parmigiano abschließen. Bei 180°C 35 Min. goldbraun backen.",
        'pt':"Refogue cebola e alho, junte a carne e doure bem. Verta o molho de tomate, tempere e cozinhe 30 min. Numa forma, alterne camadas: molho de carne, placas, béchamel, mozzarella, Parmigiano. Repita terminando com béchamel e Parmigiano. Leve ao forno a 180°C por 35 min até dourar.",
        'ru':"Спассеруйте лук и чеснок, добавьте фарш и хорошо подрумяньте. Влейте томатный соус, приправьте и тушите 30 мин. В форме чередуйте слои: мясной соус, листы лазаньи, бешамель, моцарелла, Пармиджано. Повторяйте, заканчивая толстым слоем бешамеля и Пармиджано. Запекайте при 180°C 35 мин.",
        'ar':"اقلِ البصل والثوم، أضف اللحم وحمّره جيداً. اسكب صلصة الطماطم، تبّل واطبخ 30 دقيقة. في صينية، رتّب طبقات: صلصة لحم، ألواح لازانيا، بشاميل، موزاريلا، بارميجانو. كرّر منتهياً بطبقة سميكة من البشاميل والبارميجانو. اخبز على 180°م لمدة 35 دقيقة حتى يحمرّ.",
        'zh':"洋葱大蒜炒香，加入牛肉末炒至上色。倒入番茄酱，调味后炖30分钟。烤盘中铺层：肉酱、面皮、贝夏梅、马苏里拉、Parmigiano。重复至最后一层为贝夏梅与Parmigiano。180°C烤35分钟至表面金黄。",
        'ja':"玉ねぎとにんにくを炒め、ひき肉を加えてしっかり焼く。トマトソースを注ぎ、味付けして30分煮る。耐熱皿に重ねる：肉ソース、ラザニアシート、ベシャメル、モッツァレラ、パルミジャーノ。繰り返し、最上層はベシャメルとパルミジャーノで厚めに。180℃で35分、こんがり焼く。",
        'hi':"प्याज़ और लहसुन भूनें, कीमा डालकर अच्छा सुनहरा करें। टमाटर सॉस डालें, मसाला डालकर 30 मिनट पकाएँ। बेकिंग डिश में परतें लगाएँ: मांस सॉस, शीट्स, बेशामेल, मोज़रेला, Parmigiano। दोहराएँ, ऊपर मोटी बेशामेल और Parmigiano की परत रखें। 180°C पर 35 मिनट सुनहरा होने तक बेक करें।",
        'tr':"Soğan ve sarımsağı kavurun, kıymayı ekleyip iyice kızartın. Domates sosunu dökün, baharatlayıp 30 dakika pişirin. Fırın kabına katmanlayın: et sosu, lazanya yaprakları, beşamel, mozzarella, Parmigiano. Tekrarlayın, en üst kalın beşamel ve Parmigiano. 180°C'de 35 dakika kızarana dek pişirin.",
        'it':"Soffriggi cipolla e aglio, aggiungi la carne e rosolala bene. Versa la salsa di pomodoro, condisci e cuoci 30 min. In una pirofila alterna strati: ragù, lasagne, besciamella, mozzarella, Parmigiano. Ripeti finendo con uno strato spesso di besciamella e Parmigiano. Inforna a 180°C per 35 min fino a doratura.",
        'ko':"양파와 마늘을 볶고 다진 고기를 넣어 잘 익힙니다. 토마토 소스를 붓고 간을 한 뒤 30분 끓입니다. 베이킹 그릇에 층층이 쌓습니다: 미트 소스, 라자냐 시트, 베샤멜, 모차렐라, 파르미지아노. 반복하고 맨 위는 베샤멜과 파르미지아노를 두껍게. 180°C에서 35분 노릇하게 굽습니다.",
    },
    'originText': {
        'ro':"Lasagna este pasta italiană prin excelență — straturi de foi cu sos de carne, béchamel și brânză, coapte până se aurește crusta. Versiunea modernă se hrănește din clasicul bolognez, dar a devenit un fel iconic peste tot în lume.",
        'en':"Lasagna is Italian pasta at its most generous — layers of sheets with meat sauce, béchamel and cheese, baked until the top is golden. The modern version draws from the Bolognese classic but has become an iconic dish worldwide.",
        'es':"La lasaña es la pasta italiana en su forma más generosa — capas de láminas con salsa de carne, bechamel y queso, horneadas hasta que la corteza dora. La versión moderna parte del clásico boloñés pero es un plato icónico en todo el mundo.",
        'fr':"Les lasagnes sont la pâte italienne dans toute sa générosité — des couches de feuilles, sauce viande, béchamel et fromage, cuites jusqu'à ce que le dessus dore. La version moderne s'inspire du classique bolognais mais est devenue un plat iconique partout dans le monde.",
        'de':"Lasagne ist die italienische Pasta in ihrer großzügigsten Form — Schichten aus Teig, Fleischsauce, Béchamel und Käse, gebacken bis die Oberfläche goldbraun ist. Die moderne Version geht auf den Bologneser Klassiker zurück, ist aber weltweit zum Kultgericht geworden.",
        'pt':"A lasanha é a massa italiana na sua forma mais generosa — camadas de placas com molho de carne, béchamel e queijo, levadas ao forno até dourar. A versão moderna parte do clássico bolonhês mas tornou-se um prato icónico no mundo inteiro.",
        'ru':"Лазанья — это итальянская паста в самом щедром её виде: слои теста с мясным соусом, бешамелем и сыром, запечённые до золотистой корочки. Современный вариант идёт от болонской классики, но стал кулинарной иконой по всему миру.",
        'ar':"اللازانيا هي المعكرونة الإيطالية في أكثر صورها سخاءً — طبقات من العجين مع صلصة اللحم والبشاميل والجبن، تُخبز حتى تصبح القشرة ذهبية. النسخة الحديثة تستلهم من الكلاسيكية البولونية لكنها أصبحت طبقاً أيقونياً حول العالم.",
        'zh':"千层面是意大利意面最丰盛的形态——面皮、肉酱、贝夏梅与奶酪层层叠加，烤至表面金黄。现代版本源自波隆纳经典，如今已是全世界的标志菜肴。",
        'ja':"ラザニアはイタリアパスタの中で最も豊かな一品 — シートにミートソース、ベシャメル、チーズを重ね、表面が黄金色になるまで焼く。現代版はボロネーゼの古典から派生し、世界中で象徴的な料理になった。",
        'hi':"लज़ानिए इटली के पास्ता का सबसे उदार रूप है — शीट्स की परतें, मांस सॉस, बेशामेल और चीज़, ऊपर सुनहरी परत बनने तक बेक की हुई। आधुनिक रूप बोलोनीज़ क्लासिक से प्रेरित है पर अब दुनिया भर में एक प्रतीक व्यंजन बन चुका है।",
        'tr':"Lazanya İtalyan makarnasının en cömert hali — yapraklar, et sosu, beşamel ve peynir katmanlar halinde dizilip üstü altın renkli olana kadar pişirilir. Modern hali Bolonez klasiğinden geliyor ama dünyada simgesel bir yemek oldu.",
        'it':"La lasagna è la pasta italiana nella sua forma più generosa — strati di sfoglie con ragù, besciamella e formaggio, cotte fino a doratura. La versione moderna nasce dal classico bolognese ma è diventata un piatto iconico in tutto il mondo.",
        'ko':"라자냐는 가장 풍성한 형태의 이탈리안 파스타다 — 시트 사이사이에 미트 소스, 베샤멜, 치즈를 겹겹이 쌓아 표면이 황금빛으로 익을 때까지 굽는다. 현대판은 볼로녜제 클래식에서 비롯됐지만 이제 전 세계의 상징 요리가 됐다.",
    },
})

# ── 218. Salade Niçoise ──────────────────────────────────────────────
RECIPES.append({
    'id': 218, 'tipType': 'salad', 'pairingsType': 'salad',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sala%C3%B0_ni%C3%A7oise_-_Mat_pr%C3%AD%C3%B0i.jpg/330px-Sala%C3%B0_ni%C3%A7oise_-_Mat_pr%C3%AD%C3%B0i.jpg',
    'name': {
        'ro':"Salată Niçoise",'en':"Salade Niçoise",'es':"Ensalada nizarda",'fr':"Salade niçoise",
        'de':"Salade niçoise",'pt':"Salada nicense",'ru':"Салат нисуаз",'ar':"سلطة نيسواز",
        'zh':"尼斯沙拉",'ja':"ニース風サラダ",'hi':"निसवाज़ सलाद",'tr':"Niçoise salatası",
        'it':"Insalata nizzarda",'ko':"니스 샐러드",
    },
    'origin': {
        'ro':"Franța",'en':"France",'es':"Francia",'fr':"France",'de':"Frankreich",'pt':"França",
        'ru':"Франция",'ar':"فرنسا",'zh':"法国",'ja':"フランス",'hi':"फ़्रांस",'tr':"Fransa",
        'it':"Francia",'ko':"프랑스",
    },
    'category': {
        'ro':"Salate",'en':"Salad",'es':"Ensalada",'fr':"Salade",'de':"Salat",'pt':"Salada",
        'ru':"Салат",'ar':"سلطة",'zh':"沙拉",'ja':"サラダ",'hi':"सलाद",'tr':"Salata",
        'it':"Insalata",'ko':"샐러드",
    },
    'ingredients': {
        'ro':["200 g ton la conservă în ulei","4 ouă fierte tari","200 g fasole verde","300 g cartofi noi","12 măsline Niçoise","4 file de hamsii","2 roșii","2 linguri ulei de măsline","oțet de vin, sare, piper"],
        'en':["200 g tinned tuna in oil","4 hard-boiled eggs","200 g green beans","300 g new potatoes","12 Niçoise olives","4 anchovy fillets","2 tomatoes","2 tbsp olive oil","wine vinegar, salt, pepper"],
        'es':["200 g de atún en aceite","4 huevos duros","200 g de judías verdes","300 g de patatas nuevas","12 aceitunas niçoise","4 filetes de anchoa","2 tomates","2 cdas de aceite de oliva","vinagre de vino, sal, pimienta"],
        'fr':["200 g de thon à l'huile","4 œufs durs","200 g d'haricots verts","300 g de pommes de terre nouvelles","12 olives niçoises","4 filets d'anchois","2 tomates","2 c. à s. d'huile d'olive","vinaigre de vin, sel, poivre"],
        'de':["200 g Thunfisch aus der Dose in Öl","4 hart gekochte Eier","200 g grüne Bohnen","300 g neue Kartoffeln","12 Niçoise-Oliven","4 Sardellenfilets","2 Tomaten","2 EL Olivenöl","Weinessig, Salz, Pfeffer"],
        'pt':["200 g de atum em óleo","4 ovos cozidos","200 g de feijão verde","300 g de batatas novas","12 azeitonas niçoise","4 filetes de anchova","2 tomates","2 colheres de sopa de azeite","vinagre de vinho, sal, pimenta"],
        'ru':["200 г консервированного тунца в масле","4 яйца вкрутую","200 г зелёной фасоли","300 г молодого картофеля","12 маслин Niçoise","4 филе анчоусов","2 помидора","2 ст. л. оливкового масла","винный уксус, соль, перец"],
        'ar':["200 غ تونة معلبة بالزيت","4 بيضات مسلوقة","200 غ فاصوليا خضراء","300 غ بطاطا صغيرة","12 زيتونة نيسوازية","4 فيليه أنشوجة","2 طماطم","2 ملعقة كبيرة زيت زيتون","خل نبيذ، ملح، فلفل"],
        'zh':["油浸金枪鱼罐头200克","水煮蛋4个","青豆200克","小土豆300克","尼斯橄榄12颗","凤尾鱼柳4条","番茄2个","橄榄油2汤匙","酒醋、盐、胡椒"],
        'ja':["オイル漬けツナ缶200g","固ゆで卵4個","インゲン200g","新じゃが300g","ニース風オリーブ12個","アンチョビフィレ4枚","トマト2個","オリーブオイル大さじ2","ワインビネガー、塩、こしょう"],
        'hi':["200 ग्राम तेल में डिब्बाबंद टूना","4 कड़े उबले अंडे","200 ग्राम हरी फलियाँ","300 ग्राम नए आलू","12 निसवाज़ ज़ैतून","4 एंकोवी फ़िले","2 टमाटर","2 बड़े चम्मच ज़ैतून तेल","वाइन सिरका, नमक, काली मिर्च"],
        'tr':["200 g yağda konserve ton balığı","4 haşlanmış yumurta","200 g taze fasulye","300 g yeni patates","12 Niçoise zeytini","4 hamsi fileto","2 domates","2 yk zeytinyağı","şarap sirkesi, tuz, karabiber"],
        'it':["200 g di tonno sott'olio","4 uova sode","200 g di fagiolini","300 g di patate novelle","12 olive niçoise","4 filetti di acciuga","2 pomodori","2 cucchiai di olio d'oliva","aceto di vino, sale, pepe"],
        'ko':["오일 통조림 참치 200g","완숙 달걀 4개","깍지콩 200g","햇감자 300g","니스 올리브 12개","안초비 필레 4장","토마토 2개","올리브 오일 2큰술","와인 식초, 소금, 후추"],
    },
    'howIsMade': {
        'ro':"Fierbe ouăle, cartofii și fasolea separat. Răcește, taie cartofii cuburi și ouăle felii. Aranjează pe o farfurie mare: salată verde, cartofi, fasole, roșii, ouă, ton și măsline. Așază hamsiile deasupra. Stropește cu ulei și oțet, sare și piper. Servește răcoroasă, nu rece.",
        'en':"Boil eggs, potatoes and beans separately. Cool, cube potatoes, slice eggs. Arrange on a wide plate: greens, potatoes, beans, tomatoes, eggs, tuna and olives. Lay anchovies across the top. Dress with olive oil and vinegar, season. Serve cool, not cold.",
        'es':"Cuece huevos, patatas y judías por separado. Enfría, corta patatas en cubos y huevos en rodajas. Compón en una fuente: verdes, patatas, judías, tomates, huevos, atún y aceitunas. Coloca anchoas encima. Aliña con aceite y vinagre, salpimenta. Sirve fresco, no frío.",
        'fr':"Cuisez œufs, pommes de terre et haricots séparément. Refroidissez, coupez les pommes de terre en cubes et les œufs en rondelles. Disposez dans un grand plat : verdure, pommes de terre, haricots, tomates, œufs, thon et olives. Placez les anchois dessus. Assaisonnez d'huile et vinaigre, sel et poivre. Servez frais, pas froid.",
        'de':"Eier, Kartoffeln und Bohnen getrennt kochen. Abkühlen, Kartoffeln würfeln, Eier scheiben. Auf einer Platte anrichten: Salat, Kartoffeln, Bohnen, Tomaten, Eier, Thunfisch und Oliven. Sardellen darüberlegen. Mit Olivenöl und Essig anmachen, würzen. Kühl, nicht eiskalt servieren.",
        'pt':"Coza ovos, batatas e feijão separadamente. Arrefeça, corte as batatas em cubos e os ovos em rodelas. Disponha numa travessa: verdes, batatas, feijão, tomates, ovos, atum e azeitonas. Coloque anchovas por cima. Tempere com azeite e vinagre, sal e pimenta. Sirva fresco, não frio.",
        'ru':"Сварите яйца, картофель и фасоль отдельно. Остудите, картофель нарежьте кубиками, яйца — кружочками. На большом блюде разложите: зелень, картофель, фасоль, помидоры, яйца, тунец и маслины. Сверху положите анчоусы. Заправьте маслом и уксусом, посолите. Подавайте прохладным, не холодным.",
        'ar':"اسلقي البيض والبطاطا والفاصوليا كلاً على حدة. بردي، قطّعي البطاطا مكعبات والبيض شرائح. رتّبي على طبق واسع: خضار، بطاطا، فاصوليا، طماطم، بيض، تونة وزيتون. ضعي الأنشوجة فوقها. تبّلي بزيت الزيتون والخل والملح والفلفل. قدّمي معتدلة البرودة، لا باردة.",
        'zh':"鸡蛋、土豆、青豆分别煮熟。晾凉后土豆切丁、鸡蛋切片。大盘中铺：生菜、土豆、青豆、番茄、鸡蛋、金枪鱼、橄榄。凤尾鱼条摆在最上面。淋橄榄油和酒醋，撒盐胡椒。微凉时享用，不要太冷。",
        'ja':"卵、じゃがいも、いんげんを別々に茹でる。冷ましてじゃがいもは角切り、卵はスライスに。大きな皿に盛る：葉野菜、じゃがいも、いんげん、トマト、卵、ツナ、オリーブ。アンチョビをその上に並べる。オリーブオイルとワインビネガーで和え、塩こしょう。冷たすぎず、ひんやり程度で出す。",
        'hi':"अंडे, आलू और फलियाँ अलग-अलग उबालें। ठंडा करके आलू टुकड़ों में, अंडे स्लाइस में काटें। चौड़ी प्लेट में सजाएँ: हरी सब्ज़ियाँ, आलू, फलियाँ, टमाटर, अंडे, टूना और ज़ैतून। ऊपर एंकोवी रखें। ज़ैतून तेल और सिरका, नमक काली मिर्च डालें। ठंडा नहीं, ठंडे-गरम तापमान पर परोसें।",
        'tr':"Yumurta, patates ve fasulyeyi ayrı ayrı haşlayın. Soğutun, patatesi küp, yumurtayı dilim doğrayın. Geniş tabağa dizin: yeşillik, patates, fasulye, domates, yumurta, ton ve zeytin. En üste hamsi yerleştirin. Zeytinyağı ve sirke ile sosla, tuz karabiber. Buz gibi değil, serin servis edin.",
        'it':"Lessa uova, patate e fagiolini separatamente. Raffredda, taglia le patate a cubetti e le uova a fette. Disponi su un piatto largo: verdure, patate, fagiolini, pomodori, uova, tonno e olive. Sistema le acciughe sopra. Condisci con olio e aceto, sale e pepe. Servi fresca, non fredda.",
        'ko':"달걀, 감자, 깍지콩을 각각 따로 삶습니다. 식힌 뒤 감자는 깍둑썰기, 달걀은 슬라이스. 넓은 접시에 놓습니다: 그린, 감자, 콩, 토마토, 달걀, 참치, 올리브. 그 위에 안초비를 올립니다. 올리브 오일과 와인 식초로 드레싱하고 소금 후추로 간합니다. 차게가 아니라 시원하게 냅니다.",
    },
    'originText': {
        'ro':"Salata niçoise vine din Nisa, pe Riviera franceză — o farfurie de vară cu legume crocante, ton, ouă, măsline negre și hamsii, stropită cu ulei de măsline din Provența. Niciodată cu cartofi fierți la dispute puriste, dar adesea cu ei în versiunea modernă.",
        'en':"Salade niçoise comes from Nice on the French Riviera — a summer plate of crisp vegetables, tuna, eggs, black olives and anchovies, drizzled with Provençal olive oil. Purists fight over the potato question; modern versions usually include them.",
        'es':"La ensalada nizarda viene de Niza, en la Riviera francesa — un plato de verano con verduras crujientes, atún, huevos, aceitunas negras y anchoas, regado con aceite de oliva provenzal. Los puristas discuten lo de las patatas; las versiones modernas suelen incluirlas.",
        'fr':"La salade niçoise vient de Nice, sur la Riviera française — une assiette d'été de légumes croquants, thon, œufs, olives noires et anchois, arrosée d'huile d'olive de Provence. Les puristes débattent la question des pommes de terre ; les versions modernes les incluent souvent.",
        'de':"Die Salade niçoise stammt aus Nizza an der französischen Riviera — ein sommerlicher Teller aus knackigem Gemüse, Thunfisch, Eiern, schwarzen Oliven und Sardellen, beträufelt mit provenzalischem Olivenöl. Über die Kartoffelfrage streiten Puristen; moderne Versionen enthalten sie meist.",
        'pt':"A salada nicense vem de Nice, na Riviera Francesa — um prato de verão com vegetais frescos, atum, ovos, azeitonas pretas e anchovas, regado com azeite da Provença. Os puristas discutem a questão das batatas; as versões modernas geralmente incluem-nas.",
        'ru':"Салат нисуаз родом из Ниццы на французской Ривьере — летняя тарелка с хрустящими овощами, тунцом, яйцами, чёрными маслинами и анчоусами, политая прованским оливковым маслом. Пуристы спорят о картофеле; современные версии его обычно включают.",
        'ar':"سلطة نيسواز جاءت من مدينة نيس على الريفييرا الفرنسية — طبق صيفي من الخضروات الطازجة والتونة والبيض والزيتون الأسود والأنشوجة، مع زيت زيتون بروفنسي. يختلف التقليديون حول البطاطا، والنسخ الحديثة عادة تشملها.",
        'zh':"尼斯沙拉来自法国蔚蓝海岸的尼斯——一盘夏日蔬菜、金枪鱼、鸡蛋、黑橄榄和凤尾鱼，淋上普罗旺斯橄榄油。纯正派对土豆的问题争论不休，现代版本通常都加。",
        'ja':"ニース風サラダはフランス・コートダジュールのニース発祥 — 夏のひと皿で、シャキッとした野菜、ツナ、卵、黒オリーブ、アンチョビにプロヴァンスのオリーブオイルをかけて食べる。純粋主義者はじゃがいもの是非を巡って論争するが、現代版では入れることが多い。",
        'hi':"निसवाज़ सलाद फ़्रांसीसी रिवियरा के नीस से आती है — गर्मियों की एक थाली में कुरकुरी सब्ज़ियाँ, टूना, अंडे, काले ज़ैतून और एंकोवी, ऊपर से प्रोवांस का ज़ैतून तेल। शुद्धवादी आलू पर बहस करते हैं; आधुनिक संस्करण में आम तौर पर आलू डाले जाते हैं।",
        'tr':"Niçoise salatası Fransız Rivierası'ndaki Nice'ten gelir — taze sebzeler, ton balığı, yumurta, siyah zeytin ve hamsiyle hazırlanmış yazlık bir tabak, üstüne Provence zeytinyağı. Puristler patates meselesini tartışır; modern versiyonlar genellikle patates içerir.",
        'it':"L'insalata nizzarda viene da Nizza, sulla Riviera francese — un piatto estivo di verdure croccanti, tonno, uova, olive nere e acciughe, irrorato con olio d'oliva di Provenza. I puristi discutono delle patate; le versioni moderne di solito le includono.",
        'ko':"니스 샐러드는 프랑스 리비에라의 니스에서 비롯됐다 — 신선한 채소, 참치, 달걀, 검은 올리브, 안초비에 프로방스 올리브 오일을 두른 여름 한 접시. 정통파는 감자 사용을 두고 논쟁하지만 현대판에선 보통 감자를 포함한다.",
    },
})

# ── 219. Beef Stroganoff ───────────────────────────────────────────────
RECIPES.append({
    'id': 219, 'tipType': 'meat', 'pairingsType': 'meat',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Beef_stroganoff_with_pasta.jpg/330px-Beef_stroganoff_with_pasta.jpg',
    'name': {
        'ro':"Boeuf Stroganoff",'en':"Beef Stroganoff",'es':"Estroganof de ternera",'fr':"Bœuf Stroganoff",
        'de':"Boeuf Stroganoff",'pt':"Strogonoff de carne",'ru':"Бефстроганов",'ar':"بيف ستروجانوف",
        'zh':"俄式酸奶炖牛肉",'ja':"ビーフストロガノフ",'hi':"बीफ़ स्ट्रोगानॉफ",'tr':"Beef Stroganoff",
        'it':"Boeuf Stroganoff",'ko':"비프 스트로가노프",
    },
    'origin': {
        'ro':"Rusia",'en':"Russia",'es':"Rusia",'fr':"Russie",'de':"Russland",'pt':"Rússia",
        'ru':"Россия",'ar':"روسيا",'zh':"俄罗斯",'ja':"ロシア",'hi':"रूस",'tr':"Rusya",
        'it':"Russia",'ko':"러시아",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["600 g mușchi de vită, tăiat fâșii","300 g ciuperci champignon","1 ceapă","2 căței usturoi","200 ml smântână","2 linguri muștar","200 ml supă de vită","2 linguri unt","sare, piper, pătrunjel"],
        'en':["600 g beef tenderloin, sliced into strips","300 g button mushrooms","1 onion","2 garlic cloves","200 ml sour cream","2 tbsp mustard","200 ml beef stock","2 tbsp butter","salt, pepper, parsley"],
        'es':["600 g de solomillo de ternera en tiras","300 g de champiñones","1 cebolla","2 dientes de ajo","200 ml de nata agria","2 cdas de mostaza","200 ml de caldo de carne","2 cdas de mantequilla","sal, pimienta, perejil"],
        'fr':["600 g de filet de bœuf en lanières","300 g de champignons de Paris","1 oignon","2 gousses d'ail","200 ml de crème fraîche","2 c. à s. de moutarde","200 ml de bouillon de bœuf","2 c. à s. de beurre","sel, poivre, persil"],
        'de':["600 g Rinderfilet in Streifen","300 g Champignons","1 Zwiebel","2 Knoblauchzehen","200 ml Sauerrahm","2 EL Senf","200 ml Rinderbrühe","2 EL Butter","Salz, Pfeffer, Petersilie"],
        'pt':["600 g de lombo de vaca em tiras","300 g de cogumelos","1 cebola","2 dentes de alho","200 ml de natas azedas","2 colheres de sopa de mostarda","200 ml de caldo de carne","2 colheres de sopa de manteiga","sal, pimenta, salsa"],
        'ru':["600 г говяжьей вырезки, нарезанной полосками","300 г шампиньонов","1 луковица","2 зубчика чеснока","200 мл сметаны","2 ст. л. горчицы","200 мл говяжьего бульона","2 ст. л. сливочного масла","соль, перец, петрушка"],
        'ar':["600 غ فيليه بقري بشرائح","300 غ مشروم","1 بصلة","2 فصوص ثوم","200 مل قشدة حامضة","2 ملعقة كبيرة مسطردة","200 مل مرق لحم","2 ملعقة كبيرة زبدة","ملح، فلفل، بقدونس"],
        'zh':["牛里脊600克，切条","白蘑菇300克","洋葱1个","大蒜2瓣","酸奶油200毫升","芥末2汤匙","牛肉高汤200毫升","黄油2汤匙","盐、胡椒、欧芹"],
        'ja':["牛フィレ600g（細切り）","マッシュルーム300g","玉ねぎ1個","にんにく2片","サワークリーム200ml","マスタード大さじ2","ビーフストック200ml","バター大さじ2","塩、こしょう、パセリ"],
        'hi':["600 ग्राम बीफ़ टेंडरलॉइन, स्ट्रिप्स में","300 ग्राम बटन मशरूम","1 प्याज़","2 लहसुन की कलियाँ","200 मिली खट्टी क्रीम","2 बड़े चम्मच सरसों","200 मिली बीफ़ स्टॉक","2 बड़े चम्मच मक्खन","नमक, काली मिर्च, पार्सले"],
        'tr':["600 g dana bonfile, şerit","300 g mantar","1 soğan","2 diş sarımsak","200 ml ekşi krema","2 yk hardal","200 ml et suyu","2 yk tereyağı","tuz, karabiber, maydanoz"],
        'it':["600 g di filetto di manzo a strisce","300 g di funghi champignon","1 cipolla","2 spicchi d'aglio","200 ml di panna acida","2 cucchiai di senape","200 ml di brodo di manzo","2 cucchiai di burro","sale, pepe, prezzemolo"],
        'ko':["소고기 안심 600g, 스트립으로","양송이버섯 300g","양파 1개","마늘 2쪽","사워크림 200ml","머스터드 2큰술","쇠고기 육수 200ml","버터 2큰술","소금, 후추, 파슬리"],
    },
    'howIsMade': {
        'ro':"Călește ceapa și usturoiul în unt, adaugă ciupercile feliate și rumenește. Adaugă fâșiile de vită, gătește 3 min să rumenească. Toarnă supa, lasă să scadă pe jumătate. Stinge focul, încorporează smântâna și muștarul — nu mai fierbe ca să nu se taie. Sare, piper, pătrunjel. Servește peste piure sau orez.",
        'en':"Sauté onion and garlic in butter, add sliced mushrooms and brown. Add the beef strips, cook 3 minutes to colour. Pour in stock, reduce by half. Off the heat, stir in sour cream and mustard — no more boiling so the sauce doesn't split. Salt, pepper, parsley. Serve over mash or rice.",
        'es':"Sofríe cebolla y ajo en mantequilla, añade champiñones y dora. Incorpora las tiras de carne, cocina 3 min para dorar. Vierte el caldo, reduce a la mitad. Fuera del fuego, mezcla la nata y la mostaza — no vuelve a hervir para que no se corte. Sal, pimienta, perejil. Sirve sobre puré o arroz.",
        'fr':"Faites suer oignon et ail dans le beurre, ajoutez les champignons et faites dorer. Mettez les lanières de bœuf, cuisez 3 min. Versez le bouillon, faites réduire de moitié. Hors du feu, incorporez crème et moutarde — pas d'ébullition pour que la sauce ne tranche pas. Sel, poivre, persil. Servez sur purée ou riz.",
        'de':"Zwiebel und Knoblauch in Butter andünsten, Champignons hinzu und anbraten. Rinderstreifen einlegen, 3 Minuten Farbe nehmen lassen. Brühe angießen, um die Hälfte einkochen. Vom Herd nehmen, Sauerrahm und Senf einrühren — nicht mehr kochen, sonst gerinnt die Sauce. Salzen, pfeffern, Petersilie. Über Püree oder Reis servieren.",
        'pt':"Refogue cebola e alho na manteiga, junte os cogumelos e doure. Acrescente as tiras de carne, cozinhe 3 min. Verta o caldo, reduza para metade. Fora do lume, envolva as natas e a mostarda — sem voltar a ferver para o molho não talhar. Sal, pimenta, salsa. Sirva sobre puré ou arroz.",
        'ru':"Спассеруйте лук и чеснок на сливочном масле, добавьте шампиньоны и подрумяньте. Положите полоски говядины, жарьте 3 минуты до цвета. Влейте бульон, упарьте вдвое. Снимите с огня, вмешайте сметану и горчицу — не кипятить, иначе соус расслоится. Соль, перец, петрушка. Подавайте с пюре или рисом.",
        'ar':"اقلِ البصل والثوم بالزبدة، أضف المشروم وحمّره. أضف شرائح اللحم وحمّرها 3 دقائق. اسكب المرق وقلّل للنصف. ارفع عن النار، أضف القشدة والمسطردة — بدون غليان حتى لا تنفصل الصلصة. ملح، فلفل، بقدونس. قدّم فوق البطاطا المهروسة أو الأرز.",
        'zh':"黄油里炒香洋葱和大蒜，加入蘑菇煎至上色。放入牛肉条，煎3分钟变色。倒入高汤，收汁至一半。离火加入酸奶油和芥末——不能再煮，避免汁水分离。撒盐、胡椒、欧芹。配土豆泥或米饭。",
        'ja':"バターで玉ねぎとにんにくを炒め、薄切りマッシュルームを加えて焼く。牛肉の細切りを入れ、3分焼いて色をつける。ストックを注ぎ、半量まで煮詰める。火を止めてサワークリームとマスタードを混ぜ込む — 再加熱しない（分離する）。塩、こしょう、パセリ。マッシュポテトやライスに添える。",
        'hi':"मक्खन में प्याज़ और लहसुन भूनें, मशरूम डालकर सुनहरा करें। बीफ़ की स्ट्रिप्स डालें, 3 मिनट तक रंग पकड़ने तक पकाएँ। स्टॉक डालें, आधा होने तक पकाएँ। आँच बंद करके खट्टी क्रीम और सरसों मिलाएँ — अब उबालें नहीं, सॉस फट जाएगी। नमक, काली मिर्च, पार्सले। मैश आलू या चावल के साथ परोसें।",
        'tr':"Tereyağında soğan ve sarımsağı kavurun, mantarları ekleyip kızartın. Et şeritlerini koyun, 3 dakika rengi alana dek pişirin. Et suyunu dökün, yarıya kadar buharlaştırın. Ocaktan alın, ekşi kremayı ve hardalı karıştırın — tekrar kaynatmayın, yoksa sos kesilir. Tuz, karabiber, maydanoz. Püre veya pilavın üzerine servis edin.",
        'it':"Soffriggi cipolla e aglio nel burro, aggiungi i funghi e rosolali. Unisci le strisce di carne, cuoci 3 minuti per colorire. Versa il brodo, riduci a metà. Fuori dal fuoco, incorpora panna acida e senape — niente più ebollizione altrimenti la salsa impazzisce. Sale, pepe, prezzemolo. Servi su purè o riso.",
        'ko':"버터에 양파와 마늘을 볶고, 슬라이스 버섯을 넣어 갈색이 나게 합니다. 소고기 스트립을 넣고 3분간 색이 나게 익힙니다. 육수를 붓고 절반까지 졸입니다. 불을 끄고 사워크림과 머스터드를 섞습니다 — 다시 끓이지 마세요(분리됩니다). 소금, 후추, 파슬리. 매시드 포테이토나 밥과 함께 냅니다.",
    },
    'originText': {
        'ro':"Bœuf Stroganoff vine de la curtea contelui Stroganov din Sankt Petersburg, sec. XIX — fâșii fragede de mușchi în sos de smântână, ciuperci și muștar, băutură pentru iernile rusești. A devenit clasic internațional în secolul XX.",
        'en':"Beef Stroganoff comes from the household of Count Stroganov in 19th-century St Petersburg — tender beef strips in a sauce of sour cream, mushrooms and mustard, fortifying for Russian winters. It became an international classic in the 20th century.",
        'es':"El estroganof de ternera viene del hogar del conde Stróganov en la San Petersburgo del siglo XIX — tiras tiernas de carne en salsa de nata, champiñones y mostaza, reconfortante para los inviernos rusos. En el siglo XX se hizo un clásico internacional.",
        'fr':"Le bœuf Stroganoff vient de la maison du comte Stroganov dans le Saint-Pétersbourg du XIXᵉ siècle — fines lanières de bœuf en sauce crème, champignons et moutarde, réconfortante pour les hivers russes. Devenu un classique international au XXᵉ siècle.",
        'de':"Boeuf Stroganoff stammt aus dem Haushalt des Grafen Stroganow im St. Petersburg des 19. Jahrhunderts — zarte Rindfleischstreifen in einer Sauce aus saurer Sahne, Pilzen und Senf, ein Wärmer für russische Winter. Im 20. Jahrhundert wurde es zum internationalen Klassiker.",
        'pt':"O strogonoff de carne vem da casa do conde Stróganov na S. Petersburgo do séc. XIX — tiras tenras de carne em molho de natas, cogumelos e mostarda, reconfortante para os invernos russos. Tornou-se um clássico internacional no séc. XX.",
        'ru':"Бефстроганов появился в доме графа Строганова в Петербурге XIX века — нежные полоски говядины в соусе из сметаны, грибов и горчицы, согревающее блюдо для русской зимы. В XX веке стало международной классикой.",
        'ar':"بيف ستروجانوف وُلد في بيت الكونت ستروجانوف في سان بطرسبرغ في القرن التاسع عشر — شرائح طرية من اللحم في صلصة القشدة الحامضة والمشروم والمسطردة، مغذٍّ للشتاءات الروسية. صار كلاسيكاً عالمياً في القرن العشرين.",
        'zh':"俄式酸奶炖牛肉源自19世纪圣彼得堡的斯特罗加诺夫伯爵家——嫩牛肉条配酸奶油、蘑菇和芥末调成的酱，是俄罗斯冬天的暖身菜。20世纪成为国际经典。",
        'ja':"ビーフストロガノフは19世紀サンクトペテルブルクのストロガノフ伯爵家から生まれた — 柔らかい牛肉の細切りをサワークリーム、マッシュルーム、マスタードのソースで仕上げる、ロシアの冬を温める一皿。20世紀に世界的な定番となった。",
        'hi':"बीफ़ स्ट्रोगानॉफ़ 19वीं सदी के सेंट पीटर्सबर्ग में काउंट स्ट्रोगानॉव के घर से आया — मुलायम बीफ़ की पट्टियाँ खट्टी क्रीम, मशरूम और सरसों की चटनी में, रूसी सर्दियों के लिए गर्म आराम। 20वीं सदी में अंतर्राष्ट्रीय क्लासिक बन गया।",
        'tr':"Beef Stroganoff, 19. yüzyıl St. Petersburg'da Kont Stroganov'un evinden çıktı — ekşi krema, mantar ve hardal sosunda yumuşak et şeritleri; Rus kışlarını doyuran bir yemek. 20. yüzyılda uluslararası bir klasik oldu.",
        'it':"Il boeuf Stroganoff viene dalla casa del conte Stroganov nella San Pietroburgo dell'Ottocento — strisce tenere di manzo in salsa di panna acida, funghi e senape, conforto per gli inverni russi. Nel Novecento è diventato un classico internazionale.",
        'ko':"비프 스트로가노프는 19세기 상트페테르부르크의 스트로가노프 백작가에서 비롯됐다 — 부드러운 소고기 스트립을 사워크림, 버섯, 머스터드 소스로 마무리한, 러시아 겨울을 데우는 요리. 20세기에 국제적 클래식이 됐다.",
    },
})
