"""Recipes 220-223: Pork Schnitzel, Mushroom Risotto, Coq au Vin, Bigos."""

RECIPES = []

# ── 220. Pork Schnitzel ───────────────────────────────────────────────
RECIPES.append({
    'id': 220, 'tipType': 'meat', 'pairingsType': 'meat',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Schweineschnitzel.jpg/330px-Schweineschnitzel.jpg',
    'name': {
        'ro':"Șnițel de porc",'en':"Pork Schnitzel",'es':"Escalope de cerdo",'fr':"Escalope de porc panée",
        'de':"Schweineschnitzel",'pt':"Escalope de porco panado",'ru':"Свиной шницель",'ar':"شنيتزل لحم خنزير",
        'zh':"炸猪排",'ja':"ポークシュニッツェル",'hi':"पोर्क श्निट्ज़ल",'tr':"Domuz şinitzel",
        'it':"Cotoletta di maiale",'ko':"포크 슈니첼",
    },
    'origin': {
        'ro':"Austria",'en':"Austria",'es':"Austria",'fr':"Autriche",'de':"Österreich",'pt':"Áustria",
        'ru':"Австрия",'ar':"النمسا",'zh':"奥地利",'ja':"オーストリア",'hi':"ऑस्ट्रिया",'tr':"Avusturya",
        'it':"Austria",'ko':"오스트리아",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["4 cotlete de porc fără os, bătute subțire","2 ouă","100 g făină","150 g pesmet","unt și ulei pentru prăjit","sare, piper","1 lămâie tăiată felii"],
        'en':["4 boneless pork loin chops, pounded thin","2 eggs","100 g flour","150 g breadcrumbs","butter and oil for frying","salt, pepper","1 lemon, sliced"],
        'es':["4 chuletas de lomo de cerdo sin hueso, golpeadas finas","2 huevos","100 g de harina","150 g de pan rallado","mantequilla y aceite para freír","sal, pimienta","1 limón en rodajas"],
        'fr':["4 escalopes de longe de porc désossées, aplaties","2 œufs","100 g de farine","150 g de chapelure","beurre et huile pour la friture","sel, poivre","1 citron en rondelles"],
        'de':["4 Schweinelende ohne Knochen, dünn geklopft","2 Eier","100 g Mehl","150 g Semmelbrösel","Butter und Öl zum Braten","Salz, Pfeffer","1 Zitrone in Scheiben"],
        'pt':["4 lombinhos de porco sem osso, batidos","2 ovos","100 g de farinha","150 g de pão ralado","manteiga e óleo para fritar","sal, pimenta","1 limão às rodelas"],
        'ru':["4 свиных корейки без кости, отбитых тонко","2 яйца","100 г муки","150 г панировочных сухарей","сливочное масло и растительное для жарки","соль, перец","1 лимон, нарезанный кружочками"],
        'ar':["4 شرائح خاصرة خنزير منزوعة العظم، مدقوقة","2 بيضات","100 غ دقيق","150 غ بقسماط","زبدة وزيت للقلي","ملح، فلفل","1 ليمونة بشرائح"],
        'zh':["4块去骨猪里脊，捶薄","鸡蛋2个","面粉100克","面包屑150克","黄油和油用于煎炸","盐、胡椒","柠檬1个切片"],
        'ja':["豚ロース骨なし4枚（薄く叩く）","卵2個","小麦粉100g","パン粉150g","揚げ用バターと油","塩、こしょう","レモン1個（薄切り）"],
        'hi':["4 हड्डी रहित पोर्क लोइन चॉप, पतले कुटे","2 अंडे","100 ग्राम मैदा","150 ग्राम ब्रेड क्रम्ब्स","तलने के लिए मक्खन और तेल","नमक, काली मिर्च","1 नींबू, कटा"],
        'tr':["4 kemiksiz domuz pirzolası, ince dövülmüş","2 yumurta","100 g un","150 g galeta unu","kızartmak için tereyağı ve yağ","tuz, karabiber","1 limon, dilim"],
        'it':["4 lonze di maiale disossate, battute sottili","2 uova","100 g di farina","150 g di pangrattato","burro e olio per friggere","sale, pepe","1 limone a fette"],
        'ko':["뼈 없는 돼지 등심 4쪽, 얇게 두들김","달걀 2개","밀가루 100g","빵가루 150g","튀김용 버터와 기름","소금, 후추","레몬 1개, 슬라이스"],
    },
    'howIsMade': {
        'ro':"Asezonează cotletele cu sare și piper. Trece-le prin făină, apoi prin ouă bătute și pesmet, apăsând bine să se lipească. Topește unt cu puțin ulei într-o tigaie mare, prăjește 3-4 min pe fiecare parte până devine auriu și crocant. Pune pe hârtie absorbantă. Servește imediat cu felii de lămâie.",
        'en':"Season the chops with salt and pepper. Dredge in flour, then beaten egg, then breadcrumbs, pressing well to coat. Melt butter with a splash of oil in a wide pan, fry 3-4 minutes per side until golden and crisp. Drain on paper. Serve immediately with lemon wedges.",
        'es':"Sazona las chuletas con sal y pimienta. Pásalas por harina, luego por huevo batido y pan rallado, presionando para que se adhiera. Funde mantequilla con un chorrito de aceite en una sartén ancha, fríe 3-4 min por lado hasta dorar. Escurre en papel. Sirve con limón.",
        'fr':"Assaisonnez les escalopes de sel et de poivre. Passez-les dans la farine, puis dans l'œuf battu et la chapelure en pressant bien. Faites fondre du beurre avec un trait d'huile dans une grande poêle, faites frire 3 à 4 min par face jusqu'à doré. Égouttez sur papier. Servez avec du citron.",
        'de':"Schnitzel salzen und pfeffern. In Mehl, dann in Ei, dann in Semmelbröseln wenden und gut andrücken. Butter mit etwas Öl in einer großen Pfanne erhitzen, 3-4 Min. pro Seite goldbraun braten. Auf Küchenpapier abtropfen. Sofort mit Zitronenscheiben servieren.",
        'pt':"Tempere os lombinhos com sal e pimenta. Passe-os por farinha, depois por ovo batido e pão ralado, pressionando bem. Derreta manteiga com um fio de óleo numa frigideira larga, frite 3-4 min de cada lado até dourar. Escorra em papel. Sirva com limão.",
        'ru':"Приправьте отбивные солью и перцем. Обваляйте в муке, затем во взбитом яйце, затем в сухарях, прижимая. Растопите масло с каплей растительного на большой сковороде, жарьте 3-4 минуты с каждой стороны до золотистой корочки. Обсушите на бумаге. Подавайте с ломтиками лимона.",
        'ar':"تبّلي شرائح اللحم بالملح والفلفل. مرّريها بالدقيق ثم البيض المخفوق ثم البقسماط مع الضغط جيداً. أذيبي الزبدة مع قليل من الزيت في مقلاة واسعة، اقلي 3-4 دقائق لكل وجه حتى تذهب وتقرمش. صفّيها على ورق. قدّمي فوراً مع شرائح الليمون.",
        'zh':"猪排撒盐和胡椒。先沾面粉，再裹蛋液，最后压实面包屑。大煎锅里黄油加少许油融化，每面煎3-4分钟至金黄酥脆。用厨房纸吸油。配柠檬片立即上桌。",
        'ja':"豚肉に塩こしょう。小麦粉、溶き卵、パン粉の順にしっかり押さえつけながら衣をつける。大きなフライパンでバターと油を熱し、片面3〜4分ずつ、こんがり狐色になるまで揚げる。ペーパーで油を切る。レモンを添えて熱々で食べる。",
        'hi':"चॉप्स पर नमक और काली मिर्च लगाएँ। मैदा, फिर फेंटे अंडे, फिर ब्रेड क्रम्ब्स में अच्छी तरह दबा-दबा कर लपेटें। चौड़े पैन में मक्खन और थोड़ा तेल पिघलाएँ, हर तरफ 3-4 मिनट सुनहरा कुरकुरा होने तक तलें। पेपर पर निकालें। तुरंत नींबू के टुकड़ों के साथ परोसें।",
        'tr':"Pirzolaları tuz ve karabiberle baharatlayın. Sırasıyla una, çırpılmış yumurtaya ve galeta ununa iyice bastırarak bulayın. Geniş bir tavada tereyağı ile bir tutam yağı eritin, her yüzü 3-4 dakika altın renkli ve çıtır olana kadar kızartın. Kağıt havluya alın. Hemen limonla servis edin.",
        'it':"Condisci le cotolette con sale e pepe. Passale nella farina, poi nell'uovo sbattuto, poi nel pangrattato premendo per far aderire. Sciogli burro con un filo d'olio in una padella larga, friggi 3-4 min per lato fino a dorare. Asciuga su carta. Servi subito con limone.",
        'ko':"돼지고기에 소금과 후추를 뿌립니다. 밀가루, 풀어둔 달걀, 빵가루 순으로 꼭꼭 눌러 묻힙니다. 넓은 팬에 버터와 기름 약간을 녹이고 한 면당 3-4분, 노릇하고 바삭해질 때까지 굽습니다. 키친타월에 기름을 뺍니다. 레몬 조각과 함께 즉시 냅니다.",
    },
    'originText': {
        'ro':"Șnițelul vienez clasic (de vițel) este însoțit de variante mai accesibile cu cotlet de porc — bătut subțire, pane în pesmet auriu și prăjit în unt, cu o felie de lămâie alături. Hrană de cantină centrală europeană, dar și de duminică cu familia.",
        'en':"The classic Wiener Schnitzel (veal) sits alongside its more accessible pork sibling — pounded thin, breaded in golden crumbs and shallow-fried in butter, with a wedge of lemon on the side. Central-European canteen food but also a Sunday lunch.",
        'es':"El clásico Wiener Schnitzel (de ternera) tiene su hermana más accesible con cerdo — golpeada fina, empanada en pan rallado dorado y frita en mantequilla, con un gajo de limón. Comida de cantina centroeuropea pero también almuerzo familiar.",
        'fr':"Le Wiener Schnitzel classique (veau) a son équivalent plus accessible au porc — aplati, pané dans une chapelure dorée et frit au beurre, avec un quartier de citron. Cuisine de cantine d'Europe centrale, mais aussi déjeuner du dimanche en famille.",
        'de':"Das klassische Wiener Schnitzel (Kalb) hat seinen bürgerlichen Bruder aus Schweinefleisch — dünn geklopft, in goldenen Bröseln paniert und in Butter ausgebacken, mit einer Zitronenscheibe daneben. Mitteleuropäische Kantinenkost und Sonntagsessen zugleich.",
        'pt':"O clássico Wiener Schnitzel (vitela) tem o seu primo mais acessível em porco — batido fino, panado em pão ralado dourado e frito em manteiga, com uma rodela de limão ao lado. Comida de cantina centro-europeia e almoço de domingo.",
        'ru':"Классический венский шницель из телятины имеет более доступного собрата из свинины — отбитого тонко, обвалянного в золотистых сухарях и обжаренного в масле, с долькой лимона. Центрально-европейская кухня будней и воскресных обедов.",
        'ar':"شنيتزل فيينا الكلاسيكي (من العجل) له شقيقه الأقل كلفة من لحم الخنزير — مدقوق رقيقاً، مغطى ببقسماط ذهبي ومقلي بالزبدة، مع شريحة ليمون جانباً. طعام مقاصف وسط أوروبا وغداء عائلي يوم الأحد.",
        'zh':"经典维也纳炸肉排（小牛肉）旁边总有一个更亲民的猪肉版本——捶薄、裹上金黄面包屑、用黄油浅炸，配一片柠檬。中欧食堂的常客，也是周日家庭午餐的主角。",
        'ja':"古典的なウィーン風シュニッツェル（仔牛肉）の隣には、より身近な豚肉版がある — 薄く叩いて、黄金色のパン粉をつけてバターで揚げ、レモンを添える。中欧の食堂料理であり、日曜の家族の昼食でもある。",
        'hi':"क्लासिक वियेना श्निट्ज़ल (वील) के साथ-साथ इसका सुलभ पोर्क संस्करण भी है — पतला कुटा, सुनहरे ब्रेडक्रम्ब में लपेटा और मक्खन में तला, साथ में नींबू का टुकड़ा। मध्य यूरोप के कैंटीन भोजन का प्रतीक, साथ ही रविवार का पारिवारिक भोजन भी।",
        'tr':"Klasik Wiener Schnitzel (dana) ile yan yana, ona göre daha erişilebilir bir versiyonu vardır: domuz eti şinitzel — incecik dövülmüş, altın rengi galeta ununa bulanmış ve tereyağında kızartılmış, yanında bir dilim limonla. Orta Avrupa kantininin de, Pazar aile yemeğinin de yıldızı.",
        'it':"La classica Wiener Schnitzel (vitello) ha la sua versione più accessibile con il maiale — battuta sottile, impanata in pangrattato dorato e fritta nel burro, con uno spicchio di limone a fianco. Cucina di mensa centro-europea ma anche pranzo della domenica.",
        'ko':"고전 비엔나 슈니첼(송아지 고기) 옆에는 더 친근한 돼지고기 버전이 있다 — 얇게 두들겨, 황금빛 빵가루를 입혀 버터에 튀기고 레몬 한 조각을 곁들인다. 중부 유럽 구내식당의 단골이자 일요일 가족 식탁의 주인공.",
    },
})

# ── 221. Mushroom Risotto ─────────────────────────────────────────────
RECIPES.append({
    'id': 221, 'tipType': 'pasta', 'pairingsType': 'italian',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mushroom_risotto.jpg/330px-Mushroom_risotto.jpg',
    'name': {
        'ro':"Risotto cu ciuperci",'en':"Mushroom Risotto",'es':"Risotto de setas",'fr':"Risotto aux champignons",
        'de':"Pilzrisotto",'pt':"Risoto de cogumelos",'ru':"Ризотто с грибами",'ar':"ريزوتو الفطر",
        'zh':"蘑菇烩饭",'ja':"きのこリゾット",'hi':"मशरूम रिसोटो",'tr':"Mantar risotto",
        'it':"Risotto ai funghi",'ko':"버섯 리소토",
    },
    'origin': {
        'ro':"Italia",'en':"Italy",'es':"Italia",'fr':"Italie",'de':"Italien",'pt':"Itália",
        'ru':"Италия",'ar':"إيطاليا",'zh':"意大利",'ja':"イタリア",'hi':"इटली",'tr':"İtalya",
        'it':"Italia",'ko':"이탈리아",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["300 g orez Arborio sau Carnaroli","400 g ciuperci amestecate (porcini, champignon)","1 ceapă","2 căței usturoi","100 ml vin alb sec","1 l supă de legume fierbinte","80 g Parmigiano Reggiano ras","50 g unt","ulei de măsline, pătrunjel, sare, piper"],
        'en':["300 g Arborio or Carnaroli rice","400 g mixed mushrooms (porcini, button)","1 onion","2 garlic cloves","100 ml dry white wine","1 L hot vegetable stock","80 g Parmigiano Reggiano, grated","50 g butter","olive oil, parsley, salt, pepper"],
        'es':["300 g de arroz Arborio o Carnaroli","400 g de setas variadas (porcini, champiñones)","1 cebolla","2 dientes de ajo","100 ml de vino blanco seco","1 L de caldo de verduras caliente","80 g de Parmigiano Reggiano rallado","50 g de mantequilla","aceite de oliva, perejil, sal, pimienta"],
        'fr':["300 g de riz Arborio ou Carnaroli","400 g de champignons mélangés (cèpes, Paris)","1 oignon","2 gousses d'ail","100 ml de vin blanc sec","1 L de bouillon de légumes chaud","80 g de Parmigiano Reggiano râpé","50 g de beurre","huile d'olive, persil, sel, poivre"],
        'de':["300 g Arborio- oder Carnaroli-Reis","400 g gemischte Pilze (Steinpilze, Champignons)","1 Zwiebel","2 Knoblauchzehen","100 ml trockener Weißwein","1 L heiße Gemüsebrühe","80 g geriebener Parmigiano Reggiano","50 g Butter","Olivenöl, Petersilie, Salz, Pfeffer"],
        'pt':["300 g de arroz Arborio ou Carnaroli","400 g de cogumelos variados (porcini, brancos)","1 cebola","2 dentes de alho","100 ml de vinho branco seco","1 L de caldo de legumes quente","80 g de Parmigiano Reggiano ralado","50 g de manteiga","azeite, salsa, sal, pimenta"],
        'ru':["300 г риса Арборио или Карнароли","400 г смеси грибов (белые, шампиньоны)","1 луковица","2 зубчика чеснока","100 мл сухого белого вина","1 л горячего овощного бульона","80 г тёртого Пармиджано Реджано","50 г сливочного масла","оливковое масло, петрушка, соль, перец"],
        'ar':["300 غ أرز أربوريو أو كارنارولي","400 غ مشروم مشكّل (بورشيني، أبيض)","1 بصلة","2 فصوص ثوم","100 مل نبيذ أبيض جاف","1 لتر مرق خضار ساخن","80 غ بارميجانو ريجيانو مبشور","50 غ زبدة","زيت زيتون، بقدونس، ملح، فلفل"],
        'zh':["阿尔波里奥或卡纳罗里米300克","什锦蘑菇400克（牛肝菌、白蘑菇）","洋葱1个","大蒜2瓣","干白葡萄酒100毫升","热蔬菜高汤1升","Parmigiano Reggiano磨碎80克","黄油50克","橄榄油、欧芹、盐、胡椒"],
        'ja':["アルボリオまたはカルナローリ米300g","ミックスきのこ400g（ポルチーニ、マッシュルーム）","玉ねぎ1個","にんにく2片","辛口白ワイン100ml","熱い野菜ストック1L","パルミジャーノ・レッジャーノ80g（おろし）","バター50g","オリーブオイル、パセリ、塩、こしょう"],
        'hi':["300 ग्राम Arborio या Carnaroli चावल","400 ग्राम मिश्रित मशरूम (पोर्चिनी, बटन)","1 प्याज़","2 लहसुन की कलियाँ","100 मिली ड्राई व्हाइट वाइन","1 लीटर गरम वेजिटेबल स्टॉक","80 ग्राम कद्दूकस Parmigiano Reggiano","50 ग्राम मक्खन","ज़ैतून तेल, पार्सले, नमक, काली मिर्च"],
        'tr':["300 g Arborio veya Carnaroli pirinci","400 g karışık mantar (porçini, kestane)","1 soğan","2 diş sarımsak","100 ml sek beyaz şarap","1 L sıcak sebze suyu","80 g rendelenmiş Parmigiano Reggiano","50 g tereyağı","zeytinyağı, maydanoz, tuz, karabiber"],
        'it':["300 g di riso Arborio o Carnaroli","400 g di funghi misti (porcini, champignon)","1 cipolla","2 spicchi d'aglio","100 ml di vino bianco secco","1 L di brodo vegetale caldo","80 g di Parmigiano Reggiano grattugiato","50 g di burro","olio d'oliva, prezzemolo, sale, pepe"],
        'ko':["아르보리오 또는 카르나롤리 쌀 300g","혼합 버섯 400g(포르치니, 양송이)","양파 1개","마늘 2쪽","드라이 화이트 와인 100ml","뜨거운 채소 육수 1L","갈아 놓은 파르미지아노 레지아노 80g","버터 50g","올리브유, 파슬리, 소금, 후추"],
    },
    'howIsMade': {
        'ro':"Călește ceapa și usturoiul în ulei, adaugă ciupercile feliate și rumenește 5 min. Adaugă orezul și prăjește 1 min să devină translucid. Stinge cu vin alb, lasă să se evapore. Adaugă supă fierbinte câte un polonic, amestecând des, până orezul e al dente — 18 min. Stinge focul, încorporează unt și Parmigiano. Lasă 2 min să se 'mantequeze'. Pătrunjel, servește imediat.",
        'en':"Sauté onion and garlic in oil, add sliced mushrooms and brown for 5 minutes. Add the rice and toast 1 minute until translucent. Deglaze with white wine, let evaporate. Add hot stock one ladle at a time, stirring often, until the rice is al dente — 18 minutes. Off the heat, beat in butter and Parmigiano. Rest 2 minutes for the mantecatura. Parsley, serve immediately.",
        'es':"Sofríe cebolla y ajo en aceite, añade los champiñones laminados y dora 5 min. Incorpora el arroz y tuesta 1 min hasta volverse translúcido. Desglasa con vino blanco y deja evaporar. Añade caldo caliente cucharón a cucharón, removiendo, hasta que el arroz esté al dente — 18 min. Apaga el fuego, integra mantequilla y Parmigiano. Reposa 2 min para la mantecatura. Perejil, sirve enseguida.",
        'fr':"Faites suer oignon et ail dans l'huile, ajoutez les champignons et faites-les dorer 5 min. Mettez le riz et faites-le nacrer 1 min. Déglacez au vin blanc, laissez s'évaporer. Ajoutez le bouillon chaud louche par louche en remuant, jusqu'à ce que le riz soit al dente — 18 min. Hors du feu, incorporez beurre et Parmigiano. Reposez 2 min pour la mantecatura. Persil, servez aussitôt.",
        'de':"Zwiebel und Knoblauch in Öl andünsten, Pilze hinzufügen und 5 Min. anbraten. Reis dazugeben und 1 Min. glasig rösten. Mit Weißwein ablöschen, verdampfen lassen. Heiße Brühe schöpfkellenweise zugeben unter ständigem Rühren, bis der Reis al dente ist — 18 Min. Vom Herd nehmen, Butter und Parmigiano einrühren. 2 Min. ruhen lassen (Mantecatura). Petersilie, sofort servieren.",
        'pt':"Refogue cebola e alho no azeite, junte os cogumelos fatiados e doure 5 min. Acrescente o arroz e tosteie 1 min até ficar translúcido. Refresque com vinho branco e deixe evaporar. Junte o caldo quente concha a concha, mexendo, até o arroz estar al dente — 18 min. Fora do lume, envolva manteiga e Parmigiano. Repouse 2 min para a mantecatura. Salsa, sirva já.",
        'ru':"Спассеруйте лук и чеснок на масле, добавьте грибы и подрумяньте 5 минут. Всыпьте рис и прокалите 1 минуту до прозрачности. Влейте белое вино, выпарите. Добавляйте горячий бульон по половнику, постоянно помешивая, пока рис не станет аль денте — 18 минут. Снимите с огня, вмешайте сливочное масло и Пармиджано. Дайте постоять 2 минуты (мантекатура). Петрушка, подавайте сразу.",
        'ar':"اقلِ البصل والثوم بالزيت، أضف المشروم وحمّره 5 دقائق. أضف الأرز وحمّصه دقيقة حتى يصبح شفافاً. أطفئ بنبيذ أبيض ودعه يتبخر. أضف المرق الساخن مغرفة بمغرفة مع التحريك المستمر حتى يصبح الأرز ال دنتي — 18 دقيقة. ارفع عن النار، أضف الزبدة والبارميجانو. اتركه دقيقتين (mantecatura). بقدونس وقدّمه فوراً.",
        'zh':"洋葱大蒜在油里炒香，加入蘑菇炒5分钟至上色。倒入米炒1分钟变透明。倒入白葡萄酒收干。一勺一勺加入热高汤，不断搅拌，至米粒al dente——18分钟。离火加入黄油和Parmigiano快速搅打。静置2分钟（mantecatura）。撒欧芹，立即上桌。",
        'ja':"オリーブオイルで玉ねぎとにんにくを炒め、スライスきのこを加えて5分焼く。米を入れて1分、透き通るまで軽く炒める。白ワインを注いで蒸発させる。熱いストックを玉杓子1杯ずつ加え、頻繁に混ぜながらアルデンテになるまで — 約18分。火を止めてバターとパルミジャーノを混ぜ込む。2分休ませる（マンテカトゥーラ）。パセリを散らしてすぐ食卓へ。",
        'hi':"तेल में प्याज़ और लहसुन भूनें, स्लाइस मशरूम डालकर 5 मिनट सुनहरा करें। चावल डालकर 1 मिनट तक पारदर्शी होने तक भूनें। सफ़ेद वाइन डालें, सूखने दें। एक-एक करछुल गरम स्टॉक डालते जाएँ, बीच-बीच में चलाते रहें, चावल al dente होने तक — 18 मिनट। आँच बंद करके मक्खन और Parmigiano मिलाएँ। 2 मिनट विश्राम (mantecatura)। पार्सले, तुरंत परोसें।",
        'tr':"Zeytinyağında soğan ve sarımsağı kavurun, dilimli mantarları ekleyip 5 dakika kızartın. Pirinci ekleyin ve 1 dakika şeffaflaşana dek kavurun. Beyaz şarapla deglaze edin, buharlaşmasını bekleyin. Sıcak suyu birer kepçe ekleyip sürekli karıştırarak pirinç al dente olana dek pişirin — 18 dakika. Ocağı kapatın, tereyağı ve Parmigiano'yu karıştırın. 2 dakika dinlendirin (mantecatura). Maydanoz, hemen servis edin.",
        'it':"Soffriggi cipolla e aglio nell'olio, aggiungi i funghi affettati e rosolali 5 minuti. Unisci il riso e tostalo 1 minuto fino a renderlo translucido. Sfuma con vino bianco e fai evaporare. Aggiungi brodo caldo un mestolo alla volta mescolando spesso, fino a quando il riso è al dente — 18 minuti. Fuori dal fuoco, manteca con burro e Parmigiano. Riposa 2 minuti. Prezzemolo, servi subito.",
        'ko':"올리브유에 양파와 마늘을 볶고, 슬라이스 버섯을 넣어 5분간 갈색이 나게 익힙니다. 쌀을 넣고 1분간 투명해질 때까지 볶습니다. 화이트 와인을 부어 증발시킵니다. 뜨거운 육수를 한 국자씩 넣어가며 자주 저어 쌀이 알 덴테가 될 때까지 18분 정도 익힙니다. 불을 끄고 버터와 파르미지아노를 빠르게 섞습니다(만테카투라). 2분 휴지. 파슬리를 뿌려 즉시 냅니다.",
    },
    'originText': {
        'ro':"Risotto-ul cu ciuperci este înțelepciunea umedă a Lombardiei și a Piemontului: orez Arborio sau Carnaroli, mușcat al dente, scăldat în supă și unt cu Parmigiano, parfumat de porcini autumnali găsiți în pădurile de la nord.",
        'en':"Mushroom risotto is the damp wisdom of Lombardy and Piedmont — Arborio or Carnaroli rice biting al dente, bathed in stock and butter with Parmigiano, scented with autumn porcini foraged from the northern woods.",
        'es':"El risotto de setas es la sabiduría húmeda de Lombardía y Piamonte — arroz Arborio o Carnaroli al dente, bañado en caldo y mantequilla con Parmigiano, perfumado por boletus de otoño recogidos en los bosques del norte.",
        'fr':"Le risotto aux champignons est la sagesse humide de la Lombardie et du Piémont — riz Arborio ou Carnaroli mordant al dente, baigné dans bouillon et beurre avec Parmigiano, parfumé par les cèpes d'automne ramassés dans les bois du nord.",
        'de':"Pilzrisotto ist die feuchte Weisheit der Lombardei und des Piemonts — Arborio- oder Carnaroli-Reis al dente, in Brühe und Butter mit Parmigiano gebadet, von herbstlichen Steinpilzen aus den nördlichen Wäldern parfümiert.",
        'pt':"O risoto de cogumelos é a sabedoria húmida da Lombardia e do Piemonte — arroz Arborio ou Carnaroli al dente, banhado em caldo e manteiga com Parmigiano, perfumado por porcini de outono colhidos nas florestas do norte.",
        'ru':"Грибное ризотто — влажная мудрость Ломбардии и Пьемонта: рис Арборио или Карнароли, кусается аль денте, омыт бульоном и сливочным маслом с Пармиджано, аромат осенних белых грибов из северных лесов.",
        'ar':"ريزوتو الفطر هو الحكمة الرطبة للومبارديا وبييمونتي — أرز أربوريو أو كارنارولي قضمته ال دنتي، يغرق في المرق والزبدة والبارميجانو، ويفوح بعطر فطر بورشيني الخريفي من غابات الشمال.",
        'zh':"蘑菇烩饭是伦巴第与皮埃蒙特的湿润智慧——阿尔波里奥或卡纳罗里米咬感al dente，浸润在高汤与黄油的Parmigiano中，秋日北方林间的牛肝菌香味盘旋其上。",
        'ja':"きのこリゾットはロンバルディアとピエモンテの湿った知恵 — アルボリオまたはカルナローリ米はアルデンテに、ストックとバターとパルミジャーノに浸り、北の森で採れる秋のポルチーニの香りに包まれる。",
        'hi':"मशरूम रिसोटो लोम्बार्डी और पीडमॉन्ट की नम बुद्धिमत्ता है — Arborio या Carnaroli चावल al dente, स्टॉक और मक्खन में Parmigiano के साथ, उत्तरी जंगलों से चुने पतझड़ के पोर्चिनी की खुशबू से सुगंधित।",
        'tr':"Mantarlı risotto, Lombardiya ve Piemonte'nin nemli bilgeliğidir — Arborio veya Carnaroli pirinci al dente ısırılır, et suyu ve tereyağıyla Parmigiano'da yıkanır, kuzey ormanlarından toplanan sonbahar porçinilerinin kokusunu taşır.",
        'it':"Il risotto ai funghi è la saggezza umida della Lombardia e del Piemonte — riso Arborio o Carnaroli al dente, bagnato di brodo e burro con Parmigiano, profumato dai porcini d'autunno raccolti nei boschi del nord.",
        'ko':"버섯 리소토는 롬바르디아와 피에몬테의 촉촉한 지혜다 — 아르보리오 또는 카르나롤리 쌀이 알 덴테로 씹히고, 육수와 버터, 파르미지아노 속에 잠기며, 북부 숲에서 채집된 가을 포르치니의 향이 감돈다.",
    },
})

# ── 222. Coq au Vin ───────────────────────────────────────────────────
RECIPES.append({
    'id': 222, 'tipType': 'meat', 'pairingsType': 'meat',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Coq_au_vin1.jpg/330px-Coq_au_vin1.jpg',
    'name': {
        'ro':"Coq au vin",'en':"Coq au Vin",'es':"Coq au vin",'fr':"Coq au vin",
        'de':"Coq au vin",'pt':"Coq au vin",'ru':"Кок-о-вэн",'ar':"كوك أو فان",
        'zh':"红酒炖鸡",'ja':"コック・オー・ヴァン",'hi':"कोक ओ वैन",'tr':"Coq au vin",
        'it':"Coq au vin",'ko':"코코뱅",
    },
    'origin': {
        'ro':"Franța",'en':"France",'es':"Francia",'fr':"France",'de':"Frankreich",'pt':"França",
        'ru':"Франция",'ar':"فرنسا",'zh':"法国",'ja':"フランス",'hi':"फ़्रांस",'tr':"Fransa",
        'it':"Francia",'ko':"프랑스",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["1 pui întreg, tăiat în 8 bucăți","200 g pancetta sau bacon","250 g ciuperci champignon","200 g ceapă mică","1 sticlă vin roșu Burgundia","2 căței usturoi","2 morcovi","cimbru, dafin","unt, făină, sare, piper, pătrunjel"],
        'en':["1 whole chicken, cut into 8 pieces","200 g pancetta or bacon","250 g button mushrooms","200 g pearl onions","1 bottle red Burgundy wine","2 garlic cloves","2 carrots","thyme, bay leaf","butter, flour, salt, pepper, parsley"],
        'es':["1 pollo entero en 8 trozos","200 g de panceta o bacon","250 g de champiñones","200 g de cebollitas perla","1 botella de vino tinto de Borgoña","2 dientes de ajo","2 zanahorias","tomillo, hoja de laurel","mantequilla, harina, sal, pimienta, perejil"],
        'fr':["1 poulet entier coupé en 8 morceaux","200 g de pancetta ou lard","250 g de champignons de Paris","200 g de petits oignons grelots","1 bouteille de vin rouge de Bourgogne","2 gousses d'ail","2 carottes","thym, laurier","beurre, farine, sel, poivre, persil"],
        'de':["1 ganzes Huhn, in 8 Stücke","200 g Pancetta oder Speck","250 g Champignons","200 g Perlzwiebeln","1 Flasche roter Burgunder","2 Knoblauchzehen","2 Karotten","Thymian, Lorbeerblatt","Butter, Mehl, Salz, Pfeffer, Petersilie"],
        'pt':["1 frango inteiro em 8 pedaços","200 g de panceta ou bacon","250 g de cogumelos","200 g de cebolinhas pérola","1 garrafa de vinho tinto de Borgonha","2 dentes de alho","2 cenouras","tomilho, louro","manteiga, farinha, sal, pimenta, salsa"],
        'ru':["1 целая курица, разделанная на 8 частей","200 г панчетты или бекона","250 г шампиньонов","200 г жемчужного лука","1 бутылка красного бургундского вина","2 зубчика чеснока","2 моркови","тимьян, лавровый лист","сливочное масло, мука, соль, перец, петрушка"],
        'ar':["1 دجاجة كاملة، مقطعة 8 قطع","200 غ بانشيتا أو لحم مقدد","250 غ مشروم","200 غ بصل لؤلؤي","1 زجاجة نبيذ أحمر بورغندي","2 فصوص ثوم","2 جزرة","زعتر، ورق غار","زبدة، دقيق، ملح، فلفل، بقدونس"],
        'zh':["整鸡1只，切8块","意式培根或培根200克","白蘑菇250克","珍珠洋葱200克","勃艮第红葡萄酒1瓶","大蒜2瓣","胡萝卜2根","百里香、月桂叶","黄油、面粉、盐、胡椒、欧芹"],
        'ja':["丸鶏1羽（8つに切る）","パンチェッタまたはベーコン200g","マッシュルーム250g","パールオニオン200g","ブルゴーニュ赤ワイン1本","にんにく2片","にんじん2本","タイム、ローリエ","バター、小麦粉、塩、こしょう、パセリ"],
        'hi':["1 साबुत चिकन, 8 टुकड़ों में","200 ग्राम पनचेटा या बेकन","250 ग्राम बटन मशरूम","200 ग्राम पर्ल अनियन","1 बोतल बरगंडी रेड वाइन","2 लहसुन की कलियाँ","2 गाजर","थाइम, तेज़पत्ता","मक्खन, मैदा, नमक, काली मिर्च, पार्सले"],
        'tr':["1 bütün tavuk, 8 parçaya bölünmüş","200 g pancetta veya beykın","250 g mantar","200 g inci soğan","1 şişe Burgonya kırmızı şarap","2 diş sarımsak","2 havuç","kekik, defne yaprağı","tereyağı, un, tuz, karabiber, maydanoz"],
        'it':["1 pollo intero, tagliato in 8 pezzi","200 g di pancetta o bacon","250 g di funghi champignon","200 g di cipolline borettane","1 bottiglia di Borgogna rosso","2 spicchi d'aglio","2 carote","timo, alloro","burro, farina, sale, pepe, prezzemolo"],
        'ko':["통닭 1마리, 8조각","판체타 또는 베이컨 200g","양송이 250g","펄 어니언 200g","부르고뉴 레드 와인 1병","마늘 2쪽","당근 2개","타임, 월계수잎","버터, 밀가루, 소금, 후추, 파슬리"],
    },
    'howIsMade': {
        'ro':"Marinează bucățile de pui în vin roșu cu cimbru și dafin peste noapte. Rumenește pancetta, scoate-o. Rumenește puiul scurs în grăsime, scoate-l. Călește ceapa, usturoiul și morcovii, adaugă făină. Toarnă marinada, supa, pune puiul și pancetta înapoi. Fierbe acoperit 60 min. Rumenește separat ciupercile și ceapa mică, adaugă-le în ultimele 15 min. Pătrunjel, servește cu piure.",
        'en':"Marinate chicken in red wine with thyme and bay overnight. Brown the pancetta in a heavy pot, set aside. Brown the drained chicken in the fat, set aside. Sauté onions, garlic and carrots, dust with flour. Pour in the marinade and a little stock, return chicken and pancetta. Simmer covered 60 minutes. Brown mushrooms and pearl onions separately, add for the last 15 minutes. Parsley, serve with mash.",
        'es':"Marina el pollo en vino tinto con tomillo y laurel toda la noche. Dora la panceta en una olla pesada y reserva. Dora el pollo escurrido en la grasa y reserva. Sofríe cebolla, ajo y zanahoria, espolvorea harina. Vierte la marinada y algo de caldo, devuelve el pollo y la panceta. Cuece tapado 60 min. Aparte dora champiñones y cebollitas, añádelos en los últimos 15 min. Perejil, sirve con puré.",
        'fr':"Faites mariner le poulet dans le vin rouge avec thym et laurier toute la nuit. Faites dorer la pancetta en cocotte, réservez. Faites dorer le poulet égoutté dans la graisse, réservez. Faites suer oignons, ail et carottes, saupoudrez de farine. Versez la marinade et un peu de bouillon, remettez poulet et pancetta. Mijotez à couvert 60 min. Faites dorer champignons et petits oignons à part, ajoutez les 15 dernières min. Persil, servez avec purée.",
        'de':"Hähnchen über Nacht in Rotwein mit Thymian und Lorbeer marinieren. Pancetta in einem schweren Topf anbraten, herausnehmen. Hähnchen abtropfen und im Fett anbraten, herausnehmen. Zwiebeln, Knoblauch und Karotten andünsten, mit Mehl bestäuben. Marinade und etwas Brühe angießen, Hähnchen und Pancetta zurück. Zugedeckt 60 Min. schmoren. Champignons und Perlzwiebeln getrennt anbraten, in den letzten 15 Min. zugeben. Petersilie, mit Püree servieren.",
        'pt':"Marine o frango em vinho tinto com tomilho e louro de um dia para o outro. Doure a panceta numa panela pesada, reserve. Doure o frango escorrido na gordura, reserve. Refogue cebola, alho e cenoura, polvilhe com farinha. Verta a marinada e algum caldo, devolva frango e panceta. Coza tapado 60 min. À parte doure cogumelos e cebolinhas, junte nos últimos 15 min. Salsa, sirva com puré.",
        'ru':"Замаринуйте курицу в красном вине с тимьяном и лавром на ночь. В тяжёлой кастрюле обжарьте панчетту, отложите. Обжарьте обсушенную курицу в этом жире, отложите. Спассеруйте лук, чеснок и морковь, припорошите мукой. Влейте маринад и немного бульона, верните курицу и панчетту. Тушите под крышкой 60 минут. Отдельно обжарьте грибы и жемчужный лук, добавьте за 15 минут до конца. Петрушка, подавайте с пюре.",
        'ar':"تبّلي الدجاج بالنبيذ الأحمر مع الزعتر وورق الغار طوال الليل. حمّري البانشيتا في قدر ثقيل وأخرجيها. حمّري الدجاج المصفّى في الدهن، ثم أخرجيه. اقلي البصل والثوم والجزر، رشّي الدقيق. اسكبي التتبيلة وبعض المرق، أعيدي الدجاج والبانشيتا. اطبخي مغطى 60 دقيقة. حمّري المشروم والبصل اللؤلؤي على حدة، أضيفيهم آخر 15 دقيقة. بقدونس، قدّمي مع البطاطا المهروسة.",
        'zh':"鸡块用红酒、百里香和月桂叶腌制隔夜。厚锅里把意式培根煎香取出。鸡块沥干用培根油煎至上色取出。爆香洋葱、大蒜和胡萝卜，撒上面粉。倒入腌汁和少许高汤，鸡块和培根回锅。盖盖炖60分钟。蘑菇和珍珠洋葱单独煎香，最后15分钟加入。撒欧芹，配土豆泥享用。",
        'ja':"鶏肉を赤ワインにタイムとローリエとともに一晩漬ける。重い鍋でパンチェッタを焼き、取り出す。水気を切った鶏肉を脂で焼いて取り出す。玉ねぎ、にんにく、にんじんを炒め、小麦粉をふる。マリネ液と少量のストックを注ぎ、鶏肉とパンチェッタを戻す。蓋をして60分煮込む。マッシュルームとパールオニオンを別に焼き、最後の15分で合流させる。パセリ、マッシュポテトと一緒に。",
        'hi':"चिकन को रात भर रेड वाइन, थाइम और तेज़पत्ते में मैरिनेट करें। भारी बर्तन में पनचेटा सुनहरा करें, निकाल लें। निकाला चिकन उसी चर्बी में सुनहरा करें, निकाल लें। प्याज़, लहसुन और गाजर भूनें, मैदा छिड़कें। मैरिनेड और थोड़ा स्टॉक डालें, चिकन और पनचेटा वापस डालें। ढककर 60 मिनट पकाएँ। मशरूम और पर्ल अनियन अलग से सुनहरा करें, आख़िरी 15 मिनट में डालें। पार्सले, मैश आलू के साथ परोसें।",
        'tr':"Tavuğu kırmızı şarap, kekik ve defne yaprağıyla geceleyin marine edin. Ağır bir tencerede pancetta'yı kavurup alın. Süzülmüş tavuğu yağda kızartıp alın. Soğan, sarımsak ve havucu kavurun, unla tozlandırın. Marine sıvısını ve biraz et suyunu dökün, tavuk ve pancetta'yı geri koyun. Kapağı kapalı 60 dakika pişirin. Mantar ve inci soğanları ayrı kızartıp son 15 dakikada ekleyin. Maydanoz, püreyle servis edin.",
        'it':"Marina il pollo nel vino rosso con timo e alloro per una notte. In una pentola pesante rosola la pancetta, mettila da parte. Rosola il pollo scolato nel grasso, mettilo da parte. Soffriggi cipolle, aglio e carote, spolvera con farina. Versa la marinata e un po' di brodo, rimetti pollo e pancetta. Cuoci coperto 60 minuti. A parte rosola funghi e cipolline, aggiungili negli ultimi 15 minuti. Prezzemolo, servi con purè.",
        'ko':"닭을 레드 와인, 타임, 월계수잎과 함께 하룻밤 재웁니다. 두꺼운 냄비에 판체타를 굽고 꺼냅니다. 물기를 뺀 닭을 그 기름에 노릇하게 굽고 꺼냅니다. 양파, 마늘, 당근을 볶고 밀가루를 살짝 뿌립니다. 마리네이드와 약간의 육수를 붓고 닭과 판체타를 다시 넣습니다. 뚜껑을 덮고 60분 끓입니다. 양송이와 펄 어니언을 따로 볶아 마지막 15분에 합칩니다. 파슬리, 매시드 포테이토와 함께.",
    },
    'originText': {
        'ro':"Coq au vin este Burgundia într-o oală: pui sau cocoș tăbăcit ore în vin roșu Pinot Noir cu pancetta, ciuperci și ceapă mică. O rețetă de cărbuni și răbdare, izvorâtă din bucătăria fermelor și înnobilată de Escoffier și Julia Child.",
        'en':"Coq au vin is Burgundy in a pot — chicken (or capon) braised for hours in red Pinot Noir with pancetta, mushrooms and pearl onions. A recipe of coals and patience, born of farmhouse cooking and ennobled by Escoffier and Julia Child.",
        'es':"El coq au vin es Borgoña en una cazuela — pollo (o capón) estofado durante horas en Pinot Noir tinto con panceta, champiñones y cebollitas. Una receta de brasas y paciencia, nacida en la cocina de granja y ennoblecida por Escoffier y Julia Child.",
        'fr':"Le coq au vin, c'est la Bourgogne dans une cocotte — coq (ou poule) braisé des heures dans du Pinot Noir avec pancetta, champignons et petits oignons. Une recette de braises et de patience, née des cuisines paysannes et anoblie par Escoffier et Julia Child.",
        'de':"Coq au vin ist Burgund im Topf — Hahn (oder Huhn) stundenlang in rotem Pinot Noir mit Pancetta, Champignons und Perlzwiebeln geschmort. Ein Rezept aus Kohle und Geduld, geboren in Bauernküchen und durch Escoffier und Julia Child geadelt.",
        'pt':"O coq au vin é a Borgonha numa panela — frango (ou galo) estufado durante horas em Pinot Noir tinto com panceta, cogumelos e cebolinhas. Uma receita de brasas e paciência, nascida da cozinha rural e enobrecida por Escoffier e Julia Child.",
        'ru':"Кок-о-вэн — это Бургундия в кастрюле: курица (или петух) часами томится в красном пино нуар с панчеттой, грибами и жемчужным луком. Рецепт углей и терпения, рождённый деревенской кухней и облагороженный Эскофье и Джулией Чайлд.",
        'ar':"كوك أو فان هو بورغونيا في قدر — الديك أو الدجاج يُطهى ساعات في نبيذ بينو نوار الأحمر مع البانشيتا والمشروم والبصل اللؤلؤي. وصفة من جمر وصبر، وُلدت في مطابخ المزارع وأنبلها إسكوفييه وجوليا تشايلد.",
        'zh':"红酒炖鸡是炖锅里的勃艮第——整只鸡（或阉鸡）在勃艮第Pinot Noir红酒中与意式培根、蘑菇和珍珠洋葱炖煮数小时。一道属于炭火与耐心的菜，起源于农舍厨房，被埃斯科菲耶和茱莉亚·柴尔德推上经典神坛。",
        'ja':"コック・オー・ヴァンは鍋の中のブルゴーニュ — 鶏（または去勢鶏）をピノ・ノワール赤ワインでパンチェッタ、マッシュルーム、パールオニオンとともに何時間も煮込む。炭火と忍耐の料理であり、農家の台所から生まれ、エスコフィエとジュリア・チャイルドによって名声を得た。",
        'hi':"कोक ओ वैन एक बर्तन में बर्गंडी है — मुर्गा (या पाला हुआ रोस्टर) घंटों रेड Pinot Noir में पनचेटा, मशरूम और पर्ल अनियन के साथ धीमी आँच पर पका। अंगारों और धैर्य की रेसिपी, फ़ार्महाउस रसोई से जन्मी, एस्कॉफ़ियर और जूलिया चाइल्ड ने जिसे ख्याति दी।",
        'tr':"Coq au vin tencerede Burgonya'dır — tavuk (veya horoz) saatlerce kırmızı Pinot Noir'da pancetta, mantar ve inci soğanla pişirilir. Köz ateşi ve sabır gerektiren bir tarif; köy mutfağından doğdu, Escoffier ve Julia Child onu soyluluğa taşıdı.",
        'it':"Il coq au vin è la Borgogna in una pentola — pollo (o cappone) brasato per ore in Pinot Noir rosso con pancetta, funghi e cipolline. Una ricetta di braci e pazienza, nata nella cucina contadina e nobilitata da Escoffier e Julia Child.",
        'ko':"코코뱅은 냄비 안의 부르고뉴다 — 닭(또는 거세 수탉)을 레드 피노 누아에 판체타, 양송이, 펄 어니언과 함께 몇 시간 동안 천천히 끓인다. 숯과 인내의 레시피로, 농가 부엌에서 태어나 에스코피에와 줄리아 차일드를 통해 명성을 얻었다.",
    },
})

# ── 223. Bigos ────────────────────────────────────────────────────────
RECIPES.append({
    'id': 223, 'tipType': 'meat', 'pairingsType': 'meat',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bigos2.jpg/330px-Bigos2.jpg',
    'name': {
        'ro':"Bigos",'en':"Bigos",'es':"Bigos",'fr':"Bigos",'de':"Bigos",'pt':"Bigos",
        'ru':"Бигос",'ar':"بيغوس",'zh':"猎人炖菜",'ja':"ビゴス",'hi':"बिगोस",'tr':"Bigos",
        'it':"Bigos",'ko':"비고스",
    },
    'origin': {
        'ro':"Polonia",'en':"Poland",'es':"Polonia",'fr':"Pologne",'de':"Polen",'pt':"Polónia",
        'ru':"Польша",'ar':"بولندا",'zh':"波兰",'ja':"ポーランド",'hi':"पोलैंड",'tr':"Polonya",
        'it':"Polonia",'ko':"폴란드",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["500 g varză murată, scurtă","300 g varză proaspătă, tăiată","400 g porc (umăr), cuburi","200 g cârnați afumați (kielbasa)","150 g bacon","1 ceapă","2 căței usturoi","3 prune uscate","ienibahar, dafin, boia, sare, piper"],
        'en':["500 g sauerkraut, drained","300 g fresh cabbage, shredded","400 g pork shoulder, cubed","200 g smoked sausage (kielbasa)","150 g bacon","1 onion","2 garlic cloves","3 dried prunes","allspice, bay leaf, paprika, salt, pepper"],
        'es':["500 g de chucrut escurrido","300 g de col fresca rallada","400 g de paleta de cerdo en cubos","200 g de salchicha ahumada (kielbasa)","150 g de bacon","1 cebolla","2 dientes de ajo","3 ciruelas pasas","pimienta de Jamaica, laurel, pimentón, sal, pimienta"],
        'fr':["500 g de choucroute égouttée","300 g de chou frais émincé","400 g d'épaule de porc en cubes","200 g de saucisse fumée (kielbasa)","150 g de lard","1 oignon","2 gousses d'ail","3 pruneaux secs","quatre-épices, laurier, paprika, sel, poivre"],
        'de':["500 g Sauerkraut, abgetropft","300 g frischer Kohl, fein geschnitten","400 g Schweineschulter, gewürfelt","200 g geräucherte Kielbasa","150 g Speck","1 Zwiebel","2 Knoblauchzehen","3 getrocknete Pflaumen","Piment, Lorbeer, Paprika, Salz, Pfeffer"],
        'pt':["500 g de chucrute escorrido","300 g de couve fresca ralada","400 g de pá de porco em cubos","200 g de salsicha fumada (kielbasa)","150 g de bacon","1 cebola","2 dentes de alho","3 ameixas secas","pimenta-da-jamaica, louro, paprica, sal, pimenta"],
        'ru':["500 г квашеной капусты, отжатой","300 г свежей капусты, нашинкованной","400 г свиной лопатки, кубиками","200 г копчёной колбасы (кельбаса)","150 г бекона","1 луковица","2 зубчика чеснока","3 чернослива","душистый перец, лавровый лист, паприка, соль, перец"],
        'ar':["500 غ مخلل ملفوف مصفّى","300 غ ملفوف طازج مقطع","400 غ كتف خنزير مكعبات","200 غ نقانق مدخنة (كيلباسا)","150 غ لحم مقدد","1 بصلة","2 فصوص ثوم","3 برقوق مجفف","فلفل البهار، ورق غار، بابريكا، ملح، فلفل"],
        'zh':["酸菜500克，沥干","新鲜卷心菜300克，切丝","猪肩肉400克，切块","熏肠（kielbasa）200克","培根150克","洋葱1个","大蒜2瓣","干西梅3颗","多香果、月桂叶、辣椒粉、盐、胡椒"],
        'ja':["ザワークラウト500g（水気を絞る）","生キャベツ300g（千切り）","豚肩肉400g（角切り）","スモークソーセージ（キェルバサ）200g","ベーコン150g","玉ねぎ1個","にんにく2片","プルーン3個","オールスパイス、ローリエ、パプリカ、塩、こしょう"],
        'hi':["500 ग्राम सॉरक्राट, छाना","300 ग्राम ताज़ी गोभी, कतरी","400 ग्राम पोर्क शोल्डर, टुकड़े","200 ग्राम स्मोक्ड सॉसेज (kielbasa)","150 ग्राम बेकन","1 प्याज़","2 लहसुन की कलियाँ","3 सूखे आलूबुखारे","ऑलस्पाइस, तेज़पत्ता, पपरिका, नमक, काली मिर्च"],
        'tr':["500 g lahana turşusu, suyu süzülmüş","300 g taze lahana, doğranmış","400 g domuz kürek, küp","200 g tütsülü sosis (kielbasa)","150 g pastırma","1 soğan","2 diş sarımsak","3 kuru erik","yenibahar, defne yaprağı, kırmızı toz biber, tuz, karabiber"],
        'it':["500 g di crauti, scolati","300 g di cavolo fresco a striscioline","400 g di spalla di maiale a cubetti","200 g di salsiccia affumicata (kielbasa)","150 g di pancetta","1 cipolla","2 spicchi d'aglio","3 prugne secche","pimento, alloro, paprica, sale, pepe"],
        'ko':["사우어크라우트 500g, 물기 짠 것","신선한 양배추 300g, 채썬 것","돼지 어깨살 400g, 깍둑썬 것","훈제 소시지(킬바사) 200g","베이컨 150g","양파 1개","마늘 2쪽","말린 자두 3개","올스파이스, 월계수잎, 파프리카, 소금, 후추"],
    },
    'howIsMade': {
        'ro':"Rumenește baconul, scoate-l. Călește ceapa și usturoiul, adaugă cuburile de porc și rumenește. Pune varza murată, varza proaspătă, cârnații feliați, prunele și condimentele. Adaugă apă să acopere abia. Fierbe acoperit pe foc mic 2-3 ore, amestecând din când. Bigos-ul e mai bun a doua zi, după ce 'doarme' peste noapte la frigider.",
        'en':"Brown the bacon in a heavy pot, set aside. Sauté onion and garlic, add the pork cubes and brown. Add sauerkraut, fresh cabbage, sliced sausage, prunes and spices. Pour in water just to cover. Simmer covered on low for 2-3 hours, stirring occasionally. Bigos is better the next day after it rests overnight in the fridge.",
        'es':"Dora el bacon en una olla pesada, reserva. Sofríe cebolla y ajo, añade los cubos de cerdo y dora. Incorpora el chucrut, la col fresca, la salchicha en rodajas, las ciruelas y las especias. Vierte agua justo para cubrir. Cuece tapado a fuego bajo 2-3 horas, removiendo de vez en cuando. El bigos está mejor al día siguiente, tras 'descansar' en el frigorífico.",
        'fr':"Faites dorer le lard dans une cocotte épaisse, réservez. Faites suer oignon et ail, ajoutez les cubes de porc et faites dorer. Incorporez la choucroute, le chou frais, la saucisse en rondelles, les pruneaux et les épices. Versez de l'eau juste pour couvrir. Mijotez à couvert sur feu doux 2 à 3 heures, en remuant. Le bigos est meilleur le lendemain, après une nuit au frais.",
        'de':"Speck im schweren Topf anbraten, herausnehmen. Zwiebel und Knoblauch andünsten, Schweinewürfel hinzufügen und scharf anbraten. Sauerkraut, frischen Kohl, geschnittene Wurst, Pflaumen und Gewürze einrühren. Mit Wasser knapp bedecken. Zugedeckt bei kleiner Hitze 2-3 Stunden köcheln, ab und zu rühren. Bigos ist am nächsten Tag besser, wenn er über Nacht im Kühlschrank 'ruht'.",
        'pt':"Doure o bacon numa panela pesada, reserve. Refogue cebola e alho, junte os cubos de porco e doure. Incorpore o chucrute, a couve fresca, a salsicha às rodelas, as ameixas e as especiarias. Verta água apenas para cobrir. Coza tapado em lume brando 2-3 horas, mexendo de vez em quando. O bigos fica melhor no dia seguinte, depois de 'descansar' no frigorífico.",
        'ru':"Обжарьте бекон в тяжёлой кастрюле, отложите. Спассеруйте лук и чеснок, добавьте свинину и обжарьте. Положите квашеную капусту, свежую капусту, нарезанную колбасу, чернослив и специи. Залейте водой едва покрыв. Тушите под крышкой на малом огне 2-3 часа, иногда помешивая. На следующий день, после ночи в холодильнике, бигос ещё вкуснее.",
        'ar':"حمّري اللحم المقدد في قدر ثقيل وأخرجيه. اقلي البصل والثوم، أضيفي مكعبات الخنزير وحمّريها. أضيفي مخلل الملفوف والملفوف الطازج والنقانق المقطعة والبرقوق والبهارات. اسكبي ماء يكاد يغطي. اطبخي مغطى على نار هادئة 2-3 ساعات مع التحريك. بيغوس أطيب في اليوم التالي بعد أن 'ينام' ليلة في الثلاجة.",
        'zh':"厚锅里把培根煎香取出。爆香洋葱大蒜，加入猪肉块煎至上色。加入酸菜、新鲜卷心菜、切片香肠、西梅和香料。倒入刚好没过的水。盖盖小火慢炖2-3小时，时不时搅动。Bigos隔夜冷藏后第二天更好吃。",
        'ja':"重い鍋でベーコンを焼き、取り出す。玉ねぎとにんにくを炒め、豚肉の角切りを加えて焼き色をつける。ザワークラウト、生キャベツ、薄切りソーセージ、プルーン、スパイスを加える。ひたひたの水を注ぐ。蓋をして弱火で2-3時間、時々混ぜながら煮込む。ビゴスは一晩冷蔵庫で寝かせると翌日さらに美味しい。",
        'hi':"भारी बर्तन में बेकन सुनहरा करें, निकाल लें। प्याज़ और लहसुन भूनें, पोर्क के टुकड़े डालकर सुनहरा करें। सॉरक्राट, ताज़ी गोभी, कटी सॉसेज, आलूबुखारे और मसाले डालें। बस ढकने जितना पानी डालें। ढककर धीमी आँच पर 2-3 घंटे पकाएँ, बीच-बीच में चलाएँ। बिगोस अगले दिन फ्रिज में 'सोने' के बाद बेहतर लगता है।",
        'tr':"Ağır bir tencerede pastırmayı kavurun, alın. Soğan ve sarımsağı kavurun, domuz küplerini ekleyip kızartın. Lahana turşusu, taze lahana, dilim sosis, kuru erik ve baharatları ekleyin. Tam kaplayacak kadar su dökün. Kapağı kapalı kısık ateşte 2-3 saat ara ara karıştırarak pişirin. Bigos bir gece buzdolabında 'uyuduktan' sonra ertesi gün daha lezzetlidir.",
        'it':"In una pentola pesante rosola la pancetta, mettila da parte. Soffriggi cipolla e aglio, unisci i cubetti di maiale e rosola. Aggiungi i crauti, il cavolo fresco, la salsiccia affettata, le prugne e le spezie. Versa acqua appena a coprire. Cuoci coperto a fuoco basso 2-3 ore mescolando ogni tanto. Il bigos è migliore il giorno dopo, dopo una notte 'di riposo' in frigo.",
        'ko':"두꺼운 냄비에 베이컨을 굽고 꺼냅니다. 양파와 마늘을 볶고 돼지고기 큐브를 넣어 갈색이 나게 합니다. 사우어크라우트, 신선한 양배추, 슬라이스한 소시지, 자두, 향신료를 넣습니다. 물을 겨우 잠길 정도 붓습니다. 뚜껑을 덮고 약한 불에서 2-3시간 가끔 저어가며 끓입니다. 비고스는 하룻밤 냉장 휴지 후 다음 날이 더 맛있습니다.",
    },
    'originText': {
        'ro':"Bigos, 'tocănita vânătorilor' poloneză, fierbe varza murată cu carne afumată, prune și ienibahar ore în șir. Așezat noaptea la frigider, ies din el iarna lentă a Mazoviei, vânătoarea, fumul focului din pădurea de pini.",
        'en':"Bigos — the Polish 'hunter's stew' — simmers sauerkraut with smoked meat, prunes and allspice for hours. Rested overnight, it carries the slow Mazovian winter, the hunt, the smoke of a pine-wood fire.",
        'es':"El bigos — el 'guisado del cazador' polaco — cuece chucrut con carne ahumada, ciruelas y pimienta de Jamaica durante horas. Descansado de un día para otro, lleva en él el invierno lento de Mazovia, la caza y el humo del fuego de pino.",
        'fr':"Le bigos — la 'potée du chasseur' polonaise — fait mijoter choucroute, viandes fumées, pruneaux et quatre-épices pendant des heures. Reposé une nuit, il porte en lui l'hiver lent de Mazovie, la chasse, la fumée du feu de pin.",
        'de':"Bigos — der polnische 'Jägertopf' — köchelt Sauerkraut mit Räucherfleisch, Pflaumen und Piment stundenlang. Über Nacht gerastet, trägt er in sich den langsamen masowischen Winter, die Jagd und den Rauch des Kiefernfeuers.",
        'pt':"O bigos — o 'guisado do caçador' polaco — coze chucrute com carne fumada, ameixas e pimenta-da-jamaica durante horas. Descansado de um dia para o outro, traz o inverno lento da Mazóvia, a caça e o fumo da lenha de pinheiro.",
        'ru':"Бигос — польская 'охотничья тушёнка' — томит квашеную капусту с копчёным мясом, черносливом и душистым перцем часами. После ночи в холодильнике в нём слышен медленный мазовецкий зимний день, охота и дым соснового костра.",
        'ar':"بيغوس — 'يخنة الصيادين' البولندية — يطهو مخلل الملفوف مع اللحم المدخن والبرقوق والبهارات ساعات طويلة. بعد ليلة من الراحة، يحمل في طياته شتاء مازوفيا البطيء، رحلة الصيد، ودخان نار خشب الصنوبر.",
        'zh':"Bigos——波兰的「猎人炖菜」——把酸菜与烟熏肉、西梅、多香果一同炖煮数小时。冷藏一夜后，盛在碗里便有马佐夫舍漫长冬日、猎手身影与松木炉火的烟气。",
        'ja':"ビゴスはポーランドの「猟師のシチュー」 — ザワークラウトと燻製肉、プルーン、オールスパイスを何時間も煮込む。一晩寝かせると、マゾフシェのゆっくりした冬、狩り、松の薪の煙の香りが一椀の中に立ち上る。",
        'hi':"बिगोस — पोलैंड का 'शिकारी का स्टू' — सॉरक्राट को धुएँदार मांस, आलूबुखारों और ऑलस्पाइस के साथ घंटों धीमी आँच पर पकाता है। रात भर के विश्राम के बाद इसमें मज़ोविया की धीमी सर्दी, शिकार, और चीड़ की लकड़ी की आग का धुआँ बस जाता है।",
        'tr':"Bigos — Polonya'nın 'avcı yahnisi' — lahana turşusunu tütsülü etler, kuru erik ve yenibaharla saatlerce pişirir. Bir gece dinlendirildiğinde içinde Mazovya'nın yavaş kışı, avın izi ve çam odunundan yükselen duman yatar.",
        'it':"Il bigos — lo 'stufato dei cacciatori' polacco — sobbolle crauti, carne affumicata, prugne e pimento per ore. Riposato una notte, porta dentro di sé l'inverno lento della Mazovia, la caccia e il fumo del fuoco di pino.",
        'ko':"비고스 — 폴란드의 '사냥꾼 스튜' — 는 사우어크라우트를 훈제 고기, 자두, 올스파이스와 함께 몇 시간 동안 끓인다. 하룻밤 휴지시킨 뒤에야 마조비아의 느린 겨울과 사냥, 소나무 장작 연기가 한 그릇 안에 모인다.",
    },
})
