"""Recipes 224-226: Tagine, Ramen, Vietnamese Spring Rolls."""

RECIPES = []

# ── 224. Tagine ────────────────────────────────────────────────────────
RECIPES.append({
    'id': 224, 'tipType': 'meat', 'pairingsType': 'meat',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Lamb_Tagine_with_preserved_lemons_and_olives.jpg/330px-Lamb_Tagine_with_preserved_lemons_and_olives.jpg',
    'name': {
        'ro':"Tajină",'en':"Tagine",'es':"Tajín",'fr':"Tajine",
        'de':"Tajine",'pt':"Tajine",'ru':"Тажин",'ar':"طاجين",
        'zh':"塔吉锅",'ja':"タジン",'hi':"ताजीन",'tr':"Tajin",
        'it':"Tajine",'ko':"타진",
    },
    'origin': {
        'ro':"Maroc",'en':"Morocco",'es':"Marruecos",'fr':"Maroc",'de':"Marokko",'pt':"Marrocos",
        'ru':"Марокко",'ar':"المغرب",'zh':"摩洛哥",'ja':"モロッコ",'hi':"मोरक्को",'tr':"Fas",
        'it':"Marocco",'ko':"모로코",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["800 g pulpă de miel sau pui, bucăți","2 cepe","3 căței usturoi","1 lingură ghimbir ras","1 linguriță turmeric","1 linguriță scorțișoară","1 linguriță chimion","1 lămâie murată tăiată","100 g măsline verzi","mărar, coriandru, ulei de măsline, sare"],
        'en':["800 g lamb or chicken, cut into pieces","2 onions","3 garlic cloves","1 tbsp grated ginger","1 tsp turmeric","1 tsp cinnamon","1 tsp cumin","1 preserved lemon, sliced","100 g green olives","coriander, parsley, olive oil, salt"],
        'es':["800 g de cordero o pollo en trozos","2 cebollas","3 dientes de ajo","1 cda de jengibre rallado","1 cdta de cúrcuma","1 cdta de canela","1 cdta de comino","1 limón en conserva en rodajas","100 g de aceitunas verdes","cilantro, perejil, aceite de oliva, sal"],
        'fr':["800 g d'agneau ou de poulet en morceaux","2 oignons","3 gousses d'ail","1 c. à s. de gingembre râpé","1 c. à c. de curcuma","1 c. à c. de cannelle","1 c. à c. de cumin","1 citron confit en tranches","100 g d'olives vertes","coriandre, persil, huile d'olive, sel"],
        'de':["800 g Lamm oder Hähnchen, in Stücke","2 Zwiebeln","3 Knoblauchzehen","1 EL geriebener Ingwer","1 TL Kurkuma","1 TL Zimt","1 TL Kreuzkümmel","1 Salzzitrone, geschnitten","100 g grüne Oliven","Koriander, Petersilie, Olivenöl, Salz"],
        'pt':["800 g de borrego ou frango em pedaços","2 cebolas","3 dentes de alho","1 colher de sopa de gengibre ralado","1 colher de chá de cúrcuma","1 colher de chá de canela","1 colher de chá de cominho","1 limão em conserva às rodelas","100 g de azeitonas verdes","coentros, salsa, azeite, sal"],
        'ru':["800 г баранины или курицы, кусочками","2 луковицы","3 зубчика чеснока","1 ст. л. тёртого имбиря","1 ч. л. куркумы","1 ч. л. корицы","1 ч. л. зиры","1 солёный лимон, нарезанный","100 г зелёных оливок","кинза, петрушка, оливковое масло, соль"],
        'ar':["800 غ لحم ضأن أو دجاج قطع","2 بصلة","3 فصوص ثوم","1 ملعقة كبيرة زنجبيل مبشور","1 ملعقة صغيرة كركم","1 ملعقة صغيرة قرفة","1 ملعقة صغيرة كمون","1 ليمونة مخللة بشرائح","100 غ زيتون أخضر","كزبرة، بقدونس، زيت زيتون، ملح"],
        'zh':["羊肉或鸡肉800克，切块","洋葱2个","大蒜3瓣","姜末1汤匙","姜黄1茶匙","肉桂1茶匙","孜然1茶匙","腌柠檬1个，切片","青橄榄100克","香菜、欧芹、橄榄油、盐"],
        'ja':["ラム肉または鶏肉800g（一口大）","玉ねぎ2個","にんにく3片","おろし生姜大さじ1","ターメリック小さじ1","シナモン小さじ1","クミン小さじ1","塩漬けレモン1個（薄切り）","グリーンオリーブ100g","パクチー、パセリ、オリーブオイル、塩"],
        'hi':["800 ग्राम भेड़ या चिकन, टुकड़ों में","2 प्याज़","3 लहसुन की कलियाँ","1 बड़ा चम्मच कद्दूकस अदरक","1 छोटा चम्मच हल्दी","1 छोटा चम्मच दालचीनी","1 छोटा चम्मच जीरा","1 अचारी नींबू, टुकड़ों में","100 ग्राम हरे ज़ैतून","धनिया, पार्सले, ज़ैतून तेल, नमक"],
        'tr':["800 g kuzu veya tavuk, parçalar","2 soğan","3 diş sarımsak","1 yk rendelenmiş zencefil","1 çk zerdeçal","1 çk tarçın","1 çk kimyon","1 tuzlu limon, dilim","100 g yeşil zeytin","kişniş, maydanoz, zeytinyağı, tuz"],
        'it':["800 g di agnello o pollo a pezzi","2 cipolle","3 spicchi d'aglio","1 cucchiaio di zenzero grattugiato","1 cucchiaino di curcuma","1 cucchiaino di cannella","1 cucchiaino di cumino","1 limone in salamoia a fette","100 g di olive verdi","coriandolo, prezzemolo, olio d'oliva, sale"],
        'ko':["양고기 또는 닭고기 800g, 조각","양파 2개","마늘 3쪽","간 생강 1큰술","터메릭 1작은술","계피 1작은술","쿠민 1작은술","소금 절임 레몬 1개, 슬라이스","그린 올리브 100g","고수, 파슬리, 올리브유, 소금"],
    },
    'howIsMade': {
        'ro':"Călește ceapa și usturoiul în ulei într-o tajină sau oală groasă, adaugă mirodeniile și ghimbirul, încinge un minut. Adaugă carnea, rumenește bine. Toarnă 200 ml apă, pune felii de lămâie murată și măsline. Acoperă strâns și fierbe la foc mic 90 min (pui) sau 2 ore (miel). Presară coriandru, servește cu cuscus sau pâine.",
        'en':"Sauté onion and garlic in oil in a tagine or heavy pot, add the spices and ginger, toast 1 minute. Add the meat and brown well. Pour in 200 ml water, add preserved lemon slices and olives. Cover tightly and simmer on low for 90 minutes (chicken) or 2 hours (lamb). Scatter coriander, serve with couscous or bread.",
        'es':"Sofríe cebolla y ajo en aceite en una tajín u olla pesada, añade especias y jengibre, tuesta 1 min. Incorpora la carne y dora bien. Vierte 200 ml de agua, añade el limón en conserva en rodajas y las aceitunas. Tapa bien y cuece a fuego bajo 90 min (pollo) o 2 h (cordero). Espolvorea cilantro, sirve con cuscús o pan.",
        'fr':"Faites suer oignon et ail dans l'huile dans une tajine ou cocotte épaisse, ajoutez les épices et le gingembre, faites griller 1 min. Mettez la viande et faites bien dorer. Versez 200 ml d'eau, ajoutez le citron confit et les olives. Couvrez et mijotez à feu doux 90 min (poulet) ou 2 h (agneau). Parsemez de coriandre, servez avec couscous ou pain.",
        'de':"Zwiebel und Knoblauch in der Tajine oder einem schweren Topf in Öl andünsten, Gewürze und Ingwer hinzufügen, 1 Min. anrösten. Fleisch zugeben und scharf anbraten. 200 ml Wasser, Salzzitrone und Oliven hinzu. Fest abdecken und 90 Min. (Huhn) bzw. 2 Std. (Lamm) auf kleiner Flamme schmoren. Mit Koriander bestreuen, mit Couscous oder Brot servieren.",
        'pt':"Refogue cebola e alho no azeite numa tagine ou panela pesada, junte as especiarias e o gengibre, torre 1 min. Acrescente a carne e doure bem. Verta 200 ml de água, junte o limão em conserva às rodelas e as azeitonas. Tape bem e coza em lume brando 90 min (frango) ou 2 h (borrego). Polvilhe com coentros, sirva com cuscuz ou pão.",
        'ru':"Спассеруйте лук и чеснок на масле в тажине или тяжёлой кастрюле, добавьте специи и имбирь, прокалите 1 минуту. Положите мясо и хорошо обжарьте. Влейте 200 мл воды, добавьте ломтики солёного лимона и оливки. Плотно накройте и тушите на малом огне 90 мин (курица) или 2 часа (баранина). Посыпьте кинзой, подавайте с кускусом или хлебом.",
        'ar':"اقلي البصل والثوم في الزيت داخل الطاجين أو قدر ثقيل، أضيفي البهارات والزنجبيل، حمّصيها دقيقة. أضيفي اللحم وحمّريه جيداً. اسكبي 200 مل ماء، أضيفي شرائح الليمون المخلل والزيتون. غطّي بإحكام واطبخي على نار هادئة 90 دقيقة (دجاج) أو ساعتين (ضأن). انثري الكزبرة، قدّمي مع الكسكس أو الخبز.",
        'zh':"塔吉锅或厚锅里用油炒香洋葱大蒜，加入香料和姜末炒1分钟。放入肉煎至上色。倒入200毫升水，加入腌柠檬片和橄榄。盖紧小火炖90分钟（鸡肉）或2小时（羊肉）。撒香菜，配北非小米或面包享用。",
        'ja':"タジン鍋または重い鍋にオイルを熱し、玉ねぎとにんにくを炒め、スパイスと生姜を加えて1分。肉を入れてしっかり焼き色をつける。水200mlを注ぎ、塩漬けレモンとオリーブを加える。きっちり蓋をして弱火で90分（鶏）または2時間（ラム）煮込む。パクチーを散らし、クスクスまたはパンと一緒に。",
        'hi':"ताजीन या भारी बर्तन में तेल में प्याज़ और लहसुन भूनें, मसाले और अदरक डालकर 1 मिनट भूनें। मांस डालकर अच्छा सुनहरा करें। 200 मिली पानी डालें, अचारी नींबू और ज़ैतून डालें। कसकर ढक्कन लगाएँ और धीमी आँच पर 90 मिनट (चिकन) या 2 घंटे (भेड़) पकाएँ। धनिया छिड़कें, कसकस या रोटी के साथ परोसें।",
        'tr':"Tajin veya ağır bir tencerede zeytinyağında soğan ve sarımsağı kavurun, baharatları ve zencefili ekleyip 1 dakika kavurun. Eti ekleyip iyice kızartın. 200 ml su ekleyin, tuzlu limon dilimleri ve zeytinleri katın. Sıkıca kapatın ve kısık ateşte 90 dakika (tavuk) ya da 2 saat (kuzu) pişirin. Üzerine kişniş, kuskus veya ekmekle servis edin.",
        'it':"Soffriggi cipolla e aglio in olio in una tajine o pentola pesante, aggiungi le spezie e lo zenzero, tosta 1 minuto. Unisci la carne e rosolala bene. Versa 200 ml di acqua, aggiungi limone in salamoia a fette e olive. Copri ermeticamente e cuoci a fuoco basso 90 minuti (pollo) o 2 ore (agnello). Cospargi di coriandolo, servi con cous cous o pane.",
        'ko':"타진 냄비나 두꺼운 냄비에 기름을 두르고 양파와 마늘을 볶고, 향신료와 생강을 넣어 1분 볶습니다. 고기를 넣고 잘 익혀 색을 냅니다. 물 200ml를 붓고, 슬라이스 절임 레몬과 올리브를 넣습니다. 뚜껑을 꼭 덮고 약한 불에서 90분(닭) 또는 2시간(양) 끓입니다. 고수를 흩뿌리고 쿠스쿠스 또는 빵과 함께 냅니다.",
    },
    'originText': {
        'ro':"Tajina e oala-conică din lut a Berberilor, dar și mâncarea care fierbe lent în ea — miel sau pui topit cu lămâie murată, măsline verzi, turmeric și scorțișoară, parfumul Marrakech-ului în jurul mesei.",
        'en':"The tagine is both the conical clay pot of the Berbers and the slow-cooked dish that bubbles inside it — lamb or chicken melting with preserved lemon, green olives, turmeric and cinnamon, the smell of Marrakech around the table.",
        'es':"El tajín es a la vez la olla cónica de barro de los bereberes y el guisado de cocción lenta que burbujea dentro — cordero o pollo que se deshace con limón en conserva, aceitunas verdes, cúrcuma y canela, el olor de Marrakech alrededor de la mesa.",
        'fr':"La tajine, c'est à la fois le plat conique en terre cuite des Berbères et le mijoté qui bouillonne dedans — agneau ou poulet fondant avec citron confit, olives vertes, curcuma et cannelle, l'odeur de Marrakech autour de la table.",
        'de':"Die Tajine ist sowohl der kegelförmige Tontopf der Berber als auch das langsam gegarte Gericht, das darin köchelt — Lamm oder Hähnchen, das mit Salzzitrone, grünen Oliven, Kurkuma und Zimt zergeht, der Duft von Marrakesch rund um den Tisch.",
        'pt':"A tajine é ao mesmo tempo o tacho cónico de barro dos berberes e o estufado de cozedura lenta que borbulha dentro — borrego ou frango a desfazer-se com limão em conserva, azeitonas verdes, cúrcuma e canela, o cheiro de Marraquexe à volta da mesa.",
        'ru':"Тажин — это одновременно конический глиняный горшок берберов и блюдо медленного томления внутри: баранина или курица тает с солёным лимоном, зелёными оливками, куркумой и корицей, запах Марракеша вокруг стола.",
        'ar':"الطاجين هو القدر المخروطي الفخاري للبربر، وفي الوقت نفسه الطبق الذي يطهى ببطء داخله — ضأن أو دجاج يذوب مع الليمون المخلل والزيتون الأخضر والكركم والقرفة، عبق مراكش حول المائدة.",
        'zh':"Tagine 既是柏柏尔人锥形陶锅的名字，也是在锅里慢炖的菜——羊肉或鸡肉在腌柠檬、青橄榄、姜黄与肉桂里酥烂，餐桌四周飘着马拉喀什的香气。",
        'ja':"タジンはベルベル人の円錐形の土鍋であり、その中でゆっくり煮込まれる料理でもある — ラム肉や鶏肉が塩漬けレモン、グリーンオリーブ、ターメリック、シナモンと一緒にほろほろに溶け、食卓にはマラケシュの香りが立ち上る。",
        'hi':"ताजीन बर्बर लोगों का शंक्वाकार मिट्टी का बर्तन भी है और उसमें धीमी आँच पर पका व्यंजन भी — भेड़ या चिकन अचारी नींबू, हरे ज़ैतून, हल्दी और दालचीनी में पिघलता है, मेज़ के चारों ओर मराकेश की खुशबू।",
        'tr':"Tajin hem Berberilerin konik kil çömleğinin hem de içinde ağır ateşte pişen yemeğin adıdır — kuzu ya da tavuk tuzlu limon, yeşil zeytin, zerdeçal ve tarçınla erir, masanın etrafına Marakeş kokusu yayılır.",
        'it':"La tajine è insieme la pentola conica di terracotta dei berberi e il piatto a cottura lenta che bolle dentro — agnello o pollo che si scioglie con limone in salamoia, olive verdi, curcuma e cannella, il profumo di Marrakech intorno alla tavola.",
        'ko':"타진은 베르베르인의 원뿔형 토기 이름이자 그 안에서 천천히 익는 요리의 이름이다 — 양고기나 닭이 절임 레몬, 그린 올리브, 터메릭, 계피 속에서 부드럽게 풀리고, 식탁 주변에는 마라케시의 향기가 감돈다.",
    },
})

# ── 225. Ramen ─────────────────────────────────────────────────────────
RECIPES.append({
    'id': 225, 'tipType': 'soup', 'pairingsType': 'asian',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Shoyu_Ramen.jpg/330px-Shoyu_Ramen.jpg',
    'name': {
        'ro':"Ramen",'en':"Ramen",'es':"Ramen",'fr':"Ramen",'de':"Ramen",'pt':"Ramen",
        'ru':"Рамэн",'ar':"رامن",'zh':"拉面",'ja':"ラーメン",'hi':"रामेन",'tr':"Ramen",
        'it':"Ramen",'ko':"라멘",
    },
    'origin': {
        'ro':"Japonia",'en':"Japan",'es':"Japón",'fr':"Japon",'de':"Japan",'pt':"Japão",
        'ru':"Япония",'ar':"اليابان",'zh':"日本",'ja':"日本",'hi':"जापान",'tr':"Japonya",
        'it':"Giappone",'ko':"일본",
    },
    'category': {
        'ro':"Cină",'en':"Dinner",'es':"Cena",'fr':"Dîner",'de':"Abendessen",'pt':"Jantar",
        'ru':"Ужин",'ar':"عشاء",'zh':"晚餐",'ja':"夕食",'hi':"रात का खाना",'tr':"Akşam yemeği",
        'it':"Cena",'ko':"저녁",
    },
    'ingredients': {
        'ro':["400 g tăiței ramen proaspeți","1,5 l supă de pui sau dashi","4 linguri shoyu (sos de soia)","2 linguri miso (opțional)","300 g piept de pui sau chashu (porc)","4 ouă fierte 7 min","2 cepe verzi","100 g muguri de bambus","nori, ulei de susan"],
        'en':["400 g fresh ramen noodles","1.5 L chicken stock or dashi","4 tbsp shoyu (soy sauce)","2 tbsp miso (optional)","300 g chicken breast or chashu pork","4 eggs (7-minute soft-boiled)","2 spring onions","100 g bamboo shoots","nori, sesame oil"],
        'es':["400 g de fideos ramen frescos","1,5 L de caldo de pollo o dashi","4 cdas de shoyu (salsa de soja)","2 cdas de miso (opcional)","300 g de pechuga de pollo o chashu","4 huevos pasados por agua 7 min","2 cebollas tiernas","100 g de brotes de bambú","nori, aceite de sésamo"],
        'fr':["400 g de nouilles ramen fraîches","1,5 L de bouillon de poulet ou dashi","4 c. à s. de shoyu (sauce soja)","2 c. à s. de miso (facultatif)","300 g de blanc de poulet ou chashu","4 œufs mollets (7 min)","2 ciboules","100 g de pousses de bambou","nori, huile de sésame"],
        'de':["400 g frische Ramen-Nudeln","1,5 L Hühnerbrühe oder Dashi","4 EL Shoyu (Sojasauce)","2 EL Miso (optional)","300 g Hähnchenbrust oder Chashu","4 Eier (7 Min. wachsweich)","2 Frühlingszwiebeln","100 g Bambussprossen","Nori, Sesamöl"],
        'pt':["400 g de noodles ramen frescos","1,5 L de caldo de galinha ou dashi","4 colheres de sopa de shoyu (molho de soja)","2 colheres de sopa de miso (opcional)","300 g de peito de frango ou chashu","4 ovos cozidos 7 min","2 cebolinhas verdes","100 g de rebentos de bambu","nori, óleo de gergelim"],
        'ru':["400 г свежей лапши рамэн","1,5 л куриного бульона или даси","4 ст. л. сёю (соевый соус)","2 ст. л. мисо (по желанию)","300 г куриной грудки или тясю","4 яйца всмятку (7 минут)","2 зелёных лука","100 г побегов бамбука","нори, кунжутное масло"],
        'ar':["400 غ نودلز رامن طازج","1.5 لتر مرق دجاج أو دشي","4 ملاعق كبيرة شويو (صلصة صويا)","2 ملعقة كبيرة ميسو (اختياري)","300 غ صدر دجاج أو تشاشو لحم خنزير","4 بيضات مسلوقة 7 دقائق","2 بصلة خضراء","100 غ براعم خيزران","نوري، زيت سمسم"],
        'zh':["新鲜拉面400克","鸡高汤或柴鱼高汤1.5升","酱油（shoyu）4汤匙","味噌2汤匙（可选）","鸡胸或叉烧肉300克","水煮7分钟溏心蛋4个","葱2根","笋丝100克","海苔、麻油"],
        'ja':["生ラーメン麺400g","鶏ガラだしまたは出汁1.5L","醤油大さじ4","味噌大さじ2（お好み）","鶏むね肉またはチャーシュー300g","半熟卵4個（7分茹で）","青ねぎ2本","メンマ100g","のり、ごま油"],
        'hi':["400 ग्राम ताज़ा रामेन नूडल्स","1.5 लीटर चिकन स्टॉक या दाशी","4 बड़े चम्मच शोयू (सोया सॉस)","2 बड़े चम्मच मिसो (वैकल्पिक)","300 ग्राम चिकन ब्रेस्ट या चाशू","4 अंडे 7 मिनट हल्के उबले","2 हरी प्याज़","100 ग्राम बैम्बू शूट्स","नोरी, तिल का तेल"],
        'tr':["400 g taze ramen makarnası","1,5 L tavuk suyu veya dashi","4 yk shoyu (soya sosu)","2 yk miso (isteğe bağlı)","300 g tavuk göğsü veya chashu domuz","4 yumurta (7 dakika)","2 yeşil soğan","100 g bambu filizi","nori, susam yağı"],
        'it':["400 g di noodles ramen freschi","1,5 L di brodo di pollo o dashi","4 cucchiai di shoyu (salsa di soia)","2 cucchiai di miso (facoltativo)","300 g di petto di pollo o chashu","4 uova sode 7 minuti","2 cipollotti","100 g di germogli di bambù","nori, olio di sesamo"],
        'ko':["신선한 라멘면 400g","치킨 스톡 또는 다시 1.5L","쇼유(간장) 4큰술","미소 2큰술(선택)","닭가슴살 또는 차슈 300g","반숙 달걀 4개(7분)","쪽파 2대","죽순 100g","김, 참기름"],
    },
    'howIsMade': {
        'ro':"Pune supa la fiert cu shoyu și miso, ajustează gustul. Fierbe tăițeii separat 2 min în apă clocotită, scurge. Felii subțiri de pui/chashu. În boluri largi pune tăițeii, toarnă supa fierbinte, aranjează carnea, jumătățile de ou, ceapa verde, bambusul, nori. Stropește cu ulei de susan. Servește imediat, foarte fierbinte.",
        'en':"Bring the stock to a simmer with shoyu and miso, taste. Boil noodles separately for 2 minutes in boiling water, drain. Slice chicken/chashu thinly. In wide bowls add noodles, pour hot stock over, arrange meat, egg halves, spring onion, bamboo, nori. Drizzle with sesame oil. Serve immediately and very hot.",
        'es':"Lleva el caldo a fuego suave con shoyu y miso, ajusta. Cuece los fideos aparte 2 min en agua hirviendo, escurre. Lonchea pollo/chashu fino. En cuencos anchos pon fideos, vierte caldo caliente, coloca carne, mitades de huevo, cebollino, bambú, nori. Riega con aceite de sésamo. Sirve enseguida muy caliente.",
        'fr':"Portez le bouillon à frémissement avec le shoyu et le miso, goûtez. Cuisez les nouilles à part 2 min dans l'eau bouillante, égouttez. Tranchez finement poulet/chashu. Dans des bols larges mettez les nouilles, versez le bouillon brûlant, disposez viande, demi-œufs, ciboule, bambou, nori. Filet d'huile de sésame. Servez aussitôt très chaud.",
        'de':"Brühe mit Shoyu und Miso erhitzen, abschmecken. Nudeln separat 2 Min. in kochendem Wasser garen, abgießen. Hähnchen/Chashu dünn schneiden. In weite Schüsseln Nudeln geben, heiße Brühe darübergießen, Fleisch, halbierte Eier, Frühlingszwiebel, Bambussprossen und Nori anrichten. Mit Sesamöl beträufeln. Sehr heiß und sofort servieren.",
        'pt':"Leve o caldo a fervura suave com shoyu e miso, prove. Coza os noodles separadamente 2 min em água a ferver, escorra. Fatie frango/chashu fino. Em tigelas largas ponha os noodles, verta caldo quente, disponha carne, metades de ovo, cebolinho, rebentos, nori. Regue com óleo de gergelim. Sirva já bem quente.",
        'ru':"Доведите бульон до слабого кипения с сёю и мисо, попробуйте. Сварите лапшу отдельно 2 минуты в кипятке, слейте. Курицу/тясю тонко нарежьте. В широкие миски положите лапшу, залейте горячим бульоном, разложите мясо, половинки яиц, зелёный лук, бамбук, нори. Сбрызните кунжутным маслом. Подавайте сразу, очень горячим.",
        'ar':"سخّني المرق على نار هادئة مع الشويو والميسو، تذوّقي. اسلقي النودلز منفصلاً دقيقتين في ماء يغلي وصفّيه. قطّعي الدجاج/التشاشو شرائح رفيعة. في أوعية واسعة ضعي النودلز، اسكبي المرق الساخن، ورتّبي اللحم وأنصاف البيض والبصل الأخضر والخيزران والنوري. اسكبي زيت السمسم. قدّمي فوراً ساخناً جداً.",
        'zh':"高汤加酱油、味噌煮开，调味。面条另起锅在开水中煮2分钟后捞出。鸡肉/叉烧切薄片。宽碗中放入面条，浇上热高汤，摆放肉、半颗溏心蛋、葱花、笋丝、海苔。淋几滴麻油。趁极热立即上桌。",
        'ja':"スープを醤油と味噌で味を調え、温める。麺は別鍋で熱湯に2分茹で、湯切りする。鶏むね/チャーシューは薄切り。広い丼に麺を入れ、熱々のスープを注ぎ、肉、半分に割った卵、青ねぎ、メンマ、のりを盛り付ける。仕上げにごま油をひと垂らし。熱いうちに即座に提供。",
        'hi':"स्टॉक को शोयू और मिसो के साथ धीमी आँच पर गरम करें, स्वाद देखें। नूडल्स अलग बर्तन में 2 मिनट उबालकर छान लें। चिकन/चाशू पतली स्लाइस में काटें। चौड़े बाउल में नूडल्स रखें, ऊपर गरम स्टॉक डालें, मांस, अंडे के आधे टुकड़े, हरी प्याज़, बैम्बू, नोरी सजाएँ। तिल के तेल की कुछ बूँदें छिड़कें। बहुत गरम और तुरंत परोसें।",
        'tr':"Et suyunu shoyu ve miso ile kısık ateşte ısıtın, tadına bakın. Makarnayı ayrı bir tencerede kaynar suda 2 dakika haşlayıp süzün. Tavuk/chashu'yu ince dilimleyin. Geniş kâselere makarnayı koyun, üzerine sıcak suyu dökün; eti, ikiye bölünmüş yumurtaları, yeşil soğanı, bambu filizini ve noriyi yerleştirin. Susam yağı gezdirin. Çok sıcakken hemen servis edin.",
        'it':"Porta il brodo a sobbollire con shoyu e miso, assaggia. Cuoci i noodles a parte 2 minuti in acqua bollente, scola. Affetta sottile il pollo/chashu. In ciotole larghe metti i noodles, versa il brodo bollente, disponi carne, metà delle uova, cipollotto, germogli di bambù e nori. Un filo di olio di sesamo. Servi subito, bollente.",
        'ko':"육수에 쇼유와 미소를 넣고 약한 불에서 끓이며 간을 봅니다. 면은 따로 끓는 물에 2분 삶아 건집니다. 닭가슴/차슈는 얇게 슬라이스. 넓은 그릇에 면을 담고 뜨거운 육수를 부은 뒤 고기, 반으로 자른 달걀, 쪽파, 죽순, 김을 올립니다. 마무리에 참기름 약간. 아주 뜨거울 때 즉시 냅니다.",
    },
    'originText': {
        'ro':"Ramenul — bol fierbinte cu tăiței, supă lungă, ouă cu gălbenuș moale și nori — a venit în Japonia din China la sfârșitul secolului XIX și s-a rescris în zeci de regionalisme: shoyu, miso, tonkotsu, shio. Hrana favorită a noilor nopți.",
        'en':"Ramen — a hot bowl of noodles, long-simmered broth, soft-yolk eggs and nori — came to Japan from China in the late 19th century and was rewritten into dozens of regional styles: shoyu, miso, tonkotsu, shio. The favourite food of long nights.",
        'es':"El ramen — un cuenco humeante de fideos, caldo de larga cocción, huevos de yema blanda y nori — llegó a Japón desde China a fines del s. XIX y se reescribió en decenas de estilos regionales: shoyu, miso, tonkotsu, shio. La comida favorita de las noches largas.",
        'fr':"Le ramen — un bol brûlant de nouilles, bouillon longuement mijoté, œufs au jaune coulant et nori — est venu au Japon depuis la Chine à la fin du XIXᵉ siècle et s'est réécrit en dizaines de styles régionaux : shoyu, miso, tonkotsu, shio. La nourriture des longues nuits.",
        'de':"Ramen — eine dampfende Schale Nudeln, lange gekochte Brühe, weiches Eigelb und Nori — kam Ende des 19. Jahrhunderts aus China nach Japan und wurde in Dutzenden regionaler Stile neu geschrieben: Shoyu, Miso, Tonkotsu, Shio. Das Lieblingsessen der langen Nächte.",
        'pt':"O ramen — uma tigela fumegante de noodles, caldo de longa cozedura, ovos com gema mole e nori — chegou ao Japão vindo da China no fim do séc. XIX e foi reescrito em dezenas de estilos regionais: shoyu, miso, tonkotsu, shio. A comida favorita das noites longas.",
        'ru':"Рамэн — горячая миска лапши, долго варенного бульона, яиц с жидким желтком и нори — пришёл в Японию из Китая в конце XIX века и переписался в десятки региональных стилей: сёю, мисо, тонкоцу, сио. Любимая еда долгих ночей.",
        'ar':"الرامن — وعاء ساخن من النودلز ومرق طويل التحضير وبيض بصفار طري وأوراق نوري — جاء إلى اليابان من الصين أواخر القرن التاسع عشر، وأعيد كتابته بعشرات الأنماط المحلية: شويو، ميسو، تونكوتسو، شيو. طعام الليالي الطويلة المفضّل.",
        'zh':"拉面——一碗滚烫的面条、慢熬高汤、半熟蛋黄与海苔——19世纪末从中国传入日本，又被改写成几十种地方流派：酱油、味噌、豚骨、盐味。是漫漫长夜里最爱的一餐。",
        'ja':"ラーメン — 熱々の麺、長時間炊いたスープ、半熟卵、海苔 — は19世紀末に中国から日本へ伝わり、醤油、味噌、豚骨、塩など何十もの地域の流派へと書き換えられた。長い夜のいちばんの食べ物。",
        'hi':"रामेन — गरम नूडल्स का कटोरा, घंटों उबला स्टॉक, मुलायम जर्दी वाले अंडे और नोरी — 19वीं सदी के अंत में चीन से जापान आया और दर्ज़नों क्षेत्रीय शैलियों में फिर से लिखा गया: शोयू, मिसो, टोनकोत्सु, शियो। लंबी रातों का प्रिय भोजन।",
        'tr':"Ramen — sıcacık bir kâse makarna, uzun pişen et suyu, yumuşak sarılı yumurta ve nori — 19. yüzyıl sonunda Çin'den Japonya'ya geçti ve onlarca bölgesel tarza yeniden yazıldı: shoyu, miso, tonkotsu, shio. Uzun gecelerin en sevilen yemeği.",
        'it':"Il ramen — una ciotola fumante di noodles, brodo a lunga cottura, uova con tuorlo morbido e nori — è arrivato in Giappone dalla Cina alla fine dell'Ottocento e si è riscritto in decine di stili regionali: shoyu, miso, tonkotsu, shio. Il cibo preferito delle notti lunghe.",
        'ko':"라멘은 뜨거운 면 한 그릇, 오래 끓인 육수, 반숙 달걀, 김을 담은 음식으로, 19세기 말 중국에서 일본으로 건너와 쇼유·미소·돈코쓰·시오 등 수십 가지 지역 스타일로 다시 쓰였다. 긴 밤이 가장 좋아하는 음식.",
    },
})

# ── 226. Vietnamese Spring Rolls (gỏi cuốn) ───────────────────────────
RECIPES.append({
    'id': 226, 'tipType': 'asian', 'pairingsType': 'asian',
    'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/G%E1%BB%8Fi_cu%E1%BB%91n_t%C3%B4m_th%E1%BB%8Bt%2C_2_qu%E1%BA%A7y_TLC_v%C3%A0_b%C3%A1nh_x%C3%B2.JPG/330px-G%E1%BB%8Fi_cu%E1%BB%91n_t%C3%B4m_th%E1%BB%8Bt%2C_2_qu%E1%BA%A7y_TLC_v%C3%A0_b%C3%A1nh_x%C3%B2.JPG',
    'name': {
        'ro':"Rulouri vietnameze proaspete",'en':"Vietnamese Spring Rolls",'es':"Rollitos de primavera vietnamitas",'fr':"Rouleaux de printemps vietnamiens",
        'de':"Vietnamesische Sommerrollen",'pt':"Rolinhos primavera vietnamitas",'ru':"Вьетнамские свежие роллы",'ar':"لفائف الربيع الفيتنامية",
        'zh':"越南春卷",'ja':"生春巻き",'hi':"वियतनामी स्प्रिंग रोल्स",'tr':"Vietnam tazesi sarması",
        'it':"Involtini primavera vietnamiti",'ko':"베트남 월남쌈",
    },
    'origin': {
        'ro':"Vietnam",'en':"Vietnam",'es':"Vietnam",'fr':"Vietnam",'de':"Vietnam",'pt':"Vietname",
        'ru':"Вьетнам",'ar':"فيتنام",'zh':"越南",'ja':"ベトナム",'hi':"वियतनाम",'tr':"Vietnam",
        'it':"Vietnam",'ko':"베트남",
    },
    'category': {
        'ro':"Prânz",'en':"Lunch",'es':"Almuerzo",'fr':"Déjeuner",'de':"Mittagessen",'pt':"Almoço",
        'ru':"Обед",'ar':"غداء",'zh':"午餐",'ja':"昼食",'hi':"दोपहर का भोजन",'tr':"Öğle yemeği",
        'it':"Pranzo",'ko':"점심",
    },
    'ingredients': {
        'ro':["12 foi de orez (bánh tráng)","200 g creveți fierți, decojiți","200 g piept de porc fiert, feliat","100 g tăiței de orez fierți","1 castravete","frunze de salată","frunze de mentă proaspătă","frunze de coriandru","sos hoisin sau nước chấm pentru servit"],
        'en':["12 rice paper wrappers (bánh tráng)","200 g cooked prawns, peeled","200 g cooked pork belly, sliced","100 g cooked rice vermicelli","1 cucumber","lettuce leaves","fresh mint leaves","fresh coriander leaves","hoisin or nước chấm sauce for dipping"],
        'es':["12 papeles de arroz (bánh tráng)","200 g de gambas cocidas, peladas","200 g de panceta de cerdo cocida en lonchas","100 g de fideos de arroz cocidos","1 pepino","hojas de lechuga","hojas de menta fresca","hojas de cilantro fresco","salsa hoisin o nước chấm para mojar"],
        'fr':["12 galettes de riz (bánh tráng)","200 g de crevettes cuites décortiquées","200 g de poitrine de porc cuite tranchée","100 g de vermicelles de riz cuits","1 concombre","feuilles de laitue","feuilles de menthe fraîche","feuilles de coriandre fraîche","sauce hoisin ou nước chấm pour tremper"],
        'de':["12 Reispapierblätter (bánh tráng)","200 g gekochte geschälte Garnelen","200 g gekochter Schweinebauch, in Scheiben","100 g gekochte Reisnudeln","1 Salatgurke","Salatblätter","frische Minzeblätter","frische Korianderblätter","Hoisin- oder Nước-chấm-Sauce zum Tunken"],
        'pt':["12 folhas de papel de arroz (bánh tráng)","200 g de camarões cozidos, descascados","200 g de barriga de porco cozida, fatiada","100 g de aletria de arroz cozida","1 pepino","folhas de alface","folhas de hortelã fresca","folhas de coentros frescos","molho hoisin ou nước chấm para mergulhar"],
        'ru':["12 листов рисовой бумаги (bánh tráng)","200 г варёных очищенных креветок","200 г варёной свиной грудинки, ломтиками","100 г варёной рисовой вермишели","1 огурец","листья салата","свежая мята","свежая кинза","соус хойсин или nước chấm для соуса"],
        'ar':["12 ورقة أرز (bánh tráng)","200 غ روبيان مسلوق ومقشّر","200 غ بطن خنزير مسلوق بشرائح","100 غ شعيرية أرز مسلوقة","1 خيار","أوراق خس","أوراق نعناع طازجة","أوراق كزبرة طازجة","صلصة هويسن أو nước chấm للتغميس"],
        'zh':["米纸（bánh tráng）12张","煮熟去壳虾200克","煮熟切片五花肉200克","煮熟米粉100克","黄瓜1根","生菜叶","新鲜薄荷叶","新鲜香菜叶","海鲜酱或越南鱼露蘸料"],
        'ja':["ライスペーパー（バインチャン）12枚","茹でて殻をむいたエビ200g","茹でた豚バラ薄切り200g","茹でた米麺100g","きゅうり1本","レタスの葉","フレッシュミント","フレッシュパクチー","ホイシンまたはヌクチャムソース"],
        'hi':["12 राइस पेपर शीट्स (bánh tráng)","200 ग्राम पकाए छिले झींगे","200 ग्राम पका पोर्क बेली, स्लाइस","100 ग्राम पका राइस वर्मीसैली","1 खीरा","सलाद पत्ते","ताज़ा पुदीना","ताज़ा धनिया","होइसिन या nước chấm सॉस डिप के लिए"],
        'tr':["12 pirinç yufkası (bánh tráng)","200 g haşlanmış soyulmuş karides","200 g haşlanmış kuşbaşı domuz pastırması","100 g haşlanmış pirinç şehriye","1 salatalık","marul yaprakları","taze nane","taze kişniş","sos için hoisin veya nước chấm"],
        'it':["12 fogli di carta di riso (bánh tráng)","200 g di gamberi cotti sgusciati","200 g di pancetta di maiale cotta a fette","100 g di vermicelli di riso cotti","1 cetriolo","foglie di lattuga","foglie di menta fresca","foglie di coriandolo fresco","salsa hoisin o nước chấm per intingere"],
        'ko':["라이스 페이퍼 12장(반짱)","익힌 새우 200g, 껍질 벗긴 것","익힌 삼겹살 200g, 슬라이스","익힌 쌀국수 100g","오이 1개","상추 잎","신선한 민트","신선한 고수","찍어 먹을 호이신 또는 느억짬 소스"],
    },
    'howIsMade': {
        'ro':"Pregătește toate ingredientele pe o tavă. Înmoaie o foaie de orez 5 secunde în apă caldă, scoate pe un prosop umed. Așază o frunză de salată, ierburi, tăiței, castravete și 2-3 creveți la marginea apropiată. Rulează strâns ca o burrito, îndoind capetele după prima rotire. Repetă pentru fiecare. Servește cu sos hoisin sau nước chấm.",
        'en':"Lay out all the ingredients on a tray. Soak one rice paper in warm water for 5 seconds, transfer to a damp tea towel. Place a lettuce leaf, herbs, noodles, cucumber and 2-3 prawns near one edge. Roll tightly like a burrito, folding the sides in after the first turn. Repeat for each. Serve with hoisin or nước chấm sauce.",
        'es':"Dispón los ingredientes en una bandeja. Moja una hoja de arroz 5 segundos en agua tibia, pásala a un paño húmedo. Coloca lechuga, hierbas, fideos, pepino y 2-3 gambas en un borde. Enrolla apretado como un burrito, doblando los lados tras la primera vuelta. Repite. Sirve con salsa hoisin o nước chấm.",
        'fr':"Disposez tous les ingrédients sur un plateau. Trempez une galette de riz 5 secondes dans l'eau tiède, posez-la sur un torchon humide. Placez une feuille de laitue, herbes, vermicelles, concombre et 2-3 crevettes près d'un bord. Roulez serré comme un burrito en repliant les côtés après le premier tour. Répétez. Servez avec sauce hoisin ou nước chấm.",
        'de':"Alle Zutaten auf einem Tablett bereitstellen. Ein Reispapierblatt 5 Sekunden in warmes Wasser tauchen, auf ein feuchtes Tuch legen. Salatblatt, Kräuter, Nudeln, Gurke und 2-3 Garnelen an einer Kante platzieren. Fest wie ein Burrito rollen, die Seiten nach der ersten Drehung einschlagen. Wiederholen. Mit Hoisin- oder Nước-chấm-Sauce servieren.",
        'pt':"Disponha todos os ingredientes num tabuleiro. Mergulhe uma folha de arroz 5 segundos em água morna, coloque num pano húmido. Ponha alface, ervas, aletria, pepino e 2-3 camarões num bordo. Enrole apertado como um burrito, dobrando os lados após a primeira volta. Repita. Sirva com molho hoisin ou nước chấm.",
        'ru':"Разложите все ингредиенты на подносе. Замочите рисовый лист в тёплой воде на 5 секунд, переложите на влажное полотенце. На край положите лист салата, зелень, лапшу, огурец и 2-3 креветки. Заверните плотно как буррито, подгибая бока после первого оборота. Повторите. Подавайте с соусом хойсин или nước chấm.",
        'ar':"رتّبي كل المكونات على صينية. اغمسي ورقة أرز في الماء الدافئ 5 ثواني، ضعيها على فوطة مبللة. ضعي ورقة خس وأعشاب وشعيرية وخيار و2-3 روبيان عند طرف. لفّيها بإحكام مثل البوريتو مع طي الجوانب بعد الدورة الأولى. كرّري لكل ورقة. قدّمي مع صلصة هويسن أو nước chấm.",
        'zh':"所有材料摆在托盘上。米纸在温水中浸5秒，移到湿布上。靠近一边铺生菜、香草、米粉、黄瓜、2-3只虾。像卷墨西哥卷一样紧紧卷起，第一圈后折入两侧。重复操作。配海鲜酱或越南鱼露蘸料。",
        'ja':"すべての具をトレイに並べる。ライスペーパーを温水に5秒くぐらせ、湿らせた布巾の上に置く。手前にレタス、ハーブ、米麺、きゅうり、エビ2〜3尾を並べる。最初の一巻きの後で両端を折りたたみ、ブリトーのようにきつく巻く。これを繰り返す。ホイシンまたはヌクチャムを添える。",
        'hi':"सारे सामग्री ट्रे पर रखें। एक राइस पेपर को 5 सेकंड गरम पानी में डुबोएँ, गीले कपड़े पर रखें। एक किनारे पर सलाद पत्ता, हर्ब्स, नूडल्स, खीरा और 2-3 झींगे रखें। बुर्रिटो की तरह कस के लपेटें, पहले मोड़ के बाद किनारे अंदर मोड़ लें। हर एक के लिए दोहराएँ। होइसिन या nước chấm के साथ परोसें।",
        'tr':"Tüm malzemeleri bir tepsiye dizin. Bir pirinç yufkasını 5 saniye ılık suya batırın, ıslak mutfak beziyle örtün. Bir kenara marul, otlar, şehriye, salatalık ve 2-3 karides yerleştirin. Burrito gibi sıkıca sarın; ilk dönüşten sonra yanları içe katlayın. Her yufka için tekrarlayın. Hoisin veya nước chấm sosuyla servis edin.",
        'it':"Disponi tutti gli ingredienti su un vassoio. Immergi una carta di riso 5 secondi in acqua tiepida, trasferiscila su un canovaccio umido. Su un bordo metti una foglia di lattuga, erbe, vermicelli, cetriolo e 2-3 gamberi. Arrotola stretto come un burrito, ripiegando i lati dopo il primo giro. Ripeti. Servi con salsa hoisin o nước chấm.",
        'ko':"모든 재료를 쟁반에 준비합니다. 라이스 페이퍼 한 장을 따뜻한 물에 5초 적셔 젖은 행주 위에 놓습니다. 한 쪽 가장자리에 상추, 허브, 면, 오이, 새우 2-3마리를 놓습니다. 부리토처럼 단단히 말되 첫 번째 굴림 후 양옆을 접어 넣습니다. 각 장 반복. 호이신 또는 느억짬 소스와 함께 냅니다.",
    },
    'originText': {
        'ro':"Gỏi cuốn, 'rulourile proaspete' din sudul Vietnamului, înfășoară creveți, porc fiert, ierburi de grădină și tăiței de orez în foaia translucidă de bánh tráng. Reci, crocante și parfumate de mentă, sunt opusul ușor al rulourilor prăjite.",
        'en':"Gỏi cuốn — the 'fresh rolls' of southern Vietnam — wrap prawns, poached pork, garden herbs and rice vermicelli in a translucent bánh tráng sheet. Cool, crunchy and scented with mint, they are the light opposite of the fried spring roll.",
        'es':"Gỏi cuốn — los 'rollitos frescos' del sur de Vietnam — envuelven gambas, cerdo cocido, hierbas del huerto y fideos de arroz en una hoja translúcida de bánh tráng. Frescos, crujientes y perfumados con menta, son el opuesto ligero del rollito frito.",
        'fr':"Gỏi cuốn — les 'rouleaux frais' du sud du Vietnam — enroulent crevettes, porc poché, herbes du jardin et vermicelles de riz dans une galette translucide de bánh tráng. Frais, croquants, parfumés de menthe, ils sont l'opposé léger des rouleaux frits.",
        'de':"Gỏi cuốn — die 'frischen Rollen' Südvietnams — wickeln Garnelen, pochiertes Schweinefleisch, Gartenkräuter und Reisnudeln in ein durchscheinendes Bánh-tráng-Blatt. Kühl, knackig und nach Minze duftend sind sie das leichte Gegenstück zur frittierten Frühlingsrolle.",
        'pt':"Gỏi cuốn — os 'rolinhos frescos' do sul do Vietname — envolvem camarões, porco cozido, ervas do jardim e aletria de arroz numa folha translúcida de bánh tráng. Frescos, crocantes e perfumados com hortelã, são o oposto leve do rolinho frito.",
        'ru':"Гой куон — 'свежие роллы' Южного Вьетнама — заворачивают креветки, варёную свинину, садовые травы и рисовую вермишель в полупрозрачный лист bánh tráng. Прохладные, хрустящие, с ароматом мяты — лёгкий антипод жареных спринг-роллов.",
        'ar':"غوي كون — 'لفائف الطازجة' من جنوب فيتنام — تلفّ الروبيان ولحم الخنزير المسلوق وأعشاب الحديقة وشعيرية الأرز في ورقة bánh tráng شفافة. باردة ومقرمشة بعطر النعناع، وهي النسخة الخفيفة لنظيراتها المقلية.",
        'zh':"Gỏi cuốn——越南南方的「鲜春卷」——把虾、煮熟的猪肉、园中香草与米粉裹进半透明的米纸里。清凉、爽脆、薄荷飘香，是炸春卷的轻盈反面。",
        'ja':"ゴイクオン — 南ベトナムの「生春巻き」 — はエビ、茹で豚、庭のハーブ、米麺を半透明のバインチャンに包む。冷たく、シャキッとして、ミントの香り。揚げ春巻きの軽やかな対極。",
        'hi':"गोई कुओन — दक्षिण वियतनाम के 'ताज़े रोल्स' — झींगे, उबला पोर्क, बगीचे की हर्ब्स और राइस वर्मीसैली को पारदर्शी bánh tráng में लपेटते हैं। ठंडे, करारे और पुदीने की खुशबू से भरे — तले हुए स्प्रिंग रोल्स के हल्के विपरीत।",
        'tr':"Gỏi cuốn — Güney Vietnam'ın 'taze sarması' — karides, haşlanmış domuz, bahçe otları ve pirinç şehriyesini şeffaf bir bánh tráng yaprağına sarar. Serin, çıtır ve nane kokulu; kızarmış sarmaların hafif karşıtı.",
        'it':"I gỏi cuốn — gli 'involtini freschi' del Vietnam del Sud — avvolgono gamberi, maiale lessato, erbe dell'orto e vermicelli di riso in una sfoglia translucida di bánh tráng. Freschi, croccanti e profumati di menta, sono il contrario leggero degli involtini fritti.",
        'ko':"고이꾸온은 베트남 남부의 '생춘권'으로, 새우, 삶은 돼지고기, 정원 허브, 쌀국수를 반투명 라이스 페이퍼 반짱에 감싼다. 시원하고 아삭하며 민트 향이 감도는 — 튀긴 스프링롤의 가벼운 대척점.",
    },
})
