#!/usr/bin/env python3
"""
Fix Tier C Batch 1a: IDs 47 (Bacalhau à Brás), 49 (Jerk Chicken), 54 (Moules-frites)
Replaces ingredients (quantified) and howIsMade (600–900 ch EN) for all locales.
"""
import re, sys

JS_FILE = "public/js/recipes.js"

def find_recipe_block(content, recipe_id):
    """Return (start, end) of the recipe's JS object block."""
    pattern = re.compile(r'\n  \{\n    id: ' + str(recipe_id) + r',')
    m = pattern.search(content)
    if not m:
        return None, None
    start = m.start()
    depth = 0
    i = start + 1
    while i < len(content):
        c = content[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                end = i + 1
                if end < len(content) and content[end] == ',':
                    end += 1
                return start, end
        i += 1
    return start, len(content)

def find_field_bounds(block, field):
    """Return (start, end) of `    field: { ... },` within block."""
    pat = re.compile(r'\n    ' + re.escape(field) + r': \{')
    m = pat.search(block)
    if not m:
        return None, None
    brace_start = m.end() - 1
    depth = 1
    i = brace_start + 1
    while i < len(block) and depth > 0:
        if block[i] == '{':
            depth += 1
        elif block[i] == '}':
            depth -= 1
        i += 1
    end = i
    if end < len(block) and block[end] == ',':
        end += 1
    return m.start(), end

def replace_field(content, recipe_id, field, new_lines):
    rb_start, rb_end = find_recipe_block(content, recipe_id)
    if rb_start is None:
        print(f"ERROR: recipe {recipe_id} not found"); return content
    block = content[rb_start:rb_end]
    f_start, f_end = find_field_bounds(block, field)
    if f_start is None:
        print(f"ERROR: field '{field}' not found in recipe {recipe_id}"); return content
    new_field = f'\n    {field}: {{\n{new_lines}\n    }},'
    new_block = block[:f_start] + new_field + block[f_end:]
    print(f"  [OK] recipe {recipe_id} {field} replaced")
    return content[:rb_start] + new_block + content[rb_end:]

# ============================================================
# RECIPE 47 – Bacalhau à Brás
# ============================================================

INGR_47 = """\
      ro: ["500g cod sărat (bacalhau), înmuiat 24–48h și desfăcut în fâșii", "600g cartofi cerați, curățați și tăiați în bețișoare foarte subțiri", "6 ouă mari, ușor bătute", "2 cepe medii albe, tăiate felii subțiri", "4 linguri ulei de măsline extravirgin", "3 căței de usturoi, tăiați felii subțiri", "Legătură mică de pătrunjel proaspăt, tocat grosier", "80g măsline negre, fără sâmburi", "Sare și piper alb"],
      en: ["500g salted cod (bacalhau), soaked 24–48h in cold water and shredded into flakes", "600g waxy potatoes, peeled and cut into very thin matchstick strips", "6 large eggs, lightly beaten", "2 medium white onions, thinly sliced", "4 tbsp extra-virgin olive oil", "3 garlic cloves, thinly sliced", "Small bunch of fresh flat-leaf parsley, roughly chopped", "80g black olives, pitted, to serve", "Salt and white pepper to taste"],
      es: ["500g de bacalao salado, remojado 24–48h y desmenuzado", "600g de patatas cerosas, peladas y en tiras finas", "6 huevos grandes, ligeramente batidos", "2 cebollas medianas blancas, en láminas finas", "4 cucharadas de aceite de oliva virgen extra", "3 dientes de ajo, en láminas finas", "Ramillete pequeño de perejil fresco, picado grueso", "80g de aceitunas negras sin hueso", "Sal y pimienta blanca al gusto"],
      fr: ["500g de morue salée, dessalée 24–48h et effilochée", "600g de pommes de terre à chair ferme, épluchées et taillées en fins bâtonnets", "6 grands œufs, légèrement battus", "2 oignons blancs moyens, émincés finement", "4 cuillères à soupe d'huile d'olive extra vierge", "3 gousses d'ail, émincées", "Petite botte de persil plat frais, grossièrement haché", "80g d'olives noires dénoyautées", "Sel et poivre blanc"],
      de: ["500g Salzkabeljau (Bacalhau), 24–48h gewässert und zerpflückt", "600g festkochende Kartoffeln, in sehr dünne Streichholzstreifen geschnitten", "6 große Eier, leicht verquirlt", "2 mittelgroße weiße Zwiebeln, in dünne Scheiben geschnitten", "4 EL Olivenöl extra vergine", "3 Knoblauchzehen, in dünne Scheiben", "Kleines Bund glatte Petersilie, grob gehackt", "80g schwarze Oliven, entkernt", "Salz und weißer Pfeffer"],
      pt: ["500g de bacalhau salgado, demolhado 24–48h e desfiado", "600g de batatas de polpa firme, em palha muito fina", "6 ovos grandes, levemente batidos", "2 cebolas médias brancas, em fatias finas", "4 colheres de sopa de azeite extra virgem", "3 dentes de alho, em fatias finas", "Molhinho de salsa fresca, picada grosseiramente", "80g de azeitonas pretas sem caroço", "Sal e pimenta branca a gosto"],
      ru: ["500г солёной трески, вымоченной 24–48ч и разобранной на хлопья", "600г твёрдого картофеля, нарезанного очень тонкими соломками", "6 крупных яиц, слегка взбитых", "2 средние белые луковицы, тонко нарезанные", "4 ст.л. оливкового масла extra virgin", "3 зубчика чеснока, тонко нарезанных", "Небольшой пучок плоской петрушки, крупно нарубленный", "80г чёрных оливок без косточек", "Соль и белый перец по вкусу"],
      ar: ["500 غ سمك قد مملح منقوع 24–48 ساعة ومفتت", "600 غ بطاطس متماسكة مقشرة ومقطعة شرائح رفيعة", "6 بيضات كبيرة مخفوقة قليلاً", "بصلتان بيضاوان متوسطتان مقطعتان شرائح رفيعة", "4 ملاعق كبيرة زيت زيتون بكر ممتاز", "3 فصوص ثوم مقطعة شرائح", "حفنة صغيرة بقدونس طازج مقطعة خشناً", "80 غ زيتون أسود منزوع النوى", "ملح وفلفل أبيض"],
      zh: ["500克盐腌鳕鱼，冷水浸泡24–48小时并撕成鱼片", "600克蜡质土豆，去皮切成极细的火柴棍条", "6个大鸡蛋，轻轻打散", "2个中等白洋葱，切薄片", "4汤匙特级初榨橄榄油", "3瓣大蒜，切薄片", "一小束新鲜平叶欧芹，粗略切碎", "80克去核黑橄榄", "盐和白胡椒粉适量"],
      ja: ["塩ダラ（バカリャウ）500g、冷水に24–48時間浸けてほぐす", "じゃがいも600g、皮をむき極細のマッチ棒状に切る", "卵6個（大）、軽く溶きほぐす", "中玉ねぎ2個、薄切り", "特級エキストラバージンオリーブオイル 大さじ4", "にんにく3片、薄切り", "イタリアンパセリ小束、粗みじん切り", "種抜き黒オリーブ80g", "塩と白こしょう各適量"],
      hi: ["500 ग्राम नमकीन कॉड, 24–48 घंटे ठंडे पानी में भिगोकर टुकड़ों में तोड़ा हुआ", "600 ग्राम मोमी आलू, छीलकर बहुत पतली माचिस जैसी पट्टियों में कटे", "6 बड़े अंडे, हल्के फेंटे हुए", "2 मध्यम सफेद प्याज़, पतले स्लाइस", "4 बड़े चम्मच एक्स्ट्रा-वर्जिन ज़ैतून का तेल", "3 लहसुन की कलियां, पतले स्लाइस", "ताज़े पार्सले का छोटा गुच्छा, मोटा कटा", "80 ग्राम बीज निकाले काले जैतून", "स्वाद अनुसार नमक और सफेद मिर्च"],
      tr: ["500g tuzlu morina, 24–48 saat soğuk suda bekletilmiş ve parçalanmış", "600g sert patates, soyulmuş ve çok ince kibrit şeklinde doğranmış", "6 büyük yumurta, hafifçe çırpılmış", "2 orta boy beyaz soğan, ince dilimlenmiş", "4 yemek kaşığı sızma zeytinyağı", "3 diş sarımsak, ince dilimlenmiş", "Küçük demet taze düz yapraklı maydanoz, kaba doğranmış", "80g çekirdeksiz siyah zeytin", "Tuz ve beyaz biber"],
      it: ["500g di baccalà sotto sale, dissalato 24–48h e sfilacciato", "600g di patate a pasta soda, pelate e tagliate a fiammifero sottile", "6 uova grandi, leggermente sbattute", "2 cipolle bianche medie, affettate sottili", "4 cucchiai di olio extravergine d'oliva", "3 spicchi d'aglio, affettati sottili", "Piccolo mazzo di prezzemolo fresco, tritato grossolanamente", "80g di olive nere snocciolate", "Sale e pepe bianco q.b."],
      ko: ["소금에 절인 대구 500g, 24–48시간 냉수에 불린 뒤 결결이 찢은 것", "분 없는 감자 600g, 껍질 벗겨 매우 얇은 성냥개비 모양으로 자른 것", "달걀 6개, 가볍게 풀어 놓은 것", "중간 크기 흰 양파 2개, 얇게 슬라이스", "엑스트라 버진 올리브오일 4큰술", "마늘 3쪽, 얇게 슬라이스", "신선한 이탈리아 파슬리 한 줌, 굵게 다진 것", "씨 뺀 검은 올리브 80g", "소금과 흰 후추 적당량"]"""

HOW_47 = """\
      ro: "Înmuiați codul desfăcut în apă rece, schimbând apa de patru ori pe parcursul a 24–48 de ore până când un mic bucățel are un gust plăcut sărat. Scurgeți și uscați bine. Tăiați cartofii în bețișoare foarte subțiri. Încălziți 2 cm de ulei neutru într-o tigaie adâncă la 170°C și prăjiți cartofii în tranșe câte 3–4 minute până devin aurii pal. Scurgeți pe hârtie și aruncați uleiul. Ștergeți tigaia. Înfierbântați uleiul de măsline la foc mediu-mic și fierbeți ceapa și usturoiul, amestecând des, 12–15 minute, până devin foarte moi și ușor aurii. Adăugați codul și amestecați 2 minute. Turnați cartofii, amestecați ușor, apoi adăugați ouăle bătute cu piper alb. Amestecați continuu la foc mic cu mișcări largi și lente 2–3 minute — ouăle trebuie să formeze straturi moi și cremoase, niciodată uscate. Luați de pe foc cât timp par ușor necoagulate. Gustați de sare. Presărați pătrunjel și serviți cu măsline.",
      en: "Soak the shredded cod in cold water, changing the water four times over 24–48 hours until a small piece tastes pleasantly savoury rather than sharp. Drain and pat dry. Cut potatoes into very thin matchstick strips. Heat 2cm of neutral oil in a deep frying pan to 170°C and fry the potato strips in batches for 3–4 minutes until pale golden; drain on paper. Discard the frying oil and wipe the pan. Heat olive oil over medium-low heat and cook the onion and garlic, stirring often, for 12–15 minutes until very soft and lightly golden. Add the cod flakes and stir for 2 minutes until warmed through. Tip in the potato strips and toss once. Pour in the beaten eggs seasoned with white pepper. Stir continuously over low heat with slow, wide folds for 2–3 minutes — the eggs should set in soft, creamy layers, never dry or granular. Remove from heat while the eggs still look slightly underdone; residual heat finishes the dish. Taste for salt before adding any — the cod may already hold enough. Scatter with parsley and serve straight from the pan with black olives alongside.",
      es: "Remoje el bacalao desmenuzado en agua fría, cambiando el agua cuatro veces a lo largo de 24–48 horas hasta que un trocito sepa agradablemente salado. Escurra y seque. Corte las patatas en bastones muy finos. Caliente 2cm de aceite neutro en una sartén honda a 170°C y fría las patatas en tandas 3–4 minutos hasta dorar levemente. Escurra en papel y deseche el aceite. Limpie la sartén. Caliente el aceite de oliva a fuego medio-bajo y poche la cebolla y el ajo 12–15 minutos, removiendo a menudo, hasta que estén muy blandos. Añada el bacalao y mezcle 2 minutos. Incorpore las patatas y mezcle suavemente. Vierta los huevos batidos con pimienta blanca. Remueva continuamente a fuego bajo con pliegues lentos y amplios 2–3 minutos — el huevo debe cuajar en capas suaves y cremosas. Retire del fuego mientras el huevo aún parece levemente crudo. Pruebe de sal. Esparza perejil y sirva con aceitunas negras.",
      fr: "Plongez la morue effilochée dans l'eau froide, en changeant l'eau quatre fois sur 24–48 heures jusqu'à ce qu'un morceau ait un goût agréablement salé. Égouttez et épongez. Taillez les pommes de terre en fins bâtonnets. Chauffez 2cm d'huile neutre à 170°C et faites frire les bâtonnets par lots 3–4 minutes jusqu'à légère dorure. Égouttez sur du papier et jetez l'huile. Essuyez la poêle. Faites suer l'oignon et l'ail dans l'huile d'olive à feu moyen-doux en remuant souvent 12–15 minutes. Ajoutez la morue et remuez 2 minutes. Incorporez les bâtonnets de pommes de terre et mélangez doucement. Versez les œufs battus assaisonnés de poivre blanc. Remuez en larges plis lents 2–3 minutes à feu doux — les œufs doivent former de moelleux rubans crémeux. Retirez du feu dès que les œufs semblent légèrement crus. Goûtez le sel. Parsemez de persil et servez avec les olives.",
      de: "Den zerpflückten Kabeljau in kaltem Wasser einweichen, dabei das Wasser viermal in 24–48 Stunden wechseln, bis ein Stück angenehm salzig schmeckt. Abtropfen lassen und trockentupfen. Kartoffeln in sehr dünne Streichholzstreifen schneiden. 2cm neutrales Öl auf 170°C erhitzen und die Kartoffeln portionsweise 3–4 Minuten frittieren, bis sie blass goldfarben sind. Auf Küchenpapier abtropfen, Öl entsorgen, Pfanne auswischen. Olivenöl bei mittlerer bis niedriger Hitze erwärmen, Zwiebeln und Knoblauch unter häufigem Rühren 12–15 Minuten anschwitzen. Kabeljauflocken zugeben und 2 Minuten rühren. Kartoffelstreifen einheben. Verquirlte Eier mit weißem Pfeffer würzen und dazugeben. Bei schwacher Hitze mit langsamen, weiten Falten 2–3 Minuten kontinuierlich rühren — die Eier sollen cremige Schichten bilden, nie trocken. Vom Herd nehmen, solange die Eier noch leicht flüssig wirken. Auf Salz abschmecken. Mit Petersilie und schwarzen Oliven servieren.",
      pt: "Mergulhe o bacalhau desfiado em água fria, mudando a água quatro vezes ao longo de 24–48 horas até ficar agradavelmente salgado. Escorra e seque. Corte as batatas em palha muito fina. Aqueça 2cm de óleo neutro a 170°C e frite as batatas em lotes por 3–4 minutos até dourar levemente. Escorra em papel e descarte o óleo. Limpe a frigideira. Refogue a cebola e o alho no azeite a lume médio-baixo, mexendo frequentemente, por 12–15 minutos. Junte o bacalhau e mexa por 2 minutos. Adicione as batatas e misture com cuidado. Verta os ovos batidos com pimenta branca. Mexa continuamente a lume baixo com dobras lentas e largas por 2–3 minutos — os ovos devem formar camadas suaves e cremosas. Retire do lume enquanto os ovos parecem levemente mal cozidos. Prove de sal. Polvilhe com salsa e sirva com azeitonas.",
      ru: "Залейте кусочки трески холодной водой, меняя её четыре раза за 24–48 часов, пока кусочек не станет приятно солоноватым. Откиньте и обсушите. Нарежьте картофель тонкими соломками. В 2 см нейтрального масла при 170°C обжаривайте соломку порциями 3–4 минуты до светло-золотистого цвета. Обсушите на бумаге, масло слейте. Протрите сковороду. На оливковом масле на слабом огне пассеруйте лук и чеснок, помешивая, 12–15 минут до мягкости. Добавьте треску и мешайте 2 минуты. Всыпьте картофельную соломку и осторожно перемешайте. Влейте взбитые яйца с белым перцем. Постоянно мешайте на слабом огне широкими медленными движениями 2–3 минуты — яйца должны образовать мягкие кремовые складки. Снимите с огня, пока яйца ещё слегка не готовы. Проверьте соль. Посыпьте петрушкой, подайте с оливками.",
      ar: "انقع قطع سمك القد في الماء البارد، غيّر الماء أربع مرات خلال 24–48 ساعة حتى يصبح المذاق لطيفاً مالحاً. اصفِ وجفّف. قطّع البطاطس شرائح رفيعة جداً. في 2 سم من الزيت على 170°C، اقلِ شرائح البطاطس على دفعات 3–4 دقائق حتى تذهب ذهبياً فاتحاً. صفّها على ورق وتخلص من الزيت. امسح المقلاة. سخّن زيت الزيتون على نار متوسطة-منخفضة ولطّف البصل والثوم 12–15 دقيقة مع التقليب المستمر. أضف القد وحرّك دقيقتين. أضف البطاطس وقلّب برفق. صبّ البيض المخفوق بالفلفل الأبيض. حرّك باستمرار بطيّات واسعة وبطيئة 2–3 دقائق على نار هادئة — يجب أن يتشكّل البيض في طيات ناعمة وكريمية. ارفع عن النار بينما البيض لا يزال شبه نيء. تذوّق الملح. رشّ البقدونس وقدّم مع الزيتون الأسود.",
      zh: "将鳕鱼碎在冷水中浸泡，24–48小时内换四次水，直到小块鱼肉有令人愉悦的咸鲜味。沥水擦干。将土豆切成极细的火柴棍条。中性油2厘米加热至170°C，分批炸薯条3–4分钟至淡金色。沥油置于厨房纸上，弃去炸油，擦净锅。中小火热橄榄油，翻炒洋葱和大蒜，频繁搅拌12–15分钟至软烂略金黄。加入鳕鱼翻炒2分钟。放入薯条轻轻翻匀。倒入用白胡椒调味的蛋液。小火持续以宽大缓慢的折叠动作搅拌2–3分钟——蛋液应形成柔软奶油质感，绝不干硬。蛋液看起来仍稍未熟时离火，余温完成最后加热。品尝盐分。撒上欧芹，配黑橄榄上桌。",
      ja: "ほぐした塩ダラを冷水に漬け、24–48時間かけて4回水を換え、小さな一切れが心地よい塩味になるまで続けます。水を切り水気を拭き取ります。じゃがいもを非常に細いマッチ棒状に切ります。深いフライパンに中性油2cmを入れ170°Cに熱し、2回に分けて3–4分ずつ薄く金色になるまで揚げます。キッチンペーパーに取り油を捨て、フライパンを拭きます。オリーブオイルを中弱火で熱し、玉ねぎとにんにくをよく混ぜながら12–15分炒めます。塩ダラを加えて2分混ぜます。じゃがいもを加えて優しく和えます。白こしょうで味付けした溶き卵を流し入れ、弱火でゆっくりと大きく折りたたむように絶えず2–3分混ぜます。卵がまだ少し生っぽく見えるうちに火から下ろし余熱で仕上げます。塩を確認し、パセリを散らし黒オリーブを添えて供します。",
      hi: "कटी हुई कॉड को ठंडे पानी में भिगोएं, 24–48 घंटों में चार बार पानी बदलते हुए, जब तक एक छोटा टुकड़ा सुखद नमकीन न लगे। पानी निकाल कर सुखाएं। आलू को बहुत पतली माचिस जैसी पट्टियों में काटें। एक गहरे फ्राइंग पैन में 2 सेमी न्यूट्रल तेल 170°C तक गर्म करें और आलू की पट्टियां बैचों में 3–4 मिनट फ्राई करें जब तक हल्की सुनहरी न हो जाएं। किचन पेपर पर निकालें, तेल फेंक दें। पैन पोंछें। मध्यम-कम आंच पर ज़ैतून का तेल गर्म करें, प्याज़ और लहसुन बार-बार हिलाते हुए 12–15 मिनट तक पकाएं। कॉड के टुकड़े डालें और 2 मिनट हिलाएं। आलू की पट्टियां डालें और धीरे से मिलाएं। सफ़ेद मिर्च से मसाला किया हुआ फेंटा अंडा डालें। धीमी आंच पर लगातार चौड़े धीमे मोड़ों में 2–3 मिनट हिलाएं — अंडा नरम, मलाईदार परतें बनाए। जब अंडा थोड़ा कच्चा लगे तब आंच से उतारें। नमक चखें। पार्सले छिड़कें और काले जैतून के साथ परोसें।",
      tr: "Parçalanmış morinayı soğuk suya koyun, 24–48 saat içinde dört kez suyu değiştirin; küçük bir parça hoş tuzlu bir tat verinceye kadar bekleyin. Süzün ve kurulayın. Patatesleri çok ince kibrit şeritler halinde kesin. 2cm nötr yağı 170°C'ye ısıtın ve patates şeritlerini partiler halinde 3–4 dakika açık altın rengi olana kadar kızartın. Kağıt havluya alın ve yağı atın. Tavayı silin. Zeytinyağını orta-düşük ateşte ısıtın, sık sık karıştırarak soğan ve sarımsağı 12–15 dakika çok yumuşak olana kadar pişirin. Morinayı ekleyip 2 dakika karıştırın. Patates şeritlerini ekleyip nazikçe karıştırın. Beyaz biberle tatlandırılmış çırpılmış yumurtaları dökün. Düşük ateşte geniş yavaş kıvrımlarla sürekli 2–3 dakika karıştırın — yumurtalar yumuşak, kremsi katmanlar oluşturmalı. Yumurtalar hâlâ biraz pişmemiş görünürken ateşten alın. Tuzunu tadın. Maydanoz serpin ve siyah zeytin eşliğinde tavadan servis edin.",
      it: "Immergete il baccalà sfilacciato in acqua fredda, cambiando l'acqua quattro volte in 24–48 ore, finché un pezzettino abbia un sapore piacevolmente salato. Scolate e asciugate. Tagliate le patate in bastoncini sottilissimi. Scaldate 2cm di olio neutro a 170°C e friggete i bastoncini a lotti per 3–4 minuti finché dorati pallidi. Scolate su carta e scartate l'olio. Pulite la padella. Scaldate l'olio d'oliva a fuoco medio-basso e fate appassire cipolla e aglio, mescolando spesso, per 12–15 minuti. Aggiungete il baccalà e mescolate 2 minuti. Unite i bastoncini di patate e amalgamate delicatamente. Versate le uova sbattute condite con pepe bianco. Mescolate continuamente a fuoco basso con pieghe lente e ampie per 2–3 minuti — le uova devono formare morbide onde cremose. Togliete dal fuoco mentre le uova sembrano ancora leggermente crude. Assaggiate di sale. Spolverate di prezzemolo e servite con le olive nere.",
      ko: "찢은 대구를 냉수에 담가 24–48시간 동안 물을 네 번 교체하여 작은 조각이 기분 좋은 짠맛이 날 때까지 불립니다. 물을 빼고 물기를 닦습니다. 감자를 매우 얇은 성냥개비 모양으로 자릅니다. 깊은 프라이팬에 중성 기름 2cm를 170°C로 가열하고 감자를 나누어 3–4분씩 연한 황금색이 될 때까지 튀깁니다. 키친타월에 건지고 기름은 버립니다. 팬을 닦습니다. 중약불로 올리브오일을 데우고 양파와 마늘을 자주 저으며 12–15분 볶습니다. 대구를 넣고 2분 저읍니다. 감자를 넣고 살살 버무립니다. 흰 후추로 간한 풀어놓은 달걀을 붓습니다. 약불에서 넓고 느린 접기 동작으로 2–3분 계속 저읍니다 — 달걀은 부드럽고 크리미한 결이 되어야 합니다. 달걀이 아직 약간 덜 익어 보일 때 불에서 내립니다. 소금을 맛봅니다. 파슬리를 뿌리고 검은 올리브를 곁들여 바로 냅니다."""

# ============================================================
# RECIPE 49 – Jerk Chicken
# ============================================================

INGR_49 = """\
      ro: ["1,5 kg pulpe și copane de pui, cu piele, crestați adânc", "6 fire ceapă verde, tăiate grosier", "3 ardei Scotch bonnet (sau habanero), semințele îndepărtate", "5 căței de usturoi", "Bucată de 2cm ghimbir proaspăt, curățat", "2 linguri sos de soia închis la culoare", "2 linguri zahăr brun", "1 lingură ienibahar măcinat", "1 linguriță cimbru uscat", "½ linguriță scorțișoară măcinată", "½ linguriță piper negru", "2 linguri ulei vegetal", "Suc de la 2 lămi verzi, plus felii pentru servire"],
      en: ["1.5kg chicken thighs and drumsticks, skin-on, scored deeply with a knife", "6 spring onions, roughly chopped", "3 Scotch bonnet chilies or habaneros, seeds removed for moderate heat", "5 garlic cloves", "2cm piece fresh ginger, peeled", "2 tbsp dark soy sauce", "2 tbsp brown sugar", "1 tbsp ground allspice", "1 tsp dried thyme", "½ tsp ground cinnamon", "½ tsp black pepper", "2 tbsp vegetable oil", "Juice of 2 limes, plus wedges to serve"],
      es: ["1,5 kg muslos y contramuslos de pollo con piel, con cortes profundos", "6 cebolletas, troceadas", "3 chiles Scotch bonnet o habanero, sin semillas", "5 dientes de ajo", "Trozo de 2cm de jengibre fresco, pelado", "2 cucharadas de salsa de soja oscura", "2 cucharadas de azúcar moreno", "1 cucharada de pimienta de Jamaica molida", "1 cucharadita de tomillo seco", "½ cucharadita de canela molida", "½ cucharadita de pimienta negra", "2 cucharadas de aceite vegetal", "Zumo de 2 limas, más gajos para servir"],
      fr: ["1,5 kg de cuisses et pilons de poulet avec peau, entaillés profondément", "6 oignons verts, grossièrement coupés", "3 piments Scotch bonnet ou habanero, épépinés", "5 gousses d'ail", "Morceau de 2cm de gingembre frais, épluché", "2 cuillères à soupe de sauce soja foncée", "2 cuillères à soupe de sucre roux", "1 cuillère à soupe de piment de la Jamaïque moulu", "1 cuillère à café de thym séché", "½ cuillère à café de cannelle moulue", "½ cuillère à café de poivre noir", "2 cuillères à soupe d'huile végétale", "Jus de 2 citrons verts, plus quartiers pour servir"],
      de: ["1,5 kg Hähnchenschenkel und -keulen mit Haut, tief eingeritzt", "6 Frühlingszwiebeln, grob gehackt", "3 Scotch-Bonnet-Chilis oder Habaneros, entkernt", "5 Knoblauchzehen", "2cm Stück frischer Ingwer, geschält", "2 EL dunkle Sojasoße", "2 EL brauner Zucker", "1 EL gemahlener Piment", "1 TL getrockneter Thymian", "½ TL gemahlener Zimt", "½ TL schwarzer Pfeffer", "2 EL Pflanzenöl", "Saft von 2 Limetten, plus Spalten zum Servieren"],
      pt: ["1,5 kg de coxas e sobrecoxas de frango com pele, cortadas profundamente", "6 cebolinhas, picadas grosseiramente", "3 pimentas Scotch bonnet ou habanero, sem sementes", "5 dentes de alho", "Pedaço de 2cm de gengibre fresco, descascado", "2 colheres de sopa de molho de soja escuro", "2 colheres de sopa de açúcar mascavo", "1 colher de sopa de pimenta da Jamaica moída", "1 colher de chá de tomilho seco", "½ colher de chá de canela moída", "½ colher de chá de pimenta preta", "2 colheres de sopa de óleo vegetal", "Suco de 2 limas, mais rodelas para servir"],
      ru: ["1,5 кг куриных бёдер и голеней с кожей, глубоко надрезанных", "6 стеблей зелёного лука, крупно нарезанных", "3 перца Скотч боннет или хабанеро, без семян", "5 зубчиков чеснока", "Кусок свежего имбиря 2см, очищенный", "2 ст.л. тёмного соевого соуса", "2 ст.л. коричневого сахара", "1 ст.л. молотого душистого перца", "1 ч.л. сушёного тимьяна", "½ ч.л. молотой корицы", "½ ч.л. чёрного перца", "2 ст.л. растительного масла", "Сок 2 лаймов, плюс дольки для подачи"],
      ar: ["1.5 كغ أفخاذ وأرجل دجاج بالجلد مع شقوق عميقة", "6 بصيلات خضراء مقطعة خشناً", "3 فلفل سكوتش بونيت أو هابانيرو منزوع البذور", "5 فصوص ثوم", "قطعة 2 سم زنجبيل طازج مقشر", "2 ملعقة كبيرة صويا غامقة", "2 ملعقة كبيرة سكر بني", "1 ملعقة كبيرة فلفل حلو مطحون", "1 ملعقة صغيرة زعتر مجفف", "½ ملعقة صغيرة قرفة مطحونة", "½ ملعقة صغيرة فلفل أسود", "2 ملعقة كبيرة زيت نباتي", "عصير ليمونتين خضراوتين مع شرائح للتقديم"],
      zh: ["鸡腿和鸡棒腿1.5公斤，带皮，用刀深深划花", "葱6根，粗切", "苏格兰帽椒或哈瓦那椒3个，去籽", "大蒜5瓣", "新鲜生姜2厘米段，去皮", "深色酱油2汤匙", "红糖2汤匙", "多香果粉1汤匙", "干百里香1茶匙", "肉桂粉½茶匙", "黑胡椒½茶匙", "植物油2汤匙", "2个青柠汁，外加青柠角上桌"],
      ja: ["鶏もも肉と手羽元合わせて1.5kg、皮付き、骨まで深く切り込みを入れる", "青ねぎ6本、大きく刻む", "スコッチボネットまたはハバネロ3個、種を除く", "にんにく5片", "生姜2cm、皮をむく", "濃口醤油 大さじ2", "黒砂糖 大さじ2", "オールスパイス（粉末）大さじ1", "乾燥タイム 小さじ1", "シナモン（粉末）小さじ½", "黒こしょう 小さじ½", "植物油 大さじ2", "ライム2個分の果汁、ライムくし形切りも添える"],
      hi: ["1.5 किलो चिकन जांघ और ड्रमस्टिक, चमड़ी सहित, चाकू से गहरे निशान लगाए", "6 हरे प्याज़, मोटे कटे", "3 स्कॉच बॉनेट या हबानेरो मिर्च, बीज निकाले", "5 लहसुन की कलियां", "2 सेमी ताज़े अदरक का टुकड़ा, छिला", "2 बड़े चम्मच डार्क सोया सॉस", "2 बड़े चम्मच ब्राउन शुगर", "1 बड़ा चम्मच ऑलस्पाइस पाउडर", "1 छोटा चम्मच सूखी थाइम", "½ छोटा चम्मच दालचीनी पाउडर", "½ छोटा चम्मच काली मिर्च", "2 बड़े चम्मच वनस्पति तेल", "2 नींबू का रस, साथ में परोसने के लिए नींबू के टुकड़े"],
      tr: ["1,5 kg tavuk but ve kelebek but, derili, derin çizikler yapılmış", "6 yeşil soğan, kaba doğranmış", "3 Scotch bonnet veya habanero biber, çekirdekleri çıkarılmış", "5 diş sarımsak", "2cm taze zencefil, soyulmuş", "2 yemek kaşığı koyu soya sosu", "2 yemek kaşığı esmer şeker", "1 yemek kaşığı toz yenibahar", "1 çay kaşığı kuru kekik", "½ çay kaşığı toz tarçın", "½ çay kaşığı karabiber", "2 yemek kaşığı bitkisel yağ", "2 misket limonu suyu, servis için dilimler"],
      it: ["1,5 kg di cosce e fusi di pollo con pelle, incisi in profondità", "6 cipollotti, tagliati grossolanamente", "3 peperoncini Scotch bonnet o habanero, privati dei semi", "5 spicchi d'aglio", "Pezzo da 2cm di zenzero fresco, sbucciato", "2 cucchiai di salsa di soia scura", "2 cucchiai di zucchero di canna", "1 cucchiaio di pimento macinato", "1 cucchiaino di timo secco", "½ cucchiaino di cannella macinata", "½ cucchiaino di pepe nero", "2 cucchiai di olio vegetale", "Succo di 2 lime, più spicchi per servire"],
      ko: ["닭 허벅지살과 닭다리 1.5kg, 껍질 포함, 칼로 뼈까지 깊이 칼집 낸 것", "쪽파 6개, 굵게 자른 것", "스카치 보닛 또는 하바네로 고추 3개, 씨 제거", "마늘 5쪽", "신선한 생강 2cm, 껍질 벗긴 것", "진한 간장 2큰술", "황설탕 2큰술", "올스파이스 가루 1큰술", "말린 타임 1작은술", "시나몬 가루 ½작은술", "흑후추 ½작은술", "식물성 기름 2큰술", "라임 2개분 즙, 곁들임용 라임 웨지"]"""

HOW_49 = """\
      ro: "Mixează ceapa verde, ardeii, usturoiul, ghimbirul, sosul de soia, zahărul, ieniabaharul, cimbrul, scorțișoara, piperul, uleiul și sucul de lămâie verde până la o pastă grosieră. Crestează adânc fiecare bucată de pui până la os — condimentul jerk trebuie să pătrundă în carne. Acoperă bine cu pasta și împinge-o în tăieturi. Marinează la frigider minimum 4 ore, ideal peste noapte. Scoate cu 30 de minute înainte de gătire. La grătar cu cărbuni: gătește la temperatură medie-înaltă 35–45 de minute, întorcând la fiecare 10 minute, până ce sucurile curg clare și exteriorul este ars în câteva locuri. La cuptor: la 200°C pe grătar deasupra unei tăvi, 40 de minute, apoi gratinează 5 minute. Odihnește 5 minute. Servește cu orez și mazăre, plantain prăjit și felii de lămâie verde.",
      en: "Blend spring onions, Scotch bonnets, garlic, ginger, soy sauce, brown sugar, allspice, thyme, cinnamon, black pepper, oil, and lime juice in a food processor until a rough paste forms. Score the chicken pieces deeply down to the bone — jerk only works if the marinade penetrates inside the meat. Rub the paste all over and into every cut. Cover and marinate in the refrigerator for at least 4 hours, ideally overnight. Remove from the fridge 30 minutes before cooking. To grill over charcoal: cook over medium-hot coals for 35–45 minutes, turning every 10 minutes, until the juices run clear and the exterior is deeply charred in places. To oven-roast: place on a rack over a baking tray at 200°C for 40 minutes, then finish under a hot grill for 5 minutes to char the skin. Allspice is the defining spice — do not substitute with mixed spice. Rest 5 minutes before serving. Serve with rice and peas, fried plantain, and lime wedges.",
      es: "Tritura cebolletas, Scotch bonnets, ajo, jengibre, soja, azúcar, pimienta de Jamaica, tomillo, canela, pimienta, aceite y lima hasta obtener una pasta gruesa. Haz cortes profundos hasta el hueso en cada pieza — el jerk solo funciona si la marinada penetra dentro. Cubre todo con la pasta y empújala en cada corte. Marina en el frigorífico al menos 4 horas, idealmente toda la noche. Saca 30 minutos antes de cocinar. A la brasa: cocina sobre brasas a temperatura media-alta 35–45 minutos, girando cada 10 minutos, hasta que los jugos salgan claros y el exterior esté chamuscado. Al horno: a 200°C sobre rejilla 40 minutos, luego 5 minutos al grill. Reposa 5 minutos. Sirve con arroz con guisantes, plátano frito y gajos de lima.",
      fr: "Mixez oignons verts, Scotch bonnets, ail, gingembre, soja, sucre, piment de la Jamaïque, thym, cannelle, poivre, huile et citron vert jusqu'à obtenir une pâte grossière. Entaillez chaque morceau de poulet profondément jusqu'à l'os — le jerk ne fonctionne que si la marinade pénètre à l'intérieur. Enduisez de pâte en la faisant entrer dans chaque incision. Marinez au réfrigérateur au moins 4 heures, idéalement une nuit. Sortez 30 minutes avant cuisson. Au grill à charbon: cuisez à chaleur moyenne-forte 35–45 minutes, en retournant toutes les 10 minutes, jusqu'à ce que le jus coule clair et l'extérieur soit bien grillé. Au four: 200°C sur grille 40 minutes, puis 5 minutes gril. Reposez 5 minutes. Servez avec riz et pois, banane plantain frite et quartiers de citron vert.",
      de: "Frühlingszwiebeln, Scotch Bonnets, Knoblauch, Ingwer, Sojasoße, Zucker, Piment, Thymian, Zimt, Pfeffer, Öl und Limettensaft in einer Küchenmaschine zu einer groben Paste verarbeiten. Hähnchenteile tief bis auf den Knochen einritzen — Jerk wirkt nur, wenn die Marinade ins Fleisch eindringt. Paste überall einreiben und in jeden Schnitt drücken. Im Kühlschrank mindestens 4 Stunden, am besten über Nacht marinieren. 30 Minuten vor dem Garen herausnehmen. Auf dem Holzkohlegrill: bei mittlerer bis hoher Hitze 35–45 Minuten grillen, alle 10 Minuten wenden, bis die Säfte klar laufen und die Oberfläche stellenweise verkohlt ist. Im Ofen: bei 200°C auf einem Rost 40 Minuten, dann 5 Minuten grillen. 5 Minuten ruhen lassen. Mit Reis und Erbsen, gebratenem Kochbananen und Limettenspalten servieren.",
      pt: "Triture cebolinhas, Scotch bonnets, alho, gengibre, soja, açúcar, pimenta da Jamaica, tomilho, canela, pimenta preta, óleo e sumo de lima até obter uma pasta grossa. Faça cortes profundos até ao osso em cada peça — o jerk só funciona se a marinada penetrar dentro da carne. Esfregue a pasta por toda a superfície e para cada corte. Marine no frigorífico pelo menos 4 horas, de preferência de um dia para o outro. Retire 30 minutos antes de cozinhar. Na grelha: cozinhe a fogo médio-alto 35–45 minutos, virando de 10 em 10 minutos, até os sucos correrem limpos. No forno: 200°C numa grelha 40 minutos, depois 5 minutos no grill. Descanse 5 minutos. Sirva com arroz de feijão, banana frita e gomos de lima.",
      ru: "Смешайте в блендере зелёный лук, острые перцы, чеснок, имбирь, соевый соус, сахар, душистый перец, тимьян, корицу, чёрный перец, масло и сок лайма до состояния грубой пасты. Глубоко надрежьте каждый кусочек до кости — джерк работает только если маринад проникает внутрь мяса. Тщательно покройте пастой, вдавливая в надрезы. Маринуйте в холодильнике минимум 4 часа, идеально — ночь. Достаньте за 30 минут до приготовления. На углях: готовьте при средне-высокой температуре 35–45 минут, переворачивая каждые 10 минут, до прозрачного сока и характерного обугленного внешнего вида. В духовке: 200°C на решётке 40 минут, затем 5 минут под грилем. Дайте отдохнуть 5 минут. Подавайте с рисом и горохом, жареным бананом и дольками лайма.",
      ar: "امزج البصل الأخضر والفلفل الحار والثوم والزنجبيل والصويا والسكر والفلفل الحلو والزعتر والقرفة والفلفل الأسود والزيت وعصير الليمون في الخلاط حتى تتشكل عجينة خشنة. اشقق كل قطعة دجاج عميقاً حتى العظم — لا تعمل طريقة جيرك إلا إذا اخترق التتبيل داخل اللحم. دهّن بالعجينة واضغطها داخل كل شق. دع الدجاج يتبل في الثلاجة 4 ساعات على الأقل، ومن الأفضل طوال الليل. أخرجه قبل 30 دقيقة من الطهي. على الفحم: اشوِ على حرارة متوسطة-عالية 35–45 دقيقة، مع التقليب كل 10 دقائق. في الفرن: 200°C على رف فوق صينية 40 دقيقة ثم 5 دقائق تحت الشواية. أرح 5 دقائق. قدّم مع الأرز والبازلاء والموز المقلي.",
      zh: "将葱、苏格兰帽椒、大蒜、生姜、酱油、红糖、多香果、百里香、肉桂、黑胡椒、油和青柠汁放入食品处理机，打成粗糙的酱料。在每块鸡肉上深划至骨，让腌料渗入——杰克风味只有在腌料进入肉中才有效。将酱料全面涂抹并压入每个切口。冷藏腌制至少4小时，最好过夜。烹饪前30分钟取出。炭火烤制：在中高温炭火上烤35–45分钟，每10分钟翻面一次，直到汁液清澈，表面部分焦黑。烤箱烤制：200°C架上烤盘烤40分钟，再在热烤架上烤5分钟使皮焦香。静置5分钟。配豆饭、炸大蕉和青柠角上桌。",
      ja: "フードプロセッサーで青ねぎ、スコッチボネット、にんにく、生姜、醤油、黒砂糖、オールスパイス、タイム、シナモン、黒こしょう、油、ライム果汁を粗いペースト状になるまで混ぜます。鶏肉の各ピースを骨まで深く切り込みます——マリネが肉の内側まで浸透して初めてジャークが完成します。ペーストを全体に塗り込み、各切り込みに押し込みます。冷蔵庫で最低4時間、できれば一晩マリネします。調理30分前に冷蔵庫から出します。炭火グリルの場合：中高熱で35–45分、10分ごとに裏返しながら、汁が透明になり外側が一部焦げるまで焼きます。オーブンの場合：200°Cで網の上で40分、続けてグリルで5分。5分休ませてから提供します。ライスアンドピーズ、揚げプランテーン、ライムくし形と一緒に供します。",
      hi: "फूड प्रोसेसर में हरे प्याज़, स्कॉच बॉनेट, लहसुन, अदरक, सोया सॉस, ब्राउन शुगर, ऑलस्पाइस, थाइम, दालचीनी, काली मिर्च, तेल और नींबू का रस डालकर दरदरा पेस्ट बनाएं। हर चिकन टुकड़े पर हड्डी तक गहरे निशान लगाएं — जर्क तभी काम करता है जब मैरिनेड अंदर तक पहुंचे। पेस्ट सभी तरफ और हर निशान में दबाएं। कम से कम 4 घंटे, आदर्श रूप से रात भर फ्रिज में रखें। पकाने से 30 मिनट पहले निकालें। चारकोल ग्रिल पर: मध्यम-उच्च आंच पर 35–45 मिनट, हर 10 मिनट पर पलटते हुए, जब तक रस साफ बहे और बाहर कहीं-कहीं जले निशान हों। ओवन में: 200°C पर रैक पर 40 मिनट, फिर 5 मिनट ग्रिल करें। 5 मिनट रेस्ट करें। चावल-मटर, फ्राइड प्लान्टेन और नींबू के टुकड़ों के साथ परोसें।",
      tr: "Yeşil soğan, Scotch bonnet, sarımsak, zencefil, soya sosu, esmer şeker, yenibahar, kekik, tarçın, karabiber, yağ ve misket limonu suyunu mutfak robotunda kaba bir macun haline getirin. Her tavuk parçasını kemiğe kadar derin çizin — jerk ancak marinat içine nüfuz ettiğinde işe yarar. Macunu her yere ve her çiziye ovalayın. En az 4 saat, tercihen bir gece buzdolabında marine edin. Pişirmeden 30 dakika önce çıkarın. Kömür ızgarada: orta-yüksek ateşte 35–45 dakika, her 10 dakikada bir çevirerek pişirin. Fırında: 200°C'de tel ızgara üzerinde 40 dakika, ardından 5 dakika grill. 5 dakika dinlendirin. Pirinç ve bezelye, kızarmış muz ve misket limonu dilimleriyle servis edin.",
      it: "Frullate cipollotti, Scotch bonnet, aglio, zenzero, salsa di soia, zucchero, pimento, timo, cannella, pepe nero, olio e succo di lime fino a ottenere una pasta grossolana. Incidete ogni pezzo di pollo profondamente fino all'osso — il jerk funziona solo se la marinatura penetra all'interno della carne. Spalmate la pasta ovunque e in ogni incisione. Marinate in frigorifero almeno 4 ore, idealmente tutta la notte. Tirate fuori 30 minuti prima di cuocere. Alla griglia a carbone: cuocete a fuoco medio-alto per 35–45 minuti, girando ogni 10 minuti. Al forno: 200°C su griglia per 40 minuti, poi 5 minuti sotto il grill. Fate riposare 5 minuti. Servite con riso e fagioli, banana fritto e spicchi di lime.",
      ko: "푸드 프로세서에 쪽파, 스카치 보닛, 마늘, 생강, 간장, 황설탕, 올스파이스, 타임, 시나몬, 흑후추, 기름, 라임즙을 넣고 거친 페이스트가 될 때까지 갑니다. 닭고기 각 조각을 뼈까지 깊이 칼집 냅니다 — 마리네이드가 속까지 스며들어야 저크가 제대로 완성됩니다. 페이스트를 전체에 바르고 칼집마다 눌러 넣습니다. 최소 4시간, 가능하면 하룻밤 냉장 마리네이드합니다. 조리 30분 전에 꺼냅니다. 숯불 그릴: 중강불에서 35–45분, 10분마다 뒤집어 즙이 맑게 흐르고 표면이 군데군데 탈 때까지 굽습니다. 오븐: 200°C에서 철망 위에 40분, 이어 5분 그릴에서 껍질을 태웁니다. 5분 휴지 후 라이스 앤 피스, 구운 플랜틴, 라임 웨지와 함께 냅니다."""

# ============================================================
# RECIPE 54 – Moules-frites
# ============================================================

INGR_54 = """\
      ro: ["2 kg midii proaspete vii, curățate și cu beard-ul îndepărtat", "800g cartofi făinoși, curățați și tăiați bețe groase", "50g unt nesărat", "4 șalote, tocate mărunt", "4 căței de usturoi, felii subțiri", "200ml vin alb sec", "2 tulpini de țelină, feliate subțire", "Legătură mică de pătrunjel proaspăt, tocat mărunt", "Ulei vegetal sau grăsime de vită, pentru prăjit", "Sare și piper negru"],
      en: ["2kg fresh live mussels, scrubbed and beards removed", "800g floury potatoes, peeled and cut into thick batons", "50g unsalted butter", "4 shallots, finely diced", "4 garlic cloves, thinly sliced", "200ml dry white wine", "2 celery stalks, finely sliced", "Small bunch of fresh parsley, finely chopped", "Vegetable oil or beef dripping, for deep-frying", "Salt and black pepper"],
      es: ["2 kg de mejillones frescos y vivos, cepillados y sin barbas", "800g de patatas harinosas, peladas y cortadas en palitos gruesos", "50g de mantequilla sin sal", "4 chalotas, picadas finas", "4 dientes de ajo, en láminas finas", "200ml de vino blanco seco", "2 tallos de apio, en rodajas finas", "Ramillete pequeño de perejil fresco, picado fino", "Aceite vegetal o grasa de ternera, para freír", "Sal y pimienta negra"],
      fr: ["2 kg de moules fraîches vivantes, brossées et ébarbées", "800g de pommes de terre farineuses, épluchées et coupées en bâtonnets épais", "50g de beurre non salé", "4 échalotes, finement hachées", "4 gousses d'ail, émincées finement", "200ml de vin blanc sec", "2 branches de céleri, finement tranchées", "Petite botte de persil frais, finement haché", "Huile végétale ou graisse de bœuf pour friture", "Sel et poivre noir"],
      de: ["2 kg frische lebende Miesmuscheln, geschrubbt und ohne Bart", "800g mehligkochende Kartoffeln, geschält und in dicke Stifte geschnitten", "50g ungesalzene Butter", "4 Schalotten, fein gewürfelt", "4 Knoblauchzehen, in dünne Scheiben", "200ml trockener Weißwein", "2 Selleriestangen, fein geschnitten", "Kleines Bund frische Petersilie, fein gehackt", "Pflanzenöl oder Rinderschmalz zum Frittieren", "Salz und schwarzer Pfeffer"],
      pt: ["2 kg de mexilhões frescos e vivos, esfregados e sem byssus", "800g de batatas farinhosas, descascadas e cortadas em palitos grossos", "50g de manteiga sem sal", "4 chalotas, finamente picadas", "4 dentes de alho, em fatias finas", "200ml de vinho branco seco", "2 talos de aipo, em fatias finas", "Raminho de salsa fresca, picada finamente", "Óleo vegetal ou gordura de vaca, para fritar", "Sal e pimenta preta"],
      ru: ["2 кг свежих живых мидий, промытых и очищенных от бисуса", "800г рассыпчатого картофеля, нарезанного толстыми брусками", "50г несолёного сливочного масла", "4 луковицы-шалот, мелко нарезанных", "4 зубчика чеснока, тонко нарезанных", "200мл сухого белого вина", "2 стебля сельдерея, тонко нарезанных", "Небольшой пучок свежей петрушки, мелко нарубленной", "Растительное масло или говяжий жир для жарки", "Соль и чёрный перец"],
      ar: ["2 كغ بلح بحر طازج حي مدعوك ومنزوع الخيط", "800 غ بطاطس دقيقية مقشرة ومقطعة عصي سميكة", "50 غ زبدة غير مملحة", "4 كراث مقطع ناعماً", "4 فصوص ثوم مقطعة شرائح رفيعة", "200 مل نبيذ أبيض جاف", "2 ساق كرفس مقطعتان شرائح رفيعة", "حفنة صغيرة بقدونس طازج مقطع ناعماً", "زيت نباتي أو دهن بقري للقلي", "ملح وفلفل أسود"],
      zh: ["新鲜活贻贝2公斤，刷洗干净，去除足丝", "粉质土豆800g，去皮切成厚条", "无盐黄油50g", "小葱头4个，切细末", "大蒜4瓣，切薄片", "干白葡萄酒200ml", "芹菜2根，切薄片", "一小束新鲜欧芹，切细末", "植物油或牛油，用于油炸", "盐和黑胡椒"],
      ja: ["生きた新鮮なムール貝2kg、たわしで洗い足糸を除去", "粉質じゃがいも800g、皮をむいて太めのスティック状に切る", "無塩バター50g", "エシャロット4個、みじん切り", "にんにく4片、薄切り", "辛口白ワイン200ml", "セロリ2本、薄切り", "新鮮なパセリの小束、細かく刻む", "植物油または牛脂（揚げ油用）", "塩と黒こしょう"],
      hi: ["2 किलो ताज़े जीवित मसल्स, साफ़ किए और दाढ़ी निकाली", "800 ग्राम आटेदार आलू, छीलकर मोटे बेटन में काटे", "50 ग्राम अनसाल्टेड बटर", "4 शैलोट्स, बारीक कटे", "4 लहसुन की कलियां, पतले स्लाइस", "200 मिलीलीटर सूखी सफ़ेद वाइन", "2 अजवाइन के डंठल, पतले कटे", "ताज़े पार्सले का छोटा गुच्छा, बारीक कटा", "डीप-फ्राई के लिए वनस्पति तेल या बीफ ड्रिपिंग", "नमक और काली मिर्च"],
      tr: ["2 kg taze canlı midye, fırçalanmış ve sakalları alınmış", "800g unlu patates, soyulmuş ve kalın çubuklar halinde kesilmiş", "50g tuzsuz tereyağı", "4 arpacık soğanı, ince doğranmış", "4 diş sarımsak, ince dilimlenmiş", "200ml kuru beyaz şarap", "2 kereviz sapı, ince dilimlenmiş", "Küçük demet taze maydanoz, ince kıyılmış", "Derin kızartma için bitkisel yağ veya sığır yağı", "Tuz ve karabiber"],
      it: ["2 kg di cozze fresche vive, spazzolate e private del bisso", "800g di patate farinose, pelate e tagliate a bastoncini spessi", "50g di burro non salato", "4 scalogni, finemente tritati", "4 spicchi d'aglio, affettati sottili", "200ml di vino bianco secco", "2 coste di sedano, affettate finemente", "Piccolo mazzo di prezzemolo fresco, finemente tritato", "Olio vegetale o strutto di manzo per friggere", "Sale e pepe nero"],
      ko: ["신선한 활 홍합 2kg, 솔로 문질러 씻고 족사 제거", "분 있는 감자 800g, 껍질 벗겨 두꺼운 막대 모양으로 자른 것", "무염 버터 50g", "샬롯 4개, 잘게 다진 것", "마늘 4쪽, 얇게 슬라이스", "드라이 화이트 와인 200ml", "셀러리 2줄기, 얇게 슬라이스", "신선한 파슬리 한 줌, 잘게 다진 것", "식물성 기름 또는 소기름(튀김용)", "소금과 흑후추"]"""

HOW_54 = """\
      ro: "Pentru cartofi prăjiți: înmuiați bastonașele în apă rece 30 de minute, scurgeți și uscați bine. Prima prăjire la 140°C timp de 6–8 minute până sunt gătite dar fără culoare; scurgeți și răciți complet. Bateți fiecare midie pe blat și aruncați cele care rămân deschise. Topiți untul într-o oală mare la foc mediu-înalt. Adăugați șalotele și țelina și gătiți 3 minute. Adăugați usturoiul și gătiți 1 minut. Turnați vinul alb, aduceți la fierbere, apoi adăugați midiile și acoperiți ermetic. Aburiți 4–5 minute, scuturând oala o dată-două ori, până ce cochiliile s-au deschis. Aruncați cele rămase închise. Amestecați cu cea mai mare parte a pătrunjelului. Ridicați temperatura uleiului de prăjit la 190°C și prăjiți bastonașele albe în tranșe 2–3 minute până devin aurii și crocante. Scurgeți și sărați imediat. Serviți midiile cu zeamă și cartofii alături.",
      en: "For the frites: cut potatoes into thick batons and soak in cold water for 30 minutes to remove surface starch, then drain and dry thoroughly. First fry at 140°C for 6–8 minutes until cooked through but uncoloured; drain and cool completely. Tap each open mussel on the counter — discard any that do not close. Melt butter in a large heavy pot over medium-high heat. Add shallots and celery and cook for 3 minutes until softened. Add garlic and cook for 1 minute. Pour in the white wine, bring to a boil, then add the mussels and cover tightly. Steam for 4–5 minutes, shaking the pot once or twice, until the shells have opened wide. Discard any that remain shut. Stir in most of the parsley and season the broth. Raise the frying oil to 190°C and fry the blanched batons in batches for 2–3 minutes until golden and very crisp. Drain and season immediately with salt. Serve the mussels in wide bowls in their broth, the frites alongside, with the remaining parsley and mayonnaise on the side.",
      es: "Para las patatas: córtalas en palitos gruesos y remójalos en agua fría 30 minutos para eliminar el almidón superficial, luego escurre y seca bien. Primera fritura a 140°C durante 6–8 minutos hasta que estén cocidas pero sin colorear; escurre y enfría completamente. Golpea cada mejillón abierto en la encimera — descarta los que no se cierren. Derrite la mantequilla en una olla grande a fuego medio-alto. Añade chalotas y apio y cocina 3 minutos. Añade el ajo y cocina 1 minuto. Vierte el vino blanco, lleva a ebullición, añade los mejillones y tapa bien. Vaporiza 4–5 minutos, agitando la olla una o dos veces, hasta que todas las conchas se abran. Desecha las cerradas. Incorpora el perejil y sazona el caldo. Sube el aceite a 190°C y fríe los palitos en tandas 2–3 minutos hasta que estén dorados y muy crujientes. Escurre y sala inmediatamente. Sirve los mejillones en su caldo y las patatas al lado.",
      fr: "Pour les frites: coupez les pommes de terre en bâtonnets épais et faites-les tremper dans l'eau froide 30 minutes pour éliminer l'amidon de surface, puis égouttez et séchez bien. Première friture à 140°C pendant 6–8 minutes jusqu'à cuisson complète mais sans coloration; égouttez et laissez refroidir complètement. Tapez chaque moule ouverte sur le plan de travail — jetez celles qui ne se referment pas. Faites fondre le beurre dans une grande casserole à feu moyen-vif. Ajoutez les échalotes et le céleri et cuisez 3 minutes. Ajoutez l'ail et cuisez 1 minute. Versez le vin blanc, portez à ébullition, ajoutez les moules et couvrez hermétiquement. Faites cuire à la vapeur 4–5 minutes en secouant la casserole une ou deux fois, jusqu'à ce que les coquilles soient toutes ouvertes. Jetez celles qui restent fermées. Incorporez le persil et assaisonnez le bouillon. Montez l'huile à 190°C et faites frire les bâtonnets par lots 2–3 minutes jusqu'à dorure et croustillant. Égouttez et salez immédiatement. Servez les moules dans leur bouillon avec les frites à côté.",
      de: "Für die Pommes: Kartoffelsticks 30 Minuten in kaltem Wasser einweichen, abtropfen und gut trocknen. Erste Friture bei 140°C für 6–8 Minuten, bis sie gegart aber noch blass sind; abtropfen und vollständig abkühlen. Jede offene Muschel auf die Arbeitsfläche klopfen — wegwerfen, was sich nicht schließt. Butter in einem großen Topf bei mittlerer bis hoher Hitze schmelzen. Schalotten und Sellerie zugeben und 3 Minuten garen. Knoblauch zugeben und 1 Minute garen. Weißwein eingiessen, aufkochen, Muscheln zugeben und fest zudecken. 4–5 Minuten dämpfen, den Topf einmal oder zweimal schütteln, bis alle Schalen geöffnet sind. Geschlossene Muscheln entsorgen. Petersilie einrühren und den Sud abschmecken. Öl auf 190°C erhitzen und die vorgargegebenen Sticks portionsweise 2–3 Minuten goldbraun und sehr knusprig frittieren. Sofort mit Salz würzen. Muscheln im Sud in tiefen Tellern servieren, Pommes dazu.",
      pt: "Para os frites: corte as batatas em palitos grossos e deixe-os de molho em água fria 30 minutos, depois escorra e seque bem. Primeira fritura a 140°C durante 6–8 minutos até estarem cozidos mas sem cor; escorra e arrefeça completamente. Bata cada mexilhão aberto no balcão — descarte os que não fechem. Derreta a manteiga numa panela grande em lume médio-alto. Junte as chalotas e o aipo e cozinhe 3 minutos. Junte o alho e cozinhe 1 minuto. Deite o vinho branco, deixe ferver, junte os mexilhões e tape bem. Cozinhe a vapor 4–5 minutos, agitando a panela uma ou duas vezes, até as conchas abrirem. Descarte as que ficarem fechadas. Junte a maior parte da salsa e tempere o caldo. Suba o óleo para 190°C e frite os palitos branqueados em lotes por 2–3 minutos até dourados e muito crocantes. Escorra e tempere com sal imediatamente. Sirva os mexilhões no caldo com os frites ao lado.",
      ru: "Для картофеля фри: нарежьте картофель толстыми брусками и замочите в холодной воде на 30 минут, затем обсушите насухо. Первая жарка при 140°C в течение 6–8 минут — до готовности, но без цвета; откиньте и полностью остудите. Постучите каждой открытой мидией о столешницу — выбросьте те, что не закрылись. Растопите масло в большой кастрюле при средне-высоком огне. Добавьте шалот и сельдерей и тушите 3 минуты. Добавьте чеснок и готовьте 1 минуту. Влейте белое вино, доведите до кипения, добавьте мидии и плотно накройте. Готовьте на пару 4–5 минут, раз-два встряхивая кастрюлю, до открытия раковин. Выбросьте закрытые. Добавьте петрушку и приправьте бульон. Разогрейте масло до 190°C и обжаривайте бланшированные бруски порциями 2–3 минуты до золотистого цвета и хруста. Немедленно посолите. Подавайте мидии в бульоне, картофель — рядом.",
      ar: "للبطاطا: قطّعها عصياً سميكة وانقعها في ماء بارد 30 دقيقة، ثم اصفِ وجفّف جيداً. الأولى قلي على 140°C لمدة 6–8 دقائق حتى تنضج دون اكتساب اللون؛ صفّها وبرّدها كلياً. اقرع كل صدفة مفتوحة على المنضدة — تخلص مما لا يُغلق. أذب الزبدة في إناء ثقيل على نار متوسطة-عالية. أضف الكراث والكرفس واطبخ 3 دقائق. أضف الثوم واطبخ دقيقة. صبّ النبيذ الأبيض وأحضره للغليان، أضف بلح البحر وأغلق الغطاء محكماً. اطبخ بالبخار 4–5 دقائق مع هز الإناء مرة أو مرتين حتى تنفتح القذائف. تخلص من المغلقة. أضف البقدونس وتبّل المرق. ارفع حرارة الزيت إلى 190°C واقلِ عصي البطاطا المسبقة الطهي على دفعات 2–3 دقائق حتى تذهب ذهبية ومقرمشة. صفّها وملّحها فوراً. قدّم بلح البحر في مرقه مع البطاطا جانباً.",
      zh: "制作薯条：将土豆切成厚条，在冷水中浸泡30分钟去除表面淀粉，沥干彻底擦干。第一次油炸：140°C炸6–8分钟至全熟但不上色，沥干完全冷却。将每个张开的贻贝在台面上轻敲——不合上的扔掉。大锅中以中高火融化黄油。加入小葱头和芹菜煮3分钟。加入大蒜煮1分钟。倒入白葡萄酒煮沸，加入贻贝，盖紧锅盖。大火蒸4–5分钟，期间摇锅一两次，直到贝壳全部张开。扔掉不开口的。拌入大部分欧芹并调味汤汁。油温升至190°C，分批炸预炸薯条2–3分钟至金黄酥脆。立即沥油撒盐。贻贝连汤装在大碗里，薯条放旁边，剩余欧芹撒上，配蛋黄酱上桌。",
      ja: "フリット用：ジャガイモを太めのスティック状に切り、冷水に30分浸して表面のでんぷんを抜き、しっかり水気を拭き取ります。140°Cで6–8分、火が通るが色づかない状態まで揚げ、完全に冷まします。開いているムール貝を台に打ちつけて閉じなければ捨てます。大きな鍋でバターを中強火で溶かします。エシャロットとセロリを加えて3分炒めます。にんにくを加えて1分炒めます。白ワインを注いで沸騰させ、ムール貝を加えてしっかり蓋をします。4–5分蒸し煮し、鍋を1〜2回振り、全ての貝が開いたら完成。開かないものは捨てます。パセリの大部分を加え、ブロスの味を調えます。揚げ油を190°Cに上げ、下揚げしたスティックをバッチで2–3分、こんがりとしてとてもカリカリになるまで揚げます。すぐ塩をふります。ムール貝をブロスごと深皿に盛り、フリットを添えます。",
      hi: "फ्रिट्स के लिए: आलू को मोटे बेटन में काटें और 30 मिनट ठंडे पानी में भिगोएं, फिर निकाल कर पूरी तरह सुखाएं। पहली बार 140°C पर 6–8 मिनट तलें जब तक पक जाएं लेकिन रंग न आए; निकालें और पूरी तरह ठंडे होने दें। हर खुले मसल को काउंटर पर थपथपाएं — जो बंद न हों उन्हें फेंक दें। बड़े भारी बर्तन में मध्यम-उच्च आंच पर बटर पिघलाएं। शैलोट्स और अजवाइन डालें और 3 मिनट पकाएं। लहसुन डालें और 1 मिनट पकाएं। सफ़ेद वाइन डालें, उबाल आने दें, मसल्स डालें और ढक्कन कसकर बंद करें। 4–5 मिनट भाप दें, बर्तन एक-दो बार हिलाएं, जब तक सभी शेल खुल जाएं। बंद रहे वाले फेंक दें। ज़्यादातर पार्सले मिलाएं और शोरबा सीज़न करें। तेल 190°C करें और ब्लांच किए बेटन बैचों में 2–3 मिनट तक सुनहरे और बहुत कुरकुरे होने तक तलें। तुरंत नमक डालें। मसल्स उनके शोरबे में परोसें, फ्रिट्स बगल में रखें।",
      tr: "Patates kızartması için: patatesleri kalın çubuklar halinde kesin ve yüzey nişastasını gidermek için 30 dakika soğuk suda bekletin, ardından süzün ve iyice kurulayın. 140°C'de 6–8 dakika, pişmiş ama renk almamış hale gelene kadar kızartın; süzün ve tamamen soğutun. Açık midyeleri tezgâha vurun — kapanmayanları atın. Büyük bir tencerede orta-yüksek ateşte tereyağını eritin. Arpacık soğanı ve kerevizi ekleyin, 3 dakika pişirin. Sarımsağı ekleyin, 1 dakika pişirin. Beyaz şarabı dökün, kaynatın, midyeleri ekleyin ve sıkıca kapatın. 4–5 dakika buharla pişirin, tencereyi bir-iki kez sallayın. Kapanmayan midyeleri atın. Maydanozun büyük kısmını ekleyin ve suyu tatlandırın. Yağı 190°C'ye çıkarın ve ön kızartılmış çubukları partiler halinde 2–3 dakika altın ve çıtır olana kadar kızartın. Hemen tuzlayın. Midyeleri sularıyla servis edin, yanına patates kızartmasını ekleyin.",
      it: "Per le patatine: tagliate le patate a bastoncini spessi e lasciatele in ammollo in acqua fredda per 30 minuti per rimuovere l'amido superficiale, poi scolate e asciugate bene. Prima frittura a 140°C per 6–8 minuti fino a cottura completa ma senza colore; scolate e raffreddate completamente. Picchiettate ogni cozza aperta sul piano — scartate quelle che non si chiudono. Sciogliete il burro in una capiente pentola a fuoco medio-alto. Aggiungete scalogni e sedano e cuocete 3 minuti. Aggiungete l'aglio e cuocete 1 minuto. Versate il vino bianco, portate a bollore, aggiungete le cozze e coprite bene. Cuocete a vapore 4–5 minuti scuotendo la pentola una o due volte, fino a quando i gusci sono aperti. Scartate quelle chiuse. Aggiungete il prezzemolo e regolate di sapore. Portate l'olio a 190°C e friggete i bastoncini sbianchiti a lotti per 2–3 minuti fino a doratura e croccantezza. Scolate e salate immediatamente. Servite le cozze nel loro brodo con le patatine a fianco.",
      ko: "감자튀김 준비: 감자를 두꺼운 막대 모양으로 자르고 찬물에 30분 담가 표면 전분을 제거합니다. 잘 건집니다. 1차 튀김: 140°C에서 6–8분, 익되 색이 나지 않도록 튀기고 완전히 식힙니다. 입 벌린 홍합은 조리대에 두드려 닫히지 않으면 버립니다. 큰 냄비에 중강불로 버터를 녹입니다. 샬롯과 셀러리를 넣고 3분 볶습니다. 마늘을 넣고 1분 볶습니다. 화이트 와인을 붓고 끓여 홍합을 넣은 뒤 뚜껑을 꽉 닫습니다. 4–5분 찌며 냄비를 한두 번 흔들어 모든 껍데기가 열릴 때까지 합니다. 열리지 않는 것은 버립니다. 파슬리 대부분을 넣고 육수 간합니다. 기름을 190°C로 올려 데친 감자를 나누어 2–3분씩 황금색이 되도록 바삭하게 튀깁니다. 바로 소금 뿌립니다. 홍합은 육수와 함께 그릇에 담고 감자튀김을 옆에 놓아 냅니다."""

# ============================================================
# MAIN
# ============================================================

def main():
    with open(JS_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    fixes = [
        (47, 'ingredients', INGR_47),
        (47, 'howIsMade',   HOW_47),
        (49, 'ingredients', INGR_49),
        (49, 'howIsMade',   HOW_49),
        (54, 'ingredients', INGR_54),
        (54, 'howIsMade',   HOW_54),
    ]

    for recipe_id, field, new_lines in fixes:
        print(f"Patching recipe {recipe_id} / {field}...")
        content = replace_field(content, recipe_id, field, new_lines)

    with open(JS_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print("\nDone. Run audit_quality.py and npm run build to verify.")

if __name__ == '__main__':
    main()
