with open('public/js/recipes.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the bad originText block (has real newlines inside JS string values) and replace with correct escaped version
start_marker = '    originText: {\n      ro: "Fasole cu cârnați este mâncarea'
end_marker = '\n    }\n  },\n  {\n    id: 134,'

start_idx = content.find(start_marker)
end_idx = content.find(end_marker, start_idx)

if start_idx == -1 or end_idx == -1:
    print(f"ERROR: start={start_idx}, end={end_idx}")
else:
    new_block = '    originText: {\n' \
        '      ro: "Fasole cu cârnați este mâncarea de iarnă a gospodăriei românești — fasole albă fiartă îndelung împreună cu cârnați afumați de porc, ceapă, morcovi, bulion și foi de dafin, până când zeama devine groasă și aromată. Cârnații adaugă grăsime și fum, transformând leguminoasa modestă într-un preparat consistent și satisfăcător. Se servește cu murături și pâine de casă sau mămăligă.\\n\\nRețeta variază de la regiune la regiune: în Moldova se adaugă mai mult bulion, în Ardeal cârnații sunt mai afumați și mai grași, iar în Oltenia se poate folosi cimbru proaspăt. Vasul de lut în care se fierbe lent la cuptor dă un gust diferit față de oala pe aragaz — ambele versiuni sunt valide în tradiția românească.",\n' \
        '      en: "Fasole cu cârnați is the winter dish of the Romanian household — white beans slow-cooked together with smoked pork sausages, onion, carrots, tomato paste, and bay leaves until the liquid thickens and turns deeply fragrant. The sausages add fat and smoke, transforming a humble legume into a hearty, satisfying meal. It is served with pickles and homemade bread or polenta.\\n\\nThe recipe varies by region: in Moldavia more tomato paste is added; in Transylvania the sausages are smokier and fattier; in Oltenia fresh thyme may be used. A clay pot slow-cooked in the oven yields a different flavour than a stovetop pot — both versions are valid within Romanian tradition.",\n' \
        '      es: "Fasole cu cârnați es el plato de invierno del hogar rumano — alubias blancas cocinadas lentamente con salchichas de cerdo ahumadas, cebolla, zanahorias, puré de tomate y hojas de laurel hasta que el líquido se espesa y se vuelve muy aromático. Las salchichas añaden grasa y ahumado, transformando una legumbre sencilla en una comida sustanciosa. Se sirve con encurtidos y pan casero o polenta.\\n\\nLa receta varía por regiones: en Moldavia se añade más puré de tomate; en Transilvania las salchichas son más ahumadas; en Oltenia puede usarse tomillo fresco.",\n' \
        '      fr: "Fasole cu cârnați est le plat d\'hiver des foyers roumains — haricots blancs mijotés longuement avec des saucisses de porc fumées, oignon, carottes, concentré de tomate et feuilles de laurier, jusqu\'à ce que le bouillon épaississe et soit profondément parfumé. Les saucisses apportent gras et fumé, transformant une légumineuse humble en repas nourrissant. Se sert avec des cornichons, du pain maison ou de la polenta.\\n\\nLa recette varie selon les régions : en Moldavie on ajoute plus de concentré de tomates ; en Transylvanie les saucisses sont plus fumées ; en Olténie on peut utiliser du thym frais.",\n' \
        '      de: "Fasole cu cârnați ist das Wintergericht des rumänischen Haushalts — weiße Bohnen, langsam mit geräucherten Schweinswürsten, Zwiebel, Karotten, Tomatenmark und Lorbeerblättern gekocht, bis die Flüssigkeit eindickt und tief aromatisch wird. Die Würste fügen Fett und Rauch hinzu und verwandeln eine bescheidene Hülsenfrucht in eine herzhafte, sättigende Mahlzeit. Serviert mit Essiggurken und Hausbrot oder Polenta.\\n\\nDas Rezept variiert je nach Region: In der Moldau wird mehr Tomatenmark verwendet; in Siebenbürgen sind die Würste rauchiger; in der Walachei kann frischer Thymian eingesetzt werden.",\n' \
        '      pt: "Fasole cu cârnați é o prato de inverno do lar romeno — feijão branco cozido lentamente com linguiças defumadas de porco, cebola, cenouras, extrato de tomate e folhas de louro, até o caldo engrossar e ficar profundamente perfumado. As linguiças adicionam gordura e defumado, transformando uma leguminosa humilde em uma refeição farta. Serve-se com picles e pão caseiro ou polenta.\\n\\nA receita varia por região: na Moldávia acrescenta-se mais extrato de tomate; na Transilvânia as linguiças são mais defumadas; na Oltênia pode-se usar tomilho fresco.",\n' \
        '      ru: "Фасоль с колбасой — зимнее блюдо румынского дома: белая фасоль медленно тушится вместе с копчёной свиной колбасой, луком, морковью, томатной пастой и лавровым листом, пока бульон не загустеет и не наполнится глубоким ароматом. Колбаса добавляет жир и дымность, превращая скромную бобовую в сытное, согревающее блюдо. Подаётся с солениями и домашним хлебом или мамалыгой.\\n\\nРецепт различается по регионам: в Молдове добавляют больше томатной пасты, в Трансильвании колбаса более копчёная, в Олтении используют свежий тимьян.",\n' \
        '      ar: "فاصوليا مع النقانق هو طبق شتاء المنازل الرومانية — فاصوليا بيضاء تُطهى ببطء مع نقانق لحم خنزير مدخنة وبصل وجزر ومعجون طماطم وورق غار، حتى يتكاثف السائل ويصبح عميق الأريج. تضيف النقانق الدهن والدخان محولةً البقوليات المتواضعة إلى وجبة دسمة مُشبِعة. يُقدَّم مع المخللات والخبز المنزلي أو البوليتا.\\n\\nيتفاوت الطبق بحسب المنطقة: في مولدوفا يُضاف معجون طماطم أكثر، وفي ترانسيلفانيا تكون النقانق أكثر دخاناً، وفي أولتينيا قد يُستخدم الزعتر الطازج.",\n' \
        '      zh: "香肠炖豆是罗马尼亚家庭的冬日料理——白豆与熏猪肉肠、洋葱、胡萝卜、番茄酱和月桂叶慢炖，直至汤汁浓稠、香气深厚。香肠带来油脂与烟熏味，将朴素的豆类变成一道丰盛、令人满足的主食。通常搭配泡菜、家制面包或玉米糕食用。\\n\\n各地做法略有不同：摩尔多瓦地区加入更多番茄酱；特兰西瓦尼亚的香肠更为熏制；奥尔泰尼亚则可能加入新鲜百里香。",\n' \
        '      ja: "ファソレ・クー・カルナツィはルーマニアの家庭の冬料理です——白インゲン豆を燻製豚ソーセージ、玉ねぎ、にんじん、トマトペースト、ローリエと一緒にじっくり煮込み、スープが濃くなり深い香りになるまで調理します。ソーセージが脂肪と燻製の風味を加え、素朴なマメ科の豆をボリューム満点の料理に変えます。漬物と自家製パンまたはポレンタと共に提供されます。\\n\\nレシピは地域によって異なります：モルダヴィアではトマトペーストが多め、トランシルヴァニアでは燻製度の高いソーセージ、オルテニアでは生のタイムを使うことがあります。",\n' \
        '      tr: "Fasole cu cârnați, Rumen evlerinin kış yemeğidir — beyaz fasulye, tütsülenmiş domuz sosisleri, soğan, havuç, domates salçası ve defne yaprağıyla birlikte, sıvı koyulaşıp derin bir aroma kazanana kadar yavaşça pişirilir. Sosisler yağ ve duman katarak alçakgönüllü bir baklagili doyurucu bir yemeğe dönüştürür. Turşu ve ev ekmeği ya da polenta ile servis edilir.\\n\\nTarif bölgeden bölgeye değişir: Moldova\'da daha fazla domates salçası eklenir; Transilvanya\'da sosisler daha dumanlıdır; Oltenya\'da taze kekik kullanılabilir.",\n' \
        '      it: "Fasole cu cârnați è il piatto invernale delle case rumene — fagioli bianchi cotti lentamente con salsicce di maiale affumicate, cipolla, carote, concentrato di pomodoro e foglie di alloro, finché il liquido si addensa e diventa profondamente aromatico. Le salsicce aggiungono grasso e affumicato, trasformando un umile legume in un pasto sostanzioso. Si serve con sottaceti e pane fatto in casa o polenta.\\n\\nLa ricetta varia per regione: in Moldavia si aggiunge più concentrato di pomodoro; in Transilvania le salsicce sono più affumicate; in Oltenia si può usare timo fresco.",\n' \
        '      ko: "파솔레 쿠 카르나치는 루마니아 가정의 겨울 요리입니다. 흰 강낭콩을 훈제 돼지 소시지, 양파, 당근, 토마토 페이스트, 월계수 잎과 함께 국물이 걸쭉해지고 깊은 향이 날 때까지 천천히 끓입니다. 소시지가 기름기와 훈연 향을 더해 소박한 콩 요리를 든든하고 만족스러운 한 끼로 만들어줍니다. 피클과 집에서 만든 빵 또는 폴렌타와 함께 냅니다.\\n\\n지역마다 레시피가 다릅니다: 몰다비아에서는 토마토 페이스트를 더 많이 넣고, 트란실바니아에서는 소시지가 더 진하게 훈제되며, 올테니아에서는 신선한 타임을 사용하기도 합니다.",\n' \
        '      hi: "फसोले कू कार्नाची रोमानियाई घरों का सर्दियों का व्यंजन है — सफेद बीन्स को स्मोक्ड पोर्क सॉसेज, प्याज़, गाजर, टमाटर पेस्ट और तेज़ पत्ते के साथ धीमी आँच पर तब तक पकाया जाता है जब तक तरल गाढ़ा और गहरी सुगंध से भर नहीं जाता। सॉसेज चर्बी और धुएँदार स्वाद जोड़ता है, जो एक साधारण फलीदार सब्ज़ी को पेट भरने वाले भोजन में बदल देता है। अचार और घर की रोटी या पोलेंटा के साथ परोसा जाता है।\\n\\nव्यंजन क्षेत्र के अनुसार भिन्न होता है: मोल्दोवा में अधिक टमाटर पेस्ट डाला जाता है; ट्रांसिल्वेनिया में सॉसेज अधिक धुएँदार होते हैं; ओल्तेनिया में ताज़ा थाइम का उपयोग हो सकता है।"\n' \
        '    }'

    content = content[:start_idx] + new_block + content[end_idx + len('\n    }'):]
    print("Replaced originText block for ID 133")

with open('public/js/recipes.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("ID 133 fix done")
