// Phase 7 / PR 1 — Discovery section configs + deterministic selection helpers.
//
// Pure leaf module. No I/O, no side effects, no imports from generate-content.mjs.
// Consumers (PR 2/3/4) call `enrichCatalog({ recipes, recipesMeta })` once, then
// pass the result to selectors. All selectors return new arrays sorted by recipe
// id ascending so identical inputs always produce identical output (stable across
// builds). recipes-budget.js is intentionally NOT consumed here — Phase 7 keeps
// the budget set planner-only.

// ─── Constants ──────────────────────────────────────────────────────────────

export const ALL_LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','hi','tr','it','ko'];

// Locales where a per-recipe detail page is actually generated by
// scripts/generate-content.mjs (RECIPE_LANG table). Verified during Phase
// 7 PR 3: recipe details are emitted for all 14 locales (175 recipes ×
// 14 langs = 2,450 pages). The Phase 7 audit's earlier claim of "ro+en
// only" was a miscount — superseded here. resolveDiscoveryTarget therefore
// returns 'recipe' for every locale today. A separate config concept
// (e.g. "which locales should render new discovery strips") belongs at
// the call site, not in this set.
export const RECIPE_DETAIL_LANGS = new Set(['ro','en','es','fr','de','pt','ru','ar','zh','ja','hi','tr','it','ko']);

// Closed tag taxonomy from public/js/recipes-meta.js (TAG_LABELS).
export const KNOWN_TAGS = new Set([
  'quick','budget','vegetarian','vegan','high-protein','family','healthy','spicy','one-pot'
]);

// Canonical English category values used in recipes.js. We match on `.en` so
// selection is locale-independent even when callers ask in another language.
export const MEAL_CATEGORIES = new Set(['Breakfast', 'Lunch', 'Dinner', 'Snack']);

// Dish-kind buckets derived from `tipType` / `pairingsType` in recipes.js.
// Each bucket lists the raw values that should count as a match.
export const DISH_KIND = {
  soup:    new Set(['soup']),
  pasta:   new Set(['pasta']),
  meat:    new Set(['meat']),
  veg:     new Set(['veg']),
  seafood: new Set(['seafood']),
  asian:   new Set(['japanese', 'asian']),
};

// Hand-curated marquee bias for "popular cuisines" to keep the homepage strip
// stable across builds even when recipe counts shift. Higher score wins ties
// and pushes a cuisine into the top-N list. Listed in en spelling, matched
// case-insensitively against `recipe.origin.en`.
export const CUISINE_MARQUEE = {
  italy: 100, japan: 100, mexico: 100, france: 100, india: 95, greece: 95,
  spain: 90, china: 90, vietnam: 85, thailand: 85, 'south korea': 85,
  peru: 80, turkey: 80, romania: 80, germany: 75, usa: 70, lebanon: 70,
};

// Curated culinary adjacencies for the cuisine-hub "related cuisines" strip
// (Phase 7 PR 2). Selected for shared ingredients, technique, or historical
// exchange — not continent grouping. Keys + values are lowercased English
// origin names; matched case-insensitively against `recipe.origin.en`. A
// related cuisine that has no eligible hub (< CUISINE_MIN_RECIPES) is
// silently skipped at build time so links never 404.
export const RELATED_CUISINES = Object.freeze({
  // East & Southeast Asia
  japan:         ['south korea', 'china', 'vietnam'],
  'south korea': ['japan', 'china', 'vietnam'],
  china:         ['japan', 'south korea', 'vietnam'],
  vietnam:       ['thailand', 'china', 'japan'],
  thailand:      ['vietnam', 'indonesia', 'india'],
  indonesia:     ['thailand', 'vietnam', 'india'],

  // South Asia
  india:         ['thailand', 'indonesia', 'lebanon'],

  // Mediterranean
  italy:         ['france', 'greece', 'spain'],
  france:        ['italy', 'spain', 'germany'],
  spain:         ['italy', 'portugal', 'greece'],
  greece:        ['turkey', 'lebanon', 'italy'],
  portugal:      ['spain', 'italy', 'france'],

  // Levant & Caucasus
  turkey:        ['greece', 'lebanon', 'georgia'],
  lebanon:       ['turkey', 'greece', 'india'],
  georgia:       ['russia', 'turkey', 'romania'],

  // Latin America
  mexico:        ['peru', 'spain', 'usa'],
  peru:          ['mexico', 'spain', 'brazil'],
  brazil:        ['peru', 'portugal', 'mexico'],

  // Americas
  usa:           ['mexico', 'uk', 'italy'],

  // Eastern Europe
  romania:       ['hungary', 'greece', 'turkey'],
  hungary:       ['romania', 'germany', 'georgia'],
  russia:        ['georgia', 'romania', 'hungary'],
  ukraine:       ['russia', 'romania', 'hungary'],
  poland:        ['germany', 'hungary', 'russia'],

  // Central Europe
  germany:       ['france', 'hungary', 'poland'],
  austria:       ['germany', 'hungary', 'italy'],

  // Northern Europe
  uk:            ['usa', 'france', 'india'],
});

// Hard cap on how many related cuisines we ever render per hub page.
// Curated lists in RELATED_CUISINES are length 3 today; the cap is a
// defensive ceiling so a future expansion of the map can't bloat pages.
export const MAX_RELATED_CUISINES = 6;

// ─── Catalog enrichment ─────────────────────────────────────────────────────

// Returns an array of plain recipe items merged with their meta sidecar:
// { id, name, origin, category, tipType, pairingsType, nutrition, servings,
//   time, costRon, tags, desc }.
// Missing meta is tolerated (item gets empty tags + undefined time/cost) so
// older recipes don't break selectors. Stable order: ascending id.
export function enrichCatalog({ recipes, recipesMeta }) {
  if (!Array.isArray(recipes)) throw new TypeError('enrichCatalog: recipes must be an array');
  if (!recipesMeta || typeof recipesMeta !== 'object') {
    throw new TypeError('enrichCatalog: recipesMeta must be an object');
  }
  const out = [];
  for (const r of recipes) {
    if (!r || typeof r.id !== 'number') continue;
    const meta = recipesMeta[r.id] || {};
    out.push({
      id: r.id,
      name: r.name || {},
      origin: r.origin || {},
      category: r.category || {},
      tipType: r.tipType || '',
      pairingsType: r.pairingsType || '',
      nutrition: r.nutrition || {},
      servings: typeof r.servings === 'number' ? r.servings : null,
      time: typeof meta.time === 'number' ? meta.time : null,
      costRon: typeof meta.costRon === 'number' ? meta.costRon : null,
      tags: Array.isArray(meta.tags) ? meta.tags.slice() : [],
      desc: meta.desc || {},
    });
  }
  out.sort((a, b) => a.id - b.id);
  return out;
}

// ─── Primitive predicates ───────────────────────────────────────────────────

function hasTag(item, tag) {
  return Array.isArray(item.tags) && item.tags.includes(tag);
}

function isMealCategoryEn(item, categoryEn) {
  return typeof item.category?.en === 'string' && item.category.en === categoryEn;
}

function originKeyEn(item) {
  const v = item.origin?.en;
  return typeof v === 'string' ? v.trim().toLowerCase() : '';
}

function nameMatchesEn(item, regex) {
  const n = item.name?.en;
  return typeof n === 'string' && regex.test(n);
}

// ─── Generic selectors ──────────────────────────────────────────────────────

export function selectByTag(catalog, tag, { exclude = [], max = 8 } = {}) {
  if (!KNOWN_TAGS.has(tag)) return [];
  const skip = new Set(exclude);
  return catalog
    .filter(it => hasTag(it, tag) && !skip.has(it.id))
    .slice(0, max);
}

export function selectByOrigin(catalog, originEn, { exclude = [], max = 8 } = {}) {
  if (!originEn) return [];
  const target = originEn.trim().toLowerCase();
  const skip = new Set(exclude);
  return catalog
    .filter(it => originKeyEn(it) === target && !skip.has(it.id))
    .slice(0, max);
}

export function selectByTimeMax(catalog, maxMinutes, { extraTag = null, exclude = [], max = 8 } = {}) {
  if (typeof maxMinutes !== 'number' || maxMinutes <= 0) return [];
  const skip = new Set(exclude);
  return catalog
    .filter(it => {
      if (skip.has(it.id)) return false;
      if (typeof it.time !== 'number' || it.time > maxMinutes) return false;
      if (extraTag && !hasTag(it, extraTag)) return false;
      return true;
    })
    .slice(0, max);
}

export function selectByCategoryEn(catalog, categoryEn, { exclude = [], max = 8 } = {}) {
  if (!MEAL_CATEGORIES.has(categoryEn)) return [];
  const skip = new Set(exclude);
  return catalog
    .filter(it => isMealCategoryEn(it, categoryEn) && !skip.has(it.id))
    .slice(0, max);
}

export function selectByDishKind(catalog, kind, { exclude = [], max = 8 } = {}) {
  const allowed = DISH_KIND[kind];
  if (!allowed) return [];
  const skip = new Set(exclude);
  return catalog
    .filter(it => !skip.has(it.id) && (allowed.has(it.tipType) || allowed.has(it.pairingsType)))
    .slice(0, max);
}

// Cross-cuisine bridge: items sharing tags with `currentItem` but from a
// different origin. Ranked by overlap count desc, then id asc (stable).
export function selectByTagMix(catalog, currentItem, { exclude = [], max = 4 } = {}) {
  if (!currentItem || !Array.isArray(currentItem.tags) || currentItem.tags.length === 0) return [];
  const wantTags = new Set(currentItem.tags);
  const currentOrigin = originKeyEn(currentItem);
  const skip = new Set([currentItem.id, ...exclude]);
  const scored = [];
  for (const it of catalog) {
    if (skip.has(it.id)) continue;
    if (originKeyEn(it) === currentOrigin) continue;
    let overlap = 0;
    for (const t of it.tags) if (wantTags.has(t)) overlap++;
    if (overlap > 0) scored.push({ it, overlap });
  }
  scored.sort((a, b) => b.overlap - a.overlap || a.it.id - b.it.id);
  return scored.slice(0, max).map(s => s.it);
}

// ─── Composite section selectors ────────────────────────────────────────────

export function selectQuickDinners(catalog, { exclude = [], max = 8 } = {}) {
  const skip = new Set(exclude);
  const base = catalog.filter(it =>
    !skip.has(it.id) &&
    hasTag(it, 'quick') &&
    (isMealCategoryEn(it, 'Dinner') || isMealCategoryEn(it, 'Lunch')) &&
    typeof it.time === 'number' && it.time <= 30
  );
  if (base.length >= 4) return base.slice(0, max);
  // Fallback: relax the time bound to 40 min so smaller locales still fill.
  const relaxed = catalog.filter(it =>
    !skip.has(it.id) &&
    hasTag(it, 'quick') &&
    (isMealCategoryEn(it, 'Dinner') || isMealCategoryEn(it, 'Lunch')) &&
    typeof it.time === 'number' && it.time <= 40
  );
  return relaxed.slice(0, max);
}

export function selectComfortFood(catalog, { exclude = [], max = 8 } = {}) {
  const skip = new Set(exclude);
  return catalog
    .filter(it => {
      if (skip.has(it.id)) return false;
      const kindHit = DISH_KIND.soup.has(it.tipType) || DISH_KIND.pasta.has(it.tipType) || DISH_KIND.meat.has(it.tipType);
      const tagHit = hasTag(it, 'family') || hasTag(it, 'one-pot');
      return kindHit || tagHit;
    })
    .slice(0, max);
}

const SOUP_NAME_RE = /\b(soup|stew|broth|ramen|pho|chowder|bisque)\b/i;

export function selectWorldSoups(catalog, { exclude = [], max = 8 } = {}) {
  const skip = new Set(exclude);
  const matches = catalog.filter(it => {
    if (skip.has(it.id)) return false;
    return DISH_KIND.soup.has(it.tipType) || DISH_KIND.soup.has(it.pairingsType) || nameMatchesEn(it, SOUP_NAME_RE);
  });
  // Enforce diversity: at most 1 recipe per origin so the strip looks global.
  return limitPerOrigin(matches, 1).slice(0, max);
}

const RICE_NOODLE_RE = /\b(rice|noodle|noodles|udon|soba|ramen|pasta|risotto|biryani|paella|pad\s+thai)\b/i;

export function selectRiceAndNoodles(catalog, { exclude = [], max = 8 } = {}) {
  const skip = new Set(exclude);
  return catalog
    .filter(it => {
      if (skip.has(it.id)) return false;
      if (DISH_KIND.asian.has(it.tipType) || DISH_KIND.pasta.has(it.tipType)) return true;
      return nameMatchesEn(it, RICE_NOODLE_RE);
    })
    .slice(0, max);
}

export function selectHighProtein(catalog, { exclude = [], max = 8, proteinThresholdG = 30 } = {}) {
  const skip = new Set(exclude);
  return catalog
    .filter(it => {
      if (skip.has(it.id)) return false;
      if (hasTag(it, 'high-protein')) return true;
      const p = it.nutrition?.prot;
      return typeof p === 'number' && p >= proteinThresholdG;
    })
    .slice(0, max);
}

export function selectBudgetFriendly(catalog, { exclude = [], max = 8, costRonThreshold = 18 } = {}) {
  const skip = new Set(exclude);
  return catalog
    .filter(it => {
      if (skip.has(it.id)) return false;
      if (hasTag(it, 'budget')) return true;
      return typeof it.costRon === 'number' && it.costRon <= costRonThreshold;
    })
    .slice(0, max);
}

// Returns [{ originEn, count, items }] sorted by (marquee score + count) desc,
// then by origin name asc. Top-N origins by recipe density, with hand-curated
// bias from CUISINE_MARQUEE for stability across builds.
export function selectPopularCuisines(catalog, { max = 6, minRecipes = 2 } = {}) {
  const byOrigin = new Map();
  for (const it of catalog) {
    const key = originKeyEn(it);
    if (!key) continue;
    if (!byOrigin.has(key)) byOrigin.set(key, []);
    byOrigin.get(key).push(it);
  }
  const ranked = [];
  for (const [key, items] of byOrigin) {
    if (items.length < minRecipes) continue;
    const score = (CUISINE_MARQUEE[key] || 0) + items.length;
    ranked.push({ originEn: items[0].origin?.en || key, key, count: items.length, score, items });
  }
  ranked.sort((a, b) => b.score - a.score || a.key.localeCompare(b.key));
  return ranked.slice(0, max);
}

// ─── Dedupe + diversity safeguards ──────────────────────────────────────────

// Merges multiple selection results into a single list, preserving first
// occurrence order, removing duplicates by recipe id. Use on a page that
// renders multiple strips so the same recipe never appears twice.
export function dedupeRecipes(...lists) {
  const seen = new Set();
  const out = [];
  for (const list of lists) {
    if (!Array.isArray(list)) continue;
    for (const it of list) {
      if (!it || typeof it.id !== 'number') continue;
      if (seen.has(it.id)) continue;
      seen.add(it.id);
      out.push(it);
    }
  }
  return out;
}

// Returns recipe ids already shown on the page so subsequent selectors can
// pass them via `exclude`. Pair with dedupeRecipes() — this gives you the
// "already used" id list to feed into the next strip's selector.
export function usedIds(...lists) {
  const ids = [];
  const seen = new Set();
  for (const list of lists) {
    if (!Array.isArray(list)) continue;
    for (const it of list) {
      if (!it || typeof it.id !== 'number' || seen.has(it.id)) continue;
      seen.add(it.id);
      ids.push(it.id);
    }
  }
  return ids;
}

// Caps how many items can share the same origin in a single result list.
// Stable: walks input order, keeps the first N per origin, drops the rest.
export function limitPerOrigin(items, maxPerOrigin) {
  if (!Array.isArray(items)) return [];
  if (typeof maxPerOrigin !== 'number' || maxPerOrigin <= 0) return items.slice();
  const counts = new Map();
  const out = [];
  for (const it of items) {
    const key = originKeyEn(it);
    const n = counts.get(key) || 0;
    if (n >= maxPerOrigin) continue;
    counts.set(key, n + 1);
    out.push(it);
  }
  return out;
}

// ─── Locale-aware link helper ───────────────────────────────────────────────

// Decides whether a discovery card for `recipe` in locale `lang` should link
// to the per-recipe detail page or degrade to the cuisine hub. Returns:
//   { target: 'recipe' | 'hub', lang, originEn }
// Callers compose the final URL using their own slug + lang prefix maps
// (kept in scripts/generate-content.mjs). Keeping URL construction out of
// this module avoids duplicating the RECIPE_LANG / cuisineSlug logic.
export function resolveDiscoveryTarget(recipe, lang) {
  const originEn = recipe?.origin?.en || '';
  if (RECIPE_DETAIL_LANGS.has(lang)) {
    return { target: 'recipe', lang, originEn };
  }
  return { target: 'hub', lang, originEn };
}

// ─── Section configs (declarative spec) ─────────────────────────────────────

// Each entry pairs a section id with the selector name in SECTION_SELECTORS,
// the cap, the surfaces where the strip is allowed to render, and a short
// fallback note. Phase 7 PRs 2–6 read these to decide what to emit and where.
// No translated labels live here — strings come from public/js/i18n.js so
// translators have one source of truth (added in a later PR).
export const SECTION_CONFIGS = Object.freeze({
  'popular-cuisines': {
    selector: 'selectPopularCuisines',
    maxItems: 6,
    surfaces: ['homepage', 'plan-detail', 'recipe-index'],
    fallback: 'none-needed',
    note: 'Already exists on homepage + plan detail; recipe-index surface is new in PR 4.',
  },
  'quick-dinners': {
    selector: 'selectQuickDinners',
    maxItems: 8,
    surfaces: ['homepage', 'recipe-index', 'cuisine-hub'],
    fallback: 'relax-time-to-40min',
  },
  'comfort-food': {
    selector: 'selectComfortFood',
    maxItems: 8,
    surfaces: ['homepage', 'recipe-index'],
    fallback: 'none-needed',
  },
  'world-soups': {
    selector: 'selectWorldSoups',
    maxItems: 8,
    surfaces: ['homepage', 'recipe-index'],
    fallback: 'none-needed',
    note: 'Diversity rule: max 1 recipe per origin.',
  },
  'rice-and-noodles': {
    selector: 'selectRiceAndNoodles',
    maxItems: 8,
    surfaces: ['recipe-index', 'plan-detail'],
    fallback: 'none-needed',
  },
  'high-protein-meals': {
    selector: 'selectHighProtein',
    maxItems: 8,
    surfaces: ['homepage', 'recipe-index', 'plan-detail'],
    fallback: 'none-needed',
  },
  'budget-friendly': {
    selector: 'selectBudgetFriendly',
    maxItems: 8,
    surfaces: ['recipe-index', 'plan-detail'],
    fallback: 'none-needed',
    note: 'Phase 7: does NOT consume recipes-budget.js. Planner-only stays planner-only.',
  },
  'from-this-cuisine': {
    selector: 'selectByOrigin',
    maxItems: 8,
    surfaces: ['recipe-detail', 'cuisine-hub'],
    fallback: 'none-needed',
    note: 'Recipe detail uses this today (capped at 5 in generate-content.mjs). PR 2 raises cuisine-hub cap to 8.',
  },
  'similar-tag-mix': {
    selector: 'selectByTagMix',
    maxItems: 4,
    surfaces: ['recipe-detail'],
    fallback: 'none-needed',
    note: 'Cross-cuisine bridge. New strip introduced in PR 3.',
  },
});

// Named map of selector functions so callers can dispatch by SECTION_CONFIGS[id].selector.
// Selectors below the line that take "currentItem" (selectByOrigin, selectByTagMix)
// have different signatures — callers must invoke them directly, not through this map.
export const SECTION_SELECTORS = Object.freeze({
  selectPopularCuisines,
  selectQuickDinners,
  selectComfortFood,
  selectWorldSoups,
  selectRiceAndNoodles,
  selectHighProtein,
  selectBudgetFriendly,
});
