// Discovery helpers for the generated recipe pages — related-cuisine bridges and
// deterministic related-recipe selection.
//
// Pure leaf module. No I/O, no side effects, no imports from generate-content.mjs.
// `enrichCatalog({ recipes, recipesMeta })` is called once, and its result is passed
// to `selectByTagMix`, which returns a new array sorted by recipe id ascending
// so identical inputs always produce identical output (stable across builds).
// recipes-budget.js is intentionally NOT consumed here — Phase 7 keeps the budget
// set planner-only.

// ─── Constants ──────────────────────────────────────────────────────────────

// Locales where a per-recipe detail page is actually generated by
// scripts/generate-content.mjs (RECIPE_LANG table). Recipe details are
// emitted for all 14 locales today (175 recipes × 14 langs = 2,450 pages),
// so resolveDiscoveryTarget returns 'recipe' for every locale. A separate
// config concept (e.g. "which locales should render new discovery strips")
// belongs at the call site, not in this set.
export const RECIPE_DETAIL_LANGS = new Set(['ro','en','es','fr','de','pt','ru','ar','zh','ja','hi','tr','it','ko']);

// Dish-kind buckets derived from `tipType` / `pairingsType` in recipes.js.
// Each bucket lists the raw values that should count as a match.
export const DISH_KIND = {
  soup:    new Set(['soup']),
  pasta:   new Set(['pasta']),
  meat:    new Set(['meat']),
  veg:     new Set(['veg']),
  seafood: new Set(['seafood', 'fish']),
  asian:   new Set(['japanese', 'asian']),
  dessert: new Set(['dessert']),
  salad:   new Set(['salad']),
};

// Reverse lookup (raw tipType/pairingsType value → bucket key), built once
// from DISH_KIND so the two never drift apart. `tipType` is meant to be a
// dish-kind field, but several past batches wrote the cuisine name into it
// instead (e.g. 'korean', 'italian', 'french', 'romanian') or left a stray
// 'def' placeholder — those simply aren't in DISH_KIND, so they resolve to
// `null` below and get no dish-kind bonus, same as before this change
// (pure tag-overlap ranking). Fixing that mislabeled data is a separate,
// recipe-by-recipe content task, not something this lookup should guess at.
const DISH_KIND_BY_RAW = new Map();
for (const [kind, raws] of Object.entries(DISH_KIND)) {
  for (const raw of raws) DISH_KIND_BY_RAW.set(raw, kind);
}

function dishKindOf(item) {
  return DISH_KIND_BY_RAW.get(item.tipType) || DISH_KIND_BY_RAW.get(item.pairingsType) || null;
}

// Curated culinary adjacencies for the cuisine-hub "related cuisines" strip
// (Phase 7 PR 2). Selected for shared ingredients, technique, or historical
// exchange — not continent grouping. Keys + values are lowercased English
// origin names; matched case-insensitively against `recipe.origin.en`. A
// related cuisine that has no eligible hub (< CUISINE_MIN_RECIPES) is
// silently skipped at build time so links never 404.
// NOTE on coverage: any eligible cuisine (>= CUISINE_MIN_RECIPES) missing
// from this map simply renders no "related cuisines" strip on its hub page
// — no error, no placeholder, just a silently skipped section (see
// cuisineHubPage() in generate-content.mjs). That's exactly what happened
// to every country added after this map was first curated: Sweden,
// Australia, Switzerland, Israel, Finland, Philippines, Belgium, Croatia,
// Cambodia, Uzbekistan and a dozen others all had eligible hubs (>=10
// recipes each) with an empty related-cuisines section because nobody
// added them here. Keep this list in sync with buildCuisineHubs() output —
// `node -e "import('./public/js/recipes.js').then(({recipes})=>{...})"`
// diffed against Object.keys(RELATED_CUISINES) catches drift.
export const RELATED_CUISINES = Object.freeze({
  // East & Southeast Asia
  japan:         ['south korea', 'china', 'vietnam'],
  'south korea': ['japan', 'china', 'vietnam'],
  china:         ['japan', 'south korea', 'vietnam'],
  vietnam:       ['thailand', 'china', 'japan'],
  thailand:      ['vietnam', 'indonesia', 'india'],
  indonesia:     ['thailand', 'vietnam', 'india'],
  malaysia:      ['indonesia', 'thailand', 'vietnam'],
  philippines:   ['vietnam', 'indonesia', 'malaysia'],
  cambodia:      ['thailand', 'vietnam', 'indonesia'],

  // South Asia
  india:         ['thailand', 'indonesia', 'lebanon'],
  pakistan:      ['india', 'iran', 'turkey'],

  // Mediterranean
  italy:         ['france', 'greece', 'spain'],
  france:        ['italy', 'spain', 'germany'],
  spain:         ['italy', 'portugal', 'greece'],
  greece:        ['turkey', 'lebanon', 'italy'],
  portugal:      ['spain', 'italy', 'france'],
  croatia:       ['italy', 'hungary', 'austria'],

  // Levant, Caucasus & Central Asia
  turkey:        ['greece', 'lebanon', 'georgia'],
  lebanon:       ['turkey', 'greece', 'india'],
  georgia:       ['russia', 'turkey', 'romania'],
  syria:         ['lebanon', 'turkey', 'egypt'],
  israel:        ['lebanon', 'turkey', 'egypt'],
  iran:          ['turkey', 'lebanon', 'pakistan'],
  uzbekistan:    ['russia', 'georgia', 'turkey'],

  // North & West Africa
  morocco:       ['tunisia', 'egypt', 'lebanon'],
  tunisia:       ['morocco', 'egypt', 'lebanon'],
  egypt:         ['lebanon', 'morocco', 'turkey'],
  ethiopia:      ['egypt', 'nigeria', 'morocco'],
  nigeria:       ['ethiopia', 'morocco', 'tunisia'],

  // Latin America & Caribbean
  mexico:        ['peru', 'spain', 'usa'],
  peru:          ['mexico', 'spain', 'brazil'],
  brazil:        ['peru', 'portugal', 'mexico'],
  argentina:     ['brazil', 'peru', 'spain'],
  ecuador:       ['peru', 'mexico', 'brazil'],
  cuba:          ['brazil', 'mexico', 'usa'],

  // Americas
  usa:           ['mexico', 'united kingdom', 'italy'],

  // Eastern Europe
  romania:       ['hungary', 'greece', 'turkey'],
  hungary:       ['romania', 'germany', 'georgia'],
  russia:        ['georgia', 'romania', 'hungary'],
  ukraine:       ['russia', 'romania', 'hungary'],
  poland:        ['germany', 'hungary', 'russia'],

  // Central & Western Europe
  germany:       ['france', 'hungary', 'poland'],
  austria:       ['germany', 'hungary', 'italy'],
  switzerland:   ['germany', 'france', 'italy'],
  belgium:       ['france', 'netherlands', 'germany'],
  netherlands:   ['germany', 'belgium', 'united kingdom'],

  // Northern Europe
  'united kingdom': ['usa', 'france', 'india'],
  sweden:        ['finland', 'germany', 'netherlands'],
  finland:       ['sweden', 'russia', 'germany'],

  // Oceania
  australia:     ['united kingdom', 'usa', 'vietnam'],
});

// Hard cap on how many related cuisines we ever render per hub page.
// Curated lists in RELATED_CUISINES are length 3 today; the cap is a
// defensive ceiling so a future expansion of the map can't bloat pages.
export const MAX_RELATED_CUISINES = 6;

// ─── Catalog enrichment ─────────────────────────────────────────────────────

// Returns an array of plain recipe items merged with their meta sidecar:
// { id, name, origin, category, tipType, pairingsType, nutrition, servings,
//   time, costRon, tags, desc }.
// Missing meta is tolerated (item gets empty tags + undefined time/cost) so
// older recipes don't break selectors. Stable order: ascending id.
export function enrichCatalog({ recipes, recipesMeta }) {
  if (!Array.isArray(recipes)) throw new TypeError('enrichCatalog: recipes must be an array');
  if (!recipesMeta || typeof recipesMeta !== 'object') {
    throw new TypeError('enrichCatalog: recipesMeta must be an object');
  }
  const out = [];
  for (const r of recipes) {
    if (!r || typeof r.id !== 'number') continue;
    const meta = recipesMeta[r.id] || {};
    out.push({
      id: r.id,
      name: r.name || {},
      origin: r.origin || {},
      category: r.category || {},
      tipType: r.tipType || '',
      pairingsType: r.pairingsType || '',
      nutrition: r.nutrition || {},
      servings: typeof r.servings === 'number' ? r.servings : null,
      time: typeof meta.time === 'number' ? meta.time : null,
      costRon: typeof meta.costRon === 'number' ? meta.costRon : null,
      tags: Array.isArray(meta.tags) ? meta.tags.slice() : [],
      desc: meta.desc || {},
    });
  }
  out.sort((a, b) => a.id - b.id);
  return out;
}

// ─── Primitive predicates ───────────────────────────────────────────────────

function originKeyEn(item) {
  const v = item.origin?.en;
  return typeof v === 'string' ? v.trim().toLowerCase() : '';
}

// Multiplicative mixer for deterministic-but-varied tie-breaking. Same
// technique as the same-cuisine `relWeight` mixer in generate-content.mjs
// (line ~4022) — kept here as a near-duplicate rather than shared/imported
// so this module stays a pure, dependency-free leaf. Math.imul keeps the
// 32-bit multiplication exact; shifting by 7 mixes high/low bits so the
// hash doesn't degenerate into ~sort-by-id.
function bridgeWeight(currentId, candidateId) {
  return Math.imul((candidateId + 1) ^ ((currentId + 1) << 7) ^ ((currentId + 1) >>> 3), 2654435761) >>> 0;
}

// Cross-cuisine bridge: items from a different origin that are actually
// similar to `currentItem` — same kind of dish first (soup↔soup,
// seafood↔seafood, dessert↔dessert...), then diet/practicality tag overlap
// as a secondary signal, then a deterministic per-(current,candidate) hash
// to break remaining ties — NOT ascending id.
//
// Ranking on tags alone was too weak a similarity signal on its own: tags
// are just 9 broad diet/practicality labels (quick, family, vegetarian...),
// so e.g. Miso Soup (a soup) matched Menemen (scrambled eggs) and Tzatziki
// (a yoghurt dip) purely because all three happen to be "quick" and
// "vegetarian" — nothing about them is actually alike. Layering in
// dishKindOf() (derived from tipType/pairingsType) means a soup is ranked
// against other soups before an unrelated dish that merely shares a tag.
//
// Separately, an earlier id-ascending tiebreak meant any recipe sharing
// just one generic tag always lost the tie to the same handful of
// lowest-id recipes: audited pre-fix, Cheeseburger (id 7) and Spaghetti
// Carbonara (id 1) each showed up as a "similar dish" on 167 of 274
// recipes (61% of the whole site), Tacos on 153 — regardless of relevance.
// The hash spreads which candidate wins a tie across many different
// current recipes while staying stable across rebuilds.
export function selectByTagMix(catalog, currentItem, { exclude = [], max = 4 } = {}) {
  if (!currentItem || !Array.isArray(currentItem.tags) || currentItem.tags.length === 0) return [];
  const wantTags = new Set(currentItem.tags);
  const currentOrigin = originKeyEn(currentItem);
  const currentId = currentItem.id || 0;
  const currentKind = dishKindOf(currentItem);
  const skip = new Set([currentItem.id, ...exclude]);
  const scored = [];
  for (const it of catalog) {
    if (skip.has(it.id)) continue;
    if (originKeyEn(it) === currentOrigin) continue;
    let overlap = 0;
    for (const t of it.tags) if (wantTags.has(t)) overlap++;
    const kindMatch = currentKind !== null && dishKindOf(it) === currentKind;
    if (overlap > 0 || kindMatch) {
      scored.push({ it, overlap, kindMatch, w: bridgeWeight(currentId, it.id || 0) });
    }
  }
  scored.sort((a, b) =>
    (b.kindMatch - a.kindMatch) || (b.overlap - a.overlap) || (a.w - b.w));
  return scored.slice(0, max).map(s => s.it);
}

// ─── Locale-aware link helper ───────────────────────────────────────────────

// Decides whether a discovery card for `recipe` in locale `lang` should link
// to the per-recipe detail page or degrade to the cuisine hub. Returns:
//   { target: 'recipe' | 'hub', lang, originEn }
// Callers compose the final URL using their own slug + lang prefix maps
// (kept in scripts/generate-content.mjs). Keeping URL construction out of
// this module avoids duplicating the RECIPE_LANG / cuisineSlug logic.
export function resolveDiscoveryTarget(recipe, lang) {
  const originEn = recipe?.origin?.en || '';
  if (RECIPE_DETAIL_LANGS.has(lang)) {
    return { target: 'recipe', lang, originEn };
  }
  return { target: 'hub', lang, originEn };
}
