#!/usr/bin/env python3
"""Rewrite recipe 204 (Butter Chicken): 13 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Mix the marinade in a wide bowl, add the chicken and turn each piece until well coated, then cover and chill at least 4 hours, ideally overnight. For the gravy, soak the cashews in 100 ml of hot water for 20 minutes; put the tomatoes, onion, garlic, ginger and whole spices into a heavy pan with 200 ml of water, bring to a simmer and cook covered for 20–25 minutes until the tomatoes have collapsed and the onion is fully soft, then fish out the cinnamon, cardamom, cloves and bay leaf, and blend everything — including the soaked cashews and their water — to a velvety purée and pass through a sieve. Heat the broiler high, line a tray with foil, spread the marinated chicken in a single layer with space between the pieces and broil 5–6 cm from the heat for 6–8 minutes per side, until the edges are charred and the meat is just cooked through — let the edges go genuinely dark. Melt the butter in a wide pan over medium heat, pour in the strained gravy and add the chilli powder, sugar and a teaspoon of salt, simmer gently for 10 minutes stirring often until the colour deepens to a rich brick-orange; pour in the cream, stir until the gravy turns velvet, then slide in the charred chicken with any juices from the tray and let everything bubble together for 4–5 minutes more. Crush the kasoori methi between your palms over the pan, stir in the garam masala and taste for salt and sugar, scatter coriander leaves on top, and serve with naan or basmati rice.",

'ro': "Amestecă marinata într-un bol larg, adaugă puiul și învârte fiecare bucată până e bine acoperită, apoi acoperă și răcește cel puțin 4 ore, ideal peste noapte. Pentru sos, înmoaie caju în 100 ml apă fierbinte 20 de minute; pune roșiile, ceapa, usturoiul, ghimbirul și mirodeniile întregi într-o oală groasă cu 200 ml apă, adu la fierbere și gătește acoperit 20–25 de minute până când roșiile s-au desfăcut și ceapa este complet moale, apoi scoate scorțișoara, cardamomul, cuișoarele și foaia de dafin, și blendează totul — inclusiv caju înmuiat și apa lui — la un piure mătăsos și treci-l prin sită. Încălzește grill-ul la maxim, căptușește o tavă cu folie, întinde puiul marinat într-un singur strat cu spațiu între bucăți și pune-l la 5–6 cm de la sursă 6–8 minute pe fiecare parte, până când marginile se ard și carnea este abia gătită — lasă marginile să se închidă cu adevărat. Topește untul într-o tigaie largă pe foc mediu, toarnă sosul strecurat și adaugă pudra de chili, zahărul și o linguriță de sare, fierbe ușor 10 minute, amestecând des, până culoarea se închide spre un portocaliu cărămiziu bogat; toarnă smântâna, amestecă până sosul devine catifelat, apoi pune puiul ars cu sucurile din tavă și las totul să bolborosească împreună încă 4–5 minute. Freacă kasoori methi între palme deasupra tigăii, încorporează garam masala și gustă pentru sare și zahăr, presară frunze de coriandru deasupra și servește cu naan sau orez basmati.",

'es': "Mezcla la marinada en un bol amplio, añade el pollo y voltea cada pieza hasta cubrirla bien, después tapa y refrigera al menos 4 horas, idealmente toda la noche. Para la salsa, remoja los anacardos en 100 ml de agua caliente durante 20 minutos; pon los tomates, la cebolla, el ajo, el jengibre y las especias enteras en una olla pesada con 200 ml de agua, lleva a hervor y cocina tapado 20–25 minutos hasta que los tomates se hayan deshecho y la cebolla esté del todo blanda, después pesca la canela, el cardamomo, los clavos y la hoja de laurel, y tritura todo — incluyendo los anacardos remojados y su agua — hasta un puré aterciopelado y pásalo por un colador. Calienta el grill al máximo, forra una bandeja con papel de aluminio, extiende el pollo marinado en una sola capa con espacio entre las piezas y ásalo a 5–6 cm de la fuente 6–8 minutos por lado, hasta que los bordes estén carbonizados y la carne apenas hecha — deja que los bordes se oscurezcan de verdad. Derrite la mantequilla en una sartén ancha a fuego medio, vierte la salsa colada y añade el chile en polvo, el azúcar y una cucharadita de sal, hierve suavemente 10 minutos removiendo a menudo hasta que el color se vuelva un naranja ladrillo intenso; vierte la nata, remueve hasta que la salsa se vuelva terciopelo, después desliza el pollo asado con los jugos de la bandeja y deja que todo burbujee junto otros 4–5 minutos. Frota el kasoori methi entre las palmas sobre la sartén, incorpora el garam masala y prueba de sal y azúcar, esparce hojas de cilantro por encima y sirve con naan o arroz basmati.",

'fr': "Mélangez la marinade dans un grand bol, ajoutez le poulet et retournez chaque morceau pour bien l'enrober, puis couvrez et faites refroidir au moins 4 heures, idéalement toute la nuit. Pour la sauce, faites tremper les noix de cajou dans 100 ml d'eau chaude pendant 20 minutes ; mettez les tomates, l'oignon, l'ail, le gingembre et les épices entières dans une cocotte épaisse avec 200 ml d'eau, portez à frémissement et faites cuire couvert 20 à 25 minutes jusqu'à ce que les tomates se soient effondrées et l'oignon soit complètement fondant, retirez ensuite la cannelle, la cardamome, les clous de girofle et la feuille de laurier, et mixez tout — y compris les noix de cajou trempées et leur eau — en une purée veloutée et passez au tamis. Faites chauffer le gril au maximum, tapissez une plaque d'aluminium, étalez le poulet mariné en une seule couche en laissant de l'espace entre les morceaux et grillez à 5 à 6 cm de la source 6 à 8 minutes par face, jusqu'à ce que les bords soient carbonisés et la viande tout juste cuite — laissez les bords devenir vraiment foncés. Faites fondre le beurre dans une grande poêle à feu moyen, versez la sauce passée et ajoutez le piment en poudre, le sucre et une cuillère à café de sel, faites mijoter doucement 10 minutes en remuant souvent jusqu'à ce que la couleur s'approfondisse en un orange brique riche ; versez la crème, remuez jusqu'à ce que la sauce devienne veloutée, puis glissez le poulet grillé avec les jus de la plaque et laissez le tout bouillonner encore 4 à 5 minutes. Écrasez le kasoori methi entre vos paumes au-dessus de la poêle, incorporez le garam masala et goûtez pour le sel et le sucre, parsemez de feuilles de coriandre sur le dessus, et servez avec du naan ou du riz basmati.",

'de': "Mischen Sie die Marinade in einer breiten Schüssel, geben Sie das Hähnchen dazu und wenden Sie jedes Stück, bis es gut überzogen ist, dann zudecken und mindestens 4 Stunden, idealerweise über Nacht, kalt stellen. Für die Sauce die Cashews in 100 ml heißem Wasser 20 Minuten einweichen; die Tomaten, Zwiebel, Knoblauch, Ingwer und ganzen Gewürze in einem schweren Topf mit 200 ml Wasser zum Köcheln bringen und zugedeckt 20–25 Minuten garen, bis die Tomaten zerfallen und die Zwiebel ganz weich ist, dann Zimt, Kardamom, Nelken und Lorbeerblatt herausfischen und alles — auch die eingeweichten Cashews mit ihrem Wasser — zu einer samtigen Püree mixen und durch ein Sieb passieren. Den Grill auf höchste Stufe heizen, ein Blech mit Alufolie auslegen, das marinierte Hähnchen in einer Schicht mit Abstand zwischen den Stücken verteilen und 5–6 cm unter der Hitze 6–8 Minuten pro Seite grillen, bis die Ränder verkohlt und das Fleisch gerade durch ist — lassen Sie die Ränder wirklich dunkel werden. Die Butter in einer breiten Pfanne bei mittlerer Hitze schmelzen, die passierte Sauce hineingießen und Chilipulver, Zucker sowie einen Teelöffel Salz hinzufügen, 10 Minuten sanft köcheln lassen unter häufigem Rühren, bis sich die Farbe zu einem satten Ziegelrot vertieft; die Sahne hineingießen, bis die Sauce samtig wird, dann das gegrillte Hähnchen mit den Säften vom Blech hineingleiten lassen und alles noch 4–5 Minuten zusammen blubbern lassen. Das Kasoori Methi zwischen den Handflächen über der Pfanne zerreiben, das Garam Masala einrühren und mit Salz und Zucker abschmecken, mit Korianderblättern bestreuen und mit Naan oder Basmatireis servieren.",

'pt': "Misture a marinada numa tigela ampla, junte o frango e envolva cada pedaço até estar bem coberto, depois tape e refrigere pelo menos 4 horas, idealmente de um dia para o outro. Para o molho, demolhe os cajus em 100 ml de água quente durante 20 minutos; ponha os tomates, a cebola, o alho, o gengibre e as especiarias inteiras numa panela pesada com 200 ml de água, leve a uma fervura e cozinhe tapado 20–25 minutos até os tomates se desfazerem e a cebola estar totalmente macia, depois retire a canela, o cardamomo, os cravinhos e a folha de louro, e bata tudo — incluindo os cajus demolhados e a sua água — num puré aveludado e passe por um coador. Aqueça o grelhador no máximo, forre um tabuleiro com folha de alumínio, espalhe o frango marinado numa única camada com espaço entre as peças e grelhe a 5–6 cm da fonte 6–8 minutos por lado, até as bordas estarem carbonizadas e a carne apenas cozida — deixe as bordas escurecerem a sério. Derreta a manteiga numa frigideira ampla em lume médio, verta o molho coado e junte o piri-piri em pó, o açúcar e uma colher de chá de sal, deixe ferver brandamente 10 minutos mexendo com frequência até a cor aprofundar num laranja-tijolo intenso; verta as natas, mexa até o molho ficar aveludado, depois deslize o frango grelhado com os sucos do tabuleiro e deixe tudo borbulhar mais 4–5 minutos. Esfregue o kasoori methi entre as palmas por cima da frigideira, envolva o garam masala e prove de sal e açúcar, polvilhe folhas de coentros por cima e sirva com naan ou arroz basmati.",

'ru': "Смешайте маринад в широкой миске, добавьте курицу и переверните каждый кусок, пока хорошо не покроется, затем накройте и охладите минимум 4 часа, идеально на ночь. Для подливы замочите кешью в 100 мл горячей воды на 20 минут; положите помидоры, лук, чеснок, имбирь и целые специи в тяжёлую кастрюлю с 200 мл воды, доведите до кипения и варите под крышкой 20–25 минут, пока помидоры не развалятся, а лук не станет полностью мягким, затем выловите корицу, кардамон, гвоздику и лавровый лист, и пюрируйте всё — включая замоченные кешью и их воду — до бархатистой пюре и пропустите через сито. Разогрейте гриль на максимум, выстелите противень фольгой, выложите маринованную курицу в один слой с пространством между кусками и обжарьте на расстоянии 5–6 см от источника 6–8 минут с каждой стороны, пока края не обуглятся, а мясо едва не прожарится — пусть края станут по-настоящему тёмными. Растопите масло в широкой сковороде на среднем огне, влейте процеженную подливу и добавьте чилийский порошок, сахар и чайную ложку соли, варите на лёгком огне 10 минут, часто помешивая, пока цвет не углубится до насыщенного кирпично-оранжевого; влейте сливки, помешивая, пока подлива не станет бархатной, затем опустите обугленную курицу с соками с противня и дайте всему вместе побулькать ещё 4–5 минут. Разотрите касури мети между ладоней над сковородой, вмешайте гарам масалу и попробуйте на соль и сахар, посыпьте сверху листьями кинзы и подавайте с наном или басмати.",

'ar': "اخلط التتبيلة في وعاء واسع، أضف الدجاج وقلّب كل قطعة حتى تتغطى جيداً، ثم غطّ واحفظ في البراد ساعتين على الأقل، ويفضل طوال الليل. للصلصة، انقع الكاجو في 100 مل من الماء الساخن لمدة 20 دقيقة؛ ضع الطماطم والبصل والثوم والزنجبيل والبهارات الكاملة في قدر ثقيل مع 200 مل من الماء، أوصلها للغليان واطبخ مغطىً 20–25 دقيقة حتى تنهار الطماطم ويصبح البصل طرياً تماماً، ثم انتشل القرفة والهيل والقرنفل وورقة الغار، واخفق كل شيء — بما في ذلك الكاجو المنقوع وماؤه — إلى مهروس مخملي ومرّره عبر مصفاة. سخّن الشواية لأعلى درجة، بطّن صينية بورق الألمنيوم، افرد الدجاج المتبل في طبقة واحدة مع ترك مسافة بين القطع وشوِ على بعد 5–6 سم من الحرارة 6–8 دقائق لكل جانب، حتى تتفحم الحواف ويصبح اللحم ناضجاً للتو — اترك الحواف تغمق بالفعل. أذِب الزبدة في مقلاة واسعة على نار متوسطة، اسكب الصلصة المصفاة وأضف مسحوق الفلفل والسكر وملعقة صغيرة من الملح، أغلِ برفق 10 دقائق مع التحريك المتكرر حتى يغمق اللون إلى برتقالي قرميدي غني؛ اسكب الكريمة، حرّك حتى تصبح الصلصة مخملية، ثم أنزل الدجاج المتفحم مع عصاراته من الصينية واتركها تغلي معاً 4–5 دقائق أخرى. افرك الكسوري ميثي بين راحتيك فوق المقلاة، حرّك الجارام مسالا وتذوّق الملح والسكر، انثر أوراق الكزبرة فوق، وقدّمها مع خبز النان أو أرز البسمتي.",

'zh': "在一只宽碗里调匀腌料，加入鸡肉，将每块翻匀，盖好放入冰箱冷藏至少 4 小时，最好一夜。做酱汁：腰果用 100 毫升热水泡 20 分钟；把番茄、洋葱、大蒜、生姜和整粒香料放进一只厚锅，加 200 毫升水，烧至微沸，盖盖煮 20–25 分钟，直到番茄塌陷、洋葱完全软，然后捞出肉桂、豆蔻、丁香和月桂叶，把剩下的所有材料——包括泡过的腰果和泡水——一起打成丝滑顺滑的酱，过筛回锅。把烤箱开到最高档，烤盘铺锡纸，把腌好的鸡肉单层铺开、块与块之间留空隙，放在距热源 5–6 cm 的位置每面烤 6–8 分钟，直到边缘焦黑、肉刚好熟透——让边缘真正变深。把黄油在宽锅里中火融化，倒入过筛的酱汁，加辣椒粉、糖和 1 茶匙盐，小火慢煮 10 分钟，常搅拌，直到颜色加深为浓郁的砖橙色；倒入奶油，搅拌至酱汁变为天鹅绒般顺滑，再把烤好的鸡肉连同烤盘里的汁滑入锅中，一起再咕嘟咕嘟 4–5 分钟。在锅上把卡苏里葛缕子在手心揉碎撒入，拌入葛兰玛萨拉，尝咸甜，撒上香菜叶，配 naan 或 basmati 米饭享用。",

'ja': "広めのボウルでマリネ液を混ぜ、鶏肉を加えて 1 切れずつしっかりまとわせ、蓋をして冷蔵庫で少なくとも 4 時間、理想的には一晩漬ける。グレービー用にカシューナッツを 100 ml の熱湯に 20 分浸す；トマト、玉ねぎ、にんにく、生姜、ホールスパイスを厚手の鍋に 200 ml の水と入れ、煮立たせて蓋をして 20〜25 分、トマトが崩れ玉ねぎが完全に柔らかくなるまで煮、シナモン、カルダモン、クローブ、ベイリーフを取り出し、戻したカシューとその水を含めすべてをビロードのようなピューレに撹拌して漉す。グリルを最高温度に予熱し、トレーにアルミ箔を敷き、マリネした鶏肉を間隔をあけて一段に並べ、熱源から 5〜6 cm の距離で各面 6〜8 分、縁が焦げ、肉がちょうど火が通るまで焼く — 縁は本当に黒く焦がす。広めのフライパンでバターを中火で溶かし、漉したグレービーを注ぎ、チリパウダー、砂糖、塩小さじ 1 を加え、頻繁に混ぜながら 10 分弱火で煮込み、色が深いレンガ色に深まるまで；生クリームを加えて滑らかなビロード状になるまで混ぜ、焦げ目のついた鶏肉をトレーの肉汁ごと滑り込ませ、さらに 4〜5 分一緒に煮込む。フライパンの上でカスリメティを手のひらでもんで散らし、ガラムマサラを加え、塩と砂糖の味を整え、コリアンダーの葉を散らし、ナンまたはバスマティライスと共に供する。",

'tr': "Geniş bir kâsede marineyi karıştır, tavuğu ekle ve her parçayı iyice kapla, sonra üstünü ört ve en az 4 saat, ideal olarak gece boyu buzdolabında dinlendir. Sos için kaju fıstıklarını 100 ml sıcak suda 20 dakika ıslat; domatesleri, soğanı, sarımsağı, zencefili ve bütün baharatları ağır bir tencereye 200 ml suyla koy, kaynamaya getir ve kapalı 20–25 dakika, domatesler dağılıp soğan tamamen yumuşayana dek pişir, sonra tarçın, kakule, karanfil ve defne yaprağını al, ve her şeyi — ıslatılmış kajularını ve suyunu dahil — kadife gibi pürüze çekip süzgeçten geçir. Izgarayı en yüksek dereceye ısıt, bir tepsiyi folyo ile döşe, marine edilmiş tavuğu parçalar arasında boşluk bırakarak tek katta yay ve ısıdan 5–6 cm uzaklıkta her tarafından 6–8 dakika, kenarlar yanıp et tam piştiği anda gelene dek ızgara yap — kenarların gerçekten koyulaşmasına izin ver. Tereyağını geniş bir tavada orta ateşte erit, süzülmüş sosu dök ve biber tozunu, şekeri ve 1 çay kaşığı tuzu ekle, sık karıştırarak 10 dakika yavaşça pişir, renk derin tuğla turuncusuna ulaşana dek; kremayı dök, sos kadife kıvama gelene dek karıştır, sonra ızgara edilmiş tavuğu tepsideki suyuyla birlikte içine kaydır ve hep birlikte 4–5 dakika daha kaynatın. Kasoori methi'yi avuçların arasında ovarak tavanın üstüne dök, garam masala'yı ekle ve tuz ve şeker için tadına bak, üstüne kişniş yaprakları serp ve naan veya basmati pirinçle servis et.",

'it': "Mescolate la marinata in una ciotola ampia, aggiungete il pollo e rigirate ogni pezzo finché non è ben coperto, poi coprite e riponete in frigo almeno 4 ore, idealmente tutta la notte. Per il sugo mettete a bagno gli anacardi in 100 ml di acqua calda per 20 minuti; mettete i pomodori, la cipolla, l'aglio, lo zenzero e le spezie intere in una pentola pesante con 200 ml di acqua, portate a sobbollire e cuocete coperto 20–25 minuti finché i pomodori non si sono sfatti e la cipolla non è completamente morbida, poi pescate cannella, cardamomo, chiodi di garofano e alloro, e frullate tutto — compresi gli anacardi ammollati e la loro acqua — in una purea vellutata e passate al setaccio. Scaldate il grill al massimo, rivestite una teglia con foglio di alluminio, distribuite il pollo marinato in un solo strato lasciando spazio tra i pezzi e grigliate a 5–6 cm dal calore 6–8 minuti per lato, finché i bordi non sono carbonizzati e la carne è appena cotta — lasciate che i bordi diventino davvero scuri. Fate sciogliere il burro in una padella ampia a fuoco medio, versate il sugo setacciato e aggiungete la polvere di peperoncino, lo zucchero e un cucchiaino di sale, fate sobbollire dolcemente 10 minuti mescolando spesso finché il colore non si approfondisce in un arancio mattone intenso; versate la panna, mescolate finché il sugo non diventa vellutato, poi fate scivolare il pollo grigliato con i succhi dalla teglia e lasciate sobbollire tutto insieme altri 4–5 minuti. Sbriciolate il kasoori methi tra le palme sopra la padella, unite il garam masala e regolate di sale e zucchero, cospargete con foglie di coriandolo, e servite con naan o riso basmati.",

'ko': "넓은 볼에 양념을 섞고, 닭고기를 넣어 모든 조각이 잘 묻도록 뒤집은 다음 덮어 냉장고에서 최소 4시간, 이상적으로는 하룻밤 재워둔다. 그레이비용으로 캐슈너트를 100 ml의 뜨거운 물에 20분 불린다; 토마토, 양파, 마늘, 생강과 통향신료를 두꺼운 냄비에 200 ml의 물과 함께 넣고 끓을 정도로 가열한 다음 뚜껑을 덮고 20–25분, 토마토가 무너지고 양파가 완전히 부드러워질 때까지 끓이고, 시나몬, 카다멈, 정향, 월계수잎을 건져낸 뒤, 불린 캐슈와 그 물을 포함한 모든 것을 부드러운 벨벳 같은 퓌레로 갈아 체에 거른다. 브로일러를 최고로 예열하고, 트레이에 호일을 깔고, 양념된 닭고기를 조각 사이에 공간을 두고 한 겹으로 펴고, 열원에서 5–6 cm 떨어진 곳에서 한 면당 6–8분, 가장자리가 그을리고 고기가 갓 익을 때까지 굽는다 — 가장자리가 진짜로 까맣게 그을리도록 한다. 넓은 팬에 버터를 중불로 녹이고, 체에 거른 그레이비를 붓고, 칠리 파우더, 설탕, 소금 1작은술을 넣고, 자주 저으며 10분간 약한 불에 끓여 색이 진한 벽돌-주황색이 될 때까지 졸이고; 생크림을 부어 그레이비가 벨벳처럼 부드러워질 때까지 저은 뒤, 그을린 닭고기와 트레이의 육즙까지 미끄러뜨려 넣고 전체를 4–5분 더 함께 보글거리게 한다. 카수리 메티를 손바닥에서 비벼 팬 위에 뿌리고, 가람 마살라를 더해 소금과 설탕 맛을 보고, 위에 고수 잎을 흩뿌리고, 난 또는 바스마티 라이스와 함께 낸다.",

'hi': "एक चौड़े बाउल में मैरीनेड मिलाएँ, चिकन डालें और हर टुकड़ा अच्छी तरह लपेट दें, फिर ढक कर कम से कम 4 घंटे, बेहतर रात भर फ्रिज में रखें। ग्रेवी के लिए, काजू को 100 मिली गरम पानी में 20 मिनट भिगोएँ; टमाटर, प्याज़, लहसुन, अदरक और साबुत मसाले एक भारी बर्तन में 200 मिली पानी के साथ डालें, उबाल पर लाएँ और ढक कर 20–25 मिनट तक तब तक पकाएँ जब तक टमाटर पूरी तरह से न पिघलें और प्याज़ बिल्कुल नर्म न हो जाए, फिर दालचीनी, इलायची, लौंग और तेज़पत्ता निकालें, और सब कुछ — भिगोए हुए काजू और उनके पानी समेत — एक मखमली प्यूरी में पीसें और छलनी से छानें। ब्रॉयलर को सबसे ऊँचा गरम करें, ट्रे में फ़ॉयल बिछाएँ, मैरीनेट किया चिकन एक परत में, टुकड़ों के बीच जगह छोड़ कर फैलाएँ, और हीट से 5–6 सेमी दूरी पर हर तरफ़ 6–8 मिनट तक तब तक भूनें जब तक किनारे जल कर काले न हो जाएँ और मांस बस-बस पका हो — किनारों को सचमुच गहरा होने दें। चौड़े पैन में मध्यम आँच पर मक्खन पिघलाएँ, छनी हुई ग्रेवी डालें और मिर्च पाउडर, चीनी और 1 छोटा चम्मच नमक डालें, अक्सर चलाते हुए 10 मिनट हलकी आँच पर पकाएँ जब तक रंग गहरे ईंट-नारंगी रंग का न हो जाए; क्रीम डालें, ग्रेवी मखमली होने तक चलाएँ, फिर भुना चिकन ट्रे के रस सहित डालें और सब को 4–5 मिनट और साथ में उबलने दें। हथेलियों के बीच kasoori methi को रगड़ कर पैन में डालें, गरम मसाला मिलाएँ और नमक-चीनी चखें, ऊपर से धनिया पत्ती छिड़कें, और naan या basmati चावल के साथ परोसें।",
}

FEATURE_CARDS = {
'en': '[{icon:"🌙", t:"Marinate overnight", d:"Yoghurt-spice bath, 4+ hours minimum for full depth"}, {icon:"🔥", t:"Char before saucing", d:"Genuinely dark edges under the broiler — flavour anchor"}, {icon:"🥜", t:"Cashew velvet", d:"Blended into the gravy for body without flour-thickening"}, {icon:"🌿", t:"Kasoori methi finish", d:"Crushed between palms — the dried-fenugreek lift"}]',
'ro': '[{icon:"🌙", t:"Marinează peste noapte", d:"Iaurt cu mirodenii, minim 4 ore pentru profunzime completă"}, {icon:"🔥", t:"Arde înainte de a săsa", d:"Margini cu adevărat închise sub grill — ancora de aromă"}, {icon:"🥜", t:"Catifea de caju", d:"Blendat în sos pentru corp, fără îngroșare cu făină"}, {icon:"🌿", t:"Kasoori methi la final", d:"Frecat între palme — nota de schinduf uscat"}]',
'es': '[{icon:"🌙", t:"Marina toda la noche", d:"Baño de yogur y especias, mínimo 4 horas para profundidad"}, {icon:"🔥", t:"Carboniza antes de salsear", d:"Bordes realmente oscuros bajo el grill — ancla de sabor"}, {icon:"🥜", t:"Terciopelo de anacardo", d:"Triturado en la salsa para dar cuerpo sin espesar con harina"}, {icon:"🌿", t:"Kasoori methi al final", d:"Aplastado entre las palmas — el alza del fenogreco seco"}]',
'fr': '[{icon:"🌙", t:"Marinade de nuit", d:"Bain de yaourt-épices, minimum 4 heures pour la profondeur"}, {icon:"🔥", t:"Carboniser avant de sauer", d:"Bords vraiment sombres sous le gril — ancre de saveur"}, {icon:"🥜", t:"Velours de noix de cajou", d:"Mixé dans la sauce pour le corps, sans liaison à la farine"}, {icon:"🌿", t:"Kasoori methi à la fin", d:"Écrasé entre les paumes — le fenugrec sec"}]',
'de': '[{icon:"🌙", t:"Über Nacht marinieren", d:"Joghurt-Gewürz-Bad, mindestens 4 Stunden für volle Tiefe"}, {icon:"🔥", t:"Vor dem Saucieren karamellisieren", d:"Wirklich dunkle Ränder unter dem Grill — Geschmacksanker"}, {icon:"🥜", t:"Cashew-Samt", d:"In die Sauce gemixt für Körper, ohne Mehlbindung"}, {icon:"🌿", t:"Kasoori Methi am Ende", d:"Zwischen den Handflächen zerrieben — der getrocknete Bockshornklee"}]',
'pt': '[{icon:"🌙", t:"Marinar de um dia para o outro", d:"Banho de iogurte-especiarias, mínimo 4 horas para profundidade"}, {icon:"🔥", t:"Tostar antes de molhar", d:"Bordas realmente escuras sob o grill — âncora de sabor"}, {icon:"🥜", t:"Veludo de caju", d:"Batido no molho para corpo, sem engrossar com farinha"}, {icon:"🌿", t:"Kasoori methi no fim", d:"Esfregado entre as palmas — o feno-grego seco"}]',
'ru': '[{icon:"🌙", t:"Маринуйте на ночь", d:"Йогуртово-пряная ванна, минимум 4 часа для глубины"}, {icon:"🔥", t:"Обугли перед соусом", d:"По-настоящему тёмные края под грилем — якорь вкуса"}, {icon:"🥜", t:"Бархат из кешью", d:"Вмешан в соус для тела, без муки-загустителя"}, {icon:"🌿", t:"Касури мети в конце", d:"Растёртый между ладоней — сухой пажитник"}]',
'ar': '[{icon:"🌙", t:"تتبيلة طوال الليل", d:"حمام لبن وبهارات، 4 ساعات على الأقل للعمق"}, {icon:"🔥", t:"تفحم قبل التغليس", d:"حواف داكنة فعلاً تحت الشواية — مرساة النكهة"}, {icon:"🥜", t:"مخمل الكاجو", d:"مخفوق في الصلصة للقوام، دون تثخين بالدقيق"}, {icon:"🌿", t:"كسوري ميثي في النهاية", d:"يُفرك بين الراحتين — الحلبة الجافة"}]',
'zh': '[{icon:"🌙", t:"腌过夜", d:"酸奶香料浴，至少 4 小时以达到深度"}, {icon:"🔥", t:"先焦化再做酱", d:"烤箱下真正变黑的边缘——风味之锚"}, {icon:"🥜", t:"腰果天鹅绒", d:"打入酱中提供质地，无需面粉增稠"}, {icon:"🌿", t:"末尾的卡苏里葛缕子", d:"掌心揉碎——干胡芦巴的升华"}]',
'ja': '[{icon:"🌙", t:"一晩マリネ", d:"ヨーグルト-スパイス浴、深みのため最低 4 時間"}, {icon:"🔥", t:"ソースの前に焦がす", d:"グリル下で本当に黒くなる縁 — 味のアンカー"}, {icon:"🥜", t:"カシューのビロード", d:"ソースに撹拌してコクを出す、小麦粉のとろみ不要"}, {icon:"🌿", t:"最後のカスリメティ", d:"手のひらでもむ — 乾燥フェヌグリークの高揚"}]',
'tr': '[{icon:"🌙", t:"Gece boyu marine", d:"Yoğurt-baharat banyosu, derinlik için en az 4 saat"}, {icon:"🔥", t:"Sostan önce kömürleştir", d:"Izgara altında gerçekten koyu kenarlar — lezzet çapası"}, {icon:"🥜", t:"Kaju kadifesi", d:"Sosta çekilip gövde verir, un kıvamlaştırıcı gerekmez"}, {icon:"🌿", t:"Sonda kasoori methi", d:"Avuç içinde ovulur — kuru çemen yükselişi"}]',
'it': '[{icon:"🌙", t:"Marinatura notturna", d:"Bagno yogurt-spezie, minimo 4 ore per profondità"}, {icon:"🔥", t:"Carbonizzare prima di salsare", d:"Bordi davvero scuri sotto il grill — ancora di sapore"}, {icon:"🥜", t:"Velluto di anacardio", d:"Frullato nel sugo per corpo, senza addensante di farina"}, {icon:"🌿", t:"Kasoori methi finale", d:"Sbriciolato fra le palme — il fieno greco essiccato"}]',
'ko': '[{icon:"🌙", t:"하룻밤 재우기", d:"요거트-향신료 욕조, 깊이를 위해 최소 4시간"}, {icon:"🔥", t:"소스 전에 그을리기", d:"브로일러 아래 진짜 까만 가장자리 — 풍미의 닻"}, {icon:"🥜", t:"캐슈 벨벳", d:"그레이비에 갈아 넣어 바디감, 밀가루 농후제 불필요"}, {icon:"🌿", t:"마지막 카수리 메티", d:"손바닥에서 비비기 — 마른 페누그릭의 상승"}]',
'hi': '[{icon:"🌙", t:"रात भर मैरीनेट", d:"दही-मसाला स्नान, गहराई के लिए कम से कम 4 घंटे"}, {icon:"🔥", t:"सॉस से पहले जलाएँ", d:"ब्रॉयलर के नीचे सचमुच गहरे किनारे — स्वाद का लंगर"}, {icon:"🥜", t:"काजू मखमल", d:"ग्रेवी में पीस कर बॉडी, आटे की गाढ़ापन की ज़रूरत नहीं"}, {icon:"🌿", t:"अंत में kasoori methi", d:"हथेलियों के बीच मसलना — सूखी मेथी की उठान"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*204,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 204 (Butter Chicken): {rec_end-rec_start} → {len(new_recipe_block)} chars")
