#!/usr/bin/env python3
"""Rewrite recipe 209 (Green Curry): howIsMade 9 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "In a wok or heavy pan over medium heat, spoon in the coconut cream and let it cook for 4–5 minutes, stirring occasionally, until the oil cracks out and the cream takes on a slick sheen — this foundation step is what separates Thai-restaurant green curry from the watery home version. Add the green curry paste to the split cream and fry for 2–3 minutes, stirring constantly, until the paste darkens, releases its perfume of galangal, lemongrass and Thai basil, and the oil turns a vivid green — the kitchen will smell like a Bangkok back street. Slide in the chicken and turn the pieces in the paste until coated, cook 3–4 minutes until the meat is half-sealed, then pour in the coconut milk and bring to a gentle simmer; add the eggplants, bamboo shoots and torn kaffir lime leaves, and simmer uncovered for 10–12 minutes until the eggplants are tender and the chicken is just cooked through. Season with the fish sauce and palm sugar, tasting as you go — the curry should hit salty, sweet, herbaceous and a clean green chilli heat all at once — then stir in the sliced red chillies and Thai basil, swirl the pan once and take it off the heat after 30 seconds so the basil stays bright in the bowl. Serve in shallow bowls with jasmine rice on the side.",

'ro': "Într-un wok sau o tigaie grea pe foc mediu, pune smântâna de cocos și las-o să gătească 4–5 minute, amestecând din când în când, până când uleiul iese la suprafață și crema capătă o strălucire de oglindă — acest pas de fundație este ce separă curry-ul verde de restaurant thailandez de varianta apoasă de acasă. Adaugă pasta de curry verde în crema separată și prăjește-o 2–3 minute, amestecând continuu, până când pasta se închide la culoare, eliberează parfumul de galangal, lemongrass și busuioc thailandez, iar uleiul devine de un verde vibrant — bucătăria va mirosi ca o stradă lăturalnică din Bangkok. Adaugă puiul și învârte bucățile în pastă până sunt acoperite, gătește 3–4 minute până când carnea este pe jumătate închisă la culoare, apoi toarnă laptele de cocos și adu la o fierbere blândă; adaugă vinetele, vârfurile de bambus și frunzele rupte de lămâi kaffir, și fierbe descoperit 10–12 minute, până când vinetele sunt moi și puiul abia gătit. Asezonează cu sosul de pește și zahărul de palmier, gustând pe parcurs — curry-ul trebuie să lovească sărat, dulce, ierbos și o căldură de chili verde curată simultan — apoi adaugă ardeii roșii feliați și busuiocul thailandez, învârte tigaia o dată și ia-o de pe foc după 30 de secunde, astfel încât busuiocul să rămână viu în bol. Servește în boluri puțin adânci, cu orez iasomie alături.",

'es': "En un wok o sartén pesada a fuego medio, vierte la crema de coco y deja que se cocine 4–5 minutos, removiendo de vez en cuando, hasta que el aceite se separe y la crema tome un brillo aceitoso — este paso de fondo es lo que separa el curry verde de restaurante tailandés de la versión aguada casera. Añade la pasta de curry verde a la crema separada y fríe 2–3 minutos, removiendo sin parar, hasta que la pasta se oscurezca, libere su perfume a galanga, citronela y albahaca tailandesa, y el aceite se ponga de un verde vivo — la cocina olerá a callejón de Bangkok. Incorpora el pollo y voltéalo en la pasta hasta cubrirlo, cocínalo 3–4 minutos hasta que la carne esté medio sellada, después vierte la leche de coco y lleva a un hervor suave; añade las berenjenas, los brotes de bambú y las hojas de lima kaffir rasgadas, y cuece destapado 10–12 minutos, hasta que las berenjenas estén tiernas y el pollo recién hecho. Sazona con la salsa de pescado y el azúcar de palma, probando sobre la marcha — el curry debe golpear salado, dulce, herbáceo y un picor de chile verde limpio todo a la vez — luego añade los chiles rojos en rodajas y la albahaca tailandesa, gira la sartén una vez y retírala del fuego a los 30 segundos para que la albahaca quede luminosa en el bol. Sirve en cuencos hondos con arroz jazmín al lado.",

'fr': "Dans un wok ou une sauteuse épaisse à feu moyen, versez la crème de coco et laissez-la cuire 4 à 5 minutes en remuant de temps en temps, jusqu'à ce que l'huile se sépare et que la crème prenne un brillant huileux — cette étape de fond est ce qui sépare le curry vert thaï de restaurant de la version aqueuse domestique. Ajoutez la pâte de curry vert à la crème séparée et faites-la frire 2 à 3 minutes en remuant sans cesse, jusqu'à ce qu'elle fonce, libère son parfum de galanga, citronnelle et basilic thaï, et que l'huile prenne une couleur vert vif — la cuisine sentira la ruelle de Bangkok. Glissez le poulet et tournez les morceaux dans la pâte jusqu'à enrobage, faites cuire 3 à 4 minutes jusqu'à ce que la viande soit à moitié saisie, puis versez le lait de coco et portez à frémissement doux ; ajoutez les aubergines, les pousses de bambou et les feuilles de combava déchirées, et laissez frémir à découvert 10 à 12 minutes, jusqu'à ce que les aubergines soient tendres et le poulet tout juste cuit. Assaisonnez avec le nuoc-mâm et le sucre de palme en goûtant au fur et à mesure — le curry doit toucher le salé, le sucré, l'herbeux et un piquant vert et net en même temps — puis ajoutez les piments rouges en lamelles et le basilic thaï, tournez la sauteuse une fois et retirez du feu au bout de 30 secondes pour que le basilic reste vif dans le bol. Servez dans des bols peu profonds, avec du riz jasmin à part.",

'de': "Geben Sie in einem Wok oder einer schweren Pfanne bei mittlerer Hitze die Kokoscreme hinein und lassen Sie sie 4–5 Minuten köcheln, gelegentlich umrühren, bis das Öl austritt und die Creme einen öligen Glanz bekommt — dieser Schritt ist das, was das thailändische Restaurant-Curry von der wässrigen Hausvariante trennt. Geben Sie die grüne Currypaste in die gespaltene Creme und braten Sie sie 2–3 Minuten unter ständigem Rühren, bis die Paste dunkler wird, ihren Duft von Galgant, Zitronengras und Thai-Basilikum freigibt und das Öl ein leuchtendes Grün annimmt — die Küche wird nach einer Bangkoker Seitenstraße duften. Geben Sie das Hähnchen hinein und wenden Sie es in der Paste bis es überzogen ist, garen Sie 3–4 Minuten, bis das Fleisch halb gar ist, gießen Sie dann die Kokosmilch dazu und bringen Sie das Ganze auf sanftes Köcheln; fügen Sie die Auberginen, Bambussprossen und zerrissenen Kaffirlimettenblätter hinzu und köcheln Sie unbedeckt 10–12 Minuten, bis die Auberginen weich und das Hähnchen gerade gar ist. Würzen Sie mit Fischsauce und Palmzucker und schmecken Sie unterwegs ab — das Curry soll gleichzeitig salzig, süß, krautig und mit einer klaren grünen Chili-Schärfe sein — rühren Sie dann die roten Chilis in Scheiben und das Thai-Basilikum ein, schwenken Sie die Pfanne einmal und nehmen Sie sie nach 30 Sekunden vom Herd, damit das Basilikum in der Schale leuchtend bleibt. In flachen Schalen mit Jasminreis daneben servieren.",

'pt': "Numa wok ou frigideira pesada em lume médio, deite as natas de coco e deixe cozinhar 4–5 minutos, mexendo de vez em quando, até o óleo se separar e as natas ganharem um brilho oleoso — este passo de base é o que separa o caril verde de restaurante tailandês da versão aguada de casa. Junte a pasta de caril verde às natas separadas e frite 2–3 minutos, mexendo sem parar, até a pasta escurecer, libertar o seu perfume de galanga, capim-limão e manjericão tailandês, e o óleo ficar de um verde vivo — a cozinha vai cheirar a um beco de Bangkok. Deslize o frango e envolva os pedaços na pasta até ficarem cobertos, cozinhe 3–4 minutos até a carne estar meio selada, depois deite o leite de coco e leve a uma fervura branda; junte as beringelas, os rebentos de bambu e as folhas de lima kaffir rasgadas, e deixe ferver destapado 10–12 minutos, até as beringelas estarem tenras e o frango mal feito. Tempere com o molho de peixe e o açúcar de palma, provando à medida — o caril deve atingir salgado, doce, herbáceo e um picante de piri-piri verde limpo tudo ao mesmo tempo — junte depois os piri-piris vermelhos fatiados e o manjericão tailandês, rode a wok uma vez e retire do lume aos 30 segundos para o manjericão manter o seu brilho na taça. Sirva em taças fundas com arroz jasmim ao lado.",

'ru': "В воке или тяжёлой сковороде на среднем огне выложите кокосовые сливки и томите 4–5 минут, периодически помешивая, пока масло не отделится и сливки не приобретут жирный блеск — этот фундаментальный шаг и есть то, что отделяет ресторанный тайский зелёный карри от водянистой домашней версии. Добавьте зелёную карри-пасту в разделившиеся сливки и обжаривайте 2–3 минуты, непрерывно помешивая, пока паста не потемнеет, не выпустит аромат галангала, лемонграсса и тайского базилика, а масло не станет ярко-зелёным — кухня запахнет бангкокским переулком. Опустите курицу и переверните куски в пасте до покрытия, готовьте 3–4 минуты, пока мясо не побелеет наполовину, затем влейте кокосовое молоко и доведите до лёгкого кипения; добавьте баклажаны, побеги бамбука и порванные листья каффирского лайма и томите без крышки 10–12 минут, пока баклажаны не станут мягкими, а курица — едва прожаренной. Приправьте рыбным соусом и пальмовым сахаром, пробуя по ходу — карри должен бить одновременно солёным, сладким, травянистым и чистой зелёной чили-остротой — затем вмешайте красный перец и тайский базилик, качните сковороду один раз и снимите с огня через 30 секунд, чтобы базилик остался ярким в тарелке. Подавайте в неглубоких мисках с жасминовым рисом сбоку.",

'ar': "في مقلاة عميقة (ووك) أو قدر ثقيل على نار متوسطة، ضع كريمة جوز الهند واتركها تطهو 4–5 دقائق مع التحريك بين الحين والآخر، حتى ينفصل الزيت وتأخذ الكريمة لمعاناً زيتياً — هذه الخطوة الأساسية هي ما يفصل بين كاري المطعم التايلاندي وبين النسخة المائية المنزلية. أضف معجون الكاري الأخضر إلى الكريمة المنفصلة وقلِّبه 2–3 دقائق مع التحريك المستمر، حتى يغمق المعجون ويُطلق رائحة الجلنجال والليمون العشبي والريحان التايلاندي، ويتحول الزيت إلى أخضر زاهٍ — ستفوح من المطبخ رائحة زقاق في بانكوك. أدخل الدجاج وقلّب القطع في المعجون حتى تتغطى، اطبخ 3–4 دقائق حتى يصبح اللحم نصف ناضج، ثم اسكب حليب جوز الهند وأوصله إلى غليان هادئ؛ أضف الباذنجان وبراعم الخيزران وأوراق الليمون الكافير الممزقة، واتركها تغلي مكشوفة 10–12 دقيقة، حتى يصبح الباذنجان طرياً والدجاج ناضجاً للتو. تبّل بصلصة السمك وسكر النخيل، مع التذوق أثناء العمل — يجب أن يضرب الكاري الملوحة والحلاوة ولمسة العشب وحرارة الفلفل الأخضر النظيفة كلها في آن واحد — ثم أضف شرائح الفلفل الأحمر والريحان التايلاندي، حرّك المقلاة دورة واحدة، ثم ارفعها عن النار بعد 30 ثانية كي يبقى الريحان زاهياً في الصحن. قدّمه في صحون ضحلة مع أرز الياسمين إلى الجانب.",

'zh': "在中火上的炒锅或厚锅里舀入椰浆，让它煮 4–5 分钟、间或搅拌，直到油从浆里裂出、浆面泛起油亮的光泽——这一步打底，正是把泰国餐厅的青咖喱与家里清汤寡水的版本区分开来的关键。把青咖喱酱加入裂开的椰浆中，不停搅拌炒 2–3 分钟，直到酱色变深、释放出南姜、香茅和泰国罗勒的香气，油泛起鲜亮的青绿色——整个厨房会闻起来像曼谷的一条小街。下鸡肉，在酱里翻动每一块至完全裹上，炒 3–4 分钟到肉半熟，再倒入椰奶，慢慢加热到微微沸腾；加入茄子、竹笋和撕碎的卡菲尔青柠叶，不盖锅煮 10–12 分钟，直到茄子变软、鸡肉刚刚熟透。用鱼露和棕榈糖调味，边尝边加——这锅咖喱应当同时打中咸、甜、清新的草本香、和那种干净利落的青辣椒辣味——最后撒上红辣椒丝和泰国罗勒，把锅晃一下，30 秒后离火，这样罗勒在碗里还能保持翠绿。用浅口碗盛装，旁边配一碗茉莉香米饭。",

'ja': "中火にかけた中華鍋か厚手の鍋にココナッツクリームを入れ、4〜5 分、ときどき混ぜながら煮る — 油が浮き上がり、クリームが油光を帯びるまで；この最初の一手こそ、タイ料理店のグリーンカレーと家でやると水っぽいやつを分ける土台の工程。割れたクリームにグリーンカレーペーストを加え、絶え間なく混ぜながら 2〜3 分炒める — ペーストが色を深め、ガランガル、レモングラス、タイ・バジルの香りを放ち、油が鮮やかな緑色に変わるまで；台所はバンコクの裏通りの匂いになる。鶏肉を加え、ペーストにくぐらせるように絡め、3〜4 分焼いて半分火が通ったら、ココナッツミルクを注いで穏やかに沸かす；なす、たけのこ、ちぎったコブミカンの葉を加え、蓋をせずに 10〜12 分、なすが柔らかく鶏に火がちょうど通るまで煮る。ナンプラーとパームシュガーで味を整え、途中で必ず味を見る — グリーンカレーは塩味・甘み・ハーバルな香り・青唐辛子のクリーンな辛味を同時に当ててくる味であるべき — スライスした赤唐辛子とタイ・バジルを加え、鍋を一度回し、30 秒後に火から下ろす；器の中でバジルが鮮やかなまま残るように。浅めの器に盛り、ジャスミンライスを添える。",

'tr': "Bir wok ya da ağır bir tavada orta ateşte hindistan cevizi kremasını koy ve 4–5 dakika, arada karıştırarak, yağ çekilip kremanın üstü parlayana kadar pişir — bu temel adım, Tay restoranlarındaki yeşil köri ile evdeki sulu versiyonu birbirinden ayıran şeydir. Ayrılan kremaya yeşil köri ezmesini ekle ve sürekli karıştırarak 2–3 dakika pişir — ezme koyulaşıp galangal, limon otu ve Tay fesleğeni kokusunu salıp yağ canlı bir yeşile dönene kadar — mutfağın kokusu Bangkok'un bir ara sokağına benzeyecek. Tavuğu içine kaydır, parçaları ezme içinde çevirerek kapla, 3–4 dakika eti yarı pişene dek pişir, sonra hindistan cevizi sütünü dök ve hafif kaynamaya getir; patlıcanları, bambu filizlerini ve parçalanmış kaffir limon yapraklarını ekle ve kapaksız 10–12 dakika, patlıcanlar yumuşayıp tavuk tam piştiği anda biten bir kıvama gelene dek pişir. Balık sosu ve palmiye şekeriyle tatlandır, tadına bakarak — köri aynı anda tuzlu, tatlı, otlu ve temiz yeşil acı vurmalı — sonra dilimlenmiş kırmızı biber ve Tay fesleğenini ekle, tavayı bir defa çevir, ve 30 saniye sonra ocaktan al ki fesleğen tabakta canlılığını koruyabilsin. Sığ kâselerde, yanında jasmin pirinciyle servis et.",

'it': "In una wok o padella pesante a fuoco medio, mettete la crema di cocco e lasciatela cuocere 4–5 minuti, mescolando di tanto in tanto, finché l'olio non si separa e la crema non assume un riflesso oleoso — questo passaggio di base è ciò che separa il curry verde da ristorante thailandese dalla versione casalinga acquosa. Unite la pasta di curry verde alla crema separata e friggetela 2–3 minuti, mescolando senza sosta, finché la pasta non si scurisce, libera il suo profumo di galanga, citronella e basilico thailandese, e l'olio non assume un verde vivo — la cucina sentirà di vicolo di Bangkok. Fate scivolare il pollo e rigirate i pezzi nella pasta fino a coprirli, cuocete 3–4 minuti finché la carne non è semicotta, poi versate il latte di cocco e portate a un sobbollire delicato; unite le melanzane, i germogli di bambù e le foglie di lime kaffir strappate, e fate sobbollire scoperto per 10–12 minuti, finché le melanzane non sono tenere e il pollo è appena cotto. Condite con la salsa di pesce e lo zucchero di palma, assaggiando man mano — il curry deve colpire allo stesso tempo salato, dolce, erbaceo e con un piccante verde pulito — unite poi i peperoncini rossi affettati e il basilico thailandese, fate roteare la padella una volta e toglietela dal fuoco dopo 30 secondi, così il basilico resta brillante nella ciotola. Servite in ciotole basse con riso jasmine a parte.",

'ko': "웍이나 두꺼운 팬에 코코넛 크림을 넣고 중불에서 4–5분, 가끔 저어가며, 기름이 분리되고 크림 표면에 기름진 윤기가 돌 때까지 졸인다 — 이 기초 단계가 태국 식당의 그린 커리와 집에서 만든 묽은 버전을 가르는 결정적 한 수다. 분리된 크림에 그린 커리 페이스트를 넣고, 끊임없이 저으며 2–3분 볶는다 — 페이스트가 짙어지고, 갈랑갈, 레몬그라스, 태국 바질의 향이 피어나며, 기름이 선명한 초록색으로 변할 때까지 — 부엌에서는 방콕 뒷골목의 냄새가 난다. 닭고기를 미끄러뜨려 넣고 페이스트에 잘 묻도록 뒤집어가며 3–4분 — 살이 반쯤 익을 때까지 — 볶은 다음, 코코넛 밀크를 부어 부드러운 끓음으로 가져간다; 가지, 죽순, 손으로 찢은 카피르 라임 잎을 넣고 뚜껑을 열어둔 채 10–12분, 가지가 부드러워지고 닭이 막 익을 때까지 끓인다. 피쉬 소스와 팜 슈가로 간하고, 중간중간 맛을 본다 — 그린 커리는 짠맛, 단맛, 풀향, 그리고 깨끗한 청양고추 매운맛을 동시에 때려야 한다 — 슬라이스한 빨간 고추와 태국 바질을 넣고 팬을 한 번 흔든 다음, 30초 뒤 불을 끈다; 그래야 바질이 그릇 안에서도 선명하게 남는다. 얕은 그릇에 담아 자스민 라이스와 함께 낸다.",

'hi': "एक wok या भारी पैन में मध्यम आँच पर नारियल क्रीम डालें और 4–5 मिनट तक, बीच-बीच में चलाते हुए, तब तक पकाएँ जब तक तेल अलग न हो जाए और क्रीम पर तेल जैसी चमक न आ जाए — यह बेस वाला कदम ही थाई रेस्टोरेंट की ग्रीन करी और घर की पानी-पानी वाली ग्रीन करी के बीच फ़र्क़ है। फटी हुई क्रीम में ग्रीन करी पेस्ट डालें और 2–3 मिनट लगातार चलाते हुए भूनें — जब तक पेस्ट गहरा हो जाए, गलंगाल, लेमनग्रास और थाई तुलसी की ख़ुशबू उठने लगे, और तेल चमकीले हरे रंग का न हो जाए — रसोई से बैंकॉक की एक गली की ख़ुशबू आएगी। चिकन डालें और हर टुकड़े को पेस्ट में लपेट दें, 3–4 मिनट तक तब तक पकाएँ जब तक मांस आधा-सीलिंग न हो जाए, फिर नारियल का दूध डालें और हलकी उबाल पर लाएँ; बैंगन, बांस के टुकड़े और फटे कैफिर लाइम पत्ते डालें और बिना ढके 10–12 मिनट तक पकाएँ जब तक बैंगन नरम और चिकन बस-बस पका न हो। फिश सॉस और ताड़ की चीनी से स्वाद दें, बीच-बीच में चखें — करी एक साथ नमकीन, मीठी, जड़ी-बूटी जैसी और साफ़ हरी मिर्च की तीक्ष्णता मारनी चाहिए — फिर कटी लाल मिर्च और थाई तुलसी डालें, पैन को एक बार घुमाएँ, और 30 सेकंड बाद आँच से उतार लें ताकि तुलसी कटोरे में भी ताज़ी हरी रहे। उथले कटोरों में परोसें, साथ में चमेली चावल।",
}

FEATURE_CARDS = {
'en': '[{icon:"🥥", t:"Crack the cream first", d:"What separates restaurant green curry from watery home version"}, {icon:"🌿", t:"Galangal, lemongrass, basil", d:"Bangkok-back-street perfume from the green paste"}, {icon:"🍆", t:"Thai eggplants + bamboo", d:"Soft but holding shape after 10–12 minutes uncovered"}, {icon:"🌶️", t:"Four notes at once", d:"Salty, sweet, herbaceous and a clean green-chilli heat"}]',
'ro': '[{icon:"🥥", t:"Sparge crema mai întâi", d:"Ce separă curry-ul de restaurant de varianta apoasă de acasă"}, {icon:"🌿", t:"Galangal, lemongrass, busuioc", d:"Parfumul străzii din Bangkok din pasta verde"}, {icon:"🍆", t:"Vinete thai + bambus", d:"Moi dar întregi după 10–12 minute descoperit"}, {icon:"🌶️", t:"Patru note deodată", d:"Sărat, dulce, ierbos și o căldură curată de chili verde"}]',
'es': '[{icon:"🥥", t:"Romper la crema primero", d:"Lo que separa el curry de restaurante de la versión aguada"}, {icon:"🌿", t:"Galanga, citronela, albahaca", d:"Perfume de callejón de Bangkok desde la pasta verde"}, {icon:"🍆", t:"Berenjenas thai + bambú", d:"Tiernas pero enteras tras 10–12 minutos destapado"}, {icon:"🌶️", t:"Cuatro notas a la vez", d:"Salado, dulce, herbáceo y un picor limpio de chile verde"}]',
'fr': '[{icon:"🥥", t:"Casser la crème d\'abord", d:"Ce qui sépare le curry de restaurant de la version aqueuse"}, {icon:"🌿", t:"Galanga, citronnelle, basilic", d:"Parfum de ruelle de Bangkok depuis la pâte verte"}, {icon:"🍆", t:"Aubergines thaï + bambou", d:"Tendres mais entières après 10–12 minutes à découvert"}, {icon:"🌶️", t:"Quatre notes à la fois", d:"Salé, sucré, herbeux et un piquant vert et net"}]',
'de': '[{icon:"🥥", t:"Zuerst die Sahne brechen", d:"Was Restaurant-Curry von der wässrigen Hausversion trennt"}, {icon:"🌿", t:"Galgant, Zitronengras, Basilikum", d:"Bangkoker-Seitenstraßen-Duft aus der grünen Paste"}, {icon:"🍆", t:"Thai-Auberginen + Bambus", d:"Weich, behalten aber Form nach 10–12 Minuten offen"}, {icon:"🌶️", t:"Vier Noten gleichzeitig", d:"Salzig, süß, krautig und klare grüne Chili-Schärfe"}]',
'pt': '[{icon:"🥥", t:"Quebrar as natas primeiro", d:"O que separa o caril de restaurante da versão aguada"}, {icon:"🌿", t:"Galanga, capim-limão, manjericão", d:"Perfume de beco de Bangkok da pasta verde"}, {icon:"🍆", t:"Beringelas tailandesas + bambu", d:"Tenras mas inteiras após 10–12 minutos destapado"}, {icon:"🌶️", t:"Quatro notas ao mesmo tempo", d:"Salgado, doce, herbáceo e picante limpo de piri-piri verde"}]',
'ru': '[{icon:"🥥", t:"Сначала разделить сливки", d:"Что отделяет ресторанный карри от водянистой домашней версии"}, {icon:"🌿", t:"Галангал, лемонграсс, базилик", d:"Аромат бангкокского переулка из зелёной пасты"}, {icon:"🍆", t:"Тайские баклажаны + бамбук", d:"Мягкие, но держат форму за 10–12 минут без крышки"}, {icon:"🌶️", t:"Четыре ноты сразу", d:"Солёное, сладкое, травяное и чистая зелёно-чили острота"}]',
'ar': '[{icon:"🥥", t:"اكسر الكريمة أولاً", d:"ما يفصل كاري المطعم عن النسخة المائية المنزلية"}, {icon:"🌿", t:"جلنجال، ليمون عشبي، ريحان", d:"عبير زقاق بانكوك من المعجون الأخضر"}, {icon:"🍆", t:"باذنجان تايلاندي + خيزران", d:"طري لكنه يحتفظ بشكله بعد 10–12 دقيقة مكشوفاً"}, {icon:"🌶️", t:"أربع نغمات معاً", d:"مالح، حلو، عشبي، وحرارة فلفل أخضر نظيفة"}]',
'zh': '[{icon:"🥥", t:"先把椰浆“破”开", d:"区分餐厅青咖喱与家里清汤版本的关键"}, {icon:"🌿", t:"南姜、香茅、罗勒", d:"绿酱里飘出的曼谷小巷气息"}, {icon:"🍆", t:"泰式茄子 + 竹笋", d:"不盖锅 10–12 分钟，软但保持形状"}, {icon:"🌶️", t:"四味同时打中", d:"咸、甜、清香、干净利落的青辣椒辣"}]',
'ja': '[{icon:"🥥", t:"まずクリームを割る", d:"レストランのグリーンカレーと家の水っぽい版を分ける一手"}, {icon:"🌿", t:"ガランガル・レモングラス・バジル", d:"緑のペーストから漂うバンコクの裏通りの香り"}, {icon:"🍆", t:"タイ茄子 + たけのこ", d:"蓋なし 10〜12 分、柔らかいが形は残る"}, {icon:"🌶️", t:"四つの音が同時に", d:"塩・甘・ハーブ・青唐辛子のクリーンな辛さ"}]',
'tr': '[{icon:"🥥", t:"Önce kremayı kır", d:"Restoran körisini evin sulu versiyonundan ayıran şey"}, {icon:"🌿", t:"Galangal, limon otu, fesleğen", d:"Yeşil ezmeden gelen Bangkok ara sokak kokusu"}, {icon:"🍆", t:"Tay patlıcanı + bambu", d:"Kapaksız 10–12 dakika, yumuşak ama şekli korur"}, {icon:"🌶️", t:"Dört nota bir anda", d:"Tuzlu, tatlı, otlu ve temiz yeşil biber acısı"}]',
'it': '[{icon:"🥥", t:"Rompere la crema per prima", d:"Ciò che separa il curry da ristorante dalla versione acquosa"}, {icon:"🌿", t:"Galanga, citronella, basilico", d:"Profumo di vicolo di Bangkok dalla pasta verde"}, {icon:"🍆", t:"Melanzane thai + bambù", d:"Tenere ma intere dopo 10–12 minuti scoperto"}, {icon:"🌶️", t:"Quattro note insieme", d:"Salato, dolce, erbaceo e piccante verde pulito"}]',
'ko': '[{icon:"🥥", t:"먼저 크림을 분리", d:"식당 그린 커리와 집의 묽은 버전을 가르는 한 수"}, {icon:"🌿", t:"갈랑갈·레몬그라스·바질", d:"그린 페이스트에서 풍기는 방콕 뒷골목 향"}, {icon:"🍆", t:"태국 가지 + 죽순", d:"뚜껑 없이 10–12분, 부드럽지만 형태 유지"}, {icon:"🌶️", t:"네 가지 노트가 동시에", d:"짠맛·단맛·풀향·깨끗한 청양고추 매운맛"}]',
'hi': '[{icon:"🥥", t:"पहले क्रीम फाड़ें", d:"रेस्टोरेंट करी और घर की पानी-पानी वाली के बीच फ़र्क़"}, {icon:"🌿", t:"गलंगाल, लेमनग्रास, तुलसी", d:"हरी पेस्ट से उठती बैंकॉक की गली की ख़ुशबू"}, {icon:"🍆", t:"थाई बैंगन + बांस", d:"बिना ढके 10–12 मिनट, नरम पर आकार बरक़रार"}, {icon:"🌶️", t:"चार स्वर एक साथ", d:"नमकीन, मीठा, जड़ी-बूटी जैसा और साफ़ हरी मिर्च की तीख़ापन"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*209,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 209 (Green Curry): {rec_end-rec_start} → {len(new_recipe_block)} chars")
