#!/usr/bin/env python3
"""Rewrite recipe 212 (Khao Soi): howIsMade 11 → 5 steps in 14 langs;
add 4 recipe-specific featureCards. Preserves all other fields."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Heat the coconut cream in a heavy pot over medium heat for 4–5 minutes until the oil cracks out and the cream looks slick, then stir in the khao soi paste and fry for 2–3 minutes until it darkens and smells deeply toasted — heavier and earthier than central-Thai curries because the paste leans on dry spices. Add the chicken pieces and turn them in the paste until coated, pour in the coconut milk and stock, bring to a gentle simmer and cook with the lid ajar for 30–35 minutes until the chicken is meltingly tender and the broth has reduced a little; season with fish sauce and palm sugar towards the end so the broth is rich, gently sweet and faintly sour from the curry paste itself. While the curry simmers, take a small handful of the fresh egg noodles, shake off any excess water, and deep-fry in 180°C oil for 30–45 seconds until puffed and golden — the crispy crown for every bowl — then drain on paper. Boil the remaining noodles in plain water until just tender, drain quickly and divide between deep bowls, ladle over the hot curry with at least one piece of chicken per portion, and top with the fried noodles. Pass the garnishes round the table — sliced shallots, pickled mustard greens, coriander, a lime wedge to squeeze in last, and a spoon of chilli oil — the dish lives on contrast (silky soup, soft noodles below, crisp on top, raw shallot bite, pickle tang, lime brightness) and each bowl is built at the table.",

'ro': "Încălzește smântâna de cocos într-o oală groasă pe foc mediu 4–5 minute, până când uleiul iese la suprafață și smântâna devine lucioasă, apoi adaugă pasta de khao soi și prăjește-o 2–3 minute, până când se închide la culoare și miroase profund prăjit — mai greoi și mai pământiu decât curry-urile din centrul Thailandei, fiindcă pasta se sprijină pe mirodenii uscate. Adaugă bucățile de pui și învârte-le în pastă până sunt acoperite, toarnă laptele de cocos și fondul, adu la o fierbere blândă și gătește cu capacul puțin întredeschis 30–35 de minute, până când puiul cedează la furculiță și fondul s-a redus puțin; asezonează cu sosul de pește și zahărul de palmier spre final, astfel încât supa să fie bogată, ușor dulce și abia acrișoară din pasta de curry însăși. Cât fierbe curry-ul, ia o mână mică de tăiței proaspeți, scutură excesul de apă și prăjește-i în ulei la 180°C 30–45 de secunde, până se umflă și devin aurii — coroana crocantă pentru fiecare bol — apoi scurge pe hârtie. Fierbe restul tăițeilor în apă simplă până devin abia moi, scurge-i repede și împarte-i în boluri adânci, toarnă deasupra curry-ul fierbinte cu cel puțin o bucată de pui per porție și pune deasupra tăițeii prăjiți. Trece garniturile la masă — șalote feliate, frunze de muștar murate, coriandru, o felie de lime de stors la final și o lingură de ulei de chili — felul trăiește din contrast (supă mătăsoasă, tăiței moi dedesubt, tăiței crocanți deasupra, mușcătura de șalotă crudă, acrul muratului, lumina lime-ului) și fiecare bol se construiește la masă.",

'es': "Calienta la crema de coco en una olla pesada a fuego medio 4–5 minutos, hasta que el aceite se separe y la crema se vea brillante, después incorpora la pasta de khao soi y fríela 2–3 minutos, hasta que se oscurezca y huela profundo y tostado — más pesado y terroso que los curries del centro de Tailandia, porque esta pasta se apoya en especias secas. Añade los trozos de pollo y voltéalos en la pasta hasta cubrirlos, vierte la leche de coco y el caldo, lleva a un hervor suave y cocina con la tapa entreabierta 30–35 minutos, hasta que el pollo ceda en hilachas y el caldo se haya reducido un poco; sazona con salsa de pescado y azúcar de palma hacia el final para que el caldo sea rico, suavemente dulce y apenas ácido por la propia pasta de curry. Mientras el curry hierve, toma un pequeño puñado de fideos frescos, sacude el agua sobrante y fríelos en aceite a 180°C durante 30–45 segundos, hasta que estén hinchados y dorados — la corona crujiente sobre cada cuenco — luego escurre sobre papel. Hierve el resto de los fideos en agua hasta que estén apenas tiernos, escúrrelos rápido y repártelos en cuencos hondos, vierte por encima el curry caliente con al menos una pieza de pollo por porción y cubre con los fideos fritos. Pasa las guarniciones a la mesa — chalota en rodajas, mostaza encurtida, cilantro, un gajo de lima para exprimir al final y una cucharada de aceite de chile — el plato vive del contraste (sopa sedosa, fideos blandos debajo, crujientes encima, el mordisco de chalota cruda, el toque ácido del encurtido, la luz de la lima) y cada cuenco se monta en la mesa.",

'fr': "Faites chauffer la crème de coco dans une cocotte épaisse à feu moyen 4 à 5 minutes, jusqu'à ce que l'huile se sépare et que la crème prenne un brillant huileux, puis incorporez la pâte de khao soi et faites-la frire 2 à 3 minutes, jusqu'à ce qu'elle fonce et sente profond et grillé — plus lourde et terreuse que les curries du centre de la Thaïlande, parce que cette pâte s'appuie sur des épices sèches. Ajoutez les morceaux de poulet et tournez-les dans la pâte jusqu'à enrobage, versez le lait de coco et le bouillon, portez à frémissement doux et faites cuire à couvercle entrouvert 30 à 35 minutes, jusqu'à ce que le poulet s'effeuille tendrement et que le bouillon ait réduit un peu ; assaisonnez avec la sauce poisson et le sucre de palme vers la fin pour que le bouillon soit riche, doucement sucré et à peine acide par la pâte de curry elle-même. Pendant que le curry mijote, prenez une petite poignée de nouilles fraîches, secouez l'eau en surplus, et faites-les frire dans une huile à 180°C pendant 30 à 45 secondes, jusqu'à ce qu'elles soient soufflées et dorées — la couronne croustillante de chaque bol — puis égouttez sur papier. Faites cuire le reste des nouilles dans de l'eau jusqu'à ce qu'elles soient juste tendres, égouttez-les rapidement et répartissez-les dans des bols creux, versez le curry chaud par-dessus avec au moins un morceau de poulet par portion et couronnez des nouilles frites. Faites passer les garnitures à table — échalotes en rondelles, moutarde de Chine au vinaigre, coriandre, un quartier de citron vert à presser en dernier et une cuillère d'huile de piment — le plat vit du contraste (soupe soyeuse, nouilles molles en dessous, croustillantes au-dessus, morsure de l'échalote crue, acidité du condiment, lumière du citron vert) et chaque bol se construit à table.",

'de': "Erhitzen Sie die Kokoscreme in einem schweren Topf bei mittlerer Hitze 4–5 Minuten, bis das Öl austritt und die Creme glänzend wirkt, rühren Sie dann die Khao-Soi-Paste ein und braten Sie sie 2–3 Minuten, bis sie sich dunkel färbt und tief und geröstet duftet — schwerer und erdiger als die zentralthailändischen Currys, weil diese Paste stark auf Trockengewürze setzt. Geben Sie die Hähnchenstücke hinein und wenden Sie sie in der Paste, gießen Sie die Kokosmilch und den Fond an, bringen Sie alles auf sanftes Köcheln und garen Sie bei nur leicht offenem Deckel 30–35 Minuten, bis das Hähnchen vom Knochen fällt und die Brühe etwas eingekocht ist; gegen Ende mit Fischsauce und Palmzucker abschmecken, damit die Brühe reichhaltig, sanft süß und durch die Currypaste leicht säuerlich ist. Während das Curry köchelt, nehmen Sie eine kleine Handvoll der frischen Eiernudeln, schütteln das Wasser ab und frittieren sie in 180°C heißem Öl 30–45 Sekunden, bis sie aufgepufft und goldgelb sind — die knusprige Krone für jede Schale — dann auf Papier abtropfen lassen. Die restlichen Nudeln in einfachem Wasser bissfest kochen, schnell abgießen und auf tiefe Schalen verteilen, das heiße Curry darüber schöpfen — mindestens ein Stück Hähnchen pro Portion — und die frittierten Nudeln oben auflegen. Reichen Sie die Garnituren am Tisch herum — Schalottenringe, eingelegtes Senfgrün, Koriander, eine Limettenspalte zum letzten Drücken und einen Löffel Chiliöl — das Gericht lebt vom Kontrast (seidige Brühe, weiche Nudeln darunter, knusprige Nudeln darüber, der Biss der rohen Schalotte, die Säure des Eingelegten, das Licht der Limette) und jede Schale wird am Tisch zusammengebaut.",

'pt': "Aqueça as natas de coco numa panela pesada em lume médio 4–5 minutos, até o óleo se separar e as natas ficarem brilhantes, depois incorpore a pasta de khao soi e frite 2–3 minutos, até escurecer e cheirar a profundo e tostado — mais pesado e telúrico do que os caris do centro da Tailândia, porque esta pasta apoia-se em especiarias secas. Junte os pedaços de frango e envolva-os na pasta até cobrir, verta o leite de coco e o caldo, leve a uma fervura branda e cozinhe com a tampa entreaberta 30–35 minutos, até o frango ceder facilmente e o caldo ter reduzido um pouco; tempere com molho de peixe e açúcar de palma no final para que o caldo seja rico, brandamente doce e levemente ácido pela própria pasta de caril. Enquanto o caril ferve, pegue numa mão-cheia pequena de massa fresca, escorra a água em excesso, e frite em óleo a 180°C durante 30–45 segundos, até ficar fofa e dourada — a coroa crocante para cada taça — depois escorra sobre papel. Cozinhe a massa restante em água até estar mal tenra, escorra rápido e divida por taças fundas, deite por cima o caril quente com pelo menos um pedaço de frango por dose e ponha a massa frita por cima. Leve as guarnições à mesa — chalota fatiada, mostarda chinesa em conserva, coentros, um gomo de lima para espremer no fim e uma colher de óleo de piri-piri — o prato vive do contraste (caldo sedoso, massa macia por baixo, massa estaladiça por cima, a mordida da chalota crua, o picado do conservado, a luz da lima) e cada taça monta-se à mesa.",

'ru': "Прогрейте кокосовые сливки в тяжёлой кастрюле на среднем огне 4–5 минут, пока масло не отделится, а сливки не станут глянцевыми, затем вмешайте пасту кхао сой и обжаривайте 2–3 минуты, пока она не потемнеет и не запахнет глубоко и поджаренно — тяжелее и землистее, чем у центрально-тайских карри, потому что эта паста опирается на сухие специи. Добавьте куски курицы и переворачивайте их в пасте, влейте кокосовое молоко и бульон, доведите до лёгкого кипения и варите с приоткрытой крышкой 30–35 минут, пока курица не станет совсем мягкой, а бульон чуть не уварится; к концу приправьте рыбным соусом и пальмовым сахаром, чтобы бульон был насыщенным, мягко сладким и чуть кислым от самой пасты карри. Пока карри томится, возьмите небольшую горсть свежей яичной лапши, стряхните излишек воды и обжарьте во фритюре при 180°C 30–45 секунд, до вздувшейся золотой хрусткости — это коронка для каждой тарелки — затем откиньте на бумагу. Остальную лапшу отварите в обычной воде до едва готовности, быстро слейте и разложите по глубоким мискам, сверху налейте горячий карри с хотя бы одним куском курицы на порцию и увенчайте жареной лапшой. Передавайте гарниры по столу — лук шалот, маринованную горчичную зелень, кинзу, дольку лайма, чтобы выжать в самом конце, и ложку чили-масла — блюдо живёт на контрасте (шёлковый бульон, мягкая лапша внизу, хрустящая лапша сверху, прикус сырого шалота, кислинка маринада, свет лайма) и каждая миска собирается прямо за столом.",

'ar': "سخّن كريمة جوز الهند في قدر ثقيل على نار متوسطة 4–5 دقائق، حتى ينفصل الزيت وتبدو الكريمة لامعة، ثم أضف معجون الخاو سوي وقلِّبه 2–3 دقائق، حتى يغمق وتفوح منه رائحة عميقة محمّصة — أثقل وأكثر ترابية من كاري وسط تايلاند، لأن هذا المعجون يعتمد على البهارات الجافة. أضف قطع الدجاج وقلّبها في المعجون حتى تتغطى، اسكب حليب جوز الهند والمرق، أوصلها إلى غليان هادئ واطبخها مع غطاء نصف مفتوح 30–35 دقيقة، حتى يصبح الدجاج طرياً جداً ويتراجع المرق قليلاً؛ تبّل بصلصة السمك وسكر النخيل قرب النهاية ليكون المرق غنياً، حلواً قليلاً، وحامضاً بشكل خفيف من معجون الكاري نفسه. أثناء الطهي، خذ حفنة صغيرة من النودلز الطازجة، انفض الماء الزائد، واقلِها في زيت 180°م لمدة 30–45 ثانية حتى تنتفخ وتذهب إلى الذهبي — التاج المقرمش لكل صحن — ثم صفّها على ورق. اغلِ بقية النودلز في ماء عادي حتى تطرى للتو، صفّها بسرعة، ووزّعها في صحون عميقة، اسكب فوقها الكاري الساخن مع قطعة دجاج على الأقل لكل حصة، وضع النودلز المقلية فوقها. مرّر الزينة على المائدة — شالوت شرائح، خضار الخردل المخللة، الكزبرة، شريحة ليم لعصرها أخيراً، وملعقة من زيت الفلفل — الطبق يعيش على التباين (مرق حريري، نودلز طرية تحت، نودلز مقرمشة فوق، عضّة الشالوت النيء، حموضة المخلل، إشراق الليم) وكل صحن يُبنى على المائدة.",

'zh': "在厚锅里中火加热椰浆 4–5 分钟，让油从浆里裂出、浆面发亮，然后加入 khao soi 咖喱酱炒 2–3 分钟，让它颜色变深、释放出深沉而焙烤的香气——比泰国中部的咖喱更厚重、更带土气，因为这款酱是靠干香料堆出来的。下鸡块在酱里翻一翻让每块都裹上酱，倒入椰奶和鸡汤，小火慢慢沸腾，盖子半盖煮 30–35 分钟，直到鸡肉酥软离骨、汤汁微微收浓；靠近收尾时再用鱼露和棕榈糖调味，让汤底醇厚、带温柔的甜，并因咖喱酱本身带一丝若有若无的酸。咖喱炖着的时候，拿一小把鲜面，把多余的水甩掉，下到 180°C 的油锅炸 30–45 秒，让它膨起、变金黄——这就是每一碗顶上那顶酥脆的“皇冠”——然后捞出沥油。把剩下的鸡蛋面在清水里煮到刚刚熟，迅速沥干，分到几只深口碗里，每碗淋上热咖喱汤，至少一块鸡，上面铺炸面。把配菜传到餐桌上——红葱头丝、腌芥菜、香菜、最后挤的青柠角、一勺辣椒油——这道菜活在对比里（丝绸般的汤、底下的软面、上面的酥面、生葱的辛辣咬感、酱菜的酸、青柠的亮），每一碗 khao soi 都是在餐桌上完成的。",

'ja': "厚手の鍋に中火でココナッツクリームを 4〜5 分熱し、油が浮き出てクリームが艶を帯びるまで詰めたら、カオソーイのカレーペーストを加えて 2〜3 分炒め、色が深まり、台所が深く焙煎されたような香りになるまで仕上げる——中部タイのカレーよりも重く、土の匂いを帯びている、ペーストが乾燥スパイスに寄っているから。鶏肉を加えてペーストにまとわせ、ココナッツミルクと鶏のだしを注ぎ、穏やかに沸騰させ、蓋を少し開けたまま 30〜35 分、鶏がほろりと崩れる柔らかさになり、汁が少し詰まるまで煮る；仕上がり前にナンプラーとパームシュガーで味を整え、汁がリッチで、ほのかに甘く、ペースト自体からくる淡い酸味を持つようにする。煮ている間に、生卵麺をひとつまみ取って余分な水気を払い、180℃ の油で 30〜45 秒、ふくらんで黄金色になるまで揚げる——各椀の上にのる「カリッとした王冠」——紙にあげて油を切る。残りの麺は普通の湯でちょうど火が通るまで茹で、手早く湯切りして深めの椀に分けて入れ、熱いカレーを 1 椀につき少なくとも鶏肉が 1 切れ入るように注ぎ、揚げた麺をのせる。薬味を食卓に回す——エシャロットの薄切り、漬けからし菜、コリアンダー、最後に絞るためのライムくし切り、ひとさじの辣油——この料理は対比で生きる（絹のような汁、その下の柔らかい麺、上のカリカリの麺、生エシャロットの噛みごたえ、漬物の酸、ライムの光）、1 椀のカオソーイは必ず食卓で完成される。",

'tr': "Hindistan cevizi kremasını ağır bir tencerede orta ateşte 4–5 dakika ısıt — yağ ayrılıp krema parlayana dek — sonra Khao Soi ezmesini ekle ve 2–3 dakika kavur, koyulaşıp mutfak derin ve kavrulmuş bir koku alana dek — orta Tay körilerinden daha ağır ve daha topraksı, çünkü bu ezme kuru baharatlara dayanır. Tavuk parçalarını ekleyip ezmenin içinde çevir, hindistan cevizi sütünü ve suyu dök, yumuşak bir kaynamaya getir ve kapağı aralık olarak 30–35 dakika, tavuk dağılacak kadar yumuşayıp suyu hafifçe çekene kadar pişir; sona doğru balık sosu ve palmiye şekeriyle tatlandır, böylece su zengin, hafif tatlı ve köri ezmesinin kendisinden gelen hafif bir ekşiliğe sahip olur. Köri pişerken bir avuç taze yumurtalı eriştiyi alıp fazla suyunu silkele ve 180°C yağda 30–45 saniye, kabarıp altın renge dönene kadar kızart — her kasenin üstündeki çıtır taç — sonra kağıda alıp süz. Kalan eriştiyi düz suda taze yumuşaklıkta haşla, hızla süz ve derin kâselere paylaştır, üzerine en az bir parça tavuk ile sıcak köriyi dök ve kızarmış eriştileri tepeye koy. Garnitürleri masada gezdir — arpacık soğan dilimleri, turşulu hardal yaprağı, kişniş, en sona sıkmak için bir misket limonu dilimi ve bir kaşık biber yağı — yemek karşıtlıklarla yaşar (ipeksi su, altta yumuşak erişte, üstte çıtır erişte, çiğ soğanın ısırığı, turşunun ekşiliği, limonun aydınlığı) ve her kâse sofrada kurulur.",

'it': "Scaldate la crema di cocco in una pentola pesante a fuoco medio per 4–5 minuti, finché l'olio non si separa e la crema non appare lucida, poi unite la pasta di khao soi e fatela soffriggere 2–3 minuti, finché non si scurisce e non sente di profondo e tostato — più pesante e terroso dei curry della Thailandia centrale, perché questa pasta si appoggia sulle spezie secche. Unite i pezzi di pollo e rigirateli nella pasta, versate il latte di cocco e il brodo, portate a un sobbollire delicato e cuocete con il coperchio socchiuso per 30–35 minuti, finché il pollo non si scioglie e il brodo non si è leggermente ristretto; verso la fine condite con la salsa di pesce e lo zucchero di palma, in modo che il brodo sia ricco, leggermente dolce e appena acidulo per merito della pasta di curry stessa. Mentre il curry sobbolle, prendete una piccola manciata di noodle freschi, scuotetene l'acqua in eccesso e friggeteli in olio a 180°C per 30–45 secondi, finché non sono soffiati e dorati — la corona croccante in cima a ogni ciotola — poi scolate su carta. Cuocete il resto dei noodle in acqua semplice fino a quando non sono appena teneri, scolateli rapidamente e suddivideteli in ciotole fonde, versate sopra il curry caldo con almeno un pezzo di pollo per porzione e mettete in cima i noodle fritti. Fate girare le guarnizioni a tavola — scalogno affettato, senape cinese in salamoia, coriandolo, uno spicchio di lime da spremere alla fine e un cucchiaio di olio piccante — il piatto vive di contrasti (brodo setoso, noodle morbidi sotto, noodle croccanti sopra, il morso dello scalogno crudo, l'acido del condimento, la luce del lime) e ogni ciotola si costruisce a tavola.",

'ko': "두꺼운 냄비에 코코넛 크림을 중불에서 4–5분, 기름이 분리되고 크림이 윤기 있게 빛날 때까지 졸인 뒤, 카오 소이 페이스트를 넣고 2–3분 볶아 색이 짙어지고 부엌이 깊고 구운 듯한 향으로 가득 차게 한다 — 이 페이스트는 마른 향신료에 기대고 있어, 중부 태국식 커리보다 더 무겁고 더 흙냄새가 있다. 닭고기 조각을 넣고 페이스트에 잘 묻도록 굴린 다음, 코코넛 밀크와 닭 육수를 붓고 약하게 끓을 정도로 가열해 뚜껑을 살짝 열어둔 채 30–35분, 닭이 부드럽게 풀어지고 국물이 약간 졸아들 때까지 익힌다; 마무리에 가까워질 즈음 피쉬소스와 팜 슈가로 간해, 국물이 진하고 살짝 달면서 커리 페이스트 자체에서 오는 은은한 신맛이 나도록 한다. 커리가 끓는 사이에 신선한 에그 누들 한 줌을 집어 물기를 털고 180°C 기름에 30–45초간, 부풀고 황금빛이 될 때까지 튀긴다 — 모든 그릇의 위에 올라갈 바삭한 왕관 — 종이 위에서 기름을 뺀다. 남은 면은 그냥 물에 막 부드러워질 정도로 삶고, 재빨리 물을 빼서 깊은 그릇에 나눠 담고, 그 위에 뜨거운 커리를 1인분당 닭 한 조각 이상이 들어가도록 끼얹고, 튀긴 면을 위에 얹는다. 식탁 위로 고명을 돌린다 — 슬라이스한 샬롯, 절인 갓, 고수, 마지막에 짤 라임 한 조각, 그리고 칠리 오일 한 숟갈 — 이 요리는 대비로 산다 (비단 같은 국물, 아래의 부드러운 면, 위의 바삭한 면, 생 샬롯의 톡 쏘는 식감, 절임의 산미, 라임의 빛), 카오 소이 한 그릇은 항상 식탁에서 완성된다.",

'hi': "एक भारी बर्तन में नारियल क्रीम मध्यम आँच पर 4–5 मिनट तक तब तक पकाएँ जब तक तेल अलग न हो जाए और क्रीम चमकदार न लगे, फिर khao soi पेस्ट डालें और 2–3 मिनट तक तब तक भूनें जब तक रंग गहरा हो जाए और रसोई में एक गहरी, भुनी हुई ख़ुशबू भर जाए — मध्य थाई करियों के मुक़ाबले भारी और मिट्टी जैसी, क्योंकि यह पेस्ट सूखे मसालों पर टिकी है। चिकन के टुकड़े डालें और पेस्ट में लपेट दें, नारियल का दूध और स्टॉक डालें, हल्की उबाल पर लाएँ और ढक्कन थोड़ा खुला रख कर 30–35 मिनट तक पकाएँ, जब तक चिकन हड्डी से अलग होने लायक नर्म न हो और शोरबा थोड़ा गाढ़ा न हो जाए; आख़िर में फिश सॉस और ताड़ की चीनी से स्वाद दें ताकि शोरबा गाढ़ा, हलका मीठा, और करी पेस्ट से आती हलकी खटास वाला हो। जब करी पक रही हो, ताज़े अंडे वाले नूडल्स की एक छोटी मुट्ठी लें, अतिरिक्त पानी झाड़ें, और 180°C तेल में 30–45 सेकंड तब तक तलें जब तक वो फूल कर सुनहरे न हो जाएँ — हर कटोरे के ऊपर रखा कुरकुरा ताज — फिर काग़ज़ पर निकाल लें। बाक़ी नूडल्स को सादे पानी में बस-बस नरम होने तक उबालें, जल्दी से छानें, और गहरे कटोरों में बाँट दें, ऊपर गरम करी डालें — हर कटोरे में कम से कम एक चिकन का टुकड़ा — फिर तले हुए नूडल्स ऊपर रखें। गार्निश को मेज़ पर घुमाएँ — shallot की कतरन, अचार वाली सरसों की पत्तियाँ, धनिया, आख़िर में निचोड़ने के लिए नीबू का एक टुकड़ा, और एक चम्मच मिर्च का तेल — यह व्यंजन कंट्रास्ट से जीता है (रेशम जैसा शोरबा, नीचे नरम नूडल्स, ऊपर कुरकुरे नूडल्स, कच्ची shallot की तीख़ी काट, अचार का खटास, नीबू की चमक), और हर कटोरा मेज़ पर ही बनता है।",
}

FEATURE_CARDS = {
'en': '[{icon:"🌶️", t:"Northern Thai paste", d:"Built on dry spices — earthier than central-Thai curries"}, {icon:"🥥", t:"Cream first, milk after", d:"Crack the oil out of the cream before frying the paste"}, {icon:"🍜", t:"Two noodles, one bowl", d:"Soft below, deep-fried golden crown on top"}, {icon:"🧅", t:"Built at the table", d:"Shallot, pickled mustard, lime and chilli oil — diner\'s choice"}]',
'ro': '[{icon:"🌶️", t:"Pastă din nordul Thailandei", d:"Construită pe mirodenii uscate — mai pământiu decât curry-urile centrale"}, {icon:"🥥", t:"Smântâna întâi, laptele după", d:"Scoate uleiul din smântână înainte de a prăji pasta"}, {icon:"🍜", t:"Două tăițe, un bol", d:"Moi dedesubt, coroană aurie crocantă deasupra"}, {icon:"🧅", t:"Construit la masă", d:"Șalotă, muștar murat, lime, ulei de chili — la alegerea fiecăruia"}]',
'es': '[{icon:"🌶️", t:"Pasta del norte de Tailandia", d:"Construida con especias secas — más terrosa que los curries centrales"}, {icon:"🥥", t:"Primero crema, después leche", d:"Rompe el aceite de la crema antes de freír la pasta"}, {icon:"🍜", t:"Dos fideos, un cuenco", d:"Blandos abajo, corona crujiente dorada encima"}, {icon:"🧅", t:"Se monta en la mesa", d:"Chalota, mostaza encurtida, lima y aceite de chile — al gusto"}]',
'fr': '[{icon:"🌶️", t:"Pâte du nord de la Thaïlande", d:"Bâtie sur épices sèches — plus terreuse que les curries centraux"}, {icon:"🥥", t:"Crème d\'abord, lait ensuite", d:"Faire sortir l\'huile de la crème avant de frire la pâte"}, {icon:"🍜", t:"Deux nouilles, un bol", d:"Molles en dessous, couronne dorée croustillante au-dessus"}, {icon:"🧅", t:"Construit à table", d:"Échalote, moutarde au vinaigre, citron vert, huile de piment — au choix"}]',
'de': '[{icon:"🌶️", t:"Nordthailändische Paste", d:"Auf Trockengewürzen gebaut — erdiger als zentralthailändische Currys"}, {icon:"🥥", t:"Erst Sahne, dann Milch", d:"Öl aus der Creme reißen, bevor die Paste angebraten wird"}, {icon:"🍜", t:"Zwei Nudeln, eine Schale", d:"Weich darunter, knusprig-goldene Krone darüber"}, {icon:"🧅", t:"Am Tisch gebaut", d:"Schalotte, eingelegtes Senfgrün, Limette, Chiliöl — frei wählbar"}]',
'pt': '[{icon:"🌶️", t:"Pasta do norte da Tailândia", d:"Construída em especiarias secas — mais telúrica que os caris centrais"}, {icon:"🥥", t:"Natas primeiro, leite depois", d:"Separe o óleo das natas antes de fritar a pasta"}, {icon:"🍜", t:"Duas massas, uma taça", d:"Macia em baixo, coroa dourada estaladiça em cima"}, {icon:"🧅", t:"Monta-se à mesa", d:"Chalota, mostarda em conserva, lima e óleo de piri-piri — à escolha"}]',
'ru': '[{icon:"🌶️", t:"Северо-тайская паста", d:"Построена на сухих специях — землистее центральных карри"}, {icon:"🥥", t:"Сначала сливки, потом молоко", d:"Выпарить масло из сливок прежде, чем жарить пасту"}, {icon:"🍜", t:"Две лапши, одна миска", d:"Мягкая внизу, золотая хрустящая коронка сверху"}, {icon:"🧅", t:"Собирается за столом", d:"Шалот, маринованная горчица, лайм, чили-масло — по вкусу"}]',
'ar': '[{icon:"🌶️", t:"معجون شمال تايلاند", d:"مبني على البهارات الجافة — أكثر ترابية من كاري الوسط"}, {icon:"🥥", t:"الكريمة أولاً ثم الحليب", d:"اكسر الزيت من الكريمة قبل قلي المعجون"}, {icon:"🍜", t:"نوعان من النودلز", d:"طرية تحت، تاج مقرمش ذهبي فوق"}, {icon:"🧅", t:"يُبنى على المائدة", d:"شالوت، خردل مخلل، ليم، زيت فلفل — كل واحد على ذوقه"}]',
'zh': '[{icon:"🌶️", t:"泰北咖喱酱", d:"以干香料为主 — 比泰中咖喱更带土气"}, {icon:"🥥", t:"先椰浆，后椰奶", d:"先把椰浆里的油逼出来，再下咖喱酱"}, {icon:"🍜", t:"两种面，一碗汤", d:"下面软面，上面是金黄酥脆的「皇冠」"}, {icon:"🧅", t:"在桌上完成", d:"红葱、腌芥菜、青柠、辣椒油 — 各自调味"}]',
'ja': '[{icon:"🌶️", t:"北タイのカレーペースト", d:"乾燥スパイス主体 — 中部タイより重く土の香り"}, {icon:"🥥", t:"クリーム先、ミルク後", d:"クリームから油を出してからペーストを炒める"}, {icon:"🍜", t:"麺は二種、椀は一つ", d:"下は柔らかい麺、上は黄金色のカリッとした王冠"}, {icon:"🧅", t:"卓上で完成", d:"エシャロット・漬けからし菜・ライム・辣油、各自で"}]',
'tr': '[{icon:"🌶️", t:"Kuzey Tay ezmesi", d:"Kuru baharatlara dayanır — orta Tay körilerinden daha topraksı"}, {icon:"🥥", t:"Önce krema, sonra süt", d:"Krema yağını ayırdıktan sonra ezmeyi kavurun"}, {icon:"🍜", t:"İki erişte, bir kâse", d:"Altta yumuşak erişte, üstte altın çıtır taç"}, {icon:"🧅", t:"Sofrada kurulur", d:"Arpacık, turşulu hardal, misket limonu, biber yağı — kişiye göre"}]',
'it': '[{icon:"🌶️", t:"Pasta del nord della Thailandia", d:"Basata su spezie secche — più terrosa dei curry centrali"}, {icon:"🥥", t:"Prima la crema, poi il latte", d:"Far uscire l\'olio dalla crema prima di soffriggere la pasta"}, {icon:"🍜", t:"Due noodle, una ciotola", d:"Morbidi sotto, corona dorata croccante sopra"}, {icon:"🧅", t:"Si costruisce a tavola", d:"Scalogno, senape in salamoia, lime, olio piccante — a piacere"}]',
'ko': '[{icon:"🌶️", t:"북부 태국 페이스트", d:"마른 향신료 기반 — 중부 태국 커리보다 더 흙냄새"}, {icon:"🥥", t:"크림 먼저, 밀크 다음", d:"크림에서 기름을 분리한 뒤 페이스트를 볶는다"}, {icon:"🍜", t:"두 가지 면, 한 그릇", d:"아래는 부드러운 면, 위는 황금색 바삭한 왕관"}, {icon:"🧅", t:"식탁에서 완성", d:"샬롯, 절인 갓, 라임, 칠리 오일 — 각자 취향대로"}]',
'hi': '[{icon:"🌶️", t:"उत्तरी थाई पेस्ट", d:"सूखे मसालों पर टिकी — मध्य थाई करी से ज़्यादा मिट्टी जैसी"}, {icon:"🥥", t:"पहले क्रीम, बाद में दूध", d:"क्रीम से तेल अलग कर के पेस्ट भूनें"}, {icon:"🍜", t:"दो नूडल्स, एक कटोरा", d:"नीचे नरम, ऊपर सुनहरा कुरकुरा ताज"}, {icon:"🧅", t:"मेज़ पर बनता है", d:"shallot, अचारी सरसों, नीबू, मिर्च का तेल — अपनी पसंद"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*212,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]

hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS:
    how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)

fc_lines = ['featureCards: {']
for lc in LANGS:
    fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = (
    before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
)

new_src = src[:rec_start] + new_recipe_block + src[rec_end:]

with open('public/js/recipes.js', 'w', encoding='utf-8') as f:
    f.write(new_src)

print(f"Recipe 212 (Khao Soi) rewritten:")
print(f"  Old: {rec_end - rec_start} chars → New: {len(new_recipe_block)} chars")
print(f"  howIsMade: 5 steps × {len(LANGS)} langs")
print(f"  featureCards: 4 cards × {len(LANGS)} langs (added)")
