#!/usr/bin/env python3
"""Rewrite recipe 205 (Hyderabadi Lamb Biryani): 11 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Heat the ghee and oil in a wide heavy pan over medium heat and fry the sliced onions slowly for 25–30 minutes, stirring often, until deeply golden brown (birista), then drain on paper, reserve the oil in the pan and keep half the onions for layering. Combine the lamb with the yoghurt, ginger-garlic paste, half of the fried onions crushed in your hand, chilli powder, turmeric, salt, lemon juice and a teaspoon of the shahi jeera, mix thoroughly and rest at least 2 hours or overnight in the fridge; tip the marinated lamb back into the reserved onion oil, add the cinnamon, cardamom, cloves and bay leaf, and cook covered over low heat for an hour to an hour and a quarter, until the lamb is tender and the gravy has reduced to a thick coating. Bring a deep pot of well-salted water to a rolling boil with the rest of the whole spices and a tablespoon of oil, add the soaked basmati and cook just 4–5 minutes until the grains have lengthened and are about three-quarters done — they finish in the steam — then drain quickly and gently. In the same pan over the lamb, spread the rice evenly, scatter the remaining fried onions, chopped mint and coriander, and the green chillies on top, then drizzle the saffron milk in slow streaks across the surface and the rose water if using. Seal the lid with a strip of wet dough or a tight wrap of foil, set on the lowest heat for 25–30 minutes, then turn off the flame without lifting the lid and rest sealed for another 10 minutes — break the seal at the table and plunge a long spoon to the bottom to lift straight up, so each portion comes out with both rice and meat, never stirred together.",

'ro': "Încălzește ghee-ul și uleiul într-o tigaie largă și grea pe foc mediu și prăjește feliile de ceapă încet 25–30 de minute, amestecând des, până devin adânc aurii-maro (birista), apoi scurge-le pe hârtie, păstrează uleiul în tigaie și pune deoparte jumătate din ceapă pentru stratificare. Combină mielul cu iaurtul, pasta de ghimbir-usturoi, jumătate din ceapa prăjită strivită în mână, pudra de chili, turmericul, sarea, sucul de lămâie și o linguriță de shahi jeera, amestecă temeinic și odihnește cel puțin 2 ore sau peste noapte la frigider; pune mielul marinat înapoi în uleiul de ceapă rezervat, adaugă scorțișoara, cardamomul, cuișoarele și foaia de dafin, și gătește acoperit pe foc mic o oră până la o oră și un sfert, până când mielul este fraged și sosul s-a redus la o glazură groasă. Adu o oală adâncă cu apă bine sărată la fierbere puternică împreună cu restul mirodeniilor întregi și o lingură de ulei, adaugă basmatiul înmuiat și gătește doar 4–5 minute, până când boabele s-au alungit și sunt cam trei sferturi gătite — se termină în aburi — apoi scurge-le rapid și ușor. În aceeași tigaie peste miel, întinde orezul uniform, presară restul de ceapă prăjită, mentă și coriandru tocate, și ardeii verzi deasupra, apoi picură laptele cu șofran în dâre lente peste suprafață și apa de trandafiri dacă o folosești. Sigilează capacul cu o fâșie de aluat umed sau o folie strânsă de aluminiu, pune pe focul cel mai mic 25–30 de minute, apoi stinge flacăra fără să ridici capacul și odihnește sigilat încă 10 minute — sparge sigiliul la masă și înfige o lingură lungă până la fund pentru a ridica drept, astfel încât fiecare porție să iasă cu și orez și carne, niciodată amestecate.",

'es': "Calienta el ghee y el aceite en una sartén ancha y pesada a fuego medio y fríe las cebollas en rodajas despacio 25–30 minutos, removiendo a menudo, hasta que estén profundamente doradas (birista), después escúrrelas sobre papel, reserva el aceite en la sartén y guarda la mitad de las cebollas para el montaje. Combina el cordero con el yogur, la pasta de jengibre-ajo, la mitad de las cebollas fritas aplastadas en la mano, el chile en polvo, la cúrcuma, la sal, el zumo de limón y una cucharadita de shahi jeera, mezcla bien y reposa al menos 2 horas o toda la noche en la nevera; devuelve el cordero marinado al aceite de cebolla reservado, añade la canela, el cardamomo, los clavos y la hoja de laurel, y cocina tapado a fuego bajo de una hora a una hora y cuarto, hasta que el cordero esté tierno y la salsa se haya reducido a una capa espesa. Lleva una olla profunda de agua bien salada a hervor fuerte con el resto de las especias enteras y una cucharada de aceite, añade el basmati remojado y cuécelo solo 4–5 minutos, hasta que los granos se hayan alargado y estén unos tres cuartos hechos — terminan en el vapor — después escúrrelos rápida y suavemente. En la misma sartén sobre el cordero, esparce el arroz uniformemente, reparte el resto de las cebollas fritas, la menta y el cilantro picados, y los chiles verdes por encima, después vierte la leche con azafrán en hilos lentos por la superficie y el agua de rosas si la usas. Sella la tapa con una tira de masa húmeda o un envoltorio tirante de papel aluminio, pon al fuego más bajo 25–30 minutos, después apaga la llama sin levantar la tapa y reposa sellado otros 10 minutos — rompe el sello en la mesa y mete una cuchara larga hasta el fondo para levantar recto, de modo que cada porción salga con arroz y carne juntos, nunca mezclados.",

'fr': "Faites chauffer le ghee et l'huile dans une grande cocotte épaisse à feu moyen et faites frire lentement les oignons émincés pendant 25 à 30 minutes en remuant souvent, jusqu'à ce qu'ils soient profondément dorés (birista), puis égouttez-les sur du papier, réservez l'huile dans la cocotte et gardez la moitié des oignons pour le montage. Combinez l'agneau avec le yaourt, la pâte gingembre-ail, la moitié des oignons frits écrasés à la main, le piment en poudre, le curcuma, le sel, le jus de citron et une cuillère à café de shahi jeera, mélangez bien et faites reposer au moins 2 heures ou toute la nuit au frais ; remettez l'agneau mariné dans l'huile d'oignon réservée, ajoutez la cannelle, la cardamome, les clous de girofle et la feuille de laurier, et faites cuire couvert à feu doux d'une heure à une heure et quart, jusqu'à ce que l'agneau soit tendre et que la sauce ait réduit en un enrobage épais. Portez une grande casserole d'eau bien salée à ébullition franche avec le reste des épices entières et une cuillère à soupe d'huile, ajoutez le basmati trempé et faites cuire seulement 4 à 5 minutes, jusqu'à ce que les grains se soient allongés et soient cuits aux trois quarts — ils finissent à la vapeur — puis égouttez vite et délicatement. Dans la même cocotte sur l'agneau, étalez le riz uniformément, parsemez du reste des oignons frits, de la menthe et de la coriandre hachées et des piments verts sur le dessus, puis versez le lait au safran en filets lents sur la surface et l'eau de rose si vous en utilisez. Scellez le couvercle avec une bande de pâte humide ou un emballage serré de papier alu, mettez au feu le plus bas pendant 25 à 30 minutes, puis éteignez la flamme sans soulever le couvercle et laissez reposer scellé encore 10 minutes — brisez le sceau à table et plongez une longue cuillère jusqu'au fond pour soulever droit, de sorte que chaque portion sorte avec riz et viande ensemble, jamais mélangés.",

'de': "Erhitzen Sie das Ghee und das Öl in einer breiten, schweren Pfanne bei mittlerer Hitze und braten Sie die in Scheiben geschnittenen Zwiebeln langsam 25–30 Minuten unter häufigem Rühren, bis sie tief goldbraun sind (Birista), dann auf Küchenpapier abtropfen lassen, das Öl in der Pfanne aufbewahren und die Hälfte der Zwiebeln für das Schichten zurücklassen. Kombinieren Sie das Lamm mit dem Joghurt, der Ingwer-Knoblauch-Paste, der Hälfte der frittierten Zwiebeln in der Hand zerdrückt, Chilipulver, Kurkuma, Salz, Zitronensaft und einem Teelöffel Shahi Jeera, gründlich vermengen und mindestens 2 Stunden oder über Nacht im Kühlschrank ruhen lassen; geben Sie das marinierte Lamm zurück in das aufbewahrte Zwiebelöl, fügen Sie Zimt, Kardamom, Nelken und Lorbeerblatt hinzu und garen Sie zugedeckt bei niedriger Hitze eine bis eineinviertel Stunden, bis das Lamm zart ist und die Sauce zu einem dicken Überzug reduziert ist. Bringen Sie einen tiefen Topf gut gesalzenes Wasser mit dem Rest der ganzen Gewürze und einem Esslöffel Öl zum kräftigen Kochen, geben Sie den eingeweichten Basmati hinein und kochen Sie nur 4–5 Minuten, bis die Körner sich verlängert haben und etwa zu drei Vierteln gar sind — sie ziehen im Dampf nach — dann schnell und vorsichtig abgießen. In derselben Pfanne über dem Lamm verteilen Sie den Reis gleichmäßig, streuen die restlichen frittierten Zwiebeln, gehackte Minze und Koriander sowie die grünen Chilis darüber, dann träufeln Sie die Safranmilch in langsamen Streifen über die Oberfläche und das Rosenwasser, falls Sie es verwenden. Versiegeln Sie den Deckel mit einem Streifen feuchten Teigs oder einer straffen Alufolie, stellen Sie ihn auf die niedrigste Hitze für 25–30 Minuten, dann schalten Sie die Flamme ohne den Deckel zu lüften aus und lassen Sie weitere 10 Minuten versiegelt ruhen — brechen Sie das Siegel am Tisch und stoßen Sie einen langen Löffel bis zum Boden und heben Sie gerade hoch, sodass jede Portion mit Reis und Fleisch zusammen herauskommt, nie verrührt.",

'pt': "Aqueça o ghee e o óleo numa panela larga e pesada em lume médio e frite as cebolas em fatias lentamente durante 25–30 minutos, mexendo com frequência, até ficarem profundamente douradas (birista), depois escorra sobre papel, reserve o óleo na panela e guarde metade das cebolas para a camada. Combine o borrego com o iogurte, a pasta de gengibre-alho, metade das cebolas fritas esmagadas na mão, o piri-piri em pó, o açafrão-da-índia, o sal, o sumo de limão e uma colher de chá de shahi jeera, misture bem e deixe descansar pelo menos 2 horas ou de um dia para o outro no frigorífico; volte a colocar o borrego marinado no óleo de cebola reservado, junte a canela, o cardamomo, os cravinhos e a folha de louro, e cozinhe tapado em lume baixo de uma hora a uma hora e um quarto, até o borrego estar tenro e o molho ter reduzido a uma cobertura espessa. Leve uma panela funda de água bem salgada a uma fervura forte com o resto das especiarias inteiras e uma colher de sopa de óleo, junte o basmati demolhado e cozinhe apenas 4–5 minutos, até os grãos se terem alongado e estarem cerca de três quartos cozidos — terminam no vapor — depois escorra rápida e suavemente. Na mesma panela sobre o borrego, espalhe o arroz uniformemente, polvilhe o resto das cebolas fritas, a hortelã e os coentros picados, e os piri-piris verdes por cima, depois verta o leite com açafrão em fios lentos pela superfície e a água de rosas, se usar. Sele a tampa com uma tira de massa húmida ou um envolvimento apertado de papel alumínio, ponha no lume mais baixo durante 25–30 minutos, depois apague a chama sem levantar a tampa e deixe descansar selado mais 10 minutos — quebre o selo à mesa e mergulhe uma colher longa até ao fundo para erguer a direito, para que cada porção saia com arroz e carne juntos, nunca misturados.",

'ru': "Разогрейте ги и масло в широкой тяжёлой сковороде на среднем огне и медленно обжаривайте нарезанный лук 25–30 минут, часто помешивая, пока он не станет глубоко золотисто-коричневым (бириста), затем откиньте на бумагу, оставьте масло в сковороде и сохраните половину лука для слоёв. Смешайте баранину с йогуртом, пастой имбирь-чеснок, половиной обжаренного лука, раздавленного в руке, чилийским порошком, куркумой, солью, лимонным соком и чайной ложкой шахи джиры, тщательно перемешайте и оставьте мариноваться минимум 2 часа или на ночь в холодильнике; верните маринованную баранину в зарезервированное луковое масло, добавьте корицу, кардамон, гвоздику и лавровый лист, и готовьте под крышкой на слабом огне час — час с четвертью, пока баранина не станет мягкой, а соус не сократится до густого покрытия. Доведите глубокую кастрюлю хорошо подсоленной воды до энергичного кипения вместе с остальными целыми специями и столовой ложкой масла, добавьте замоченный басмати и варите всего 4–5 минут, пока зёрна не удлинятся и не будут готовы примерно на три четверти — они дойдут на пару — затем быстро и аккуратно слейте. В той же сковороде поверх баранины распределите рис равномерно, посыпьте сверху оставшимся жареным луком, рубленой мятой и кинзой и зелёным перцем, затем медленными струями полейте шафрановое молоко по поверхности и розовую воду, если используете. Запечатайте крышку полоской влажного теста или плотной фольгой, поставьте на самый слабый огонь на 25–30 минут, затем выключите пламя, не поднимая крышку, и оставьте под печатью ещё 10 минут — сорвите печать за столом и погрузите длинную ложку до дна, поднимая прямо вверх, чтобы каждая порция вышла с рисом и мясом вместе, никогда не перемешанным.",

'ar': "سخّن السمن والزيت في مقلاة واسعة وثقيلة على نار متوسطة وحمّر شرائح البصل ببطء 25–30 دقيقة، مع التحريك المتكرر، حتى تصير ذهبية بنية عميقة (بيريستا)، ثم صفّها على ورق، احتفظ بالزيت في المقلاة، واترك نصف البصل جانباً للتطبيق. اخلط الضأن مع اللبن، عجينة الزنجبيل-الثوم، نصف البصل المقلي المهروس في اليد، مسحوق الفلفل، الكركم، الملح، عصير الليمون، وملعقة صغيرة من شاهي جيرا، اخلط جيداً ودع المزيج يرتاح ساعتين على الأقل أو طوال الليل في الثلاجة؛ أعد الضأن المتبل إلى زيت البصل المحفوظ، أضف القرفة والهيل والقرنفل وورقة الغار، واطبخ مغطىً على نار هادئة من ساعة إلى ساعة وربع، حتى يصبح الضأن طرياً وتتقلص الصلصة إلى طبقة سميكة. أوصِل قدراً عميقاً من الماء المملح جيداً إلى غليان قوي مع بقية البهارات الكاملة وملعقة كبيرة من الزيت، أضف البسمتي المنقوع واطبخه فقط 4–5 دقائق، حتى تستطيل الحبوب وتصبح نحو ثلاثة أرباع مطهوة — يكتمل النضج في البخار — ثم صفّها بسرعة وبلطف. في المقلاة نفسها فوق الضأن، افرد الأرز بشكل متساوٍ، انثر بقية البصل المقلي، النعناع والكزبرة المفرومين، والفلفل الأخضر فوق، ثم اسكب حليب الزعفران بخطوط بطيئة عبر السطح وماء الورد إذا كنت تستخدمه. اغلق الغطاء بشريط من العجين الرطب أو ورق ألمنيوم مشدود، ضعه على أهدأ نار لمدة 25–30 دقيقة، ثم أطفئ اللهب دون رفع الغطاء واتركه مغلقاً 10 دقائق أخرى — اكسر الإغلاق على المائدة واغرز ملعقة طويلة إلى القاع وارفع مباشرة، بحيث تخرج كل حصة بأرز ولحم معاً، لا ممزوجين أبداً.",

'zh': "在一只宽厚的锅中以中火加热酥油和油，慢慢地把切片洋葱炒 25–30 分钟，频繁搅拌，直到颜色变得深金棕色（birista），然后捞出在纸上沥干，把油留在锅里，留一半洋葱用于分层。把羊肉与酸奶、姜蒜泥、用手捏碎的一半炸洋葱、辣椒粉、姜黄、盐、柠檬汁和 1 茶匙 shahi jeera 混合，充分搅拌，腌制至少 2 小时或一夜放冰箱；把腌好的羊肉放回保留的洋葱油中，加入肉桂、豆蔻、丁香和月桂叶，盖盖小火炖 1 小时到 1 小时 15 分钟，直到羊肉变嫩、酱汁收浓成厚厚一层。把一只深锅的咸水大火烧开，加入其余的整粒香料和 1 汤匙油，倒入泡好的 basmati 米，只煮 4–5 分钟，直到米粒变长、大约七分熟——剩下的会在蒸汽中完成——然后迅速、轻柔地沥干。在同一只锅中羊肉上方，把米均匀铺开，在顶上撒上剩下的炸洋葱、切碎的薄荷和香菜以及青辣椒，然后将藏红花牛奶以缓慢的细线浇过表面，玫瑰水若用也是。用湿面团条或紧密的铝箔密封锅盖，放在最小火上 25–30 分钟，然后不掀盖关火，密封再静置 10 分钟——在餐桌上打开密封，把一只长勺插到锅底直直舀起，让每份都同时带米和肉，绝不搅拌在一起。",

'ja': "厚手の広いフライパンに中火でギーと油を熱し、薄切り玉ねぎを 25〜30 分かけてゆっくり炒め、頻繁にかき混ぜながら深い黄金色（バリスタ）になるまで揚げ焼きし、紙にあげて油を切り、油はフライパンに残し、玉ねぎの半量を層作り用に取り分ける。ラム肉をヨーグルト、ジンジャー・ガーリックペースト、手で潰した炒め玉ねぎの半量、チリパウダー、ターメリック、塩、レモン汁、シャヒ・ジーラ小さじ 1 と合わせ、よく混ぜて冷蔵庫で 2 時間以上、できれば一晩マリネする；マリネしたラムを取っておいた玉ねぎ油に戻し、シナモン、カルダモン、クローブ、ベイリーフを加え、蓋をして弱火で 1 時間〜1 時間 15 分、ラムが柔らかくグレービーが濃いコーティングまで煮詰まるまで煮込む。深鍋にしっかり塩を入れた湯を沸騰させ、残りのホールスパイスと油大さじ 1 を加え、浸水したバスマティを入れて 4〜5 分だけ茹で、米粒が伸び、約 7 分通り火が通る程度に — 残りは蒸気で仕上げる — 素早く優しく湯切りする。同じフライパンのラムの上に米を均等に広げ、残りの炒め玉ねぎ、刻んだミントとコリアンダー、青唐辛子を散らし、サフランミルクを表面にゆっくり筋状に流し入れ、使う場合はローズウォーターも。湿らせた生地のテープか、ぴっちりとしたアルミ箔で蓋を密閉し、最弱火で 25〜30 分、蓋を持ち上げずに火を止めて、さらに 10 分密閉のまま蒸らす — 食卓で封を開け、長いスプーンを底まで差し込み、まっすぐに持ち上げて、1 人分の中に米とラム肉が共に取り出されるように、決して混ぜずに盛る。",

'tr': "Ghee ve yağı geniş, ağır bir tavada orta ateşte ısıt ve dilimlenmiş soğanları 25–30 dakika boyunca sık sık karıştırarak yavaşça kavur, derin altın kahverengiye (birista) ulaşana dek, sonra kağıda al, yağı tavada bırak ve soğanların yarısını katmanlama için ayır. Kuzu etini yoğurt, zencefil-sarımsak ezmesi, elinde ezilen kızarmış soğanın yarısı, biber tozu, zerdeçal, tuz, limon suyu ve 1 çay kaşığı şahi jeera ile birleştir, iyice karıştır ve en az 2 saat ya da gece boyunca buzdolabında dinlendir; marine edilmiş kuzuyu ayrılmış soğan yağına geri al, tarçın, kakule, karanfil ve defne yaprağını ekle ve kapalı olarak kısık ateşte 1 saat ila 1 saat 15 dakika boyunca, kuzu yumuşayıp sosu kalın bir kaplama haline gelene dek pişir. Derin bir tencerede iyice tuzlanmış suyu kalan bütün baharatlar ve 1 yemek kaşığı yağla şiddetli kaynamaya getir, ıslatılmış basmati pirincini ekle ve sadece 4–5 dakika pişir, taneler uzayıp yaklaşık dörtte üç oranında pişene dek — kalanı buhar tamamlayacak — sonra hızlı ve nazikçe süz. Aynı tavada kuzunun üzerine pirinci eşit şekilde yay, kalan kızarmış soğanları, doğranmış nane ve kişnişi ve yeşil biberleri üstüne serp, sonra safranlı sütü yavaş şeritler halinde yüzeye dök ve kullanıyorsan gül suyunu da. Kapağı ıslak hamur şeridiyle veya sıkı bir folyo sarımıyla mühürle, en kısık ateşte 25–30 dakika bırak, sonra kapağı kaldırmadan ateşi söndür ve mühürlü olarak 10 dakika daha dinlendir — mührü sofrada kır ve uzun bir kaşığı dibe kadar sapla, dik yukarı kaldır, böylece her porsiyon hem pirinç hem et ile birlikte çıksın, asla karıştırılmamış olarak.",

'it': "Scaldate il ghee e l'olio in una padella larga e pesante a fuoco medio e fate friggere le cipolle a fette lentamente per 25–30 minuti, mescolando spesso, finché non sono di un dorato marrone profondo (birista), poi scolatele su carta, conservate l'olio in padella e mettete da parte metà delle cipolle per la stratificazione. Combinate l'agnello con lo yogurt, la pasta zenzero-aglio, metà delle cipolle fritte schiacciate in mano, la polvere di peperoncino, la curcuma, il sale, il succo di limone e un cucchiaino di shahi jeera, mescolate bene e fate riposare almeno 2 ore o tutta la notte in frigo; rimettete l'agnello marinato nell'olio di cipolla riservato, aggiungete cannella, cardamomo, chiodi di garofano e alloro, e cuocete coperto a fuoco basso da un'ora a un'ora e un quarto, finché l'agnello non è tenero e il sugo si è ridotto a un rivestimento spesso. Portate una pentola profonda di acqua ben salata a un'ebollizione vigorosa con il resto delle spezie intere e un cucchiaio di olio, aggiungete il basmati ammollato e cuocete solo 4–5 minuti, finché i chicchi non si sono allungati e sono cotti per circa tre quarti — finiscono al vapore — poi scolate rapidamente e con delicatezza. Nella stessa padella sopra l'agnello, distribuite il riso uniformemente, cospargete il resto delle cipolle fritte, la menta e il coriandolo tritati e i peperoncini verdi in cima, poi versate il latte allo zafferano in fili lenti sulla superficie e l'acqua di rose se usata. Sigillate il coperchio con una striscia di pasta umida o una stretta avvolgenza di alluminio, mettete sul fuoco più basso per 25–30 minuti, poi spegnete la fiamma senza alzare il coperchio e fate riposare sigillato altri 10 minuti — rompete il sigillo a tavola e tuffate un cucchiaio lungo fino al fondo per sollevare dritto, in modo che ogni porzione esca con riso e carne insieme, mai mescolati.",

'ko': "넓고 두꺼운 팬에 기와 기름을 중불로 데우고, 슬라이스한 양파를 25–30분 동안 자주 저으며 천천히 볶아 깊은 황금빛 갈색(비리스타)이 되면 종이에 올려 기름을 빼고, 팬의 기름은 그대로 두고, 양파의 절반은 레이어링용으로 따로 둔다. 양고기를 요거트, 생강-마늘 페이스트, 손으로 부순 튀긴 양파의 절반, 칠리 파우더, 강황, 소금, 레몬즙, 샤히 지라 1작은술과 함께 섞고, 잘 버무린 뒤 냉장고에서 최소 2시간 또는 하룻밤 재워둔다; 양념된 양고기를 따로 둔 양파 기름에 다시 넣고, 시나몬, 카다멈, 정향, 월계수잎을 더해 약불에 뚜껑을 덮고 1시간에서 1시간 15분간, 양고기가 부드러워지고 소스가 진한 코팅 정도로 졸 때까지 익힌다. 깊은 냄비에 잘 소금간한 물을 통향신료 나머지와 기름 1큰술과 함께 격하게 끓이고, 불려둔 바스마티 쌀을 넣어 4–5분만 — 알이 길어지고 약 3/4 정도 익을 때까지 — 끓인 뒤(나머지는 김으로 마무리됨) 재빠르고 부드럽게 물을 뺀다. 같은 팬의 양고기 위에 쌀을 고르게 펴고, 남은 튀긴 양파, 다진 민트와 고수, 청양고추를 위에 흩뿌리고, 사프란 우유를 표면에 천천히 줄로 두르고, 사용한다면 장미수도 함께 두른다. 뚜껑을 젖은 반죽 띠나 단단한 알루미늄 호일로 봉인하고, 가장 약한 불에 25–30분, 그다음 뚜껑을 들지 않고 불을 끈 채 봉인 상태로 10분 더 둔다 — 식탁에서 봉인을 깨고 긴 숟가락을 바닥까지 찔러 곧추 들어 올려, 매 한 그릇이 쌀과 고기를 함께 담아 나오게 한다, 절대 섞지 않은 채로.",

'hi': "एक चौड़े और भारी पैन में मध्यम आँच पर घी और तेल गरम करें और कटी प्याज़ को 25–30 मिनट तक, बार-बार चलाते हुए, गहरे सुनहरे-भूरे (बिरिस्ता) रंग तक धीरे-धीरे भूनें, फिर काग़ज़ पर निकाल कर तेल पैन में रखें और परत के लिए आधी प्याज़ अलग रखें। मटन को दही, अदरक-लहसुन पेस्ट, हाथ में मसली हुई आधी तली प्याज़, मिर्च पाउडर, हल्दी, नमक, नीबू का रस और 1 छोटा चम्मच शाही जीरा के साथ मिलाएँ, अच्छी तरह मिला कर कम से कम 2 घंटे या रात भर फ्रिज में रखें; मैरीनेट किया मटन को बचाई हुई प्याज़ के तेल में वापस डालें, दालचीनी, इलायची, लौंग और तेज़पत्ता डालें, और ढक कर धीमी आँच पर 1 घंटे से 1 घंटा 15 मिनट तक पकाएँ, जब तक मटन नर्म न हो और ग्रेवी एक गाढ़ी परत में सिमट न जाए। एक गहरे बर्तन में अच्छी तरह नमक वाला पानी बाक़ी साबुत मसालों और 1 बड़े चम्मच तेल के साथ तेज़ उबाल पर लाएँ, भीगा बासमती डालें और सिर्फ़ 4–5 मिनट तक पकाएँ, जब तक चावल लंबे हो जाएँ और लगभग तीन-चौथाई पक जाएँ — बाक़ी भाप में पूरा होगा — फिर जल्दी और हलके से छानें। उसी पैन में मटन के ऊपर चावल को एकसमान फैलाएँ, ऊपर बची हुई तली प्याज़, कटी पुदीना और धनिया और हरी मिर्चें छिड़कें, फिर केसर वाला दूध सतह पर धीमी धारियों में डालें और रोज़वाटर अगर इस्तेमाल कर रहे हैं तो वो भी। ढक्कन को गीले आटे की पट्टी या कस के बंधी फॉयल से सील करें, सबसे धीमी आँच पर 25–30 मिनट रखें, फिर ढक्कन उठाए बिना आँच बंद करें और सील्ड अवस्था में 10 मिनट और आराम दें — सील को मेज़ पर तोड़ें, और एक लंबा चम्मच तले तक डाल कर सीधा ऊपर उठाएँ, ताकि हर हिस्से में चावल और मटन साथ-साथ निकलें, कभी मिक्स किए हुए नहीं।",
}

FEATURE_CARDS = {
'en': '[{icon:"🧅", t:"Birista — deep brown onions", d:"25–30 minutes slow-fried; the soul of Hyderabadi flavour"}, {icon:"🥣", t:"Marinate the lamb overnight", d:"Yoghurt + crushed birista works the meat for hours"}, {icon:"🌾", t:"Rice 3/4 done, never full", d:"Boil 4–5 minutes; the dum steam finishes it"}, {icon:"🔒", t:"Sealed-lid dum cooking", d:"Wet dough seal + lowest heat + 10-min off-heat rest"}]',
'ro': '[{icon:"🧅", t:"Birista — ceapă maro adânc", d:"25–30 minute prăjire lentă; sufletul aromei Hyderabadi"}, {icon:"🥣", t:"Marinează mielul peste noapte", d:"Iaurt + birista zdrobit lucrează carnea ore în șir"}, {icon:"🌾", t:"Orez ¾ făcut, niciodată complet", d:"Fierbe 4–5 minute; aburul dum-ului îl termină"}, {icon:"🔒", t:"Gătit dum cu capac sigilat", d:"Sigiliu de aluat umed + foc minim + 10 minute odihnă"}]',
'es': '[{icon:"🧅", t:"Birista — cebollas marrón profundo", d:"25–30 minutos a fuego lento; el alma del sabor Hyderabadi"}, {icon:"🥣", t:"Marina el cordero toda la noche", d:"Yogur + birista aplastada trabajan la carne durante horas"}, {icon:"🌾", t:"Arroz ¾ hecho, nunca entero", d:"Hierve 4–5 minutos; el vapor del dum lo termina"}, {icon:"🔒", t:"Cocción dum con tapa sellada", d:"Sello de masa húmeda + fuego mínimo + 10 min de reposo"}]',
'fr': '[{icon:"🧅", t:"Birista — oignons brun profond", d:"25–30 minutes à feu doux ; l\'âme du goût Hyderabadi"}, {icon:"🥣", t:"Marinade d\'agneau toute la nuit", d:"Yaourt + birista écrasés travaillent la viande pendant des heures"}, {icon:"🌾", t:"Riz aux ¾ cuit, jamais entier", d:"Bouillir 4–5 minutes ; la vapeur du dum le termine"}, {icon:"🔒", t:"Cuisson dum à couvercle scellé", d:"Sceau de pâte humide + feu minimum + 10 min de repos"}]',
'de': '[{icon:"🧅", t:"Birista — tiefbraune Zwiebeln", d:"25–30 Min. langsam frittiert; die Seele des Hyderabadi-Aromas"}, {icon:"🥣", t:"Lamm über Nacht marinieren", d:"Joghurt + zerstoßenes Birista bearbeitet das Fleisch stundenlang"}, {icon:"🌾", t:"Reis ¾ gar, nie ganz", d:"4–5 Min. kochen; der Dum-Dampf vollendet ihn"}, {icon:"🔒", t:"Dum-Garung mit Siegeldeckel", d:"Feuchter Teig-Siegel + niedrigste Hitze + 10 Min. Ruhen"}]',
'pt': '[{icon:"🧅", t:"Birista — cebolas castanho profundo", d:"25–30 minutos fritura lenta; a alma do sabor Hyderabadi"}, {icon:"🥣", t:"Marinar o borrego de um dia para o outro", d:"Iogurte + birista esmagada trabalham a carne durante horas"}, {icon:"🌾", t:"Arroz ¾ feito, nunca completo", d:"Ferver 4–5 minutos; o vapor do dum termina-o"}, {icon:"🔒", t:"Cozedura dum com tampa selada", d:"Selo de massa húmida + lume mínimo + 10 min de repouso"}]',
'ru': '[{icon:"🧅", t:"Бириста — глубоко-коричневый лук", d:"25–30 минут медленной жарки; душа хайдерабадского вкуса"}, {icon:"🥣", t:"Маринуйте баранину на ночь", d:"Йогурт + раздавленная бириста работают с мясом часами"}, {icon:"🌾", t:"Рис ¾ готов, никогда не полностью", d:"Варить 4–5 минут; пар дума доводит его"}, {icon:"🔒", t:"Дум-приготовление с печатью", d:"Печать из влажного теста + минимум огня + 10 мин отдых"}]',
'ar': '[{icon:"🧅", t:"بيريستا — بصل بنّي عميق", d:"25–30 دقيقة قلي بطيء؛ روح نكهة الحيدر آبادية"}, {icon:"🥣", t:"تتبيل الضأن طوال الليل", d:"اللبن + البيريستا المسحوقة يعملان على اللحم لساعات"}, {icon:"🌾", t:"الأرز ثلاثة أرباع، أبداً كاملاً", d:"اغلِه 4–5 دقائق؛ بخار الدم يكمله"}, {icon:"🔒", t:"الطبخ بطريقة الدم وغطاء مغلق", d:"إغلاق بعجين رطب + أهدأ نار + 10 دقائق راحة"}]',
'zh': '[{icon:"🧅", t:"Birista — 深棕色洋葱", d:"25–30 分钟慢火炒；海得拉巴风味的灵魂"}, {icon:"🥣", t:"羊肉腌一夜", d:"酸奶 + 捏碎 birista 让肉腌几小时"}, {icon:"🌾", t:"米七分熟，绝不到熟", d:"煮 4–5 分钟；dum 的蒸汽完成它"}, {icon:"🔒", t:"密封盖 dum 烹饪法", d:"湿面团封 + 最小火 + 10 分钟离火静置"}]',
'ja': '[{icon:"🧅", t:"バリスタ — 深い茶色の玉ねぎ", d:"25〜30 分のじっくり揚げ焼き；ハイデラバード風味の核"}, {icon:"🥣", t:"ラムを一晩マリネ", d:"ヨーグルト + 砕いたバリスタが何時間も肉に効く"}, {icon:"🌾", t:"米は 7 分目、決して全火入れせず", d:"4〜5 分茹で；ダムの蒸気が仕上げる"}, {icon:"🔒", t:"密封蓋のダム調理", d:"湿った生地で密閉 + 最弱火 + 10 分の蒸らし"}]',
'tr': '[{icon:"🧅", t:"Birista — derin kahve soğanlar", d:"25–30 dakika yavaş kavurma; Hyderabadi tadının ruhu"}, {icon:"🥣", t:"Kuzu gece boyu marine", d:"Yoğurt + ezilmiş birista eti saatlerce çalıştırır"}, {icon:"🌾", t:"Pirinç ¾ pişmiş, tam değil", d:"4–5 dk kaynat; dum buharı tamamlar"}, {icon:"🔒", t:"Mühürlü kapakla dum pişirme", d:"Islak hamur mührü + en kısık ateş + 10 dk dinlenme"}]',
'it': '[{icon:"🧅", t:"Birista — cipolle marrone scuro", d:"25–30 minuti di frittura lenta; l\'anima del gusto Hyderabadi"}, {icon:"🥣", t:"Marinare l\'agnello tutta la notte", d:"Yogurt + birista schiacciata lavorano la carne per ore"}, {icon:"🌾", t:"Riso ¾ cotto, mai del tutto", d:"Bollire 4–5 minuti; il vapore del dum lo finisce"}, {icon:"🔒", t:"Cottura dum con coperchio sigillato", d:"Sigillo di pasta umida + fuoco minimo + 10 min di riposo"}]',
'ko': '[{icon:"🧅", t:"비리스타 — 짙은 갈색 양파", d:"25–30분 느린 튀김; 하이데라바디 풍미의 핵심"}, {icon:"🥣", t:"양고기 하룻밤 재우기", d:"요거트 + 부순 비리스타가 고기를 몇 시간 작업"}, {icon:"🌾", t:"쌀 ¾ 익힘, 절대 완전하지 않게", d:"4–5분 끓임; 둠 증기가 마무리"}, {icon:"🔒", t:"봉인 뚜껑 둠 요리", d:"젖은 반죽 봉인 + 가장 약한 불 + 10분 휴지"}]',
'hi': '[{icon:"🧅", t:"बिरिस्ता — गहरी भूरी प्याज़", d:"25–30 मिनट धीमी फ़्राइंग; हैदराबादी स्वाद की आत्मा"}, {icon:"🥣", t:"मटन रात भर मैरीनेट", d:"दही + मसली बिरिस्ता घंटों मांस पर काम करते हैं"}, {icon:"🌾", t:"चावल ¾ पका, कभी पूरा नहीं", d:"4–5 मिनट उबालें; दम की भाप उसे पूरा करती है"}, {icon:"🔒", t:"सीलबंद ढक्कन वाली दम पकाई", d:"गीले आटे की सील + सबसे धीमी आँच + 10 मिनट विश्राम"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*205,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 205 (Hyderabadi Lamb Biryani): {rec_end-rec_start} → {len(new_recipe_block)} chars")
