#!/usr/bin/env python3
"""Rewrite recipe 210 (Massaman Curry): howIsMade 10 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Spoon the coconut cream into a heavy pot over medium heat and let it cook for 5 minutes, stirring, until the oil separates and the cream looks glossy and slightly grainy. Add the Massaman paste and the whole spices and fry for 3 minutes — the paste will darken and the kitchen should smell of cinnamon, cardamom and roasted cumin; this early bloom of the spices is what gives Massaman its Persian-inflected depth. Add the beef and turn it in the paste until every piece is dark red, pour in the coconut milk, tamarind paste and kaffir lime leaves, bring to a bare simmer and braise gently with the lid ajar for an hour and a half, stirring every 20 minutes — the beef is ready when it gives easily to a spoon but still holds its shape. Slide in the potatoes, onions and peanuts and continue cooking uncovered for another 30 minutes until the potatoes are tender and the gravy has thickened to a glossy rich brown; stir in the fish sauce and palm sugar at the end, balancing the salt-sweet-sour triangle until it tastes deep and round, neither too sweet nor too sharp. Rest off the heat for 10 minutes, then serve in shallow bowls with jasmine rice, scattered with a few crushed peanuts on top — Massaman is the Thai curry that gains depth overnight, and any leftovers taste better the next day.",

'ro': "Pune smântâna de cocos într-o oală groasă pe foc mediu și las-o să gătească 5 minute, amestecând, până când uleiul se separă, iar smântâna devine lucioasă și ușor granulată. Adaugă pasta Massaman și mirodeniile întregi și prăjește 3 minute — pasta se va închide la culoare, iar bucătăria va mirosi a scorțișoară, cardamom și chimion prăjit; această înflorire timpurie a mirodeniilor este ceea ce dă Massaman-ului profunzimea lui de inspirație persană. Adaugă carnea de vită și învârte-o în pastă până când fiecare bucată este de un roșu închis, toarnă laptele de cocos, pasta de tamarind și frunzele de lămâi kaffir, adu la o fierbere abia perceptibilă și înăbușe blând cu capacul puțin întredeschis o oră și jumătate, amestecând la fiecare 20 de minute — carnea este gata când cedează ușor la lingură dar își păstrează forma. Adaugă cartofii, cepele și arahidele și continuă să gătești descoperit încă 30 de minute, până când cartofii sunt moi, iar sosul s-a îngroșat într-un maro lucios și bogat; adaugă sosul de pește și zahărul de palmier la final, echilibrând triunghiul sărat-dulce-acru până capătă un gust adânc și rotund, nici prea dulce, nici prea ascuțit. Odihnește departe de foc 10 minute, apoi servește în boluri puțin adânci cu orez iasomie, presărând câteva arahide zdrobite deasupra — Massaman este curry-ul thailandez care câștigă profunzime peste noapte, iar orice resturi au un gust mai bun a doua zi.",

'es': "Vierte la crema de coco en una olla pesada a fuego medio y deja que se cocine 5 minutos, removiendo, hasta que el aceite se separe y la crema parezca brillante y ligeramente granulada. Añade la pasta Massaman y las especias enteras y fríe 3 minutos — la pasta se oscurecerá y la cocina olerá a canela, cardamomo y comino tostado; esta floración temprana de las especias es lo que da al Massaman su profundidad de inflexión persa. Añade la ternera y voltéala en la pasta hasta que cada pieza esté de un rojo oscuro, vierte la leche de coco, la pasta de tamarindo y las hojas de lima kaffir, lleva a un hervor apenas perceptible y brasea suavemente con la tapa entreabierta durante una hora y media, removiendo cada 20 minutos — la carne está lista cuando cede fácilmente a la cuchara pero aún mantiene su forma. Incorpora las patatas, las cebollas y los cacahuetes y sigue cocinando destapado otros 30 minutos, hasta que las patatas estén tiernas y la salsa se haya espesado en un marrón brillante y rico; al final, añade la salsa de pescado y el azúcar de palma, equilibrando el triángulo salado-dulce-ácido hasta que el sabor sea profundo y redondo, ni demasiado dulce ni demasiado punzante. Reposa fuera del fuego 10 minutos, luego sirve en cuencos hondos con arroz jazmín, esparciendo unos cacahuetes machacados por encima — el Massaman es el curry tailandés que gana profundidad de un día para otro, y cualquier resto sabe mejor al día siguiente.",

'fr': "Versez la crème de coco dans une cocotte épaisse à feu moyen et laissez-la cuire 5 minutes en remuant, jusqu'à ce que l'huile se sépare et que la crème devienne brillante et légèrement granuleuse. Ajoutez la pâte Massaman et les épices entières et faites frire 3 minutes — la pâte s'assombrira et la cuisine sentira la cannelle, la cardamome et le cumin grillé ; cette éclosion précoce des épices est ce qui donne au Massaman sa profondeur d'accent persan. Ajoutez le bœuf et tournez-le dans la pâte jusqu'à ce que chaque morceau soit d'un rouge sombre, versez le lait de coco, la pâte de tamarin et les feuilles de combava, portez à frémissement à peine perceptible et faites braiser doucement à couvercle entrouvert pendant une heure et demie, en remuant toutes les 20 minutes — le bœuf est prêt quand il cède facilement à la cuillère mais garde encore sa forme. Glissez-y les pommes de terre, les oignons et les cacahuètes et poursuivez à découvert encore 30 minutes, jusqu'à ce que les pommes de terre soient tendres et que la sauce ait épaissi en un brun brillant et profond ; incorporez la sauce poisson et le sucre de palme à la fin, en équilibrant le triangle salé-sucré-acide jusqu'à un goût profond et rond, ni trop sucré ni trop vif. Laissez reposer hors du feu 10 minutes, puis servez dans des bols peu profonds avec du riz jasmin, parsemé de quelques cacahuètes concassées — le Massaman est le curry thaï qui gagne en profondeur la nuit, et les restes sont meilleurs le lendemain.",

'de': "Geben Sie die Kokoscreme in einen schweren Topf bei mittlerer Hitze und lassen Sie sie 5 Minuten unter Rühren köcheln, bis das Öl austritt und die Creme glänzend und leicht körnig wirkt. Geben Sie die Massaman-Paste und die ganzen Gewürze dazu und braten Sie 3 Minuten — die Paste wird dunkler und die Küche wird nach Zimt, Kardamom und geröstetem Kreuzkümmel duften; diese frühe Entfaltung der Gewürze ist es, was Massaman seine persisch geprägte Tiefe gibt. Geben Sie das Rindfleisch hinzu und wenden Sie es in der Paste, bis jedes Stück dunkelrot überzogen ist, gießen Sie die Kokosmilch, die Tamarindenpaste und die Kaffirlimettenblätter an, bringen Sie alles zum sanften Köcheln und schmoren Sie bei nur leicht geöffnetem Deckel anderthalb Stunden, alle 20 Minuten umrühren — das Fleisch ist fertig, wenn es dem Löffel leicht nachgibt, aber noch seine Form hält. Geben Sie die Kartoffeln, Zwiebeln und Erdnüsse hinein und garen Sie weitere 30 Minuten offen, bis die Kartoffeln weich und die Sauce zu einem glänzend tiefen Braun eingedickt sind; rühren Sie zum Schluss Fischsauce und Palmzucker ein und balancieren Sie das Dreieck aus salzig, süß und sauer aus, bis der Geschmack tief und rund ist, weder zu süß noch zu scharf. Lassen Sie alles 10 Minuten vom Herd ruhen, servieren Sie dann in flachen Schalen mit Jasminreis, mit ein paar zerkleinerten Erdnüssen darüber gestreut — Massaman ist das Thai-Curry, das über Nacht an Tiefe gewinnt, und Reste schmecken am nächsten Tag besser.",

'pt': "Deite as natas de coco numa panela pesada em lume médio e deixe cozinhar 5 minutos, mexendo, até o óleo se separar e as natas ficarem brilhantes e ligeiramente granulosas. Junte a pasta Massaman e as especiarias inteiras e frite 3 minutos — a pasta vai escurecer e a cozinha vai cheirar a canela, cardamomo e cominho torrado; esta floração precoce das especiarias é o que dá ao Massaman a sua profundidade de inflexão persa. Junte a carne e envolva-a na pasta até cada pedaço estar de um vermelho escuro, verta o leite de coco, a pasta de tamarindo e as folhas de lima kaffir, leve a uma fervura quase imperceptível e estufe brandamente com a tampa entreaberta durante uma hora e meia, mexendo a cada 20 minutos — a carne está pronta quando cede facilmente à colher mas ainda mantém a forma. Deslize as batatas, as cebolas e os amendoins e continue a cozinhar destapado mais 30 minutos, até as batatas estarem tenras e o molho ter engrossado num castanho brilhante e profundo; no fim, envolva o molho de peixe e o açúcar de palma, equilibrando o triângulo salgado-doce-ácido até o sabor ser profundo e redondo, nem demasiado doce nem demasiado afiado. Deixe descansar fora do lume 10 minutos, depois sirva em taças fundas com arroz jasmim, polvilhado com alguns amendoins esmagados por cima — o Massaman é o caril tailandês que ganha profundidade durante a noite, e qualquer sobra sabe melhor no dia seguinte.",

'ru': "Положите кокосовые сливки в тяжёлую кастрюлю на среднем огне и томите 5 минут, помешивая, пока масло не отделится, а сливки не станут глянцевыми и слегка зернистыми. Добавьте пасту Массаман и целые специи и обжаривайте 3 минуты — паста потемнеет, а кухня запахнет корицей, кардамоном и поджаренной зирой; это раннее раскрытие специй и даёт Массаману его глубину персидского отзвука. Добавьте говядину и переверните её в пасте, пока каждый кусок не покроется тёмно-красным, влейте кокосовое молоко, тамариндовую пасту и листья каффирского лайма, доведите до едва заметного кипения и тушите с приоткрытой крышкой полтора часа, помешивая каждые 20 минут — говядина готова, когда легко поддаётся ложке, но ещё держит форму. Добавьте картофель, лук и арахис и продолжайте варить без крышки ещё 30 минут, пока картофель не станет мягким, а соус не загустеет до глянцевого насыщенно-коричневого; в конце вмешайте рыбный соус и пальмовый сахар, балансируя треугольник солёное-сладкое-кислое, пока вкус не станет глубоким и округлым, не слишком сладким и не слишком резким. Дайте отдохнуть 10 минут вне огня, затем подавайте в неглубоких мисках с жасминовым рисом, посыпав сверху раздавленным арахисом — Массаман это тайский карри, который за ночь набирает глубину, и остатки на следующий день вкуснее.",

'ar': "ضع كريمة جوز الهند في قدر ثقيل على نار متوسطة واتركها تطهو 5 دقائق مع التحريك، حتى ينفصل الزيت وتبدو الكريمة لامعة وحبيبية قليلاً. أضف معجون الماسامان والبهارات الكاملة واقلِها 3 دقائق — سيغمق المعجون وستفوح من المطبخ رائحة القرفة والهيل والكمون المحمّص؛ هذا الإزهار المبكّر للبهارات هو ما يمنح الماسامان عمقه ذا اللمسة الفارسية. أضف لحم البقر وقلّبه في المعجون حتى تتلوّن كل قطعة بالأحمر الداكن، اسكب حليب جوز الهند ومعجون التمر الهندي وأوراق الليمون الكافير، أوصلها إلى غليان بالكاد محسوس، واطبخها برفق مع غطاء نصف مغلق ساعة ونصف مع التحريك كل 20 دقيقة — ينضج اللحم حين يستجيب بسهولة للملعقة لكنه يحتفظ بشكله. أضف البطاطس والبصل والفول السوداني واستمر في الطهي مكشوفاً 30 دقيقة إضافية، حتى تنضج البطاطس وتثخن الصلصة إلى بنيّ غامق لامع؛ حرّك صلصة السمك وسكر النخيل في النهاية، موازناً مثلث المالح-الحلو-الحامض حتى يصبح الطعم عميقاً ومستديراً، لا حلوًا أكثر من اللازم ولا حادًا. أرحه بعيداً عن النار 10 دقائق، ثم قدّمه في صحون ضحلة مع أرز الياسمين، مع نثرة من الفول السوداني المهروس فوقه — الماسامان هو الكاري التايلاندي الذي يكتسب عمقاً ليلة كاملة، وأي بقايا يكون طعمها أفضل في اليوم التالي.",

'zh': "把椰浆放入厚锅中火加热，煮 5 分钟、间或搅拌，直到油分离、椰浆变得油亮、略呈颗粒。加入玛沙曼咖喱酱和整粒香料，炒 3 分钟——咖喱酱会变深，整个厨房会飘出肉桂、豆蔻和烤孜然的香气；这一步早早“激活”香料，正是玛沙曼那种带波斯气息厚度的来源。加入牛肉块，在酱里翻动，让每一块都裹上深红色，倒入椰奶、罗望子膏和卡菲尔青柠叶，慢慢加热到刚刚冒泡，盖子半盖小火炖 1 小时 30 分钟，每 20 分钟搅一次——当一压就开但还能保持形状时，牛肉就好了。加入土豆块、洋葱和花生，不盖锅继续煮 30 分钟，直到土豆软透、酱汁收成油亮的深棕色；最后加入鱼露和棕榈糖，慢慢平衡咸-甜-酸的三角，直到味道既深又圆，不过甜也不刺。离火静置 10 分钟，然后盛在浅口碗里配茉莉香米饭，顶上撒一点拍碎的花生——玛沙曼是泰国咖喱里那种隔夜更好吃的版本，剩下的明天会更香。",

'ja': "厚手の鍋にココナッツクリームを入れて中火で 5 分、ときどき混ぜながら煮詰める — 油が浮き出し、クリームが艶を帯び、わずかにざらつき始めるまで。マッサマンペーストとホールスパイスを加えて 3 分炒める — ペーストは色を深め、台所はシナモン、カルダモン、焙煎クミンの香りに包まれる；スパイスを早めに花開かせるこの工程こそ、マッサマンに与えられるペルシャ的な深みの源だ。牛肉を加えてペーストにくぐらせ、表面が暗い赤に染まるまで返したら、ココナッツミルク、タマリンドペースト、コブミカンの葉を注ぎ、ぎりぎり沸騰しない火加減にして、蓋を少し開けたまま 1 時間半、20 分ごとにかき混ぜながら煮込む — スプーンで押すと簡単にほどけるが形は残っている、それが牛肉の合図。じゃがいも、玉ねぎ、ピーナッツを加え、蓋を取ったまま 30 分、じゃがいもが柔らかく、ソースが艶のある濃い茶色になるまで煮詰め、最後にナンプラーとパームシュガーを加えて塩味・甘味・酸味の三角を、深くまろやかな味になるまで整える — 甘すぎず、刺し過ぎず。火から下ろし 10 分休ませ、浅めの器にジャスミンライスを添えて盛り、上に砕いたピーナッツを少し散らす — マッサマンは一晩寝かせて深みを増すタイカレーで、翌日の方が美味い。",

'tr': "Hindistan cevizi kremasını ağır bir tencerede orta ateşte koy ve 5 dakika, karıştırarak, yağ ayrılana ve krema parlak ve hafif tanecikli görünene dek pişir. Massaman ezmesini ve bütün baharatları ekle ve 3 dakika kavur — ezme koyulaşacak, mutfak tarçın, kakule ve kavrulmuş kimyon kokacak; baharatların bu erken açılması, Massaman'a o Pers etkili derinliği veren şeydir. Dana etini ekle ve ezmenin içinde her parçanın koyu kırmızıya dönmesine kadar çevir, hindistan cevizi sütünü, demirhindi ezmesini ve kaffir limon yapraklarını dök, neredeyse algılanamayan bir kaynamaya getir ve kapağı aralık olarak bir buçuk saat, her 20 dakikada bir karıştırarak yavaşça pişir — et, kaşığa kolayca boyun eğdiği ama hâlâ şeklini koruduğu noktada hazırdır. Patatesleri, soğanları ve fıstığı içine kaydır ve kapaksız 30 dakika daha pişir — patatesler yumuşayıp sos parlak, koyu kahverengiye dönene dek; sonda balık sosunu ve palmiye şekerini katarak tuzlu-tatlı-ekşi üçgenini dengele, derin ve yuvarlak bir tat, ne aşırı tatlı ne fazla keskin. Ocaktan al ve 10 dakika dinlendir, sonra sığ kâselere jasmin pirinciyle birlikte koy, üstüne birkaç ezilmiş fıstık serpiştir — Massaman, bir gecede derinleşen Tay körisidir, artıklar ertesi gün daha iyi olur.",

'it': "Versate la crema di cocco in una pentola pesante a fuoco medio e fatela cuocere per 5 minuti, mescolando, finché l'olio non si separa e la crema non appare lucida e leggermente granulosa. Aggiungete la pasta Massaman e le spezie intere e fate soffriggere 3 minuti — la pasta si scurirà e la cucina sentirà di cannella, cardamomo e cumino tostato; questo schiudersi precoce delle spezie è ciò che dà al Massaman la sua profondità di inflessione persiana. Unite la carne e rigirate i pezzi nella pasta finché ognuno non è rosso scuro, versate il latte di cocco, la pasta di tamarindo e le foglie di lime kaffir, portate a un sobbollire appena percettibile e brasate dolcemente con il coperchio socchiuso per un'ora e mezza, mescolando ogni 20 minuti — la carne è pronta quando cede facilmente al cucchiaio ma mantiene ancora la forma. Fate scivolare le patate, le cipolle e le arachidi nella pentola e continuate a cuocere scoperto per altri 30 minuti, finché le patate non sono tenere e il sugo non si è addensato in un marrone lucido e profondo; unite la salsa di pesce e lo zucchero di palma alla fine, bilanciando il triangolo salato-dolce-acido finché il gusto non risulta profondo e rotondo, né troppo dolce né troppo pungente. Lasciate riposare fuori dal fuoco 10 minuti, poi servite in ciotole basse con riso jasmine, con qualche arachide schiacciata sopra — il Massaman è il curry thailandese che guadagna profondità in una notte, e gli avanzi sono migliori il giorno dopo.",

'ko': "두꺼운 냄비에 코코넛 크림을 넣고 중불에서 5분간, 가끔 저어가며, 기름이 분리되고 크림이 윤기 있고 살짝 알갱이가 보일 때까지 졸인다. 마사만 페이스트와 통향신료를 넣고 3분간 볶는다 — 페이스트는 색이 짙어지고, 부엌에는 시나몬, 카다멈, 볶은 쿠민의 향이 가득 찰 것이다; 이 향신료를 일찍 피워내는 단계가 마사만에 페르시아풍의 깊이를 주는 핵심이다. 소고기를 넣고 페이스트 안에서 굴려 모든 면이 진한 붉은색이 될 때까지 코팅한 다음, 코코넛 밀크, 타마린드 페이스트, 카피르 라임 잎을 부어 거의 느껴지지 않을 정도의 약한 끓음으로 만들고, 뚜껑을 살짝 열어둔 채 1시간 30분, 20분마다 저어가며 부드럽게 졸인다 — 숟가락에 쉽게 풀리지만 모양은 유지하는 시점이 소고기 완성이다. 감자, 양파, 땅콩을 넣고 뚜껑 없이 30분 더, 감자가 부드러워지고 소스가 윤기 있는 진한 갈색으로 농축될 때까지 끓인 다음, 마지막에 피쉬 소스와 팜 슈가를 넣고, 짠맛–단맛–신맛의 삼각형을 깊고 둥근 맛이 될 때까지 균형 잡는다 — 너무 달지도, 너무 날카롭지도 않게. 불에서 내려 10분 쉬게 한 뒤, 얕은 그릇에 자스민 라이스와 함께 내고, 위에 부순 땅콩을 조금 흩뿌린다 — 마사만은 하룻밤 사이에 깊이가 자라는 태국식 커리이며, 남은 분량은 다음 날이 더 맛있다.",

'hi': "नारियल क्रीम को एक भारी बर्तन में मध्यम आँच पर डालें और 5 मिनट तक चलाते हुए तब तक पकाएँ जब तक तेल अलग न हो जाए और क्रीम चमकदार और हलकी दानेदार न लगे। मसामन पेस्ट और साबुत मसाले डालें और 3 मिनट भूनें — पेस्ट गहरा होगा और रसोई से दालचीनी, इलायची और भुने जीरे की ख़ुशबू उठेगी; मसालों का यह जल्दी खिल जाना ही मसामन को उसका फ़ारसी-झुकाव वाला गहरा स्वाद देता है। बीफ़ डालें और हर टुकड़े को पेस्ट में लपेट कर गहरे लाल रंग का होने तक चलाएँ, फिर नारियल का दूध, इमली पेस्ट और कैफिर लाइम के पत्ते डालें, बिल्कुल हल्की उबाल पर लाएँ, और ढक्कन थोड़ा खुला रख कर 1 घंटा 30 मिनट तक, हर 20 मिनट पर चलाते हुए, धीमी आँच पर पकाएँ — बीफ़ तब तैयार है जब चम्मच के दबाव से आसानी से अलग हो जाए पर आकार बनाए रखे। आलू, प्याज़ और मूँगफली डालें और बिना ढके 30 मिनट और पकाएँ, जब तक आलू नर्म और ग्रेवी चमकदार गहरे भूरे रंग की न हो जाए; फिश सॉस और ताड़ की चीनी आख़िर में डालें, नमकीन-मीठा-खट्टा वाला त्रिकोण ऐसा संतुलित करें कि स्वाद गहरा और गोलमटोल लगे, न ज़्यादा मीठा, न ज़्यादा तीखा। आँच से उतार कर 10 मिनट आराम दें, फिर उथले कटोरों में चमेली चावल के साथ परोसें, ऊपर कुछ कुटी मूँगफली छिड़कें — मसामन वो थाई करी है जो रात भर रखने पर और गहरी हो जाती है, और अगले दिन और भी अच्छी लगती है।",
}

FEATURE_CARDS = {
'en': '[{icon:"🌶️", t:"Persian-inflected depth", d:"Cinnamon, cardamom, cumin — Muslim-trader heritage in a Thai pot"}, {icon:"🥥", t:"Bloom the cream first", d:"Crack the oil from the coconut before the paste hits"}, {icon:"⏱️", t:"90-minute low simmer", d:"Beef soft but still holds shape; stir every 20"}, {icon:"🌙", t:"Better tomorrow", d:"Tastes deeper overnight — the leftovers are the prize"}]',
'ro': '[{icon:"🌶️", t:"Profunzime de inspirație persană", d:"Scorțișoară, cardamom, chimion — moștenirea negustorilor musulmani"}, {icon:"🥥", t:"Înflorește smântâna mai întâi", d:"Scoate uleiul din cocos înainte să intre pasta"}, {icon:"⏱️", t:"90 minute la foc mic", d:"Carne fragedă dar care își păstrează forma; amestec la 20 min"}, {icon:"🌙", t:"Mai bun mâine", d:"Capătă profunzime peste noapte — resturile sunt premiul"}]',
'es': '[{icon:"🌶️", t:"Profundidad de inflexión persa", d:"Canela, cardamomo, comino — herencia de comerciantes musulmanes"}, {icon:"🥥", t:"Floración previa de la crema", d:"Separa el aceite del coco antes de añadir la pasta"}, {icon:"⏱️", t:"90 minutos a fuego bajo", d:"Carne tierna pero entera; remover cada 20"}, {icon:"🌙", t:"Mejor mañana", d:"Gana profundidad de un día para otro — el resto es el premio"}]',
'fr': '[{icon:"🌶️", t:"Profondeur d\'accent persan", d:"Cannelle, cardamome, cumin — héritage des marchands musulmans"}, {icon:"🥥", t:"Faire éclore la crème d\'abord", d:"Séparer l\'huile du coco avant que la pâte n\'entre"}, {icon:"⏱️", t:"90 minutes à feu doux", d:"Bœuf tendre mais qui garde sa forme ; remuer toutes les 20"}, {icon:"🌙", t:"Meilleur demain", d:"Gagne en profondeur la nuit — les restes sont le prix"}]',
'de': '[{icon:"🌶️", t:"Persisch geprägte Tiefe", d:"Zimt, Kardamom, Kreuzkümmel — Erbe der muslimischen Händler"}, {icon:"🥥", t:"Sahne zuerst entfalten", d:"Öl aus der Kokoscreme reißen, bevor die Paste hineinkommt"}, {icon:"⏱️", t:"90 Minuten sanft schmoren", d:"Rind weich, aber Form bleibt; alle 20 Minuten rühren"}, {icon:"🌙", t:"Morgen besser", d:"Gewinnt über Nacht an Tiefe — die Reste sind der Gewinn"}]',
'pt': '[{icon:"🌶️", t:"Profundidade de inflexão persa", d:"Canela, cardamomo, cominho — herança dos comerciantes muçulmanos"}, {icon:"🥥", t:"Florescer as natas primeiro", d:"Separar o óleo do coco antes de a pasta entrar"}, {icon:"⏱️", t:"90 minutos em lume brando", d:"Carne tenra mas com forma; mexer a cada 20"}, {icon:"🌙", t:"Melhor amanhã", d:"Ganha profundidade durante a noite — as sobras são o prémio"}]',
'ru': '[{icon:"🌶️", t:"Персидская глубина", d:"Корица, кардамон, зира — наследие мусульманских торговцев"}, {icon:"🥥", t:"Сначала раскрыть сливки", d:"Выпарить масло из кокоса до того, как войдёт паста"}, {icon:"⏱️", t:"90 минут тихого томления", d:"Говядина мягкая, но держит форму; помешивать каждые 20"}, {icon:"🌙", t:"Завтра лучше", d:"За ночь набирает глубину — остатки и есть приз"}]',
'ar': '[{icon:"🌶️", t:"عمق ذو لمسة فارسية", d:"قرفة، هيل، كمون — إرث التجار المسلمين"}, {icon:"🥥", t:"أزهر الكريمة أولاً", d:"اكسر الزيت من جوز الهند قبل أن يدخل المعجون"}, {icon:"⏱️", t:"90 دقيقة على نار هادئة", d:"اللحم طري لكنه يحتفظ بشكله؛ حرّك كل 20 دقيقة"}, {icon:"🌙", t:"أفضل غداً", d:"يكتسب عمقاً ليلة كاملة — البقايا هي الجائزة"}]',
'zh': '[{icon:"🌶️", t:"波斯气息的厚度", d:"肉桂、豆蔻、孜然——穆斯林商人的遗产"}, {icon:"🥥", t:"先把椰浆“激活”", d:"在咖喱酱下锅前先逼出椰浆里的油"}, {icon:"⏱️", t:"小火炖 90 分钟", d:"牛肉酥软但还保持形状；每 20 分钟搅一次"}, {icon:"🌙", t:"明天更好", d:"隔夜风味更深——剩下的才是奖赏"}]',
'ja': '[{icon:"🌶️", t:"ペルシャ風の深み", d:"シナモン、カルダモン、クミン — ムスリム商人の遺産"}, {icon:"🥥", t:"まずクリームを開かせる", d:"ペーストを入れる前にココナッツから油を出す"}, {icon:"⏱️", t:"90 分の弱火煮込み", d:"牛肉は柔らかいが形は残る；20 分ごとに混ぜる"}, {icon:"🌙", t:"明日の方が美味い", d:"一晩で深みが増す — 残り物が本番"}]',
'tr': '[{icon:"🌶️", t:"Pers etkili derinlik", d:"Tarçın, kakule, kimyon — Müslüman tüccarların mirası"}, {icon:"🥥", t:"Önce kremayı aç", d:"Ezme girmeden hindistan cevizinden yağı çıkar"}, {icon:"⏱️", t:"90 dakika kısık ateşte", d:"Et yumuşak ama şeklini korur; 20 dakikada bir karıştır"}, {icon:"🌙", t:"Yarın daha iyi", d:"Bir gecede derinleşir — artıklar asıl ödüldür"}]',
'it': '[{icon:"🌶️", t:"Profondità di inflessione persiana", d:"Cannella, cardamomo, cumino — eredità dei mercanti musulmani"}, {icon:"🥥", t:"Far sbocciare la crema prima", d:"Separare l\'olio dal cocco prima che entri la pasta"}, {icon:"⏱️", t:"90 minuti di sobbollire", d:"Carne morbida ma forma intera; mescolare ogni 20"}, {icon:"🌙", t:"Migliore domani", d:"Guadagna profondità in una notte — gli avanzi sono il premio"}]',
'ko': '[{icon:"🌶️", t:"페르시아풍의 깊이", d:"시나몬, 카다멈, 쿠민 — 무슬림 상인의 유산"}, {icon:"🥥", t:"크림을 먼저 피우기", d:"페이스트가 들어가기 전에 코코넛에서 기름을 분리"}, {icon:"⏱️", t:"90분 약불 졸이기", d:"소고기 부드럽지만 형태 유지; 20분마다 저어주기"}, {icon:"🌙", t:"내일이 더 맛있다", d:"하룻밤 사이 깊이가 자란다 — 남은 것이 진짜"}]',
'hi': '[{icon:"🌶️", t:"फ़ारसी-झुकाव की गहराई", d:"दालचीनी, इलायची, जीरा — मुस्लिम व्यापारियों की विरासत"}, {icon:"🥥", t:"पहले क्रीम खिलाओ", d:"पेस्ट डालने से पहले नारियल से तेल अलग करो"}, {icon:"⏱️", t:"90 मिनट धीमी आँच", d:"बीफ़ नर्म पर आकार बना रहे; हर 20 मिनट पर चलाएँ"}, {icon:"🌙", t:"कल बेहतर", d:"रात भर में और गहरी हो जाती है — बचा हुआ ही असली इनाम"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*210,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)

fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 210 (Massaman): {rec_end-rec_start} → {len(new_recipe_block)} chars")
