#!/usr/bin/env python3
"""Rewrite recipe 206 (Palak Paneer): 11 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Bring a large pot of water to a boil, blanch the spinach for 90 seconds and transfer immediately to a bowl of ice water, then drain, squeeze gently and blend to a smooth purée with one of the green chillies and a few tablespoons of cold water. Heat a tablespoon of ghee in a wide pan and fry the paneer cubes over medium heat for 2–3 minutes per side until lightly gold, then lift onto paper or slip them into a bowl of warm salted water while everything else cooks. In the same pan add the remaining ghee and the cumin seeds and let them sizzle for 30 seconds, tip in the onion and cook 8–10 minutes until soft and golden at the edges, then add the ginger-garlic paste and the second slit green chilli and cook a minute more. Stir in the chopped tomato with the coriander, chilli powder, turmeric and a teaspoon of salt and cook 6–8 minutes until the masala is jammy and the oil starts to separate at the edges, then pour in the spinach purée and 100 ml of water, stir well and simmer gently for 5 minutes. Slide the paneer cubes into the gravy, swirl in the cream, crush the kasoori methi between your palms over the pan and sprinkle the garam masala, heat through for another 2 minutes, taste for salt, finish with julienned ginger on top, and serve with naan, paratha or basmati.",

'ro': "Adu o oală mare de apă la fiert, opărește spanacul 90 de secunde și transferă-l imediat într-un castron cu apă cu gheață, apoi scurge-l, stoarce-l ușor și blendează-l până la un piure neted împreună cu unul dintre ardeii verzi și câteva linguri de apă rece. Încălzește o lingură de ghee într-o tigaie largă și prăjește cuburile de paneer pe foc mediu 2–3 minute pe fiecare parte până sunt ușor aurii, apoi ridică-le pe o hârtie sau scufundă-le într-un bol cu apă caldă cu sare cât timp se gătește restul. În aceeași tigaie adaugă restul de ghee și semințele de chimion și las-le să sfârâie 30 de secunde, pune ceapa și gătește-o 8–10 minute până e moale și aurie la margini, apoi adaugă pasta de ghimbir-usturoi și al doilea ardei verde tăiat și gătește încă un minut. Adaugă roșia tocată cu coriandrul, pudra de chili, turmericul și o linguriță de sare și gătește 6–8 minute până când masala devine ca un dulceață și uleiul începe să se separe la margini, apoi toarnă piureul de spanac și 100 ml de apă, amestecă bine și fierbe blând 5 minute. Pune cuburile de paneer în sos, învârte smântâna, freacă kasoori methi între palme deasupra tigăii și presară garam masala, încălzește încă 2 minute, gustă pentru sare, finalizează cu ghimbir julienne deasupra și servește cu naan, paratha sau basmati.",

'es': "Lleva una olla grande de agua a ebullición, blanquea las espinacas 90 segundos y pásalas inmediatamente a un bol con agua helada, después escurre, exprime con suavidad y tritura hasta un puré liso con uno de los chiles verdes y unas cucharadas de agua fría. Calienta una cucharada de ghee en una sartén amplia y fríe los cubos de paneer a fuego medio 2–3 minutos por lado hasta que estén ligeramente dorados, después pásalos a papel o sumérgelos en un bol con agua templada salada mientras se cocina lo demás. En la misma sartén añade el resto del ghee y las semillas de comino y déjalas chisporrotear 30 segundos, incorpora la cebolla y cocínala 8–10 minutos hasta que esté blanda y dorada en los bordes, después añade la pasta de jengibre-ajo y el segundo chile verde cortado y cocina un minuto más. Incorpora el tomate picado con el cilantro, el chile en polvo, la cúrcuma y una cucharadita de sal y cocina 6–8 minutos hasta que la masala esté como mermelada y el aceite empiece a separarse en los bordes, después vierte el puré de espinacas y 100 ml de agua, remueve bien y deja cocer suavemente 5 minutos. Desliza los cubos de paneer al sazón, vierte la nata, frota el kasoori methi entre las palmas sobre la sartén y espolvorea el garam masala, calienta otros 2 minutos, prueba de sal, termina con jengibre en juliana por encima, y sirve con naan, paratha o basmati.",

'fr': "Portez une grande casserole d'eau à ébullition, blanchissez les épinards 90 secondes et plongez-les immédiatement dans un bol d'eau glacée, puis égouttez, pressez doucement et mixez en une purée lisse avec l'un des piments verts et quelques cuillères à soupe d'eau froide. Faites chauffer une cuillère à soupe de ghee dans une grande poêle et faites dorer les cubes de paneer à feu moyen 2 à 3 minutes par face jusqu'à ce qu'ils soient légèrement dorés, puis sortez-les sur du papier ou plongez-les dans un bol d'eau tiède salée pendant que tout le reste cuit. Dans la même poêle ajoutez le reste de ghee et les graines de cumin et laissez-les crépiter 30 secondes, versez l'oignon et faites-le cuire 8 à 10 minutes jusqu'à ce qu'il soit fondant et doré sur les bords, puis ajoutez la pâte gingembre-ail et le deuxième piment vert fendu et faites cuire une minute de plus. Incorporez la tomate hachée avec la coriandre, le piment en poudre, le curcuma et une cuillère à café de sel et faites cuire 6 à 8 minutes jusqu'à ce que la masala soit comme une confiture et que l'huile commence à se séparer sur les bords, puis versez la purée d'épinards et 100 ml d'eau, mélangez bien et laissez frémir doucement 5 minutes. Glissez les cubes de paneer dans la sauce, ajoutez la crème, écrasez le kasoori methi entre vos paumes au-dessus de la poêle et saupoudrez le garam masala, faites chauffer encore 2 minutes, rectifiez le sel, terminez par le gingembre en julienne sur le dessus, et servez avec naan, paratha ou basmati.",

'de': "Bringen Sie einen großen Topf Wasser zum Kochen, blanchieren Sie den Spinat 90 Sekunden und schrecken Sie ihn sofort in einer Schüssel mit Eiswasser ab, dann abgießen, leicht ausdrücken und mit einer der grünen Chilis und ein paar Esslöffeln kaltem Wasser zu einem glatten Püree mixen. Erhitzen Sie einen Esslöffel Ghee in einer breiten Pfanne und braten Sie die Paneerwürfel bei mittlerer Hitze 2–3 Minuten pro Seite leicht goldgelb, dann auf Küchenpapier abtropfen lassen oder in eine Schüssel mit warmem Salzwasser legen, während der Rest gart. In derselben Pfanne das restliche Ghee und die Kreuzkümmelsamen hinzufügen und 30 Sekunden aufzischen lassen, die Zwiebel hineingeben und 8–10 Minuten weich und an den Rändern goldgelb braten, dann die Ingwer-Knoblauch-Paste und die zweite eingeschnittene grüne Chili dazugeben und eine Minute länger garen. Die gehackte Tomate mit Koriander, Chilipulver, Kurkuma und einem Teelöffel Salz einrühren und 6–8 Minuten kochen, bis die Masala marmeladenartig wird und sich das Öl an den Rändern abzusetzen beginnt, dann das Spinatpüree und 100 ml Wasser angießen, gut umrühren und 5 Minuten sanft köcheln lassen. Schieben Sie die Paneerwürfel in die Sauce, rühren Sie die Sahne ein, zerreiben Sie das Kasoori Methi zwischen den Handflächen über der Pfanne und streuen Sie das Garam Masala darüber, erhitzen Sie weitere 2 Minuten, schmecken Sie mit Salz ab, garnieren Sie mit Ingwer-Julienne obenauf, und servieren Sie mit Naan, Paratha oder Basmati.",

'pt': "Leve uma panela grande de água a ferver, escalde os espinafres 90 segundos e transfira-os de imediato para uma tigela com água gelada, depois escorra, esprema com cuidado e bata num puré liso com um dos piri-piris verdes e algumas colheres de água fria. Aqueça uma colher de sopa de ghee numa frigideira ampla e frite os cubos de paneer em lume médio 2–3 minutos de cada lado até estarem ligeiramente dourados, depois transfira para papel ou mergulhe-os numa tigela com água morna salgada enquanto se cozinha o resto. Na mesma frigideira junte o resto do ghee e as sementes de cominho e deixe-as estalar 30 segundos, deite a cebola e cozinhe 8–10 minutos até estar macia e dourada nas bordas, depois junte a pasta de gengibre-alho e o segundo piri-piri verde cortado e cozinhe mais um minuto. Junte o tomate picado com os coentros, o piri-piri em pó, o açafrão-da-índia e uma colher de chá de sal e cozinhe 6–8 minutos até a masala ficar quase em geleia e o óleo começar a separar-se nas bordas, depois verta o puré de espinafres e 100 ml de água, mexa bem e deixe cozer suavemente 5 minutos. Deslize os cubos de paneer no molho, envolva as natas, esfregue o kasoori methi entre as palmas por cima da frigideira e polvilhe o garam masala, aqueça mais 2 minutos, prove de sal, finalize com gengibre em juliana por cima, e sirva com naan, paratha ou basmati.",

'ru': "Доведите большую кастрюлю воды до кипения, бланшируйте шпинат 90 секунд и сразу переложите в миску с ледяной водой, затем слейте, аккуратно отожмите и пюрируйте до гладкости вместе с одним из зелёных перцев и парой ложек холодной воды. Разогрейте столовую ложку ги в широкой сковороде и обжарьте кубики панира на среднем огне 2–3 минуты с каждой стороны до лёгкой золотистости, затем выложите на бумагу или опустите в миску с тёплой подсоленной водой, пока готовится остальное. В ту же сковороду добавьте оставшееся ги и семена зиры и дайте им подсиплеть 30 секунд, всыпьте лук и обжаривайте 8–10 минут до мягкости и золотистых краёв, затем добавьте пасту имбирь-чеснок и второй надрезанный зелёный перец и готовьте ещё минуту. Вмешайте нарезанный помидор с кориандром, чилийским порошком, куркумой и чайной ложкой соли и готовьте 6–8 минут, пока масала не станет джемообразной и масло не начнёт отделяться по краям, затем влейте пюре шпината и 100 мл воды, хорошо размешайте и потомите 5 минут на лёгком огне. Опустите кубики панира в соус, вмешайте сливки, разотрите касури мети между ладоней над сковородой и присыпьте гарам масалой, прогрейте ещё 2 минуты, попробуйте на соль, завершите имбирной соломкой сверху и подавайте с наном, паратхой или басмати.",

'ar': "أوصِل قدراً كبيراً من الماء إلى الغليان، اسلق السبانخ 90 ثانية وانقلها فوراً إلى وعاء ماء مثلج، ثم صفّها واعصرها برفق واخفقها إلى مهروس ناعم مع إحدى الفلفلتين الخضراوين وبضع ملاعق من الماء البارد. سخّن ملعقة كبيرة من السمن في مقلاة واسعة وحمّر مكعبات البانير على نار متوسطة 2–3 دقائق لكل جهة حتى تذهب إلى ذهبي خفيف، ثم انقلها على ورق أو اغمسها في وعاء ماء دافئ مالح بينما يطهى الباقي. في المقلاة نفسها أضف بقية السمن وبذور الكمون واتركها تطقطق 30 ثانية، أدخل البصل واطبخه 8–10 دقائق حتى يصبح طرياً وذهبي الحواف، ثم أضف عجينة الزنجبيل-الثوم والفلفل الأخضر الثاني المشقوق واطبخ دقيقة إضافية. حرّك الطماطم المفرومة مع الكزبرة ومسحوق الفلفل والكركم وملعقة صغيرة من الملح واطبخ 6–8 دقائق حتى يصبح المعجون كالمربى ويبدأ الزيت بالانفصال عند الأطراف، ثم اسكب مهروس السبانخ و 100 مل من الماء، حرّك جيداً واطهُ برفق 5 دقائق. أنزل مكعبات البانير في الصلصة، اسكب الكريمة، افرك الكسوري ميثي بين راحتيك فوق المقلاة ورشّ الجارام مسالا، سخّن لـ 2 دقيقة أخرى، تذوّق الملح، أنهِ بالزنجبيل المقطع جوليان فوقه، وقدّمه مع الخبز النان أو الباراثا أو الأرز البسمتي.",

'zh': "把一大锅水烧开，将菠菜焯 90 秒后立刻转入一碗冰水中，沥干、轻轻挤干水分，再与其中一根青辣椒和几汤匙凉水一起打成顺滑的菠菜泥。在一只宽锅中烧热一汤匙酥油，把帕尼尔奶酪小块在中火上每面煎 2–3 分钟至浅金色，捞出放在纸上，或者把它们泡进一碗温盐水里，等其他配料煮好再说。同一只锅里加入剩下的酥油和孜然籽，让它们爆香 30 秒，下洋葱炒 8–10 分钟，至变软且边缘金黄，再加入姜蒜泥和第二根剖开的青辣椒，再炒一分钟。加入切碎的番茄、香菜末、辣椒粉、姜黄和一茶匙盐，炒 6–8 分钟，直到马萨拉变得果酱般浓稠、油从边缘开始析出，然后倒入菠菜泥和 100 毫升水，搅匀，轻火炖 5 分钟。把帕尼尔小块滑入酱汁中，淋入奶油，把卡苏里葛缕子在掌心揉碎撒入锅里，再撒上葛兰玛萨拉，再加热 2 分钟，尝咸淡，最后顶上摆一小把姜丝，配上 naan、paratha 或巴斯马蒂米饭享用。",

'ja': "大鍋にたっぷりの湯を沸かし、ほうれん草を 90 秒湯がいてすぐに氷水のボウルに移し、湯切りして軽く絞り、青唐辛子の 1 本と冷水大さじ数杯と共に滑らかなピューレにする。広めのフライパンに大さじ 1 のギーを熱し、パニールのキューブを中火で各面 2〜3 分、軽く金色になるまで焼き、紙にあげるか、温めた塩水のボウルに浸して残りを調理する間キープしておく。同じフライパンに残りのギーとクミンシードを入れて 30 秒香り立たせ、玉ねぎを入れて 8〜10 分、しんなりして縁が金色になるまで炒め、ジンジャー・ガーリックペーストと 2 本目の切り込みを入れた青唐辛子を加えてさらに 1 分炒める。刻んだトマトをコリアンダー、チリパウダー、ターメリック、小さじ 1 の塩と共に入れて 6〜8 分、マサラがジャム状になり、縁から油が分離し始めるまで炒め、ほうれん草のピューレと水 100 ml を加え、よく混ぜて穏やかに 5 分煮る。パニールのキューブをソースに滑り込ませ、生クリームを回し入れ、カスリメティを手のひらで揉んでフライパンに振り入れ、ガラムマサラを散らし、さらに 2 分加熱、塩を見て、千切り生姜をトップに添え、ナン、パラタ、またはバスマティライスと共に供する。",

'tr': "Büyük bir tencerede su kaynat, ıspanağı 90 saniye haşla ve hemen bir kâse buzlu suya aktar, sonra süz, hafifçe sık ve yeşil biberlerden biri ve birkaç yemek kaşığı soğuk suyla pürüzsüz bir pürede çek. Geniş bir tavada bir yemek kaşığı ghee'yi ısıt ve paneer küplerini orta ateşte her tarafından 2–3 dakika hafif altın rengine dönene kadar kızart, sonra kağıda al veya kalan kısım pişerken bir kâse ılık tuzlu suya daldır. Aynı tavaya kalan ghee'yi ve kimyon tohumlarını ekle ve 30 saniye cızırdat, soğanı içine dök ve 8–10 dakika yumuşayıp kenarları altın olana dek pişir, sonra zencefil-sarımsak ezmesini ve yarılmış ikinci yeşil biberi ekle ve bir dakika daha pişir. Doğranmış domatesi kişniş, biber tozu, zerdeçal ve bir çay kaşığı tuzla içine ekle ve masala reçel kıvamına gelene ve yağ kenarlardan ayrılmaya başlayana dek 6–8 dakika pişir, sonra ıspanak püresini ve 100 ml suyu ekle, iyice karıştır ve 5 dakika hafif ateşte pişir. Paneer küplerini sosa kaydır, kremayı içine dök, kasoori methi'yi avuçların arasında ovalayarak tavanın üstüne serp ve garam masala'yı ekle, 2 dakika daha ısıt, tuzunu kontrol et, jülyen kesilmiş zencefili üzerine koyarak bitir ve naan, paratha veya basmati pirinçle servis et.",

'it': "Portate a bollore una grossa pentola d'acqua, sbollentate gli spinaci 90 secondi e trasferiteli subito in una ciotola di acqua ghiacciata, poi scolateli, strizzateli delicatamente e frullateli a purea liscia con uno dei peperoncini verdi e qualche cucchiaio di acqua fredda. Scaldate un cucchiaio di ghee in una padella ampia e fate dorare i cubetti di paneer a fuoco medio per 2–3 minuti per lato fino a un colore dorato chiaro, poi trasferiteli su carta o immergeteli in una ciotola di acqua tiepida salata mentre cuoce il resto. Nella stessa padella aggiungete il resto del ghee e i semi di cumino e lasciateli sfrigolare 30 secondi, aggiungete la cipolla e cuocete 8–10 minuti finché non è morbida e dorata sui bordi, poi unite la pasta di zenzero-aglio e il secondo peperoncino verde inciso e cuocete ancora un minuto. Unite il pomodoro tritato con il coriandolo, la polvere di peperoncino, la curcuma e un cucchiaino di sale e cuocete 6–8 minuti finché la masala non è marmellatosa e l'olio non inizia a separarsi sui bordi, poi versate la purea di spinaci e 100 ml di acqua, mescolate bene e fate sobbollire dolcemente 5 minuti. Fate scivolare i cubetti di paneer nel sugo, aggiungete la panna a vortice, sbriciolate il kasoori methi fra le palme sopra la padella e cospargete il garam masala, riscaldate altri 2 minuti, regolate di sale, finite con zenzero a julienne in cima, e servite con naan, paratha o basmati.",

'ko': "큰 냄비에 물을 끓이고 시금치를 90초 데친 다음 즉시 얼음물에 옮기고, 물기를 빼고 가볍게 짜낸 뒤 청양고추 한 개와 찬물 몇 큰술을 함께 넣어 부드러운 퓌레로 갈아낸다. 넓은 팬에 기 1큰술을 데우고 파니르 큐브를 중불에서 한 면당 2–3분, 살짝 황금색이 될 때까지 굽고, 키친타월에 올리거나 다음 단계를 진행하는 동안 따뜻한 소금물 그릇에 담가둔다. 같은 팬에 남은 기와 쿠민 씨를 넣고 30초 동안 향을 일으키고, 양파를 넣어 8–10분 부드럽고 가장자리가 황금색이 될 때까지 볶은 뒤, 생강-마늘 페이스트와 두 번째 청양고추 (칼집 낸 것)를 넣고 1분 더 볶는다. 다진 토마토, 고수, 칠리 파우더, 강황, 소금 1작은술을 넣고 6–8분간 마살라가 잼처럼 끈적해지고 가장자리에서 기름이 분리되기 시작할 때까지 볶은 뒤, 시금치 퓌레와 물 100 ml를 부어 잘 섞고 5분간 부드럽게 끓인다. 파니르 큐브를 소스에 미끄러뜨려 넣고, 생크림을 두르고, 카수리 메티를 손바닥 사이에 비벼 팬 위에 뿌리고, 가람 마살라를 흩뿌린 다음 2분 더 가열하고, 소금 간을 보고, 위에 채 썬 생강을 올려 마무리하여 난, 파라타 또는 바스마티 라이스와 함께 낸다.",

'hi': "एक बड़े बर्तन में पानी उबालें, पालक को 90 सेकंड के लिए blanch करें और तुरंत बर्फ़ के पानी वाले बाउल में डालें, फिर छानें, हलके से निचोड़ें और एक हरी मिर्च तथा 2-3 बड़े चम्मच ठंडे पानी के साथ चिकनी प्यूरी में पीस लें। एक चौड़े पैन में 1 बड़ा चम्मच घी गरम करें और पनीर के टुकड़ों को मध्यम आँच पर 2–3 मिनट प्रत्येक तरफ़ हलके सुनहरे होने तक भूनें, फिर काग़ज़ पर निकालें या जब तक बाक़ी सब बन रहा है तब तक गुनगुने नमक वाले पानी में रखें। उसी पैन में बचा हुआ घी और जीरा डालें और 30 सेकंड चटकने दें, प्याज़ डालें और 8–10 मिनट तक नर्म और किनारों पर सुनहरा होने तक भूनें, फिर अदरक-लहसुन पेस्ट और चीरी हुई दूसरी हरी मिर्च डालें और 1 मिनट और भूनें। कटा टमाटर धनिया पाउडर, मिर्च पाउडर, हल्दी और 1 छोटा चम्मच नमक के साथ डालें और 6–8 मिनट तक भूनें जब तक मसाला जैम जैसा गाढ़ा न हो और तेल किनारों से अलग होने न लगे, फिर पालक प्यूरी और 100 मिली पानी डालें, अच्छे से मिलाएँ और 5 मिनट हलकी आँच पर पकाएँ। पनीर के टुकड़े ग्रेवी में डालें, क्रीम मिलाएँ, kasoori methi को हथेलियों के बीच रगड़कर पैन में डालें और गरम मसाला छिड़कें, 2 मिनट और गरम करें, नमक चखें, ऊपर से जुलिएन कटा अदरक डाल कर सजाएँ, और नान, पराठा या बासमती चावल के साथ परोसें।",
}

FEATURE_CARDS = {
'en': '[{icon:"❄️", t:"Ice bath = bright green", d:"Shock stops cooking instantly and locks the colour"}, {icon:"🧀", t:"Paneer kept tender", d:"Warm salted water holds the cubes soft until plating"}, {icon:"🍅", t:"Masala until oil splits", d:"6–8 minutes — the cue the tomato is fully cooked"}, {icon:"🌿", t:"Kasoori methi at the end", d:"Crushed between palms releases the dried-fenugreek lift"}]',
'ro': '[{icon:"❄️", t:"Baia de gheață = verde viu", d:"Oprește gătitul instant și fixează culoarea"}, {icon:"🧀", t:"Paneer păstrat moale", d:"Apa caldă cu sare ține cuburile fragede până la emplatare"}, {icon:"🍅", t:"Masala până se separă uleiul", d:"6–8 minute — indiciul că roșia e gătită complet"}, {icon:"🌿", t:"Kasoori methi la final", d:"Frecat între palme eliberează nota de schinduf uscat"}]',
'es': '[{icon:"❄️", t:"Baño de hielo = verde vivo", d:"Corta la cocción al instante y fija el color"}, {icon:"🧀", t:"Paneer tierno", d:"El agua templada salada mantiene los cubos suaves hasta servir"}, {icon:"🍅", t:"Masala hasta que se separe el aceite", d:"6–8 minutos — la señal de que el tomate está cocinado"}, {icon:"🌿", t:"Kasoori methi al final", d:"Aplastado entre las palmas libera el alza del fenogreco seco"}]',
'fr': '[{icon:"❄️", t:"Bain glacé = vert éclatant", d:"Stoppe la cuisson net et fige la couleur"}, {icon:"🧀", t:"Paneer tendre", d:"L\'eau tiède salée garde les cubes moelleux jusqu\'au dressage"}, {icon:"🍅", t:"Masala jusqu\'à séparation de l\'huile", d:"6–8 minutes — le signe que la tomate est bien cuite"}, {icon:"🌿", t:"Kasoori methi à la fin", d:"Écrasé entre les paumes libère le fenugrec sec"}]',
'de': '[{icon:"❄️", t:"Eisbad = leuchtend grün", d:"Stoppt das Garen sofort und fixiert die Farbe"}, {icon:"🧀", t:"Paneer bleibt weich", d:"Warmes Salzwasser hält die Würfel zart bis zum Anrichten"}, {icon:"🍅", t:"Masala bis das Öl austritt", d:"6–8 Minuten — das Signal, dass die Tomate fertig ist"}, {icon:"🌿", t:"Kasoori Methi am Ende", d:"Zwischen den Handflächen zerrieben gibt es den Bockshornklee-Lift frei"}]',
'pt': '[{icon:"❄️", t:"Banho de gelo = verde vivo", d:"Para a cozedura na hora e fixa a cor"}, {icon:"🧀", t:"Paneer macio", d:"A água morna salgada mantém os cubos suaves até ao prato"}, {icon:"🍅", t:"Masala até o óleo separar", d:"6–8 minutos — o sinal de que o tomate está pronto"}, {icon:"🌿", t:"Kasoori methi no fim", d:"Esfregado entre as palmas liberta o feno-grego seco"}]',
'ru': '[{icon:"❄️", t:"Ледяная баня = ярко-зелёный", d:"Мгновенно останавливает варку и фиксирует цвет"}, {icon:"🧀", t:"Панир остаётся мягким", d:"Тёплая подсоленная вода держит кубики нежными до подачи"}, {icon:"🍅", t:"Масала пока масло не отделится", d:"6–8 минут — сигнал, что томат готов"}, {icon:"🌿", t:"Касури мети в конце", d:"Растёртый между ладоней высвобождает сухой пажитник"}]',
'ar': '[{icon:"❄️", t:"حمام الثلج = أخضر زاهٍ", d:"يوقف الطهي فوراً ويثبت اللون"}, {icon:"🧀", t:"البانير يبقى طرياً", d:"الماء الدافئ المالح يحافظ على نعومة المكعبات حتى التقديم"}, {icon:"🍅", t:"المسالا حتى ينفصل الزيت", d:"6–8 دقائق — العلامة على أن الطماطم نضجت"}, {icon:"🌿", t:"كسوري ميثي في النهاية", d:"الفرك بين الراحتين يحرر الحلبة الجافة"}]',
'zh': '[{icon:"❄️", t:"冰水浴 = 鲜亮的绿", d:"瞬间停止烹饪、锁住颜色"}, {icon:"🧀", t:"帕尼尔保持嫩", d:"温盐水让奶酪块在装盘前都保持柔软"}, {icon:"🍅", t:"马萨拉直到油分离", d:"6–8 分钟 — 番茄完全熟透的信号"}, {icon:"🌿", t:"卡苏里葛缕子末尾加入", d:"掌心揉碎释放干胡芦巴的香气"}]',
'ja': '[{icon:"❄️", t:"氷水浴 = 鮮やかな緑", d:"加熱を即停止し色を閉じ込める"}, {icon:"🧀", t:"パニールは柔らかいまま", d:"温かい塩水でキューブを盛り付けまで柔らかく保つ"}, {icon:"🍅", t:"油が分離するまでマサラ", d:"6〜8 分 — トマトが完全に火入れされた合図"}, {icon:"🌿", t:"カスリメティは最後に", d:"手のひらでもむと、乾燥フェヌグリークの香りが立つ"}]',
'tr': '[{icon:"❄️", t:"Buz banyosu = parlak yeşil", d:"Pişirmeyi anında durdurur ve rengi sabitler"}, {icon:"🧀", t:"Paneer yumuşak kalır", d:"Ilık tuzlu su, küpleri sunuma kadar yumuşak tutar"}, {icon:"🍅", t:"Yağ ayrılana dek masala", d:"6–8 dakika — domatesin tamamen piştiğinin işareti"}, {icon:"🌿", t:"Sonda kasoori methi", d:"Avuç içinde ovularak kuru çemen otunu açar"}]',
'it': '[{icon:"❄️", t:"Bagno di ghiaccio = verde acceso", d:"Ferma la cottura all\'istante e fissa il colore"}, {icon:"🧀", t:"Paneer mantenuto morbido", d:"L\'acqua tiepida salata tiene i cubetti teneri fino all\'impiattamento"}, {icon:"🍅", t:"Masala finché l\'olio non si separa", d:"6–8 minuti — il segnale che il pomodoro è cotto"}, {icon:"🌿", t:"Kasoori methi alla fine", d:"Sbriciolato fra le palme libera il fieno greco essiccato"}]',
'ko': '[{icon:"❄️", t:"얼음물 = 선명한 초록", d:"즉시 가열을 멈추고 색을 고정"}, {icon:"🧀", t:"부드럽게 유지되는 파니르", d:"따뜻한 소금물이 큐브를 플레이팅까지 부드럽게 유지"}, {icon:"🍅", t:"기름이 분리될 때까지의 마살라", d:"6–8분 — 토마토가 완전히 익었다는 신호"}, {icon:"🌿", t:"마지막에 카수리 메티", d:"손바닥에서 비비면 마른 페누그릭 향이 살아남"}]',
'hi': '[{icon:"❄️", t:"बर्फ़ का स्नान = चटक हरा", d:"पकना तुरंत रोकता है और रंग पकड़ लेता है"}, {icon:"🧀", t:"पनीर नर्म रहता है", d:"गुनगुना नमक वाला पानी प्लेटिंग तक टुकड़ों को नर्म रखता है"}, {icon:"🍅", t:"मसाला तब तक जब तक तेल अलग न हो", d:"6–8 मिनट — टमाटर पूरी तरह पकने का इशारा"}, {icon:"🌿", t:"अंत में kasoori methi", d:"हथेलियों के बीच रगड़ने से सूखी मेथी की महक उभरती है"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*206,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 206 (Palak Paneer): {rec_end-rec_start} → {len(new_recipe_block)} chars")
