#!/usr/bin/env python3
"""Rewrite recipe 211 (Som Tam): howIsMade 10 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "In a clay krok or sturdy stone mortar, pound the garlic and chillies together until bruised — not pulverised, just opened up — then add the palm sugar and pound a few more times to dissolve it into the chilli oil. Pour in the fish sauce, lime juice and tamarind, stir with the pestle until the sugar dissolves, then tip in the dried shrimp and pound a couple of times to flatten them into the dressing. Add the long beans and tomato halves and pound gently — five or six taps each, just enough to bruise them and release their juices into the dressing — the pestle here is a tool of seasoning, not destruction. Tip in the shredded papaya in two batches, alternating light pounding with turning everything with a spoon until each strand is glossy with the dressing but still crisp, then add the peanuts (whole for crunch, crushed for body) and toss one last time. Taste — Som Tam should hit four flavours at once: sour, salty, sweet and chilli-fierce — then pile into shallow bowls or onto lettuce leaves and eat immediately with sticky rice or grilled chicken.",

'ro': "Într-un mojaru de lut (krok) sau unul robust de piatră, pisează usturoiul și ardeii iuți împreună până sunt zdrobiți — nu pulverizați, doar deschiși — apoi adaugă zahărul de palmier și mai pisează de câteva ori, ca să se topească în uleiul ardeiului. Toarnă sosul de pește, sucul de lime și tamarindul, amestecă cu pistolul pentru a dizolva zahărul, apoi adaugă creveții uscați și pisează de câteva ori ca să-i aplatizezi în dressing. Adaugă fasolea lungă și jumătățile de roșii și pisează blând — cinci-șase lovituri pentru fiecare, doar cât să le zdrobești ușor și să le eliberezi sucurile în dressing — pistolul este aici un instrument de condimentare, nu de distrugere. Adaugă papaya tăiată julienne în două reprize, alternând între lovituri ușoare și amestecat cu o lingură până când fiecare fâșie strălucește de dressing dar rămâne crocantă, apoi adaugă arahidele (întregi pentru crocant, zdrobite pentru corp) și învârte ultima dată. Gustă — Som Tam trebuie să lovească patru gusturi simultan: acru, sărat, dulce și fierbinte de la chili — apoi adună-l în boluri puțin adânci sau pe frunze de salată și mănânc-o imediat cu orez glutinos sau pui la grătar.",

'es': "En un mortero de barro (krok) o uno robusto de piedra, maja juntos el ajo y los chiles hasta machacarlos — sin pulverizarlos, sólo abiertos — después añade el azúcar de palma y maja unas cuantas veces más, hasta que se deshaga en el aceite del chile. Vierte la salsa de pescado, el zumo de lima y el tamarindo, remueve con el majador para disolver el azúcar, después echa las gambas secas y maja un par de veces para aplastarlas dentro del aliño. Añade las judías largas y las mitades de tomate y maja con suavidad — cinco o seis toques en cada una, lo justo para magullarlos y soltar sus jugos en el aliño — el majador es aquí una herramienta para sazonar, no para destruir. Incorpora la papaya rallada en dos tandas, alternando majados ligeros con remover todo con cuchara hasta que cada hebra brille con el aliño pero siga crujiente, después añade los cacahuetes (enteros para textura, picados para cuerpo) y dale una última vuelta. Prueba — la Som Tam debe golpear cuatro sabores a la vez: ácido, salado, dulce y un calor feroz de chile — luego amontona en cuencos hondos o sobre hojas de lechuga y come al momento con arroz glutinoso o pollo a la parrilla.",

'fr': "Dans un mortier en argile (krok) ou un mortier de pierre solide, pilez ensemble l'ail et les piments jusqu'à ce qu'ils soient ouverts — pas pulvérisés — puis ajoutez le sucre de palme et pilez encore quelques fois pour le faire fondre dans l'huile de piment. Versez le nuoc-mâm, le jus de citron vert et le tamarin, remuez avec le pilon pour dissoudre le sucre, puis ajoutez les crevettes séchées et pilez deux à trois fois pour les aplatir dans la vinaigrette. Ajoutez les haricots longs et les moitiés de tomates et pilez doucement — cinq ou six coups chacun, juste assez pour les meurtrir et libérer leurs jus dans la vinaigrette — le pilon est ici un outil pour assaisonner, pas pour détruire. Incorporez la papaye râpée en deux fois, en alternant les frappes légères et un brassage à la cuillère jusqu'à ce que chaque filament brille de vinaigrette mais reste croquant, puis ajoutez les cacahuètes (entières pour le croquant, concassées pour le corps) et donnez un dernier tour. Goûtez — le Som Tam doit atteindre quatre saveurs en même temps : acide, salé, sucré et un piment féroce — puis servez en monticules dans des bols peu profonds ou sur des feuilles de laitue et mangez aussitôt avec du riz gluant ou un poulet grillé.",

'de': "In einem Tonmörser (Krok) oder einem robusten Steinmörser den Knoblauch und die Chilis zusammen zerstoßen — nicht pulverisieren, nur öffnen — dann den Palmzucker dazugeben und ein paar Mal weiter stoßen, damit er sich im Chiliöl auflöst. Fischsauce, Limettensaft und Tamarinde angießen, mit dem Stößel umrühren um den Zucker aufzulösen, dann die getrockneten Garnelen dazugeben und ein paarmal stoßen, um sie in das Dressing zu drücken. Geben Sie die langen Bohnen und die halbierten Tomaten dazu und stoßen Sie sanft — fünf oder sechs Schläge je Sorte, nur so viel, dass sie weich werden und ihre Säfte ins Dressing geben — der Stößel ist hier ein Würzwerkzeug, kein Zerstörungswerkzeug. Die geraspelte Papaya in zwei Portionen dazugeben, abwechselnd leicht stoßen und mit einem Löffel umwenden, bis jeder Streifen vom Dressing glänzt aber noch knackig ist, dann die Erdnüsse hinzufügen (ganze für den Knack, zerstoßene für die Tiefe) und ein letztes Mal durchschwenken. Probieren — Som Tam soll vier Geschmäcker gleichzeitig treffen: sauer, salzig, süß und chili-feurig — in flache Schalen häufen oder auf Salatblätter setzen und sofort mit Klebreis oder gegrilltem Hühnchen essen.",

'pt': "Num almofariz de barro (krok) ou num robusto de pedra, pise o alho e os piri-piris juntos até estarem amassados — não pulverizados, apenas abertos — depois junte o açúcar de palma e bata mais algumas vezes para se desfazer no óleo do piri-piri. Verta o molho de peixe, o sumo de lima e o tamarindo, mexa com o pilão para dissolver o açúcar, depois acrescente o camarão seco e bata duas vezes para o achatar no tempero. Junte os feijões-compridos e as metades de tomate e pise com suavidade — cinco ou seis batidas em cada, apenas o suficiente para magoá-los e libertar os sucos no tempero — o pilão aqui é uma ferramenta de tempero, não de destruição. Incorpore a papaia ralada em duas vezes, alternando batidas leves com mexer tudo com uma colher até cada fio brilhar com o tempero mas continuar crocante, depois junte os amendoins (inteiros para o crocante, esmagados para corpo) e dê uma última volta. Prove — o Som Tam deve atingir quatro sabores ao mesmo tempo: ácido, salgado, doce e um picante feroz de piri-piri — depois disponha em taças baixas ou em folhas de alface e coma de imediato com arroz pegajoso ou frango grelhado.",

'ru': "В глиняной ступке (krok) или прочной каменной разотрите чеснок и чили вместе до раскрытия, а не до пыли, затем добавьте пальмовый сахар и пробейте ещё несколько раз, чтобы он разошёлся в чилийном масле. Влейте рыбный соус, сок лайма и тамаринд, помешайте пестиком, чтобы растворить сахар, затем добавьте сушёные креветки и пробейте пару раз, расплющив их в заправке. Добавьте длинную фасоль и половинки помидоров и слегка постучите — по пять-шесть ударов на каждую часть, ровно столько, чтобы помять их и выпустить соки в заправку — пестик здесь инструмент приправы, а не разрушения. Введите тёртую папайю в два приёма, чередуя лёгкие удары пестика с перемешиванием ложкой, пока каждая полоска не заблестит от заправки, оставаясь хрустящей, затем добавьте арахис (целый для хруста, толчёный для тела) и переверните в последний раз. Попробуйте — Сом Там должен бить одновременно по четырём вкусам: кислому, солёному, сладкому и яростно-перечному — затем накладывайте горкой в неглубокие миски или на листья салата и ешьте сразу же с клейким рисом или жареной курицей.",

'ar': "في هاون فخاري (كروك) أو هاون حجري متين، اطحن الثوم والفلفل معاً حتى يفتح طعمهما — لا تطحنهما إلى مسحوق، فقط افتحهما — ثم أضف سكر النخيل واطحن مرات قليلة أخرى ليذوب في زيت الفلفل. اسكب صلصة السمك وعصير الليم والتمر الهندي، حرّك بالمدقّة لإذابة السكر، ثم أضف الجمبري المجفف واطرقه مرتين لتسطيحه في الصلصة. أضف الفاصولياء الطويلة وأنصاف الطماطم وادقّ برفق — خمس أو ست طرقات لكل صنف، فقط لتفتيتها وإطلاق عصاراتها في الصلصة — المدقّة هنا أداة تتبيل لا أداة تحطيم. أدخل البابايا المبشورة على دفعتين، متناوباً بين الدقّ الخفيف والتقليب بملعقة حتى يلمع كل خيط بالصلصة ويبقى مقرمشاً، ثم أضف الفول السوداني (الكامل من أجل القرمشة، والمهروس من أجل قوام) وقلّب لمرة أخيرة. تذوّق — السوم تام يجب أن يضرب أربعة نكهات في آن واحد: حامض، مالح، حلو، وحرارة فلفل شرسة — ثم كوّمه في صحون ضحلة أو على أوراق الخس وتناوله فوراً مع الأرز اللزج أو الدجاج المشوي.",

'zh': "在陶杵臼（krok）或一只结实的石臼里，把蒜瓣和辣椒一起捣开——不要捣成粉，只要把它们打开就好——再加入棕榈糖，捣几下让它在辣椒油里散开。倒入鱼露、青柠汁和罗望子，用杵搅拌让糖溶化，再放入干虾米，轻捣两下让它们压扁、融进调味汁里。放入长豆和切半的小番茄，轻轻地捣——每样五六下，刚好把它们打软、把汁水带进调料里——在这里，杵是用来调味的，不是用来摧毁的。把擦丝的青木瓜分两次倒入，捣几下、用勺子翻几下、再捣几下，直到每根丝都裹满调味汁但仍然脆，再加入花生（整粒带来口感，碎粒带来厚度），最后再翻一次。尝一下——Som Tam 应该同时打中四种味道：酸、咸、甜、和凶猛的辣——然后盛进浅口碗里或放在生菜叶上，配糯米饭或烤鸡立即享用。",

'ja': "クロック（タイの素焼き乳鉢）または頑丈な石臼で、にんにくと唐辛子を一緒に砕く — 粉にせず、香りが開く程度まで — その後パームシュガーを加えて数回叩き、唐辛子の油に溶け込ませる。ナンプラー、ライム果汁、タマリンドを注ぎ、すりこぎで混ぜて砂糖を溶かし、続けて干しエビを加えて 2 回ほど叩いてドレッシングに平らに溶け込ませる。ヤードロングビーンズと半分に切ったミニトマトを加えて優しく叩く — 各 5〜6 回ずつ、軽く潰してジュースをドレッシングに移すだけでいい — すりこぎはここでは味付けの道具であって、破壊の道具ではない。青パパイヤの千切りを 2 回に分けて加え、軽く叩いてはスプーンで全体を返すを繰り返し、すべての糸がドレッシングで光りながらシャキ感を残している状態に仕上げ、続いてピーナッツを加える（食感のために丸ごと、コクのために砕いたものを）、もう一度だけ全体を返す。味を見る — ソムタムは「酸味・塩味・甘味・容赦のない辛味」の四つを同時に当ててこなければならない — 浅い器、あるいはレタスの上に盛り、もち米やグリルチキンと共にすぐに食べる。",

'tr': "Bir kil havan (krok) ya da sağlam taş havanda, sarımsak ile biberi birlikte dövün — toza dönüşmesini değil, sadece açılmasını istiyoruz — sonra palmiye şekerini ekleyin ve birkaç defa daha vurun ki acı biber yağında erisin. Balık sosunu, limon suyunu ve demirhindiyi dökün, şekeri eritmek için havan eli ile karıştırın, sonra kurutulmuş karidesleri ekleyin ve birkaç vuruşla soslara düzleştirin. Uzun fasulyeleri ve domates yarımlarını ekleyin ve nazikçe dövün — her birine beş-altı vuruş, sadece ezilip sularını sosa bırakacak kadar — havan eli burada bir terbiye aletidir, yıkım aleti değil. Rendelenmiş papayayı iki partide ekleyin, hafif vuruşlarla bir kaşıkla harmanlamayı dönüşümlü olarak yapın, her telin sosla parlamasına ama hâlâ çıtır kalmasına dikkat edin, sonra fıstığı ekleyin (bütünleri çıtırlık, ezilmişler gövde için) ve son bir kez harmanlayın. Tadına bakın — Som Tam aynı anda dört tadı vurmalı: ekşi, tuzlu, tatlı ve sert bir biber acısı — sığ kâselerde ya da marul yapraklarının üzerinde, yapışkan pirinç ya da ızgara tavukla hemen yiyin.",

'it': "In un mortaio di terracotta (krok) o uno robusto di pietra, pestate l'aglio e i peperoncini insieme finché non sono ammaccati — non polverizzati, solo aperti — poi aggiungete lo zucchero di palma e pestate altre poche volte per scioglierlo nell'olio del peperoncino. Versate la salsa di pesce, il succo di lime e il tamarindo, mescolate con il pestello per sciogliere lo zucchero, poi aggiungete i gamberetti essiccati e pestate un paio di volte per appiattirli nel condimento. Unite i fagiolini lunghi e le metà dei pomodorini e pestate con delicatezza — cinque o sei colpi ciascuno, quanto basta per ammaccarli e liberare i loro succhi nel condimento — il pestello qui è uno strumento di condimento, non di distruzione. Unite la papaya grattugiata in due volte, alternando colpi leggeri e una mescolata con il cucchiaio finché ogni filo non è lucido di condimento ma resta croccante, poi aggiungete le arachidi (intere per la croccantezza, schiacciate per il corpo) e date un'ultima girata. Assaggiate — il Som Tam deve colpire quattro sapori contemporaneamente: acido, salato, dolce e un piccante feroce — disponete a piccoli monti in ciotole basse o su foglie di lattuga e mangiate subito con riso glutinoso o pollo alla griglia.",

'ko': "흙으로 만든 절구(크록)나 단단한 돌 절구에 마늘과 고추를 함께 빻는다 — 가루로 만들지 말고, 향이 열릴 정도로만 — 그런 다음 팜 슈가를 더하고 몇 번 더 빻아 고추 기름에 녹아들게 한다. 피쉬소스, 라임즙, 타마린드를 붓고 절굿공이로 저어 설탕을 녹이고, 건새우를 넣어 두 번 정도 더 두드려 드레싱 안으로 납작하게 흩어지게 한다. 롱빈과 반으로 자른 토마토를 넣고 부드럽게 빻는다 — 각각 다섯 여섯 번 정도, 살짝 뭉개져 즙이 드레싱으로 빠질 정도면 충분하다 — 절굿공이는 여기서 양념의 도구이지, 파괴의 도구가 아니다. 채 썬 파파야를 두 번에 나눠 넣고, 가볍게 두드리기와 숟가락으로 휘젓기를 번갈아 하며, 모든 가닥이 드레싱에 윤기 나게 묻으면서도 아삭함을 잃지 않도록 한 뒤, 땅콩을 넣고 (통째로는 식감, 부순 것은 깊이를 위해), 마지막으로 한 번 더 뒤집어 섞는다. 맛을 본다 — 쏨땀은 동시에 네 가지 맛을 때려야 한다: 신맛, 짠맛, 단맛, 그리고 사납게 매운맛 — 얕은 그릇에 수북이 담거나 양상추 잎 위에 올려, 찹쌀밥이나 구운 닭과 함께 곧장 먹는다.",

'hi': "एक मिट्टी की ओखली (krok) या मज़बूत पत्थर की ओखली में लहसुन और मिर्च को साथ कूटें — पाउडर मत बनाएँ, बस उन्हें खोल दें — फिर ताड़ की चीनी डालें और थोड़ा और कूटें ताकि वो मिर्च के तेल में घुल जाए। फिश सॉस, नीबू का रस और इमली डालें, मूसल से चलाकर चीनी घोलें, फिर सूखी झींगा डालें और दो-तीन बार ठोकें ताकि वो ड्रेसिंग में चपटी होकर मिल जाएँ। लंबी फलियाँ और कटे टमाटर डालें और हलके से कूटें — हर एक पर पाँच-छह बार ठोकें, बस इतना कि वो थोड़े टूट जाएँ और उनका रस ड्रेसिंग में आ जाए — यहाँ मूसल मसाला बैठाने का औज़ार है, तोड़ने का नहीं। कद्दूकस किया पपीता दो बार में डालें, बीच-बीच में हलकी कुटाई और चम्मच से उलट-पुलट करते रहें, जब तक हर रेशा ड्रेसिंग में चमक न जाए लेकिन कुरकुरापन बना रहे, फिर मूँगफली डालें (साबुत क्रंच के लिए, कुटी हुई गहराई के लिए) और एक आख़िरी बार पलट दें। चखें — Som Tam को एक साथ चार स्वाद मारने चाहिए: खट्टा, नमकीन, मीठा, और एक उग्र मिर्ची-तीख़ापन — फिर उथले कटोरों में या लेट्यूस के पत्तों पर ढेर बना कर रखें, और चिपचिपे चावल या ग्रिल्ड चिकन के साथ तुरंत खाएँ।",
}

FEATURE_CARDS = {
'en': '[{icon:"🧉", t:"The clay krok mortar", d:"A tool of seasoning, not destruction — bruise, don\'t pulverise"}, {icon:"🌶️", t:"Four flavours at once", d:"Sour, salty, sweet and chilli-fierce, all in every bite"}, {icon:"🥭", t:"Green papaya julienne", d:"Crisp shreds that drink the dressing"}, {icon:"🥜", t:"Peanuts two ways", d:"Whole for crunch, crushed for body"}]',
'ro': '[{icon:"🧉", t:"Mojarul de lut (krok)", d:"Instrument de condimentare, nu de distrugere — zdrobește, nu pulveriza"}, {icon:"🌶️", t:"Patru gusturi deodată", d:"Acru, sărat, dulce și fierbinte de la chili, în fiecare gură"}, {icon:"🥭", t:"Papaya verde julienne", d:"Fâșii crocante care beau dressing-ul"}, {icon:"🥜", t:"Arahide în două forme", d:"Întregi pentru crocant, zdrobite pentru corp"}]',
'es': '[{icon:"🧉", t:"El mortero de barro (krok)", d:"Herramienta de sazón, no de destrucción — machaca, no pulverices"}, {icon:"🌶️", t:"Cuatro sabores a la vez", d:"Ácido, salado, dulce y feroz de chile, en cada bocado"}, {icon:"🥭", t:"Papaya verde en juliana", d:"Hebras crujientes que beben el aliño"}, {icon:"🥜", t:"Cacahuetes en dos formas", d:"Enteros para textura, picados para cuerpo"}]',
'fr': '[{icon:"🧉", t:"Le mortier en argile (krok)", d:"Outil pour assaisonner, pas pour détruire — meurtrir, ne pas pulvériser"}, {icon:"🌶️", t:"Quatre saveurs à la fois", d:"Acide, salé, sucré et un piment féroce, à chaque bouchée"}, {icon:"🥭", t:"Papaye verte en julienne", d:"Filaments croquants qui boivent la vinaigrette"}, {icon:"🥜", t:"Cacahuètes en deux formes", d:"Entières pour le croquant, concassées pour le corps"}]',
'de': '[{icon:"🧉", t:"Der Tonmörser (Krok)", d:"Würzwerkzeug, kein Zerstörungswerkzeug — quetschen, nicht pulverisieren"}, {icon:"🌶️", t:"Vier Geschmäcker auf einmal", d:"Sauer, salzig, süß und chili-feurig, in jedem Bissen"}, {icon:"🥭", t:"Grüne Papaya in Streifen", d:"Knackige Fasern, die das Dressing trinken"}, {icon:"🥜", t:"Erdnüsse zweifach", d:"Ganz für den Knack, zerstoßen für die Tiefe"}]',
'pt': '[{icon:"🧉", t:"O almofariz de barro (krok)", d:"Ferramenta de tempero, não de destruição — magoar, não pulverizar"}, {icon:"🌶️", t:"Quatro sabores ao mesmo tempo", d:"Ácido, salgado, doce e picante feroz, em cada garfada"}, {icon:"🥭", t:"Papaia verde em juliana", d:"Fios crocantes que bebem o tempero"}, {icon:"🥜", t:"Amendoins em duas formas", d:"Inteiros para crocância, esmagados para corpo"}]',
'ru': '[{icon:"🧉", t:"Глиняная ступка (krok)", d:"Инструмент приправы, не разрушения — мять, а не превращать в пыль"}, {icon:"🌶️", t:"Четыре вкуса одновременно", d:"Кислый, солёный, сладкий и яростно-перечный, в каждом куске"}, {icon:"🥭", t:"Зелёная папайя соломкой", d:"Хрустящие полоски, которые пьют заправку"}, {icon:"🥜", t:"Арахис в двух видах", d:"Целый для хруста, толчёный для тела"}]',
'ar': '[{icon:"🧉", t:"الهاون الفخاري (كروك)", d:"أداة تتبيل لا تحطيم — اهرس، لا تطحن إلى مسحوق"}, {icon:"🌶️", t:"أربع نكهات معاً", d:"حامض، مالح، حلو، وحرارة فلفل شرسة في كل قضمة"}, {icon:"🥭", t:"البابايا الخضراء جوليان", d:"خيوط مقرمشة تشرب الصلصة"}, {icon:"🥜", t:"فول سوداني بشكلين", d:"كامل من أجل القرمشة، ومهروس من أجل القوام"}]',
'zh': '[{icon:"🧉", t:"陶杵臼 (krok)", d:"用来调味的工具，不是用来摧毁 — 打开，不要打粉"}, {icon:"🌶️", t:"四味同时上桌", d:"酸、咸、甜、辣，一口里全有"}, {icon:"🥭", t:"青木瓜丝", d:"脆爽的丝，把调味汁喝进去"}, {icon:"🥜", t:"两种花生", d:"整粒为口感，碎粒为厚度"}]',
'ja': '[{icon:"🧉", t:"素焼きのクロック", d:"味付けの道具であって、破壊の道具ではない — 潰すのではなく開く"}, {icon:"🌶️", t:"四つの味が同時に", d:"酸味・塩味・甘味・容赦のない辛味、一口にすべて"}, {icon:"🥭", t:"青パパイヤの千切り", d:"ドレッシングを吸う、シャキッとした繊維"}, {icon:"🥜", t:"二種類のピーナッツ", d:"丸ごとは食感、砕いたものはコクのため"}]',
'tr': '[{icon:"🧉", t:"Kil havan (krok)", d:"Terbiye aleti, yıkım aleti değil — ez, toza dönüştürme"}, {icon:"🌶️", t:"Dört tat birlikte", d:"Ekşi, tuzlu, tatlı ve sert biber acısı, her lokmada"}, {icon:"🥭", t:"Yeşil papaya jülyen", d:"Sosu içen çıtır lifler"}, {icon:"🥜", t:"İki şekilde fıstık", d:"Bütünleri çıtırlık, ezilmişler gövde için"}]',
'it': '[{icon:"🧉", t:"Il mortaio di terracotta (krok)", d:"Strumento di condimento, non di distruzione — ammaccare, non polverizzare"}, {icon:"🌶️", t:"Quattro sapori insieme", d:"Acido, salato, dolce e piccante feroce, in ogni boccone"}, {icon:"🥭", t:"Papaya verde a julienne", d:"Fili croccanti che bevono il condimento"}, {icon:"🥜", t:"Arachidi in due forme", d:"Intere per la croccantezza, schiacciate per il corpo"}]',
'ko': '[{icon:"🧉", t:"흙으로 만든 크록", d:"양념의 도구이지 파괴의 도구가 아니다 — 빻지 말고 열어라"}, {icon:"🌶️", t:"네 맛이 동시에", d:"신맛·짠맛·단맛·사납게 매운맛, 한 입에 모두"}, {icon:"🥭", t:"풋파파야 채", d:"드레싱을 빨아들이는 아삭한 가닥"}, {icon:"🥜", t:"두 가지 땅콩", d:"통째는 식감, 부순 것은 깊이"}]',
'hi': '[{icon:"🧉", t:"मिट्टी की ओखली (krok)", d:"मसाला बैठाने का औज़ार, तोड़ने का नहीं — खोलें, पाउडर मत बनाएँ"}, {icon:"🌶️", t:"चार स्वाद एक साथ", d:"खट्टा, नमकीन, मीठा, और उग्र मिर्ची-तीख़ापन, हर निवाले में"}, {icon:"🥭", t:"कच्चा पपीता जुलिएन", d:"कुरकुरे रेशे जो ड्रेसिंग पी लेते हैं"}, {icon:"🥜", t:"मूँगफली दो रूपों में", d:"साबुत क्रंच के लिए, कुटी हुई गहराई के लिए"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*211,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)

fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 211 (Som Tam): {rec_end-rec_start} → {len(new_recipe_block)} chars, 5 steps + 4 cards × 14 langs")
