#!/usr/bin/env python3
"""Rewrite recipe 202 (Tiramisu): 12 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Whisk the egg yolks with the sugar in a large bowl for 4–5 minutes — by hand or with an electric beater — until pale, foamy and dramatically tripled in volume; the sugar should be completely dissolved when you rub a little between your fingers, undermixing here gives you a grainy tiramisu later. Add the mascarpone in three batches, whisking gently after each, until the cream is smooth and glossy, then in a separate clean bowl whisk the egg whites with a pinch of salt to firm glossy peaks that hold their shape when the whisk is lifted, and fold the whites into the mascarpone in three additions with a large spatula, folding from the centre outwards to keep the air in — the finished cream should be light, almost pourable but holding soft peaks. Mix the cold espresso and Marsala in a shallow dish, then dip the savoiardi one at a time — just briefly, 2 seconds per side at most — they are sponges, and oversoaked ladyfingers turn to mush and weep through the cream, and lay them in a tight single layer in the bottom of a 22×30 cm dish. Spread half the mascarpone cream over the ladyfingers in an even layer, then repeat — another tight layer of dipped savoiardi, then the rest of the cream on top, smoothed level with the spatula. Cover with clingfilm and refrigerate at least 6 hours, ideally overnight — tiramisu eaten the same day tastes like its parts, tiramisu rested overnight tastes like one dessert — just before serving dust the top generously with cocoa pushed through a fine sieve, shave over a little dark chocolate if you like, and cut with a hot knife wiped between slices.",

'ro': "Bate gălbenușurile cu zahărul într-un bol mare 4–5 minute — cu mâna sau cu mixerul electric — până sunt palide, spumoase și triplate dramatic în volum; zahărul trebuie să fie complet dizolvat când freci puțin între degete, sub-amestecul aici îți dă un tiramisu cu cristale mai târziu. Adaugă mascarpone în trei reprize, bătând ușor după fiecare, până când crema este netedă și lucioasă, apoi într-un bol separat curat bate albușurile cu un vârf de sare până la vârfuri ferme și lucioase care își țin forma când ridici telul, și încorporează albușurile în mascarpone în trei adăugări cu o spatulă mare, împăturind dinspre centru spre afară pentru a păstra aerul — crema finală trebuie să fie ușoară, aproape turnabilă dar ținând vârfuri moi. Amestecă espressoul rece și Marsala într-un vas puțin adânc, apoi înmoaie savoiardi unul câte unul — doar scurt, 2 secunde pe fiecare parte maxim — sunt bureți, și pișcoturile prea îmbibate se transformă în mâl și plâng prin cremă, și pune-le într-un singur strat strâns pe fundul unui vas de 22×30 cm. Întinde jumătate din crema de mascarpone peste pișcoturi într-un strat uniform, apoi repetă — alt strat strâns de savoiardi înmuiate, apoi restul de cremă deasupra, neted cu spatula. Acoperă cu folie alimentară și refrigerează cel puțin 6 ore, ideal peste noapte — tiramisu mâncat în aceeași zi are gust de părți componente, tiramisu odihnit peste noapte are gust de un singur desert — chiar înainte de servire pudrează deasupra generos cu cacao trecută printr-o sită fină, rade puțină ciocolată neagră dacă vrei, și taie cu un cuțit fierbinte șters între felii.",

'es': "Bate las yemas con el azúcar en un bol grande durante 4–5 minutos — a mano o con batidora eléctrica — hasta que estén pálidas, espumosas y dramáticamente triplicadas en volumen; el azúcar debe estar completamente disuelto cuando frotes un poco entre los dedos, un mezclado insuficiente aquí te da un tiramisú granuloso después. Añade el mascarpone en tres tandas, batiendo con suavidad después de cada una, hasta que la crema esté lisa y brillante, luego en un bol separado limpio bate las claras con una pizca de sal hasta picos firmes y brillantes que mantengan su forma al levantar las varillas, y envuelve las claras en el mascarpone en tres adiciones con una espátula grande, plegando desde el centro hacia afuera para mantener el aire dentro — la crema final debe ser ligera, casi vertible pero manteniendo picos suaves. Mezcla el espresso frío y el Marsala en una fuente baja, después moja los savoiardi de uno en uno — sólo brevemente, 2 segundos por lado como máximo — son esponjas, y los soletillas remojadas en exceso se convierten en papilla y lloran a través de la crema, y colócalos en una sola capa apretada en el fondo de un molde de 22×30 cm. Extiende la mitad de la crema de mascarpone sobre los soletillas en una capa uniforme, luego repite — otra capa apretada de savoiardi mojados, después el resto de la crema encima, alisado con la espátula. Cubre con film transparente y refrigera al menos 6 horas, idealmente toda la noche — el tiramisú comido el mismo día sabe a sus partes, el tiramisú reposado toda la noche sabe a un postre — justo antes de servir, espolvorea generosamente por encima cacao pasado por un colador fino, ralla un poco de chocolate negro si quieres, y corta con un cuchillo caliente limpiado entre porciones.",

'fr': "Fouettez les jaunes d'œufs avec le sucre dans un grand bol pendant 4 à 5 minutes — à la main ou au batteur électrique — jusqu'à ce qu'ils soient pâles, mousseux et triplés de volume de façon spectaculaire ; le sucre doit être complètement dissous quand vous en frottez un peu entre les doigts, un sous-mélange ici vous donne un tiramisu granuleux plus tard. Ajoutez le mascarpone en trois fois en fouettant doucement après chaque, jusqu'à ce que la crème soit lisse et brillante, puis dans un bol séparé propre fouettez les blancs avec une pincée de sel jusqu'à des pics fermes et brillants qui tiennent leur forme quand le fouet est levé, et incorporez les blancs dans le mascarpone en trois ajouts à la grande spatule, en pliant du centre vers l'extérieur pour garder l'air à l'intérieur — la crème finie doit être légère, presque coulante mais tenant des pics souples. Mélangez l'espresso froid et le Marsala dans un plat peu profond, puis trempez les savoiardi un par un — juste brièvement, 2 secondes par face au maximum — ce sont des éponges, et les boudoirs trop trempés tournent en bouillie et pleurent à travers la crème, et posez-les en une seule couche serrée au fond d'un plat de 22×30 cm. Étalez la moitié de la crème mascarpone sur les boudoirs en couche uniforme, puis répétez — une autre couche serrée de savoiardi trempés, puis le reste de la crème par-dessus, lissé à la spatule. Couvrez de film alimentaire et réfrigérez au moins 6 heures, idéalement toute la nuit — le tiramisu mangé le jour même a le goût de ses parties, le tiramisu reposé toute la nuit a le goût d'un seul dessert — juste avant de servir saupoudrez généreusement le dessus de cacao passé au tamis fin, râpez un peu de chocolat noir si vous voulez, et coupez avec un couteau chaud essuyé entre les tranches.",

'de': "Schlagen Sie die Eigelbe mit dem Zucker in einer großen Schüssel 4–5 Minuten — von Hand oder mit dem elektrischen Quirl — bis sie blass, schaumig und dramatisch im Volumen verdreifacht sind; der Zucker sollte vollständig aufgelöst sein, wenn Sie ein wenig zwischen den Fingern reiben, ein Untermixen hier gibt Ihnen später ein körniges Tiramisu. Geben Sie den Mascarpone in drei Portionen hinzu, nach jeder sanft schlagen, bis die Creme glatt und glänzend ist, dann in einer separaten sauberen Schüssel die Eiweiße mit einer Prise Salz zu festen glänzenden Spitzen schlagen, die ihre Form halten wenn der Quirl gehoben wird, und die Eiweiße in drei Zugaben mit einem großen Spatel in den Mascarpone heben, dabei von der Mitte nach außen falten um die Luft drin zu halten — die fertige Creme sollte leicht sein, fast gießfähig aber weiche Spitzen haltend. Mischen Sie den kalten Espresso und Marsala in einer flachen Schale, dann tauchen Sie die Savoiardi einzeln — nur kurz, maximal 2 Sekunden pro Seite — sie sind Schwämme, und durchgeweichte Löffelbiskuits werden zu Brei und weinen durch die Creme, und legen Sie sie in einer engen einlagigen Schicht auf den Boden einer 22×30 cm Form. Verstreichen Sie die Hälfte der Mascarponecreme über die Löffelbiskuits in einer gleichmäßigen Schicht, dann wiederholen — eine weitere enge Schicht eingetauchter Savoiardi, dann der Rest der Creme oben drauf, mit dem Spatel glatt gestrichen. Mit Frischhaltefolie abdecken und mindestens 6 Stunden, idealerweise über Nacht, im Kühlschrank ruhen lassen — Tiramisu, das am selben Tag gegessen wird, schmeckt nach seinen Teilen, Tiramisu, das über Nacht geruht hat, schmeckt nach einem einzigen Dessert — kurz vor dem Servieren großzügig mit durch ein feines Sieb gedrücktem Kakao bestäuben, etwas dunkle Schokolade darüber raspeln wenn Sie mögen, und mit einem heißen Messer schneiden, das zwischen den Scheiben abgewischt wird.",

'pt': "Bata as gemas com o açúcar numa tigela grande durante 4–5 minutos — à mão ou com batedeira elétrica — até estarem pálidas, espumosas e dramaticamente triplicadas em volume; o açúcar deve estar completamente dissolvido quando esfregar um pouco entre os dedos, sub-bater aqui dá-lhe um tiramisu granulado depois. Junte o mascarpone em três vezes, batendo suavemente após cada, até a creme estar liso e brilhante, depois numa tigela limpa separada bata as claras com uma pitada de sal até picos firmes e brilhantes que mantenham a forma quando a vara é levantada, e envolva as claras no mascarpone em três adições com uma espátula grande, dobrando do centro para fora para manter o ar dentro — o creme final deve ser leve, quase derramável mas mantendo picos macios. Misture o espresso frio e o Marsala num prato baixo, depois molhe os savoiardi um a um — apenas brevemente, 2 segundos por lado no máximo — são esponjas, e os palitos de la reine encharcados demais viram papa e choram através do creme, e disponha-os numa única camada apertada no fundo de uma forma de 22×30 cm. Espalhe metade do creme de mascarpone sobre os palitos numa camada uniforme, depois repita — outra camada apertada de savoiardi molhados, depois o resto do creme por cima, alisado com a espátula. Cubra com película aderente e refrigere pelo menos 6 horas, idealmente de um dia para o outro — o tiramisu comido no mesmo dia sabe às suas partes, o tiramisu repousado de um dia para o outro sabe a uma sobremesa — pouco antes de servir polvilhe generosamente o topo com cacau passado por um coador fino, lasque um pouco de chocolate negro se quiser, e corte com uma faca quente limpa entre fatias.",

'ru': "Взбейте желтки с сахаром в большой миске 4–5 минут — вручную или электрическим венчиком — до бледного, пенистого состояния, объёмом увеличенного в три раза; сахар должен быть полностью растворён, когда вы трёте немного между пальцами, недомешивание здесь даёт зернистый тирамису позже. Добавьте маскарпоне в три приёма, аккуратно взбивая после каждого, пока крем не станет гладким и блестящим, затем в отдельной чистой миске взбейте белки со щепоткой соли до твёрдых блестящих пиков, которые держат форму при поднятии венчика, и вмешайте белки в маскарпоне в три добавления большой лопаткой, складывая от центра наружу, чтобы сохранить воздух внутри — готовый крем должен быть лёгким, почти текучим, но держать мягкие пики. Смешайте холодный эспрессо и марсалу в неглубокой посуде, затем окунайте савоярди по одному — лишь кратко, максимум 2 секунды с каждой стороны — это губки, и чрезмерно вымоченные дамские пальчики превращаются в кашу и плачут сквозь крем, и положите их плотным одним слоем на дно формы 22×30 см. Распределите половину крема маскарпоне по савоярди ровным слоем, затем повторите — ещё один плотный слой замоченных савоярди, затем остальной крем сверху, разглаженный лопаткой. Накройте плёнкой и поставьте в холодильник минимум на 6 часов, идеально на ночь — тирамису, съеденный в тот же день, имеет вкус своих частей, тирамису, отдохнувший за ночь, имеет вкус одного десерта — прямо перед подачей обильно посыпьте сверху какао, пропущенным через мелкое сито, натрите немного тёмного шоколада если хотите, и нарежьте горячим ножом, вытираемым между ломтиками.",

'ar': "اخفق صفار البيض مع السكر في وعاء كبير لمدة 4–5 دقائق — يدوياً أو بالخفاقة الكهربائية — حتى يصبح المزيج فاتح اللون، رغوياً، ومتضاعف الحجم إلى ثلاثة أمثاله؛ يجب أن يذوب السكر تماماً حين تفرك القليل بين أصابعك، الخفق الناقص هنا يعطيك تيراميسو حبيبياً لاحقاً. أضف المسكربون على ثلاث دفعات، اخفق برفق بعد كل دفعة، حتى تصبح الكريمة ناعمة ولامعة، ثم في وعاء نظيف منفصل اخفق بياض البيض مع رشة ملح إلى قمم متماسكة ولامعة تحتفظ بشكلها عند رفع الخفاقة، وادمج البياض في المسكربون على ثلاث إضافات بملعقة كبيرة، مع الطي من المركز إلى الخارج للحفاظ على الهواء بالداخل — يجب أن تكون الكريمة النهائية خفيفة، تكاد تكون قابلة للسكب لكنها تحتفظ بقمم لينة. اخلط الإسبريسو البارد والمارسالا في طبق ضحل، ثم اغمس السافواردي قطعةً واحدة في كل مرة — لفترة قصيرة فقط، ثانيتان لكل جانب على الأكثر — فهي إسفنجات، وأصابع السيدات المنقوعة أكثر من اللازم تتحول إلى عجين وتبكي عبر الكريمة، ورتّبها في طبقة واحدة محكمة في قاع طبق 22×30 سم. افرد نصف كريمة المسكربون فوق السافواردي في طبقة متساوية، ثم كرّر — طبقة أخرى محكمة من السافواردي المغموسة، ثم بقية الكريمة فوقها، مسطّحة بالملعقة. غطّ بغشاء بلاستيكي وضع في الثلاجة لمدة 6 ساعات على الأقل، ويفضل طوال الليل — التيراميسو المأكول في نفس اليوم يكون طعمه كأجزائه المنفصلة، أما المرتاح ليلة كاملة فطعمه كحلوى واحدة — قبل التقديم مباشرة، انثر الكاكاو بسخاء عبر مصفاة ناعمة، ابشر فوقه قليلاً من الشوكولاتة الداكنة إذا أحببت، واقطعه بسكين ساخن يُمسح بين الشرائح.",

'zh': "在大碗里把蛋黄和糖一起搅打 4–5 分钟——用手或电动打蛋器——直到颜色变浅、起泡、体积夸张地涨到三倍；糖必须完全溶解（在手指间搓一点试试），这里搅打不足会让你后面得到一份颗粒状的提拉米苏。把马斯卡彭分三次加入，每次都温和地搅匀，让奶油变得顺滑而光亮，再在另一只干净的碗里把蛋白和一小撮盐打到坚挺、光亮的尖角，提起打蛋器时能保持形状，然后用大刮刀分三次把蛋白翻拌入马斯卡彭中——从中心向外翻折，把空气留在里面——最终的奶油应当轻盈、近乎可倒，但仍能挂住柔软的尖。把冷的浓缩咖啡和玛萨拉酒在一只浅盘里调匀，然后把萨沃伊亚迪一根一根地蘸——只是短暂地蘸，每面最多 2 秒——它们是海绵，泡过头的女士手指饼会化成糊并把奶油哭穿，把它们紧密地铺成一层放进 22×30 cm 的盘底。在女士手指饼上铺一层均匀的一半马斯卡彭奶油，然后重复一次——再铺一层紧密蘸过的萨沃伊亚迪，再把剩下的奶油铺在上面，用刮刀刮平。盖上保鲜膜，至少冷藏 6 小时，最好一夜——当天吃的提拉米苏吃起来像它的各个部分；放过一夜的提拉米苏吃起来像一道甜点——上桌前用细筛把可可粉慷慨地撒在表面，喜欢的话再刨一点黑巧克力，切的时候用热刀，每切一片就擦一次。",

'ja': "大きなボウルで卵黄と砂糖を 4〜5 分間 — 手でも電動の泡立て器でも — 色が淡くなり、泡立ち、体積が劇的に 3 倍に膨らむまで泡立てる；指で少しこすってみて砂糖が完全に溶けているはず、ここで混ぜが足りないとあとでざらついたティラミスになる。マスカルポーネを 3 回に分けて加え、加えるたびに優しく泡立てて、クリームが滑らかで艶を持つまで仕上げる、別の清潔なボウルで卵白に塩ひとつまみを加え、泡立て器を持ち上げても形を保つしっかりとした艶のあるピークまで泡立て、大きなヘラで卵白を 3 回に分けてマスカルポーネに合わせ、中央から外側へと畳むように混ぜて空気を残す — 仕上がりのクリームは軽く、ほとんど流れるようでありながら、柔らかなピークを保っているはず。冷たいエスプレッソとマルサラを浅い皿で混ぜ、サヴォイアルディを 1 本ずつ浸す — ほんの一瞬、片面につき最大 2 秒 — 彼らはスポンジで、浸しすぎたレディーフィンガーはどろどろになり、クリームを通して泣き出す、22×30 cm のバットの底にぴったりと 1 段に並べる。マスカルポーネクリームの半量をレディーフィンガーの上に均等に広げ、もう一度繰り返す — もう一段、浸したサヴォイアルディをぴったり並べ、残りのクリームを上に乗せ、ヘラで平らに整える。ラップで覆い、少なくとも 6 時間、理想的には一晩冷蔵庫で寝かせる — 当日のティラミスはそれぞれのパーツの味、一晩寝かせたティラミスは一つのデザートの味になる — 提供直前に細かなふるいに通してたっぷりのココアを表面に振り、好みでダークチョコレートを少し削り、熱いナイフでカット、一切れごとにナイフを拭く。",

'tr': "Yumurta sarılarını şekerle büyük bir kâsede 4–5 dakika boyunca — elle ya da elektrikli mikserle — soluk renkli, köpüklü ve hacmi dramatik olarak üçe katlanana dek çırpın; parmaklarınız arasında biraz ovaladığınızda şeker tamamen erimiş olmalı, burada yetersiz çırpma sonra granüllü bir tiramisu verir. Mascarpone'yi üç partide ekleyin, her ekleyişten sonra hafifçe çırpın, krema pürüzsüz ve parlak olana dek, sonra ayrı temiz bir kâsede yumurta aklarını bir tutam tuzla, çırpıcı kaldırıldığında şeklini koruyan sıkı parlak tepelere ulaşana kadar çırpın, ve akları üç ekleme halinde büyük bir spatula ile mascarpone'ye katlayın, havayı içeride tutmak için merkezden dışa doğru katlayarak — bitmiş krema hafif olmalı, neredeyse dökülebilir ama yumuşak tepeleri koruyan. Soğuk espresso ve Marsala'yı sığ bir kapta karıştırın, sonra savoiardi'yi birer birer batırın — sadece kısa süre, her tarafına en fazla 2 saniye — onlar süngerdir ve aşırı ıslanmış kedi dilleri bulamaca dönüşür ve kremanın içine sızıp ağlar, ve onları 22×30 cm bir kabın tabanına sıkı tek katta yerleştirin. Mascarpone kremasının yarısını kedi dillerinin üzerine eşit bir katmanda yayın, sonra tekrarlayın — bir başka sıkı batırılmış savoiardi katmanı, sonra kalan kremayı üstüne, spatulayla düz yayın. Streç filmle örtün ve en az 6 saat, ideal olarak gece boyu buzdolabında bekletin — aynı gün yenen tiramisu parçaları gibi tadar, gece boyu dinlendirilmiş tiramisu tek bir tatlı gibi tadar — servisten hemen önce ince bir elekten geçirilmiş kakaoyu cömertçe üstüne serpin, isterseniz biraz bitter çikolata rendeleyin, ve dilimler arası silinen sıcak bir bıçakla kesin.",

'it': "Montate i tuorli con lo zucchero in una grande ciotola per 4–5 minuti — a mano o con la frusta elettrica — fino a quando sono pallidi, spumosi e drammaticamente triplicati di volume; lo zucchero deve essere completamente sciolto quando ne strofinate un po' tra le dita, una montata insufficiente qui vi dà un tiramisu granuloso dopo. Aggiungete il mascarpone in tre volte, montando delicatamente dopo ciascuna, fino a quando la crema è liscia e lucida, poi in una ciotola pulita separata montate gli albumi con un pizzico di sale a picchi fermi e lucidi che tengono la forma quando la frusta viene sollevata, e incorporate gli albumi nel mascarpone in tre aggiunte con una spatola grande, piegando dal centro verso l'esterno per mantenere l'aria all'interno — la crema finita deve essere leggera, quasi versabile ma tenendo picchi morbidi. Mescolate l'espresso freddo e il Marsala in una pirofila bassa, poi bagnate i savoiardi uno alla volta — solo brevemente, 2 secondi per lato al massimo — sono spugne, e i savoiardi troppo bagnati si trasformano in poltiglia e piangono attraverso la crema, e disponeteli in un singolo strato stretto sul fondo di una pirofila 22×30 cm. Spalmate metà della crema mascarpone sui savoiardi in uno strato uniforme, poi ripetete — un altro strato stretto di savoiardi bagnati, poi il resto della crema sopra, livellato con la spatola. Coprite con pellicola e refrigerate almeno 6 ore, idealmente tutta la notte — il tiramisu mangiato il giorno stesso sa delle sue parti, il tiramisu riposato tutta la notte sa di un solo dolce — appena prima di servire spolverate generosamente la superficie con cacao passato al setaccio fine, grattugiate sopra un po' di cioccolato fondente se vi piace, e tagliate con un coltello caldo pulito tra una fetta e l'altra.",

'ko': "큰 볼에서 노른자와 설탕을 4–5분 — 손으로든 전동 휘퍼로든 — 색이 옅고 거품이 일고 부피가 3배로 극적으로 늘어날 때까지 휘젓는다; 손가락 사이로 조금 비벼봤을 때 설탕이 완전히 녹아 있어야 하고, 여기서 덜 휘저으면 나중에 거친 티라미수가 된다. 마스카포네를 3회에 나눠 넣고 매번 부드럽게 휘저어 크림이 매끄럽고 윤기 있게 되면, 별도의 깨끗한 볼에서 흰자를 소금 한 꼬집과 함께 단단하고 윤기 있는 뾰족한 봉우리 — 휘퍼를 들었을 때 형태가 유지되는 — 까지 휘젓고, 큰 스패튤라로 흰자를 마스카포네에 3회에 나눠 폴딩하여, 공기를 가두기 위해 중앙에서 바깥으로 접듯이 — 완성된 크림은 가볍고 거의 흐를 정도지만 부드러운 뾰족함을 유지해야 한다. 차가운 에스프레소와 마르살라를 얕은 접시에 섞은 다음 사보이아르디를 하나씩 담근다 — 잠깐, 각 면에 최대 2초 — 그들은 스펀지여서, 너무 많이 적신 레이디핑거는 진흙이 되어 크림을 통해 울게 된다 — 22×30 cm 그릇 바닥에 빽빽이 한 겹으로 놓는다. 마스카포네 크림의 절반을 레이디핑거 위에 균일한 층으로 펴고, 반복한다 — 또 한 겹의 적신 사보이아르디, 그 위에 나머지 크림, 스패튤라로 평평하게. 랩으로 덮어 최소 6시간, 이상적으로는 하룻밤 냉장한다 — 같은 날 먹는 티라미수는 그 부분들의 맛이 나고, 하룻밤 쉰 티라미수는 하나의 디저트 맛이 난다 — 서빙 직전에 고운 체에 코코아를 통과시켜 윗면에 넉넉히 뿌리고, 원한다면 다크초콜릿을 약간 갈아 얹고, 뜨거운 칼로 자르되 슬라이스 사이에 닦는다.",

'hi': "बड़े बाउल में अंडे की पीली ज़र्दी और चीनी को 4–5 मिनट तक — हाथ से या इलेक्ट्रिक बीटर से — तब तक फेंटें जब तक रंग हलका, झागदार और मात्रा नाटकीय रूप से तीन गुनी न हो जाए; जब आप उँगलियों के बीच रगड़ें तो चीनी पूरी तरह घुली होनी चाहिए — यहाँ कम फेंटना बाद में दानेदार तिरामिसु देता है। मस्करपोन को तीन बार में डालें, हर बार धीरे से फेंटते हुए, जब तक क्रीम चिकनी और चमकदार न हो जाए, फिर एक अलग साफ़ बाउल में अंडे के सफ़ेद हिस्से को एक चुटकी नमक के साथ तब तक फेंटें जब तक मज़बूत चमकदार चोटियाँ बनें जो फेंटनी उठाने पर आकार बनाए रखें, और एक बड़ी स्पैटुला से सफ़ेद हिस्से को मस्करपोन में तीन बार में फ़ोल्ड करें, हवा अंदर रखने के लिए केंद्र से बाहर की ओर पलटते हुए — तैयार क्रीम हलकी होनी चाहिए, लगभग बहने योग्य पर नर्म चोटियाँ बनाए रखती। ठंडे एस्प्रेसो और मार्साला को एक उथली डिश में मिलाएँ, फिर savoiardi को एक-एक करके डुबोएँ — बस ज़रा-सा, हर तरफ़ अधिकतम 2 सेकंड — वे स्पंज हैं, और बहुत ज़्यादा भीगे हुए लेडी फ़िंगर्स गाढ़ी लुगदी बन जाते हैं और क्रीम के बीच से रोते हैं, और उन्हें 22×30 सेमी डिश के तले में एक चुस्त परत में रखें। savoiardi पर आधी मस्करपोन क्रीम को एकसमान परत में फैलाएँ, फिर दोहराएँ — और एक चुस्त परत डुबोए हुए savoiardi की, फिर बाकी क्रीम ऊपर से, स्पैटुला से चिकनी की। क्लिंगफ़िल्म से ढक कर कम से कम 6 घंटे, बेहतर हो तो रात भर फ्रिज में रखें — उसी दिन खाया तिरामिसु अपने हिस्सों जैसा स्वाद देता है, रात भर रखा तिरामिसु एक मिठाई जैसा स्वाद देता है — परोसने से ठीक पहले ऊपर महीन छलनी से कोको पाउडर उदारता से छिड़कें, चाहें तो थोड़ी डार्क चॉकलेट कद्दूकस कर लें, और गरम चाक़ू से काटें, हर स्लाइस के बीच पोंछते रहें।",
}

FEATURE_CARDS = {
'en': '[{icon:"🥚", t:"Triple-volume yolks", d:"4–5 minutes whisking until pale, foamy and sugar fully dissolved"}, {icon:"☕", t:"Two-second dip", d:"Any longer and the savoiardi weep through the cream"}, {icon:"❄️", t:"Overnight rest is the dish", d:"Same-day tastes like parts; rested tastes like one dessert"}, {icon:"🍫", t:"Cocoa through a sieve", d:"Fine even cloud, never a dump on top"}]',
'ro': '[{icon:"🥚", t:"Gălbenușuri triplate", d:"4–5 minute de bătut până palide, spumoase, zahăr complet dizolvat"}, {icon:"☕", t:"Înmuiere de 2 secunde", d:"Mai mult și savoiardi plâng prin cremă"}, {icon:"❄️", t:"Odihna peste noapte este desertul", d:"Aceeași zi are gust de părți; odihnit gust de un singur desert"}, {icon:"🍫", t:"Cacao prin sită", d:"Nor fin și uniform, niciodată grămadă deasupra"}]',
'es': '[{icon:"🥚", t:"Yemas triplicadas", d:"4–5 minutos batiendo hasta pálidas, espumosas, azúcar disuelto"}, {icon:"☕", t:"Mojado de 2 segundos", d:"Cualquier más y los savoiardi lloran a través de la crema"}, {icon:"❄️", t:"El reposo nocturno es el postre", d:"Mismo día sabe a partes; reposado sabe a un solo postre"}, {icon:"🍫", t:"Cacao por colador", d:"Nube fina y uniforme, nunca un montón encima"}]',
'fr': '[{icon:"🥚", t:"Jaunes triplés de volume", d:"4–5 minutes à fouetter jusqu\'à pâles, mousseux, sucre dissous"}, {icon:"☕", t:"Trempage de 2 secondes", d:"Plus longtemps et les savoiardi pleurent à travers la crème"}, {icon:"❄️", t:"Le repos nocturne est le dessert", d:"Le jour même goûte des parties ; reposé goûte un seul dessert"}, {icon:"🍫", t:"Cacao au tamis", d:"Nuage fin et uniforme, jamais un tas sur le dessus"}]',
'de': '[{icon:"🥚", t:"Verdreifachte Eigelbe", d:"4–5 Min. schlagen bis blass, schaumig, Zucker gelöst"}, {icon:"☕", t:"Zwei-Sekunden-Tauchen", d:"Länger und die Savoiardi weinen durch die Creme"}, {icon:"❄️", t:"Über-Nacht-Ruhe ist das Dessert", d:"Selbiger Tag schmeckt nach Teilen; geruht nach einem Dessert"}, {icon:"🍫", t:"Kakao durchs Sieb", d:"Feine gleichmäßige Wolke, nie ein Haufen oben drauf"}]',
'pt': '[{icon:"🥚", t:"Gemas triplicadas", d:"4–5 minutos a bater até pálidas, espumosas, açúcar dissolvido"}, {icon:"☕", t:"Mergulho de 2 segundos", d:"Mais tempo e os savoiardi choram através do creme"}, {icon:"❄️", t:"O repouso noturno é a sobremesa", d:"No próprio dia sabe a partes; repousado a uma só sobremesa"}, {icon:"🍫", t:"Cacau pelo coador", d:"Nuvem fina e uniforme, nunca um monte por cima"}]',
'ru': '[{icon:"🥚", t:"Утроённые желтки", d:"4–5 мин взбивания до бледного, пенистого, сахар растворён"}, {icon:"☕", t:"Двух-секундное окунание", d:"Дольше и савоярди плачут сквозь крем"}, {icon:"❄️", t:"Ночной отдых = десерт", d:"В тот же день — вкус частей; отдохнувший — вкус одного десерта"}, {icon:"🍫", t:"Какао через сито", d:"Тонкое равномерное облако, никогда куча сверху"}]',
'ar': '[{icon:"🥚", t:"صفار مضاعف ثلاثة أضعاف", d:"4–5 دقائق خفق حتى يشحب، يتفجر، السكر يذوب"}, {icon:"☕", t:"غمس لثانيتين", d:"أطول من ذلك ويبكي السافواردي عبر الكريمة"}, {icon:"❄️", t:"الراحة الليلية هي الحلوى", d:"اليوم نفسه طعمه أجزاء؛ المرتاح طعم حلوى واحدة"}, {icon:"🍫", t:"كاكاو عبر المصفاة", d:"سحابة ناعمة متجانسة، أبداً ليس كومة فوق"}]',
'zh': '[{icon:"🥚", t:"三倍体积的蛋黄", d:"打 4–5 分钟直到颜色变浅、起泡、糖完全溶解"}, {icon:"☕", t:"两秒钟一蘸", d:"再久一点萨沃伊亚迪就会哭穿奶油"}, {icon:"❄️", t:"过夜静置就是这道甜点", d:"当天吃像各个部分；过夜吃像一道甜点"}, {icon:"🍫", t:"可可粉过筛", d:"细腻均匀的一层云，绝不是一堆扔在上面"}]',
'ja': '[{icon:"🥚", t:"3 倍に膨らむ卵黄", d:"4〜5 分泡立て、淡色・泡立ち・砂糖完全に溶ける"}, {icon:"☕", t:"2 秒の浸し", d:"これ以上長くするとサヴォイアルディがクリームを通して泣く"}, {icon:"❄️", t:"一晩寝かせがこのデザート", d:"当日はパーツの味；寝かせは 1 つのデザートの味"}, {icon:"🍫", t:"ココアはふるいで", d:"細かく均一な雲、決して上にどさっとではない"}]',
'tr': '[{icon:"🥚", t:"Üç katı hacim sarısı", d:"4–5 dk çırpma, soluk, köpüklü, şeker tamamen erimiş"}, {icon:"☕", t:"İki saniyelik daldırma", d:"Daha uzun olursa savoiardi krema içinden ağlar"}, {icon:"❄️", t:"Gecelik dinlenme tatlının kendisidir", d:"Aynı gün parçaların tadı; dinlenmiş tek tatlının tadı"}, {icon:"🍫", t:"Kakaoyu elekten geçir", d:"İnce ve eşit bir bulut, asla üstüne yığın değil"}]',
'it': '[{icon:"🥚", t:"Tuorli triplicati di volume", d:"4–5 minuti di frusta finché pallidi, spumosi, zucchero sciolto"}, {icon:"☕", t:"Bagno di due secondi", d:"Oltre e i savoiardi piangono attraverso la crema"}, {icon:"❄️", t:"Il riposo notturno è il dolce", d:"Stesso giorno sa di parti; riposato sa di un solo dolce"}, {icon:"🍫", t:"Cacao al setaccio", d:"Nuvola fine e uniforme, mai un mucchio sopra"}]',
'ko': '[{icon:"🥚", t:"3배 부피의 노른자", d:"4–5분 휘젓기, 옅고 거품진, 설탕 완전 용해"}, {icon:"☕", t:"2초 담그기", d:"더 길면 사보이아르디가 크림을 통해 운다"}, {icon:"❄️", t:"하룻밤 휴지가 디저트", d:"같은 날은 부분의 맛; 휴지한 것은 하나의 디저트 맛"}, {icon:"🍫", t:"체로 친 코코아", d:"고운 균일한 구름, 위에 더미가 아니라"}]',
'hi': '[{icon:"🥚", t:"तीन गुनी मात्रा वाली ज़र्दी", d:"4–5 मिनट फेंटना — फीकी, झागदार, चीनी पूरी घुली"}, {icon:"☕", t:"दो सेकंड का डुबकी", d:"इससे ज़्यादा और savoiardi क्रीम से रोते हैं"}, {icon:"❄️", t:"रात भर का विश्राम ही मिठाई है", d:"उसी दिन का स्वाद हिस्सों जैसा; रखा हुआ एक मिठाई जैसा"}, {icon:"🍫", t:"छलनी से कोको", d:"महीन एकसमान बादल, ऊपर ढेर कभी नहीं"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*202,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 202 (Tiramisu): {rec_end-rec_start} → {len(new_recipe_block)} chars")
