#!/usr/bin/env python3
"""Rewrite recipe 201 (Osso Buco alla Milanese): 13 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Pat the shanks dry — wet meat steams instead of searing — season aggressively with salt and pepper and dust lightly in flour knocking off the excess, then heat half the butter and all the oil in a heavy braising pan over medium-high heat until foaming, lay the shanks in and do not touch them for 4 minutes until the bottom is deeply browned, flip and do the second side, then lift onto a plate. Lower the heat to medium, add the rest of the butter and the soffritto, and cook gently for 10 minutes until soft and golden at the edges, then pour in the wine, raise the heat, and reduce by half while scraping up the caramelised bits from the bottom of the pan. Stir in the tomatoes, bay leaf and thyme, return the shanks to the pan in a single layer, and pour in just enough stock to come about two-thirds of the way up the meat — the bones should stay exposed so the marrow stays in — and bring to a bare simmer. Cover and braise on the lowest heat or in a 160°C oven for 2 to 2½ hours, turning the shanks gently every 30 minutes so they cook evenly — they are done when the meat slumps off the bone at the press of a spoon and the sauce has thickened to a glossy gravy — then lift them out carefully because the bones and marrow are fragile at this point. While the shanks rest, stir together the lemon zest, garlic and parsley to make the gremolata, place a shank on each plate, spoon over plenty of sauce, and crown with a generous pinch of the raw gremolata — its sharpness cuts the richness and is what makes osso buco Milanese rather than just braised veal — serve with risotto alla milanese, polenta, or a piece of bread for the marrow.",

'ro': "Tamponează ciolanele uscate — carnea udă aburește în loc să se rumenească — asezonează agresiv cu sare și piper și pudrează ușor cu făină scuturând surplusul, apoi încălzește jumătate din unt și tot uleiul într-o cratiță grea de înăbușit pe foc mediu-puternic până spumează, pune ciolanele înăuntru și nu le atinge 4 minute până când partea de jos este adânc rumenită, întoarce-le pentru cealaltă parte, apoi ridică-le pe o farfurie. Micșorează focul la mediu, adaugă restul de unt și soffritto-ul, și gătește blând 10 minute până sunt moi și aurii la margini, apoi toarnă vinul, ridică focul și redu la jumătate în timp ce răzui bucățile caramelizate de pe fundul tigăii. Încorporează roșiile, foaia de dafin și cimbrul, întoarce ciolanele în tigaie într-un singur strat, și toarnă suficient fond cât să acopere aproximativ două treimi din carne — oasele trebuie să rămână expuse pentru ca măduva să nu iasă — și adu la o fierbere abia perceptibilă. Acoperă și înăbușe pe focul cel mai mic sau într-un cuptor de 160°C 2 până la 2 ore și jumătate, întorcând ciolanele blând la fiecare 30 de minute pentru a se găti uniform — sunt gata când carnea se desprinde de pe os la presiunea unei linguri și sosul s-a îngroșat la o glazură lucioasă — apoi ridică-le cu grijă pentru că oasele și măduva sunt fragile în acest punct. Cât se odihnesc ciolanele, amestecă coaja de lămâie, usturoiul și pătrunjelul pentru gremolata, pune un ciolan pe fiecare farfurie, toarnă peste mult sos, și încununează cu un vârf generos de gremolata crudă — picătura ei de acid taie bogăția și este ceea ce face osso buco milanez în loc de simplu vițel înăbușit — servește cu risotto alla milanese, polenta sau o bucată de pâine pentru măduvă.",

'es': "Seca los jarretes con papel — la carne húmeda se evapora en vez de sellarse — sazona agresivamente con sal y pimienta y enharina ligeramente sacudiendo el exceso, después calienta la mitad de la mantequilla y todo el aceite en una cazuela pesada a fuego medio-alto hasta que esté espumosa, coloca los jarretes y no los toques durante 4 minutos hasta que el fondo esté profundamente dorado, voltea para hacer el segundo lado, después retira a un plato. Baja el fuego a medio, añade el resto de la mantequilla y el sofrito, y cocina suavemente 10 minutos hasta que esté blando y dorado en los bordes, después vierte el vino, sube el fuego y reduce a la mitad mientras raspas los pegotes caramelizados del fondo de la sartén. Incorpora los tomates, el laurel y el tomillo, devuelve los jarretes a la sartén en una sola capa, y vierte caldo justo hasta cubrir unas dos terceras partes de la carne — los huesos deben quedar expuestos para que la médula no se salga — y lleva a un hervor apenas perceptible. Tapa y brasea al fuego más bajo o en horno a 160°C de 2 a 2½ horas, volteando los jarretes suavemente cada 30 minutos para que se cocinen uniformemente — están listos cuando la carne se desprende del hueso al apretar con una cuchara y la salsa se ha espesado en una glasa brillante — después sácalos con cuidado porque los huesos y la médula son frágiles en este punto. Mientras los jarretes reposan, mezcla la ralladura de limón, el ajo y el perejil para hacer la gremolada, coloca un jarrete en cada plato, cubre con abundante salsa y corona con una pizca generosa de gremolada cruda — su acidez corta la riqueza y es lo que hace al osso buco milanés en vez de simple ternera braseada — sirve con risotto alla milanese, polenta o un pedazo de pan para la médula.",

'fr': "Séchez les jarrets — la viande humide cuit à la vapeur au lieu de saisir — assaisonnez agressivement avec sel et poivre et farinez légèrement en secouant l'excès, puis faites chauffer la moitié du beurre et toute l'huile dans une cocotte épaisse à feu moyen-vif jusqu'à ce que ça mousse, posez les jarrets et ne les touchez pas pendant 4 minutes jusqu'à ce que le fond soit profondément doré, retournez pour le second côté, puis transférez sur une assiette. Baissez le feu à moyen, ajoutez le reste du beurre et le soffritto, et faites cuire doucement 10 minutes jusqu'à ce que ce soit fondant et doré sur les bords, puis versez le vin, montez le feu, et réduisez de moitié tout en grattant les sucs caramélisés du fond de la cocotte. Incorporez les tomates, la feuille de laurier et le thym, remettez les jarrets dans la cocotte en une seule couche, et versez juste assez de bouillon pour atteindre environ les deux tiers de la viande — les os doivent rester exposés pour que la moelle reste dedans — et portez à frémissement à peine perceptible. Couvrez et faites braiser à feu très doux ou au four à 160°C pendant 2 à 2½ heures, en retournant les jarrets délicatement toutes les 30 minutes pour qu'ils cuisent uniformément — ils sont prêts quand la viande se détache de l'os sous la pression d'une cuillère et que la sauce s'est épaissie en une glace brillante — puis sortez-les avec précaution car les os et la moelle sont fragiles à ce stade. Pendant que les jarrets reposent, mélangez le zeste de citron, l'ail et le persil pour faire la gremolata, placez un jarret dans chaque assiette, nappez généreusement de sauce, et couronnez d'une pincée généreuse de gremolata crue — son acidité tranche la richesse et c'est ce qui fait de l'osso buco milanais plutôt que du simple veau braisé — servez avec risotto alla milanese, polenta, ou un morceau de pain pour la moelle.",

'de': "Tupfen Sie die Beinscheiben trocken — feuchtes Fleisch dampft statt zu braten — würzen Sie aggressiv mit Salz und Pfeffer und mehlieren Sie leicht, klopfen Sie den Überschuss ab, dann erhitzen Sie die Hälfte der Butter und das gesamte Öl in einem schweren Schmortopf bei mittlerer bis hoher Hitze bis es schäumt, legen Sie die Beinscheiben hinein und berühren Sie sie 4 Minuten lang nicht, bis der Boden tief gebräunt ist, wenden und die zweite Seite anbraten, dann auf einen Teller heben. Reduzieren Sie die Hitze auf mittel, fügen Sie den Rest der Butter und das Soffritto hinzu, und garen Sie sanft 10 Minuten bis es weich und an den Rändern golden ist, dann gießen Sie den Wein an, erhöhen Sie die Hitze und reduzieren Sie auf die Hälfte, während Sie die karamellisierten Stückchen vom Pfannenboden lösen. Geben Sie die Tomaten, das Lorbeerblatt und den Thymian dazu, legen Sie die Beinscheiben in einer Schicht zurück in die Pfanne, und gießen Sie gerade so viel Brühe an, dass etwa zwei Drittel des Fleisches bedeckt sind — die Knochen sollten freiliegen, damit das Mark drin bleibt — und bringen Sie alles zum sanften Köcheln. Zudecken und auf niedrigster Hitze oder in einem 160°C Ofen 2 bis 2½ Stunden schmoren, die Beinscheiben alle 30 Minuten sanft wenden, damit sie gleichmäßig garen — sie sind fertig, wenn das Fleisch beim Druck eines Löffels vom Knochen rutscht und die Sauce zu einer glänzenden Glasur eingedickt ist — dann vorsichtig herausnehmen, weil Knochen und Mark in diesem Stadium fragil sind. Während die Beinscheiben ruhen, mischen Sie Zitronenschale, Knoblauch und Petersilie zur Gremolata, geben Sie eine Beinscheibe auf jeden Teller, löffeln Sie reichlich Sauce darüber und krönen Sie mit einer großzügigen Prise roher Gremolata — ihre Schärfe schneidet die Fülle und macht es zum Mailänder Osso Buco statt nur geschmortem Kalbsfleisch — servieren Sie mit Risotto alla Milanese, Polenta oder einem Stück Brot für das Mark.",

'pt': "Seque os ossobucos com papel — a carne húmida evapora em vez de selar — tempere agressivamente com sal e pimenta e polvilhe ligeiramente em farinha sacudindo o excesso, depois aqueça metade da manteiga e todo o azeite numa caçarola pesada em lume médio-alto até espumar, coloque os ossobucos e não toque neles durante 4 minutos até o fundo estar profundamente dourado, vire para o segundo lado, depois retire para um prato. Baixe o lume a médio, junte o resto da manteiga e o sofrito, e cozinhe suavemente 10 minutos até estar macio e dourado nas bordas, depois verta o vinho, suba o lume, e reduza a metade enquanto raspa os pedaços caramelizados do fundo da panela. Junte os tomates, a folha de louro e o tomilho, devolva os ossobucos à panela numa única camada, e verta caldo até cobrir cerca de dois terços da carne — os ossos devem ficar expostos para que o tutano não escape — e leve a uma fervura quase imperceptível. Tape e estufe no lume mais baixo ou em forno a 160°C 2 a 2½ horas, virando os ossobucos suavemente a cada 30 minutos para cozer uniformemente — estão prontos quando a carne se desprende do osso à pressão de uma colher e o molho engrossou numa glace brilhante — depois retire-os com cuidado porque os ossos e o tutano estão frágeis nesta altura. Enquanto os ossobucos descansam, misture a raspa de limão, o alho e a salsa para fazer a gremolata, coloque um ossobuco em cada prato, regue com bastante molho, e coroe com uma pitada generosa de gremolata crua — a sua acidez corta a riqueza e é o que faz osso buco milanês em vez de apenas vitela estufada — sirva com risotto alla milanese, polenta ou um pedaço de pão para o tutano.",

'ru': "Обсушите голяшки — мокрое мясо паруется вместо обжарки — обильно посолите и поперчите и слегка обваляйте в муке, стряхнув излишек, затем разогрейте половину сливочного масла и всё растительное в тяжёлой жаровне на среднем-высоком огне до пены, выложите голяшки и не трогайте 4 минуты, пока низ не подрумянится глубоко, переверните для второй стороны, затем переложите на тарелку. Уменьшите огонь до среднего, добавьте оставшееся масло и софритто, и томите аккуратно 10 минут, пока не размягчится и не подзолотится по краям, затем влейте вино, увеличьте огонь и уварите вдвое, соскребая карамелизованные кусочки со дна. Вмешайте помидоры, лавровый лист и тимьян, верните голяшки в жаровню одним слоем, и влейте бульон, чтобы он покрыл мясо примерно на две трети — кости должны оставаться открытыми, чтобы костный мозг не вытек — и доведите до едва заметного кипения. Накройте и тушите на самом слабом огне или в духовке 160°C 2–2½ часа, аккуратно переворачивая голяшки каждые 30 минут для равномерного приготовления — они готовы, когда мясо отваливается от кости при нажатии ложкой и соус загустел до глянцевой глазури — затем достаньте их осторожно, поскольку кости и мозг хрупки в этот момент. Пока голяшки отдыхают, смешайте лимонную цедру, чеснок и петрушку для гремолаты, положите голяшку на каждую тарелку, полейте обильным соусом, и увенчайте щедрой щепоткой сырой гремолаты — её резкость прорезает жирность и это то, что делает osso buco по-милански, а не просто тушёной телятиной — подавайте с ризотто алла миланезе, полентой или куском хлеба для мозга.",

'ar': "جفّف قطع الكاحل بمنشفة ورقية — اللحم الرطب يتبخّر بدلاً من أن يُحمّر — تبّلها بقوة بالملح والفلفل ورشّها بالطحين قليلاً مع نفض الفائض، ثم سخّن نصف الزبدة وكامل الزيت في قدر طهي بطيء ثقيل على نار متوسطة-عالية حتى يرغو، ضع قطع الكاحل ولا تلمسها لمدة 4 دقائق حتى يصبح القعر بنياً عميقاً، اقلبها للجانب الآخر، ثم ارفعها على طبق. اخفض النار إلى متوسطة، أضف باقي الزبدة والصوفريتو، واطبخ برفق 10 دقائق حتى يصبح طرياً وذهبياً عند الأطراف، ثم اسكب النبيذ، ارفع النار، وقلّل إلى النصف مع كشط القطع المتكرملة من قعر القدر. أضف الطماطم وورقة الغار والزعتر، أعد قطع الكاحل إلى القدر في طبقة واحدة، واسكب مرقاً بما يكفي تماماً ليصل إلى ثلثي ارتفاع اللحم — يجب أن تبقى العظام مكشوفة لتظل الفقمة فيها — وأوصلها إلى غليان بالكاد محسوس. غطّ واطبخ ببطء على أهدأ نار أو في فرن 160°م لمدة 2 إلى 2½ ساعة، مع تقليب قطع الكاحل برفق كل 30 دقيقة كي تنضج بانتظام — تكون جاهزة حين يسقط اللحم عن العظم عند الضغط بملعقة وتثخن الصلصة إلى طلاء لامع — ثم ارفعها بحذر لأن العظام والفقمة هشّة في هذه المرحلة. أثناء راحة قطع الكاحل، اخلط قشر الليمون والثوم والبقدونس لصنع الغريمولاتا، ضع قطعة كاحل في كل طبق، اسكب فوقها كمية وفيرة من الصلصة، وتوّجها برشة سخية من الغريمولاتا الخام — حدّتها تقطع الثراء وهي ما يجعله أوسو بوكو ميلاني بدلاً من مجرد لحم عجل مطهو — قدّمه مع ريزوتو ميلاني أو بولينتا أو قطعة خبز للفقمة.",

'zh': "把小牛胫骨用纸巾拍干——湿肉会蒸而不是煎——大量地用盐和胡椒调味，再轻轻撒上面粉，把多余的拍掉，然后在厚锅中以中高火加热一半黄油和所有油，直到起泡，把胫骨放进去，4 分钟不要动它，直到底部煎成深棕色，翻面煎另一面，再夹到盘子上。把火调到中火，加入剩下的黄油和 soffritto，温和地煮 10 分钟，直到变软、边缘发金，然后倒入葡萄酒，调大火力，收汁到一半，同时把锅底焦化的部分刮起来。加入番茄、月桂叶和百里香，把胫骨单层放回锅里，再倒入足够的高汤，刚好淹到肉的三分之二——骨头必须露在汤面之上，骨髓才不会流出来——然后烧到微微冒泡。盖盖以最小火或放进 160°C 的烤箱炖 2 至 2½ 小时，每 30 分钟轻轻翻一次胫骨，让它们均匀受热——当用勺子一压肉就从骨头上滑下、酱汁收成发亮的浓汁时，就好了——然后小心夹出，因为此时骨头和骨髓都很脆弱。胫骨歇着的时候，把柠檬皮、大蒜和欧芹拌在一起做 gremolata，每盘放一块胫骨，浇上大量酱汁，再顶上一小撮生 gremolata——它的尖锐酸味切开浓厚，正是让这道菜成为「米兰式 osso buco」而不只是普通炖小牛肉的关键——配 risotto alla milanese、polenta 或一块面包蘸骨髓食用。",

'ja': "スネ肉をペーパーでよく拭き — 濡れた肉は焼き付かず蒸気が立つ — 塩こしょうをしっかり振り、小麦粉を薄くまぶして余分を払い、厚手の鍋に半量のバターと全量の油を強めの中火で熱して泡が立ったら、スネ肉を並べて 4 分間動かさず、底面が深く色付くまで焼き、ひっくり返してもう片面も焼き、皿に取り出す。火を中火に下げて、残りのバターとソフリットを加え、優しく 10 分炒めて柔らかく縁が金色になるまで仕上げ、ワインを注ぎ火を強めて、鍋底のキャラメル化した部分をこそげながら半量まで煮詰める。トマト、ベイリーフ、タイムを混ぜ、スネ肉を一段に戻し入れ、肉の高さの 3 分の 2 までブイヨンを注ぐ — 骨は露出させておき、骨髄が逃げないように — そして火を最弱でぎりぎり沸騰の状態にする。蓋をして最弱火、または 160℃ のオーブンで 2 〜 2 時間半、スネ肉を 30 分ごとに優しく返しながら均一に火を通す — スプーンで押すと肉が骨から崩れ落ち、ソースが艶のあるグレービー状になったら出来上がり — その時点で骨と骨髄は脆いので、注意して取り出す。スネ肉を休ませる間に、レモンの皮、にんにく、パセリを混ぜてグレモラータを作り、皿に 1 個ずつスネ肉を盛り、たっぷりのソースをかけ、生のグレモラータをひとつまみたっぷり王冠のように乗せる — そのキレが豊かさを断ち切り、ただの煮込み仔牛肉ではなく『ミラノ風オッソブーコ』にする — リゾット・アッラ・ミラネーゼ、ポレンタ、または骨髄を取るためのパンと共に供する。",

'tr': "Et parçalarını kâğıt havluyla kurula — ıslak et kavurmak yerine buharlaşır — bolca tuz ve karabiberle baharatla ve hafifçe una bula, fazlasını silkele, sonra ağır bir güveç tavasında orta-yüksek ateşte yarım tereyağı ve tüm yağı köpürene dek ısıt, et parçalarını içine yerleştir ve alt kısım derin kahverengileşene dek 4 dakika dokunma, çevir ve diğer tarafı da yap, sonra bir tabağa al. Ateşi orta seviyeye düşür, kalan tereyağı ve sofritoyu ekle ve 10 dakika nazikçe pişir — yumuşayıp kenarları altın olana dek — sonra şarabı dök, ateşi yükselt, ve tavanın dibindeki karamelize kısımları sıyırarak yarıya kadar uçur. Domatesleri, defne yaprağını ve kekik ekle, et parçalarını tek katmanda tavaya geri al, ve etin yaklaşık üçte ikisine ulaşacak kadar et suyu dök — kemikler açık kalsın ki ilik içinde kalsın — ve neredeyse algılanamayan bir kaynamaya getir. Kapağı kapat ve en kısık ateşte veya 160°C fırında 2 ila 2½ saat, et parçalarını her 30 dakikada bir nazikçe çevirerek eşit pişmesini sağla — kaşığın baskısıyla et kemikten düştüğünde ve sos parlak bir kıvamlı sosa dönüştüğünde hazırdır — sonra kemikler ve ilik bu noktada hassas olduğu için dikkatlice çıkar. Et parçaları dinlenirken, limon kabuğu, sarımsak ve maydanozu karıştırarak gremolata hazırla, her tabağa bir et parçası koy, üzerine bolca sostan dök ve cömert bir tutam çiğ gremolata ile taçlandır — sertliği zenginliği keser ve bunu sadece haşlanmış dana eti değil, Milano usulü osso buco yapan şeydir — risotto alla milanese, polenta veya iliği almak için bir parça ekmekle servis et.",

'it': "Asciugate gli stinchi — la carne bagnata cuoce a vapore invece di rosolare — conditeli aggressivamente con sale e pepe e infarinate leggermente scrollando l'eccesso, poi scaldate metà del burro e tutto l'olio in una pentola da brasare pesante a fuoco medio-alto fino a quando schiumeggia, adagiate gli stinchi e non toccateli per 4 minuti finché il fondo non è profondamente rosolato, girate e fate il secondo lato, poi sollevateli su un piatto. Abbassate il fuoco a medio, aggiungete il resto del burro e il soffritto, e cuocete dolcemente per 10 minuti finché non è morbido e dorato sui bordi, poi versate il vino, alzate la fiamma, e riducete di metà raschiando i fondi caramellati dal fondo della pentola. Unite i pomodori, l'alloro e il timo, riportate gli stinchi nella pentola in un singolo strato, e versate brodo quanto basta a coprire circa due terzi della carne — le ossa devono restare esposte affinché il midollo resti dentro — e portate a un sobbollire appena percettibile. Coprite e brasate a fuoco bassissimo o in forno a 160°C per 2 a 2½ ore, girando gli stinchi delicatamente ogni 30 minuti perché cuociano uniformemente — sono pronti quando la carne si stacca dall'osso al tocco di un cucchiaio e il sugo si è addensato in una salsa lucida — poi sollevateli con cura perché ossa e midollo sono fragili a questo punto. Mentre gli stinchi riposano, mescolate la scorza di limone, l'aglio e il prezzemolo per fare la gremolata, mettete uno stinco su ogni piatto, versate sopra abbondante sugo, e incoronate con una generosa presa di gremolata cruda — la sua acidità taglia la ricchezza ed è ciò che lo rende osso buco alla milanese piuttosto che semplice vitello brasato — servite con risotto alla milanese, polenta o un pezzo di pane per il midollo.",

'ko': "정강이살을 페이퍼타월로 두드려 물기를 빼고 — 젖은 고기는 시어링되지 않고 증기만 — 소금과 후추로 적극적으로 간하고 밀가루를 가볍게 묻혀 여분을 떨어내고, 두꺼운 브레이즈팬에 버터 절반과 기름 전부를 중강불에 거품이 일 때까지 가열한 다음, 정강이살을 넣고 4분간 건드리지 않아 바닥이 진한 갈색이 될 때까지 두고, 뒤집어 반대편도 같은 식으로 굽고, 접시에 옮긴다. 불을 중불로 낮추고, 남은 버터와 소프리토(양파·당근·셀러리 다진 것)를 넣고 10분간 부드럽고 가장자리가 황금색이 될 때까지 부드럽게 익힌 다음, 와인을 붓고 불을 올려, 팬 바닥의 캐러멜화된 부분을 긁어내면서 절반으로 졸인다. 토마토, 월계수잎, 타임을 넣고, 정강이살을 한 겹으로 다시 팬에 놓고, 고기 높이의 약 2/3까지만 육수를 부어 — 뼈는 노출되어야 골수가 빠지지 않는다 — 거의 느껴지지 않는 약한 끓음으로 가져간다. 뚜껑을 덮고 가장 약한 불 또는 160°C 오븐에서 2~2시간 30분간, 정강이살을 30분마다 부드럽게 뒤집어 고르게 익게 한다 — 숟가락으로 누르면 뼈에서 살이 떨어지고 소스가 윤기 있는 그레이비로 농축되면 완성 — 이 시점에 뼈와 골수가 약하기 때문에 조심스럽게 들어낸다. 정강이살이 휴지하는 동안, 레몬 제스트, 마늘, 파슬리를 섞어 그레몰라타를 만들고, 접시마다 정강이살을 하나씩 놓고, 그 위에 소스를 풍부하게 끼얹고, 생 그레몰라타를 한 꼬집 넉넉히 왕관처럼 올린다 — 그 날카로움이 풍부함을 자르고, 이것이 단순한 송아지 브레이즈가 아닌 밀라노식 오소부코로 만드는 핵심 — 리조토 알라 밀라네세, 폴렌타, 또는 골수를 위한 빵 한 조각과 함께 낸다.",

'hi': "शैंक्स को कागज़ से थपथपा कर सुखाएँ — गीला मांस सीयर होने के बजाय भाप बनाता है — नमक और काली मिर्च से ज़ोरदार ढंग से सीज़न करें और हलके आटे में लपेट कर अतिरिक्त झाड़ दें, फिर एक भारी ब्रेज़िंग पैन में मध्यम-तेज़ आँच पर आधा मक्खन और पूरा तेल झाग आने तक गरम करें, शैंक्स को रखें और 4 मिनट तक न छुएँ जब तक नीचे का हिस्सा गहरा भूरा न हो जाए, पलट कर दूसरा साइड करें, फिर एक प्लेट पर निकाल लें। आँच को मध्यम कर दें, बाक़ी मक्खन और soffritto (प्याज़-गाजर-अजवाइन डंठल) डालें, और हलके से 10 मिनट पकाएँ जब तक नर्म और किनारों पर सुनहरा न हो जाए, फिर शराब डालें, आँच बढ़ाएँ, और पैन के तले से कैरेमलाइज़ हुए हिस्सों को खुरचते हुए आधी तक रिड्यूस करें। टमाटर, तेज़पत्ता और थाइम मिलाएँ, शैंक्स को एक परत में पैन में वापस रखें, और मांस की लगभग दो-तिहाई ऊँचाई तक स्टॉक डालें — हड्डियाँ ऊपर खुली रहनी चाहिए ताकि मज्जा अंदर रहे — और बेहद हलकी उबाल पर लाएँ। ढक कर सबसे धीमी आँच पर या 160°C ओवन में 2 से 2½ घंटे तक ब्रेज़ करें, हर 30 मिनट पर शैंक्स को धीरे से पलट कर एकसमान पकने दें — जब चम्मच के दबाव से मांस हड्डी से अलग हो जाए और सॉस चमकदार ग्रेवी में सिमट जाए तब तैयार — फिर सावधानी से निकालें क्योंकि हड्डियाँ और मज्जा इस वक़्त नाज़ुक हैं। शैंक्स के विश्राम के दौरान, नीबू का छिलका, लहसुन और पार्सले मिला कर gremolata बनाएँ, हर प्लेट पर एक शैंक रखें, ऊपर से ख़ूब सॉस डालें, और कच्ची gremolata की एक भरी चुटकी से ताज पहनाएँ — उसका तीख़ापन समृद्धि को काटता है और यही इसे मिलानी osso buco बनाता है, सिर्फ़ ब्रेज़्ड वील नहीं — risotto alla milanese, polenta, या मज्जा के लिए ब्रेड के टुकड़े के साथ परोसें।",
}

FEATURE_CARDS = {
'en': '[{icon:"🥩", t:"Dry sear, deep brown", d:"4 minutes without touching — wet meat steams"}, {icon:"🦴", t:"Marrow stays in the bone", d:"Stock two-thirds up; bones exposed above the line"}, {icon:"⏱️", t:"2½ hours at 160°C", d:"Done when meat slumps off the bone at a spoon press"}, {icon:"🍋", t:"Raw gremolata at the end", d:"Lemon zest + garlic + parsley cuts through the richness"}]',
'ro': '[{icon:"🥩", t:"Sear uscat, brun adânc", d:"4 minute fără să atingi — carnea udă aburește"}, {icon:"🦴", t:"Măduva rămâne în os", d:"Fond până la două treimi; oasele expuse deasupra liniei"}, {icon:"⏱️", t:"2½ ore la 160°C", d:"Gata când carnea cade de pe os la presiunea lingurii"}, {icon:"🍋", t:"Gremolata crudă la final", d:"Coajă de lămâie + usturoi + pătrunjel taie bogăția"}]',
'es': '[{icon:"🥩", t:"Sellado seco, dorado profundo", d:"4 minutos sin tocar — la carne húmeda se vaporiza"}, {icon:"🦴", t:"La médula se queda en el hueso", d:"Caldo a dos tercios; huesos expuestos sobre la línea"}, {icon:"⏱️", t:"2½ horas a 160°C", d:"Listo cuando la carne cede al hueso con una cuchara"}, {icon:"🍋", t:"Gremolada cruda al final", d:"Ralladura de limón + ajo + perejil corta la riqueza"}]',
'fr': '[{icon:"🥩", t:"Saisie sèche, brun profond", d:"4 minutes sans toucher — la viande humide cuit à la vapeur"}, {icon:"🦴", t:"La moelle reste dans l\'os", d:"Bouillon aux deux tiers ; os exposés au-dessus de la ligne"}, {icon:"⏱️", t:"2½ heures à 160°C", d:"Prêt quand la viande cède à l\'os sous la cuillère"}, {icon:"🍋", t:"Gremolata crue à la fin", d:"Zeste de citron + ail + persil tranche la richesse"}]',
'de': '[{icon:"🥩", t:"Trockenes Anbraten, tief gebräunt", d:"4 Minuten ohne Berühren — feuchtes Fleisch dampft"}, {icon:"🦴", t:"Mark bleibt im Knochen", d:"Brühe bis zu zwei Dritteln; Knochen über der Linie"}, {icon:"⏱️", t:"2½ Stunden bei 160°C", d:"Fertig wenn Fleisch beim Löffeldruck vom Knochen fällt"}, {icon:"🍋", t:"Rohe Gremolata am Ende", d:"Zitronenschale + Knoblauch + Petersilie schneidet die Fülle"}]',
'pt': '[{icon:"🥩", t:"Selagem seca, castanho profundo", d:"4 minutos sem tocar — carne húmida evapora"}, {icon:"🦴", t:"Tutano fica no osso", d:"Caldo a dois terços; ossos expostos acima da linha"}, {icon:"⏱️", t:"2½ horas a 160°C", d:"Pronto quando a carne cede ao osso à pressão da colher"}, {icon:"🍋", t:"Gremolata crua no fim", d:"Raspa de limão + alho + salsa corta a riqueza"}]',
'ru': '[{icon:"🥩", t:"Сухая обжарка, глубокий бурый", d:"4 минуты без касания — мокрое мясо паруется"}, {icon:"🦴", t:"Костный мозг остаётся в кости", d:"Бульон до двух третей; кости открыты над линией"}, {icon:"⏱️", t:"2½ часа при 160°C", d:"Готово когда мясо отваливается от кости под ложкой"}, {icon:"🍋", t:"Сырая гремолата в конце", d:"Цедра + чеснок + петрушка прорезает жирность"}]',
'ar': '[{icon:"🥩", t:"تسوية جافة، بنّي عميق", d:"4 دقائق بدون لمس — اللحم الرطب يتبخّر"}, {icon:"🦴", t:"الفقمة تبقى في العظم", d:"المرق إلى الثلثين؛ العظام مكشوفة فوق الخط"}, {icon:"⏱️", t:"2½ ساعة على 160°م", d:"جاهز حين يسقط اللحم عن العظم بضغطة ملعقة"}, {icon:"🍋", t:"غريمولاتا نيئة في النهاية", d:"قشر ليمون + ثوم + بقدونس يقطع الثراء"}]',
'zh': '[{icon:"🥩", t:"干煎，深棕色", d:"4 分钟不要动——湿肉只会蒸发"}, {icon:"🦴", t:"骨髓留在骨头里", d:"高汤到三分之二；骨头露在汤面上方"}, {icon:"⏱️", t:"160°C 慢炖 2½ 小时", d:"勺子轻压肉就离骨时即成"}, {icon:"🍋", t:"末尾的生 gremolata", d:"柠檬皮 + 大蒜 + 欧芹切开浓厚"}]',
'ja': '[{icon:"🥩", t:"乾いた焼き付け、深い茶色", d:"4 分間動かさない — 濡れた肉は蒸気立つ"}, {icon:"🦴", t:"骨髄は骨の中に残す", d:"ブイヨンは 3 分の 2 まで；骨はその上に出す"}, {icon:"⏱️", t:"160℃ で 2 時間半", d:"スプーンの圧で肉が骨から崩れ落ちれば完成"}, {icon:"🍋", t:"最後の生グレモラータ", d:"レモンの皮 + にんにく + パセリが豊かさを断ち切る"}]',
'tr': '[{icon:"🥩", t:"Kuru kavurma, derin kahverengi", d:"4 dakika dokunmadan — ıslak et buharlanır"}, {icon:"🦴", t:"İlik kemikte kalır", d:"Su et yüksekliğinin üçte ikisine; kemikler üstte"}, {icon:"⏱️", t:"160°C\'de 2½ saat", d:"Kaşık baskısıyla et kemikten düştüğünde hazır"}, {icon:"🍋", t:"Sonda çiğ gremolata", d:"Limon kabuğu + sarımsak + maydanoz zenginliği keser"}]',
'it': '[{icon:"🥩", t:"Rosolatura asciutta, marrone profondo", d:"4 minuti senza toccare — la carne bagnata cuoce a vapore"}, {icon:"🦴", t:"Il midollo resta nell\'osso", d:"Brodo ai due terzi; ossa esposte sopra la linea"}, {icon:"⏱️", t:"2½ ore a 160°C", d:"Pronto quando la carne si stacca dall\'osso al cucchiaio"}, {icon:"🍋", t:"Gremolata cruda alla fine", d:"Scorza di limone + aglio + prezzemolo taglia la ricchezza"}]',
'ko': '[{icon:"🥩", t:"마른 시어링, 진한 갈색", d:"4분간 건드리지 말기 — 젖은 고기는 증기만 난다"}, {icon:"🦴", t:"골수는 뼈 안에 머문다", d:"육수는 고기 높이의 2/3까지; 뼈는 위로 노출"}, {icon:"⏱️", t:"160°C에서 2½시간", d:"숟가락 누름에 고기가 뼈에서 떨어지면 완성"}, {icon:"🍋", t:"마지막에 생 그레몰라타", d:"레몬 제스트 + 마늘 + 파슬리가 풍부함을 자른다"}]',
'hi': '[{icon:"🥩", t:"सूखा सीयर, गहरा भूरा", d:"4 मिनट बिना छुए — गीला मांस सिर्फ़ भाप बनाता है"}, {icon:"🦴", t:"मज्जा हड्डी में रहती है", d:"स्टॉक मांस की दो-तिहाई ऊँचाई तक; हड्डियाँ ऊपर खुली"}, {icon:"⏱️", t:"160°C पर 2½ घंटे", d:"चम्मच के दबाव से मांस हड्डी से अलग होने पर तैयार"}, {icon:"🍋", t:"अंत में कच्ची gremolata", d:"नीबू का छिलका + लहसुन + पार्सले समृद्धि को काटता है"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*201,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 201 (Osso Buco): {rec_end-rec_start} → {len(new_recipe_block)} chars")
