#!/usr/bin/env python3
"""Rewrite recipe 207 (Rogan Josh): 11 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Heat the mustard oil in a heavy pan until it just begins to smoke, then pull it off the heat for a moment — letting it smoke neutralises the raw pungency without scorching — and return to medium heat, add the whole spices and bay leaf, and let them perfume the oil for 30 seconds. Add the lamb in a single layer and brown well on all sides for 8–10 minutes (this is the only browning the dish gets, so let the colour develop properly), then stir in the asafoetida, ginger powder and fennel powder and let them coat the meat in the hot oil for another minute. Whisk the yoghurt with the Kashmiri chilli paste and a tablespoon of cold water, then add it to the pan a ladleful at a time stirring continuously after each addition — going slowly keeps the yoghurt from splitting — add the salt, lower the heat and cook covered for 10 minutes until the yoghurt has melted into a glossy red base. Pour in 500 ml of hot water, bring back to a simmer, then drop the heat to its lowest and braise covered for an hour and 20 minutes, stirring every 20 minutes, until the lamb yields to a spoon and the gravy is thin, glossy and a deep mahogany red; swirl the saffron milk through 5 minutes before the end without fully stirring it out. Rest off the heat for 10 minutes before serving with steamed basmati — Rogan Josh is meant to be soup-like, brilliantly coloured and aromatic rather than spicy hot, the heat supplied by the meat, the colour by the chillies, and the perfume by everything else.",

'ro': "Încălzește uleiul de muștar într-o oală groasă până începe abia să fumege, apoi ia-l de pe foc pentru o clipă — fumul neutralizează asprimea fără să-l ardă — pune-l înapoi pe foc mediu, adaugă mirodeniile întregi și foaia de dafin și las-le să parfumeze uleiul 30 de secunde. Adaugă mielul într-un singur strat și rumenește-l bine pe toate părțile 8–10 minute (aceasta este singura rumenire pe care o primește felul, așa că las-o să capete culoare cum trebuie), apoi încorporează asafoetida, pudra de ghimbir și cea de fenicul și las-le să îmbrace carnea în uleiul fierbinte încă un minut. Bate iaurtul cu pasta de chili Kashmiri și o lingură de apă rece, apoi adaugă-l în oală câte un polonic, amestecând continuu după fiecare adăugare — încet, iaurtul nu se taie — adaugă sarea, micșorează focul și gătește acoperit 10 minute, până când iaurtul s-a topit într-o bază roșie și lucioasă. Toarnă 500 ml apă fierbinte, adu din nou la fierbere, apoi coboară focul la minim și înăbușe acoperit o oră și 20 de minute, amestecând la fiecare 20 de minute, până când mielul cedează la lingură și sosul este subțire, lucios și de un roșu adânc de mahon; introdu laptele cu șofran cu 5 minute înainte de final, doar amestecând-l ușor. Odihnește departe de foc 10 minute înainte de a servi cu orez basmati la abur — Rogan Josh trebuie să fie aproape ca o supă, viu colorată și parfumată mai degrabă decât picantă, căldura vine din carne, culoarea din ardei, iar parfumul din tot restul.",

'es': "Calienta el aceite de mostaza en una olla pesada hasta que apenas empiece a humear, después retírala del fuego un instante — el humo neutraliza la aspereza sin quemarse — devuelve a fuego medio, añade las especias enteras y la hoja de laurel, y deja que perfumen el aceite 30 segundos. Añade el cordero en una sola capa y dóralo bien por todos los lados 8–10 minutos (es el único dorado que recibe el plato, así que deja que el color se desarrolle como toca), después incorpora la asafétida, el jengibre seco y el hinojo en polvo y deja que envuelvan la carne en el aceite caliente un minuto más. Bate el yogur con la pasta de chile Kashmiri y una cucharada de agua fría, después añádelo a la olla cucharón a cucharón removiendo sin parar después de cada adición — despacio, el yogur no se corta — añade la sal, baja el fuego y cuece tapado 10 minutos hasta que el yogur se haya fundido en una base roja y brillante. Vierte 500 ml de agua caliente, vuelve a llevar a hervor, después baja al fuego más bajo y brasea tapado durante una hora y 20 minutos, removiendo cada 20 minutos, hasta que el cordero ceda a la cuchara y la salsa esté fina, brillante y de un rojo caoba profundo; vierte la leche con azafrán 5 minutos antes del final, sin removerla del todo. Reposa fuera del fuego 10 minutos antes de servir con basmati al vapor — el Rogan Josh debe ser casi como una sopa, vivamente coloreado y aromático más que picante, el calor lo aporta la carne, el color los chiles y el perfume todo lo demás.",

'fr': "Faites chauffer l'huile de moutarde dans une cocotte épaisse jusqu'à ce qu'elle commence tout juste à fumer, puis retirez-la du feu un instant — la fumée neutralise l'âcreté sans la brûler — remettez à feu moyen, ajoutez les épices entières et la feuille de laurier, et laissez-les parfumer l'huile 30 secondes. Ajoutez l'agneau en une seule couche et faites-le bien dorer sur toutes les faces pendant 8 à 10 minutes (c'est le seul moment de coloration du plat, alors laissez la couleur se développer comme il faut), incorporez ensuite l'asa-fœtida, le gingembre en poudre et le fenouil en poudre, et laissez-les enrober la viande dans l'huile chaude encore une minute. Fouettez le yaourt avec la pâte de piment Kashmiri et une cuillère à soupe d'eau froide, puis ajoutez-le dans la cocotte louche par louche en remuant sans cesse après chaque ajout — en y allant doucement, le yaourt ne tranche pas — salez, baissez le feu et faites cuire couvert 10 minutes, jusqu'à ce que le yaourt ait fondu en une base rouge et brillante. Versez 500 ml d'eau chaude, ramenez à frémissement, puis baissez le feu au minimum et faites braiser couvert pendant 1 heure 20, en remuant toutes les 20 minutes, jusqu'à ce que l'agneau cède sous la cuillère et que la sauce soit fluide, brillante et d'un rouge acajou profond ; versez le lait au safran 5 minutes avant la fin, en l'incorporant à peine. Laissez reposer hors du feu 10 minutes avant de servir avec un riz basmati à la vapeur — le Rogan Josh doit ressembler à une soupe, vivement coloré et parfumé plutôt que piquant, la chaleur vient de la viande, la couleur des piments et le parfum de tout le reste.",

'de': "Erhitzen Sie das Senföl in einem schweren Topf, bis es gerade zu rauchen beginnt, dann kurz vom Herd nehmen — der Rauch neutralisiert die Schärfe, ohne zu verbrennen — wieder bei mittlerer Hitze auf den Herd stellen, die ganzen Gewürze und das Lorbeerblatt einrühren und 30 Sekunden im Öl parfümieren lassen. Das Lammfleisch in einer Lage hinzufügen und 8–10 Minuten von allen Seiten gut bräunen (dies ist die einzige Bräunung, die das Gericht bekommt, also lassen Sie der Farbe Zeit), dann Asafoetida, Ingwer- und Fenchelpulver einrühren und eine Minute lang das Fleisch im heißen Öl umhüllen lassen. Den Joghurt mit der Kashmiri-Chilipaste und einem Esslöffel kaltem Wasser verquirlen, dann kellenweise in den Topf geben und nach jeder Zugabe ständig rühren — langsam zugegeben gerinnt der Joghurt nicht — salzen, die Hitze reduzieren und 10 Minuten zugedeckt köcheln, bis der Joghurt zu einer glänzenden roten Basis geschmolzen ist. 500 ml heißes Wasser angießen, wieder zum Köcheln bringen, dann auf die niedrigste Stufe stellen und zugedeckt 1 Stunde 20 Minuten schmoren, alle 20 Minuten umrühren, bis das Lamm dem Löffel nachgibt und die Sauce dünn, glänzend und von tiefem Mahagonirot ist; die Safranmilch 5 Minuten vor Schluss vorsichtig einrühren, ohne sie ganz unterzumischen. 10 Minuten vom Herd ruhen lassen und mit gedämpftem Basmati servieren — Rogan Josh soll suppenartig sein, leuchtend gefärbt und aromatisch statt scharf, die Schärfe kommt vom Fleisch, die Farbe von den Chilis und der Duft von allem anderen.",

'pt': "Aqueça o óleo de mostarda numa panela pesada até começar mesmo a fumegar, depois retire-a do lume por um instante — o fumo neutraliza a aspereza sem queimar — devolva ao lume médio, junte as especiarias inteiras e a folha de louro, e deixe perfumarem o óleo durante 30 segundos. Junte o borrego numa única camada e doure-o bem de todos os lados durante 8–10 minutos (é o único douramento que o prato recebe, por isso deixe a cor desenvolver-se como deve ser), depois junte a assa-fétida, o gengibre seco e o funcho em pó e deixe-os envolver a carne no óleo quente mais um minuto. Bata o iogurte com a pasta de piri-piri Kashmiri e uma colher de sopa de água fria, depois adicione à panela uma concha de cada vez, mexendo sem parar após cada adição — devagar, o iogurte não talha — tempere com sal, baixe o lume e cozinhe tapado durante 10 minutos, até o iogurte se ter fundido numa base vermelha e brilhante. Verta 500 ml de água quente, volte a uma fervura branda, depois baixe o lume ao mínimo e estufe tapado durante uma hora e 20 minutos, mexendo a cada 20 minutos, até o borrego ceder à colher e o molho ficar fino, brilhante e de um vermelho mogno profundo; envolva o leite com açafrão 5 minutos antes do fim, sem o misturar por completo. Deixe descansar fora do lume 10 minutos antes de servir com basmati ao vapor — o Rogan Josh deve ser quase sopa, intensamente colorido e aromático mais do que picante, o calor vem da carne, a cor dos piri-piris e o perfume de tudo o resto.",

'ru': "Разогрейте горчичное масло в тяжёлой кастрюле, пока оно не начнёт чуть дымить, затем на мгновение снимите с огня — дымок нейтрализует жёсткость без пригорания — верните на средний огонь, добавьте целые специи и лавровый лист и дайте им ароматизировать масло 30 секунд. Добавьте баранину в один слой и хорошо подрумяньте со всех сторон 8–10 минут (это единственное обжаривание блюда, так что дайте цвету развиться по-настоящему), вмешайте асафетиду, имбирный и фенхельный порошок и дайте им обволочь мясо в горячем масле ещё минуту. Взбейте йогурт с кашмирской пастой и столовой ложкой холодной воды, затем добавляйте его в кастрюлю по половнику, непрерывно помешивая после каждого — медленно, йогурт не сворачивается — посолите, убавьте огонь и тушите под крышкой 10 минут, пока йогурт не растворится в глянцевую красную основу. Влейте 500 мл горячей воды, верните к лёгкому кипению, затем сделайте огонь минимальным и тушите под крышкой 1 час 20 минут, помешивая каждые 20 минут, пока ягнятина не станет уступать ложке, а соус — жидким, глянцевым и глубокого красного дерева; влейте шафрановое молоко за 5 минут до конца, лишь слегка вмешав. Дайте отдохнуть 10 минут вне огня перед подачей с басмати на пару — Роган джош должен быть почти как суп, ярко окрашенным и ароматным, а не острым, жар идёт от мяса, цвет — от перцев, аромат — от всего остального.",

'ar': "سخّن زيت الخردل في قدر ثقيل حتى يبدأ بإصدار الدخان للتو، ثم ارفعه عن النار لحظة — الدخان يحيّد الحدّة دون أن يحرق — أعده إلى نار متوسطة، أضف البهارات الكاملة وورقة الغار، واتركها تعطّر الزيت 30 ثانية. أضف الضأن في طبقة واحدة وحمّره من كل الجهات 8–10 دقائق (هذا هو التحمير الوحيد للطبق، فاترك اللون يتطور كما يجب)، ثم أضف الهنغ ومسحوق الزنجبيل ومسحوق الشمر، واتركها تغطي اللحم في الزيت الساخن دقيقة إضافية. اخفق اللبن مع عجينة الفلفل الكشميري وملعقة كبيرة من الماء البارد، ثم أضفه إلى القدر مغرفةً مغرفة، مع التحريك المستمر بعد كل إضافة — ببطء، لا ينقطع اللبن — أضف الملح، خفّف النار، واطبخ مغطىً 10 دقائق حتى يذوب اللبن في قاعدة حمراء لامعة. اسكب 500 مل من الماء الساخن، أعد المزيج إلى الغليان، ثم اخفض النار إلى أهدأ درجة، واطبخ مغطىً ساعة و 20 دقيقة مع التحريك كل 20 دقيقة، حتى يلين الضأن أمام الملعقة ويصبح المرق رفيعاً لامعاً بلون أحمر ماهوغني عميق؛ اسكب حليب الزعفران قبل النهاية بـ 5 دقائق وحرّكه قليلاً فقط. أرحه بعيداً عن النار 10 دقائق قبل التقديم مع أرز البسمتي المطهو على البخار — الروغن جوش يجب أن يكون شبه شوربة، حاد اللون والعطر أكثر من كونه حاراً، الحرارة من اللحم، واللون من الفلفل، والعطر من كل ما تبقى.",

'zh': "在厚重的锅里把芥末油烧到刚刚开始冒烟，然后离火片刻——冒烟可以让油的辛辣味变温和，又不会烧焦——再放回中火上，加入整粒香料和月桂叶，让它们在油里飘香 30 秒。把羊肉单层下锅，把每一面都好好煎 8–10 分钟（这是整道菜唯一一次煎色，所以请让颜色真正出来），加入阿魏、姜粉和茴香粉，让它们在热油里包裹羊肉再 1 分钟。把酸奶与克什米尔辣椒糊和 1 汤匙冷水一起搅打，然后一勺一勺地加入锅里，每加一勺都不停搅拌——慢慢加，酸奶就不会分离——加盐，调小火，盖盖煮 10 分钟，直到酸奶融化成发亮的红色基底。倒入 500 毫升热水，再煮至微沸，然后转最小火盖盖炖 1 小时 20 分钟，每 20 分钟搅一次，直到羊肉一压就散、酱汁稀薄发亮、呈深红木色；最后 5 分钟把藏红花牛奶轻轻拌入，只是稍稍带过即可。离火静置 10 分钟，再配蒸 basmati 米饭上桌——Rogan Josh 应当像一碗轻盈的汤，颜色鲜亮、香气浓郁，而不是辣味突出，辣味来自羊肉本身，颜色来自辣椒，香气来自其余一切。",

'ja': "厚手の鍋でマスタードオイルを煙が立ち始める寸前まで熱し、一瞬火から外す — この煙が刺激臭を和らげる、焦がさずに — 中火に戻し、ホールスパイスとローリエを入れて 30 秒、油に香りを移す。ラム肉を 1 段に並べ、全面を 8〜10 分かけてしっかり焼き色をつける（この料理の焼き色のチャンスはこれ 1 回だけだから、しっかり色を出す）、アサフォエティダ、ジンジャーパウダー、フェンネルパウダーを加え、熱い油で肉を 1 分包む。ヨーグルトにカシミール唐辛子のペーストと冷水大さじ 1 を加えて混ぜ、鍋にひしゃく 1 杯ずつ加え、加えるたびに絶えず混ぜる — ゆっくり加えれば、ヨーグルトは分離しない — 塩を加えて火を弱め、蓋をして 10 分、ヨーグルトが艶のある赤いベースに溶けるまで煮る。熱湯 500 ml を加えて再沸騰させ、火を最弱にし、蓋をして 1 時間 20 分、20 分ごとに混ぜながら煮込む、ラムがスプーンに従って崩れ、ソースが薄く艶のある深いマホガニー色になるまで；サフランミルクは終了の 5 分前に流し入れ、完全には混ぜきらない。火から外して 10 分休ませ、蒸したバスマティライスと共に供する — ローガン・ジョシュはスープに近い料理、鮮やかな色と豊かな香りを持ち、辛さで攻めない；辛さは肉そのものから、色は唐辛子から、香りはそれ以外のすべてから来る。",

'tr': "Hardal yağını ağır bir tencerede tütmeye yeni başlayana dek ısıt, sonra bir an için ocaktan al — bu duman keskinliği yumuşatır, yağı yakmadan — orta ateşe geri al, bütün baharatları ve defne yaprağını ekle ve 30 saniye boyunca yağı parfümlemelerine izin ver. Kuzu etini tek katta yerleştir ve her tarafından iyice 8–10 dakika kahverengileştir (bu yemeğin tek kahverengileştirme aşamasıdır, bu yüzden rengin gerçekten gelişmesine izin ver), şeytan tersini, zencefil tozunu ve rezene tozunu ekle ve sıcak yağ içinde eti bir dakika daha kapla. Yoğurdu Keşmir biber ezmesi ve 1 yemek kaşığı soğuk suyla çırp, sonra tencereye birer kepçe halinde, her ekleyişten sonra sürekli karıştırarak ekle — yavaş gidersen yoğurt kesilmez — tuzu ekle, ateşi düşür ve kapalı 10 dakika pişir, yoğurt parlak kırmızı bir tabana eriyene dek. 500 ml sıcak suyu dök, kaynamaya geri getir, sonra en kısık ateşe düşür ve kapalı 1 saat 20 dakika, her 20 dakikada bir karıştırarak pişir; et kaşığa boyun eğene ve sos ince, parlak ve koyu maun kırmızısı olana dek; safranlı sütü bitime 5 dakika kala içine dök, tam karıştırmadan. Ocaktan alıp 10 dakika dinlendir ve buğulanmış basmati pirinçle servis et — Rogan Josh bir çorbaya yakın olmalı, keskin değil, parlak renkli ve aromatik; sıcaklık etten, renk biberlerden ve koku geri kalan her şeyden gelir.",

'it': "Scaldate l'olio di senape in una pentola pesante fino al primo accenno di fumo, poi togliete dal fuoco per un istante — il fumo neutralizza la punta acre senza bruciare — rimettete sul fuoco medio, aggiungete le spezie intere e l'alloro, e lasciatele profumare l'olio per 30 secondi. Unite l'agnello in un solo strato e fatelo rosolare bene su tutti i lati per 8–10 minuti (è l'unica rosolatura del piatto, quindi lasciate che il colore si sviluppi davvero), unite l'asafetida, il ginger in polvere e il finocchio in polvere, e lasciate che avvolgano la carne nell'olio caldo per un altro minuto. Montate lo yogurt con la pasta di peperoncino Kashmiri e un cucchiaio di acqua fredda, poi aggiungetelo in pentola un mestolo alla volta, mescolando senza sosta dopo ogni aggiunta — piano, lo yogurt non impazzisce — salate, abbassate il fuoco e cuocete coperto 10 minuti, finché lo yogurt non si è sciolto in una base rossa e lucida. Versate 500 ml di acqua calda, riportate a sobbollire, poi abbassate al minimo e brasate coperto per un'ora e 20 minuti, mescolando ogni 20 minuti, finché l'agnello non cede al cucchiaio e il sugo non è fluido, lucido e di un rosso mogano profondo; versate il latte allo zafferano 5 minuti prima della fine, senza mescolarlo del tutto. Fate riposare fuori dal fuoco 10 minuti prima di servire con riso basmati al vapore — il Rogan Josh deve essere quasi una zuppa, dai colori brillanti e dal profumo intenso piuttosto che dal piccante, il piccante viene dalla carne, il colore dai peperoncini, il profumo da tutto il resto.",

'ko': "두꺼운 냄비에 겨자유를 막 연기가 피어오르기 시작할 때까지 가열한 다음, 잠시 불에서 내려둔다 — 이 연기가 거친 매운맛을 누그러뜨려준다, 태우지 않으면서 — 다시 중불에 올리고 통향신료와 월계수잎을 넣어 30초 동안 기름에 향을 입힌다. 양고기를 한 겹으로 깔고 8–10분에 걸쳐 모든 면을 잘 갈색이 되게 굽는다 (이 요리에서 유일하게 색을 내는 단계이니, 색이 충분히 나도록 둔다), 아사푀티다, 건강 가루, 펜넬 가루를 넣고 뜨거운 기름이 고기를 1분 더 감싸게 한다. 요거트를 카슈미르 칠리 페이스트와 차가운 물 1큰술과 함께 휘젓고, 한 국자씩 냄비에 더해 매번 끊임없이 저어준다 — 천천히 더하면 요거트는 분리되지 않는다 — 소금을 더하고 불을 줄여 뚜껑을 덮고 10분, 요거트가 윤기 있는 빨간 베이스로 녹아들 때까지 익힌다. 뜨거운 물 500 ml를 붓고 다시 끓을 정도로 가열한 다음, 불을 가장 약하게 하고 뚜껑을 덮어 1시간 20분, 20분마다 저어주며 익힌다; 양고기가 숟가락에 굴복하고 소스가 묽고 윤기 있는 짙은 마호가니 적색이 될 때까지; 끝나기 5분 전에 사프란 우유를 살짝 둘러 넣되 완전히 섞지 않는다. 불에서 내려 10분 쉬게 한 다음, 김 오른 바스마티 라이스와 함께 낸다 — 로간 조시는 거의 수프에 가까운 요리, 강하게 매운 것이 아니라 강렬한 색과 향이 주인공이다; 매운맛은 고기에서, 색은 칠리에서, 향은 그 외 모든 것에서 온다.",

'hi': "एक भारी बर्तन में सरसों के तेल को बस धुआँ उठने तक गरम करें, फिर एक पल के लिए आँच से उतार लें — यह धुआँ कच्चेपन को कम कर देता है, बिना तेल जलाए — मध्यम आँच पर वापस रखें, साबुत मसाले और तेज़पत्ता डालें, और उन्हें 30 सेकंड तक तेल को महक देने दें। मटन को एक परत में डालें और हर तरफ़ 8–10 मिनट तक अच्छी तरह सुनहरा-भूरा होने दें (यह व्यंजन का एकमात्र भूरा करने का मौक़ा है, इसलिए रंग को सही ढंग से उभरने दें), हींग, सोंठ और सौंफ पाउडर मिलाएँ और उन्हें गरम तेल में मांस के साथ 1 मिनट और लिपटाएँ। दही को कश्मीरी मिर्च पेस्ट और 1 बड़े चम्मच ठंडे पानी के साथ फेंटें, फिर बर्तन में एक करछुल भर के डालते जाएँ, हर बार लगातार चलाते रहें — धीरे-धीरे डालने से दही फटता नहीं — नमक डालें, आँच कम करें और ढक कर 10 मिनट पकाएँ जब तक दही चमकीले लाल बेस में न घुल जाए। 500 मिली गरम पानी डालें, फिर से उबाल पर लाएँ, फिर सबसे धीमी आँच कर दें और ढक कर 1 घंटा 20 मिनट तक पकाएँ — हर 20 मिनट पर चलाएँ — जब तक मटन चम्मच की दबाव पर पिघले जैसा हो जाए और ग्रेवी पतली, चमकदार और गहरे महोगनी रंग की हो जाए; ख़त्म होने से 5 मिनट पहले केसर वाला दूध हलके से मिलाएँ, पूरी तरह न चलाएँ। आँच से उतार कर 10 मिनट आराम दें, फिर भाप वाले बासमती चावल के साथ परोसें — रोगन जोश एक सूप-जैसा व्यंजन है, चमकीले रंग और सुगंध से भरा, तीखा नहीं; तीख़ापन मांस से आता है, रंग मिर्च से, और सुगंध बाक़ी सब चीज़ों से।",
}

FEATURE_CARDS = {
'en': '[{icon:"🔥", t:"Smoke the mustard oil", d:"Neutralises raw pungency without scorching"}, {icon:"🧂", t:"One browning chance", d:"Let the lamb take real colour — there is no second pass"}, {icon:"🥣", t:"Yoghurt one ladle at a time", d:"Slow incorporation keeps it from splitting"}, {icon:"🌶️", t:"Colour from Kashmiri", d:"Brilliant red, not blazing heat — the meat brings the spice"}]',
'ro': '[{icon:"🔥", t:"Uleiul de muștar la fumegat", d:"Neutralizează asprimea brută fără să-l ardă"}, {icon:"🧂", t:"O singură șansă la rumenire", d:"Las mielul să capete culoare cum trebuie — nu vine altă oară"}, {icon:"🥣", t:"Iaurt câte un polonic", d:"Adăugat încet, nu se taie"}, {icon:"🌶️", t:"Culoare din Kashmiri", d:"Roșu viu, nu foc — căldura vine din carne"}]',
'es': '[{icon:"🔥", t:"Ahúma el aceite de mostaza", d:"Neutraliza la aspereza sin quemarse"}, {icon:"🧂", t:"Una sola oportunidad de dorar", d:"Que el cordero coja color de verdad — no hay segunda"}, {icon:"🥣", t:"Yogur cucharón a cucharón", d:"Incorporación lenta para que no se corte"}, {icon:"🌶️", t:"Color del Kashmiri", d:"Rojo vivo, no fuego — el calor lo trae la carne"}]',
'fr': '[{icon:"🔥", t:"Fumer l\'huile de moutarde", d:"Neutralise l\'âcreté sans brûler"}, {icon:"🧂", t:"Une seule chance de coloration", d:"Laisser l\'agneau prendre vraiment couleur — pas de seconde passe"}, {icon:"🥣", t:"Yaourt louche par louche", d:"Incorporation lente pour qu\'il ne tranche pas"}, {icon:"🌶️", t:"Couleur du Kashmiri", d:"Rouge éclatant, pas brûlant — la chaleur vient de la viande"}]',
'de': '[{icon:"🔥", t:"Senföl rauchen lassen", d:"Neutralisiert die rohe Schärfe ohne zu verbrennen"}, {icon:"🧂", t:"Einmal bräunen, dann nie wieder", d:"Lammfleisch Farbe nehmen lassen — kein zweiter Anlauf"}, {icon:"🥣", t:"Joghurt kellenweise", d:"Langsames Einrühren verhindert das Gerinnen"}, {icon:"🌶️", t:"Farbe vom Kashmiri", d:"Leuchtend rot, nicht brennend — Schärfe kommt vom Fleisch"}]',
'pt': '[{icon:"🔥", t:"Fumegar o óleo de mostarda", d:"Neutraliza a aspereza sem queimar"}, {icon:"🧂", t:"Uma única chance de dourar", d:"Deixe o borrego ganhar cor a sério — não há segunda"}, {icon:"🥣", t:"Iogurte concha a concha", d:"Incorporação lenta para não talhar"}, {icon:"🌶️", t:"Cor do Kashmiri", d:"Vermelho vivo, não fogo — o calor vem da carne"}]',
'ru': '[{icon:"🔥", t:"Дымление горчичного масла", d:"Нейтрализует жёсткость без пригорания"}, {icon:"🧂", t:"Один шанс на подрумянивание", d:"Дайте баранине взять цвет — второго раза не будет"}, {icon:"🥣", t:"Йогурт по половнику", d:"Медленное введение не даёт ему свернуться"}, {icon:"🌶️", t:"Цвет от кашмирского", d:"Ярко-красный, не жгучий — острота от мяса"}]',
'ar': '[{icon:"🔥", t:"تدخين زيت الخردل", d:"يحيّد الحدّة الخام دون أن يحترق"}, {icon:"🧂", t:"فرصة تحمير واحدة", d:"اترك الضأن يأخذ لوناً حقيقياً — لا توجد مرة ثانية"}, {icon:"🥣", t:"اللبن مغرفةً مغرفة", d:"الإضافة البطيئة تمنعه من الانقطاع"}, {icon:"🌶️", t:"اللون من الكشميري", d:"أحمر برّاق، لا نار — الحرارة من اللحم"}]',
'zh': '[{icon:"🔥", t:"芥末油烧到冒烟", d:"中和生辛味，又不会烧焦"}, {icon:"🧂", t:"只有一次煎色机会", d:"让羊肉真正上色——没有第二次"}, {icon:"🥣", t:"酸奶一勺一勺", d:"慢慢加入，避免分离"}, {icon:"🌶️", t:"颜色来自克什米尔辣椒", d:"鲜亮的红，不是猛烈的辣——辣味来自肉"}]',
'ja': '[{icon:"🔥", t:"マスタードオイルを煙の寸前まで", d:"刺激臭を中和、焦がさずに"}, {icon:"🧂", t:"焼き色のチャンスは 1 度だけ", d:"ラムにしっかり色を出す — 二度目はない"}, {icon:"🥣", t:"ヨーグルトはひしゃくずつ", d:"ゆっくり加えれば分離しない"}, {icon:"🌶️", t:"色はカシミール唐辛子から", d:"鮮やかな赤、燃えるような辛さではない — 辛さは肉から"}]',
'tr': '[{icon:"🔥", t:"Hardal yağını tüttür", d:"Yakmadan keskinliği yumuşatır"}, {icon:"🧂", t:"Tek kahverengileştirme şansı", d:"Kuzunun gerçekten rengini almasına izin ver — ikinci yok"}, {icon:"🥣", t:"Yoğurt kepçe kepçe", d:"Yavaş ekleyince kesilmez"}, {icon:"🌶️", t:"Renk Keşmir biberinden", d:"Parlak kırmızı, alev değil — acılık etten"}]',
'it': '[{icon:"🔥", t:"Affumicare l\'olio di senape", d:"Neutralizza la punta acre senza bruciarlo"}, {icon:"🧂", t:"Una sola occasione di rosolatura", d:"Lasciate che l\'agnello prenda colore vero — non c\'è una seconda"}, {icon:"🥣", t:"Yogurt un mestolo alla volta", d:"L\'incorporazione lenta lo tiene unito"}, {icon:"🌶️", t:"Colore dal Kashmiri", d:"Rosso brillante, non fuoco — il piccante viene dalla carne"}]',
'ko': '[{icon:"🔥", t:"겨자유를 연기 직전까지", d:"태우지 않으면서 거친 매운맛을 누그러뜨림"}, {icon:"🧂", t:"단 한 번의 갈색화", d:"양고기가 진짜 색을 내도록 — 두 번째는 없다"}, {icon:"🥣", t:"요거트는 한 국자씩", d:"천천히 더하면 분리되지 않는다"}, {icon:"🌶️", t:"색은 카슈미르 고추로부터", d:"강한 매움이 아니라 선명한 빨강 — 매운맛은 고기로부터"}]',
'hi': '[{icon:"🔥", t:"सरसों के तेल को धुआँ तक", d:"बिना जलाए कच्चे तीखेपन को कम करता है"}, {icon:"🧂", t:"भूरा करने का एक ही मौक़ा", d:"मटन का असली रंग आने दें — दूसरा मौक़ा नहीं"}, {icon:"🥣", t:"दही एक करछुल कर के", d:"धीरे-धीरे डालने से फटता नहीं"}, {icon:"🌶️", t:"रंग कश्मीरी मिर्च से", d:"चटक लाल, न कि भड़कीला तीख़ापन — तीख़ापन मांस से"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*207,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 207 (Rogan Josh): {rec_end-rec_start} → {len(new_recipe_block)} chars")
