#!/usr/bin/env python3
"""Rewrite recipe 198 (Galaktoboureko): 13 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Start the syrup well in advance — it must be cold when the hot pie comes out of the oven — combine the sugar, water, lemon juice, orange peel and cinnamon in a small saucepan, bring to a boil then simmer 4 minutes, take off the heat and leave to cool completely. For the custard, heat the milk in a wide saucepan with the sugar and lemon zest until just steaming (do not let it boil), sprinkle the semolina in a fine even stream while whisking constantly, then keep whisking on low heat for 5–6 minutes until it thickens to a loose pudding; off the heat, beat in the eggs one at a time (the mixture should be warm but not hot enough to scramble them) and the vanilla, then press clingfilm directly onto the surface to stop a skin forming. Brush a 22×30 cm baking dish with melted butter, lay 7 sheets of phyllo across the bottom brushing each generously with butter and letting the edges hang over the sides (those flaps will fold back over the top later), pour in the still-warm custard, smooth it level, fold the overhanging flaps inward and brush them with butter, then cover with another 7 sheets of phyllo (again buttering each) and trim or tuck the edges so the pie is fully sealed. Score the top phyllo into diamonds or squares with a sharp knife — cut all the way through so the syrup can later penetrate — brush the surface lavishly with the last of the butter, and bake at 170°C for 45–55 minutes until the top is deeply golden brown. The moment it comes out of the oven, pour the cold syrup evenly over the hot pie — it will sizzle and steam — leave to settle at least 4 hours, ideally overnight, before cutting along the score lines and serving at room temperature.",

'ro': "Începe siropul cu mult timp înainte — trebuie să fie rece când plăcinta fierbinte iese din cuptor — combină zahărul, apa, sucul de lămâie, coaja de portocală și scorțișoara într-o crăticioară, adu la fierbere apoi fierbe 4 minute, ia de pe foc și lasă să se răcească complet. Pentru cremă, încălzește laptele într-o crăticioară largă cu zahărul și coaja de lămâie până abia abureste (nu lăsa să fiarbă), presară grișul într-un fir fin și uniform în timp ce bați continuu, apoi continuă să bați pe foc mic 5–6 minute până se îngroașă la o budincă slabă; departe de foc, încorporează ouăle pe rând (amestecul trebuie să fie cald dar nu suficient de fierbinte cât să le coaguleze) și vanilia, apoi pune o folie alimentară direct pe suprafață pentru a opri formarea unei pelicule. Unge un vas de copt 22×30 cm cu unt topit, întinde 7 foi de phyllo pe fund, ungând generos fiecare cu unt și lăsând marginile să atârne peste părți (acele clape se vor pleca peste partea de sus mai târziu), toarnă crema încă caldă, netezește-o, pliază clapele care atârnă spre interior și unge-le cu unt, apoi acoperă cu alte 7 foi de phyllo (ungând din nou fiecare) și taie sau bagă marginile pentru ca plăcinta să fie complet sigilată. Crestează partea de sus a foilor de phyllo în romburi sau pătrate cu un cuțit ascuțit — taie până la capăt astfel încât siropul să poată pătrunde mai târziu — unge suprafața din belșug cu restul de unt și coace la 170°C 45–55 de minute până când partea de sus este auriu maro adânc. În momentul în care iese din cuptor, toarnă siropul rece uniform peste plăcinta fierbinte — va sfârâi și va aburi — las-o să se așeze cel puțin 4 ore, ideal peste noapte, înainte de a o tăia pe liniile crestate și a o servi la temperatura camerei.",

'es': "Comienza el almíbar con mucha antelación — debe estar frío cuando la tarta caliente sale del horno — combina el azúcar, el agua, el zumo de limón, la corteza de naranja y la canela en un cazo, lleva a ebullición y luego cuece 4 minutos, retira del fuego y deja enfriar completamente. Para la crema, calienta la leche en un cazo amplio con el azúcar y la ralladura de limón hasta que apenas humee (no la dejes hervir), espolvorea la sémola en un chorro fino y uniforme mientras bates constantemente, después sigue batiendo a fuego bajo durante 5–6 minutos hasta que espese a una crema suelta; fuera del fuego, incorpora los huevos uno a uno (la mezcla debe estar tibia pero no tan caliente que los cuaje) y la vainilla, después presiona film transparente directamente sobre la superficie para evitar que se forme nata. Pinta un molde de horno de 22×30 cm con mantequilla derretida, coloca 7 hojas de phyllo en el fondo pintando cada una generosamente con mantequilla y dejando los bordes colgando por los lados (esas tapas se doblarán sobre la parte superior más tarde), vierte la crema aún tibia, alísala, dobla las tapas colgantes hacia dentro y úntales con mantequilla, después cubre con otras 7 hojas de phyllo (untando cada una de nuevo) y recorta o mete los bordes para que la tarta esté completamente sellada. Marca la parte superior de la phyllo en rombos o cuadrados con un cuchillo afilado — corta hasta el final para que el almíbar pueda penetrar después — pinta la superficie abundantemente con la última mantequilla, y hornea a 170°C durante 45–55 minutos hasta que la parte superior esté dorada oscura. En el momento en que sale del horno, vierte el almíbar frío uniformemente sobre la tarta caliente — chisporroteará y echará vapor — déjala asentar al menos 4 horas, idealmente toda la noche, antes de cortar por las líneas marcadas y servir a temperatura ambiente.",

'fr': "Commencez le sirop bien à l'avance — il doit être froid quand la tarte chaude sort du four — combinez le sucre, l'eau, le jus de citron, le zeste d'orange et la cannelle dans une petite casserole, portez à ébullition puis laissez frémir 4 minutes, retirez du feu et laissez refroidir complètement. Pour la crème, chauffez le lait dans une grande casserole avec le sucre et le zeste de citron jusqu'à ce qu'il fume à peine (ne le laissez pas bouillir), saupoudrez la semoule en un mince filet régulier en fouettant constamment, puis continuez à fouetter à feu doux pendant 5 à 6 minutes jusqu'à ce qu'il épaississe en un pudding souple ; hors du feu, incorporez les œufs un à un (le mélange doit être tiède mais pas assez chaud pour les coaguler) et la vanille, puis pressez le film alimentaire directement sur la surface pour empêcher la formation d'une peau. Beurrez un plat de 22×30 cm avec du beurre fondu, posez 7 feuilles de phyllo au fond en badigeonnant chacune généreusement de beurre et en laissant les bords pendre sur les côtés (ces rabats se replieront sur le dessus plus tard), versez la crème encore tiède, lissez-la, repliez les rabats vers l'intérieur et badigeonnez-les de beurre, puis recouvrez de 7 autres feuilles de phyllo (en beurrant à nouveau chacune) et coupez ou rentrez les bords pour que la tarte soit entièrement scellée. Marquez le phyllo du dessus en losanges ou carrés avec un couteau aiguisé — coupez jusqu'au bout pour que le sirop puisse pénétrer plus tard — badigeonnez généreusement la surface du dernier beurre, et faites cuire à 170°C pendant 45 à 55 minutes jusqu'à ce que le dessus soit doré foncé. Au moment où elle sort du four, versez le sirop froid uniformément sur la tarte chaude — ça grésille et fume — laissez reposer au moins 4 heures, idéalement toute la nuit, avant de couper le long des marques et de servir à température ambiante.",

'de': "Beginnen Sie den Sirup gut im Voraus — er muss kalt sein, wenn die heiße Pastete aus dem Ofen kommt — kombinieren Sie den Zucker, das Wasser, den Zitronensaft, die Orangenschale und den Zimt in einem kleinen Topf, zum Kochen bringen, dann 4 Minuten köcheln lassen, vom Herd nehmen und vollständig abkühlen lassen. Für die Creme erhitzen Sie die Milch in einem breiten Topf mit dem Zucker und der Zitronenschale, bis sie gerade dampft (nicht kochen lassen), streuen Sie den Grieß in einem feinen gleichmäßigen Strahl unter ständigem Schlagen ein, dann weiter bei niedriger Hitze 5–6 Minuten schlagen, bis die Masse zu einem lockeren Pudding eindickt; vom Herd nehmen, die Eier einzeln einrühren (die Mischung sollte warm sein, aber nicht heiß genug, um sie zu stocken) und die Vanille, dann Frischhaltefolie direkt auf die Oberfläche drücken, damit sich keine Haut bildet. Bestreichen Sie eine 22×30 cm Backform mit geschmolzener Butter, legen Sie 7 Phyllo-Blätter auf den Boden und bestreichen Sie jedes großzügig mit Butter, lassen Sie die Ränder über die Seiten hängen (diese Klappen werden später über die Oberseite gefaltet), gießen Sie die noch warme Creme ein, glätten Sie sie, klappen Sie die überhängenden Klappen nach innen und bestreichen Sie sie mit Butter, dann decken Sie mit weiteren 7 Phyllo-Blättern ab (wieder jedes mit Butter bestrichen) und schneiden oder stecken Sie die Ränder so, dass die Pastete vollständig versiegelt ist. Schneiden Sie das obere Phyllo mit einem scharfen Messer in Rauten oder Quadrate ein — schneiden Sie ganz durch, damit der Sirup später eindringen kann — bestreichen Sie die Oberfläche reichlich mit der letzten Butter und backen Sie bei 170°C für 45–55 Minuten, bis die Oberseite tief goldbraun ist. In dem Moment, wo sie aus dem Ofen kommt, gießen Sie den kalten Sirup gleichmäßig über die heiße Pastete — es wird zischen und dampfen — lassen Sie mindestens 4 Stunden, idealerweise über Nacht, ruhen, bevor Sie entlang der Markierungen schneiden und bei Raumtemperatur servieren.",

'pt': "Comece a calda bem antes — deve estar fria quando a torta quente sair do forno — combine o açúcar, a água, o sumo de limão, a casca de laranja e a canela numa caçarola pequena, leve a ferver e depois deixe ferver 4 minutos, retire do lume e deixe arrefecer completamente. Para o creme, aqueça o leite numa caçarola larga com o açúcar e a raspa de limão até estar mesmo a fumegar (não deixe ferver), polvilhe a sêmola num fio fino e regular enquanto bate constantemente, depois continue a bater em lume baixo durante 5–6 minutos até engrossar num pudim solto; fora do lume, incorpore os ovos um a um (a mistura deve estar morna mas não quente o suficiente para os escaldar) e a baunilha, depois pressione película aderente diretamente na superfície para impedir a formação de pele. Pincele uma forma de 22×30 cm com manteiga derretida, disponha 7 folhas de phyllo no fundo pincelando cada uma generosamente com manteiga e deixando as bordas penduradas dos lados (essas abas serão dobradas sobre o topo mais tarde), verta o creme ainda morno, alise-o, dobre as abas penduradas para dentro e pincele-as com manteiga, depois cubra com mais 7 folhas de phyllo (novamente pincelando cada uma com manteiga) e apare ou enfie as bordas para que a torta esteja totalmente selada. Marque o phyllo de cima em losangos ou quadrados com uma faca afiada — corte até ao fim para que a calda possa penetrar mais tarde — pincele a superfície abundantemente com o resto da manteiga, e asse a 170°C durante 45–55 minutos até o topo estar dourado escuro. No momento em que sai do forno, verta a calda fria uniformemente sobre a torta quente — vai chiar e vaporizar — deixe assentar pelo menos 4 horas, idealmente de um dia para o outro, antes de cortar ao longo das linhas marcadas e servir à temperatura ambiente.",

'ru': "Начните сироп заранее — он должен быть холодным, когда горячий пирог выйдет из духовки — соедините сахар, воду, лимонный сок, апельсиновую цедру и корицу в маленькой кастрюле, доведите до кипения, затем варите 4 минуты, снимите с огня и дайте полностью остыть. Для крема нагрейте молоко в широкой кастрюле с сахаром и лимонной цедрой, пока оно едва не задымится (не давайте кипеть), всыпьте манку тонкой равномерной струйкой при постоянном помешивании, затем продолжайте взбивать на слабом огне 5–6 минут, пока не загустеет до жидкого пудинга; сняв с огня, вмешайте яйца по одному (смесь должна быть тёплой, но не настолько горячей, чтобы свернуть их) и ваниль, затем прижмите плёнку прямо к поверхности, чтобы предотвратить образование плёнки. Смажьте форму 22×30 см растопленным маслом, выложите 7 листов фило на дно, обильно смазывая каждый маслом и оставляя края свисать по бокам (эти клапаны потом загнётся обратно поверх), влейте ещё тёплый крем, разровняйте его, загните свисающие клапаны внутрь и смажьте их маслом, затем накройте ещё 7 листами фило (снова смазывая каждый) и обрежьте или подоткните края, чтобы пирог был полностью запечатан. Надрежьте верхнее фило ромбами или квадратами острым ножом — режьте до конца, чтобы сироп позже мог проникнуть — обильно смажьте поверхность остатком масла, и запекайте при 170°C 45–55 минут, пока верх не станет глубоко золотисто-коричневым. В момент, когда он выходит из духовки, равномерно полейте холодным сиропом горячий пирог — он зашипит и задымится — дайте отстояться минимум 4 часа, идеально на ночь, прежде чем нарезать по линиям и подавать при комнатной температуре.",

'ar': "ابدأ بالقطر مسبقاً — يجب أن يكون بارداً حين تخرج الفطيرة الساخنة من الفرن — اخلط السكر، الماء، عصير الليمون، قشر البرتقال والقرفة في قدر صغير، أوصلها إلى الغليان ثم اطهِها 4 دقائق، ارفعها عن النار واتركها تبرد تماماً. للكاسترد، سخّن الحليب في قدر واسع مع السكر وبشر الليمون حتى يكاد يتبخّر (لا تتركه يغلي)، انثر السميد في خيط رفيع متجانس وأنت تخفق باستمرار، ثم استمر في الخفق على نار هادئة لمدة 5–6 دقائق حتى يثخن إلى بودنغ خفيف؛ بعيداً عن النار، أدخل البيض واحدة تلو الأخرى (يجب أن يكون المزيج دافئاً ولكن ليس ساخناً بما يكفي لطهيها) والفانيلا، ثم اضغط غشاء بلاستيكي مباشرة على السطح لمنع تكوّن طبقة. ادهن صحن فرن 22×30 سم بالزبدة المذابة، ضع 7 شرائح من الفيلو في القاع وادهن كل واحدة بالزبدة بسخاء واترك الحواف معلقة على الجانبين (هذه الأطراف ستُطوى على الأعلى لاحقاً)، اسكب الكاسترد الدافئ، سوّه، اطو الأطراف المعلقة إلى الداخل وادهنها بالزبدة، ثم غطّ بـ 7 شرائح فيلو إضافية (وادهن كل واحدة بالزبدة) وقص أو ادفع الحواف بحيث تكون الفطيرة مغلقة تماماً. قطع الفيلو العلوي إلى ماسات أو مربعات بسكين حاد — اقطع حتى الأسفل ليتمكن القطر لاحقاً من الاختراق — ادهن السطح بسخاء بآخر الزبدة، واخبز على 170°م لمدة 45–55 دقيقة حتى يصبح الأعلى ذهبياً بنياً عميقاً. في اللحظة التي تخرج فيها من الفرن، اسكب القطر البارد بالتساوي على الفطيرة الساخنة — ستفور وتتبخّر — اتركها تستقر 4 ساعات على الأقل، ويفضل طوال الليل، قبل أن تقطعها عبر خطوط التقطيع وتقدمها في درجة حرارة الغرفة.",

'zh': "提前很久就开始做糖浆——它必须在热的派出炉时已经是凉的——在小锅里把糖、水、柠檬汁、橙皮和肉桂混合，烧开后再小火炖 4 分钟，离火放凉至完全冷却。做卡仕达酱：在一只大锅里把牛奶、糖和柠檬皮屑加热到刚冒热气（不要让它沸腾），把粗麦粉以细而均匀的流撒入并不停搅打，然后继续在小火上打 5–6 分钟，直到稠到像松软的布丁；离火，把鸡蛋一个一个搅入（混合物应当是温热的但不能热到把蛋烫熟）然后加入香草，把保鲜膜直接贴在表面上以防结皮。在 22×30 cm 的烤盘上刷融化的黄油，在底部铺 7 张 phyllo 面皮，每一张都慷慨地刷上黄油，让边缘垂出盘子两侧（这些垂边稍后会折回到顶部上来），倒入还是温的卡仕达酱，把它抹平，把垂出来的边折回到馅料里面并刷上黄油，再盖上另外 7 张 phyllo 面皮（每张同样刷黄油），把边缘切齐或塞进去，让派完全封闭。用一把锋利的刀在顶层 phyllo 上切出菱形或方形——一定要切到底，这样糖浆稍后才能渗进去——把表面用最后的黄油慷慨地刷一遍，然后放进 170°C 的烤箱烤 45–55 分钟，直到顶部呈深金棕色。出炉的那一刻，把冷糖浆均匀地浇在热的派上——它会咝咝作响并冒蒸汽——让它静置至少 4 小时，最好一夜，然后再沿着切痕切开，在室温下享用。",

'ja': "シロップは早めに作っておく — 熱いパイがオーブンから出てきた時点で冷たくなっていなければならない — 小鍋に砂糖、水、レモン汁、オレンジの皮、シナモンを合わせ、沸騰させてから 4 分煮詰め、火から下ろして完全に冷ます。カスタードは、大きな鍋に牛乳、砂糖、レモンの皮を入れ、湯気が立つ寸前まで温め（沸騰させない）、セモリナを細く均一に振り入れながら絶え間なく泡立て、その後弱火で 5〜6 分、緩めのプディング状にとろみがつくまで泡立て続ける；火から下ろし、卵を 1 個ずつ加え（混合物は温かいがスクランブルしない温度であるべき）、バニラも加え、表面に直接ラップを密着させて膜が張るのを防ぐ。22×30 cm の耐熱皿に溶かしバターを塗り、フィロを 7 枚重ねて底に敷き、それぞれにバターをたっぷり塗り、端を皿の側面から垂らしておく（このフラップは後で上に折り戻す）、まだ温かいカスタードを注ぎ入れ、表面を平らに整え、垂れているフラップを内側に折り、バターを塗り、さらに 7 枚のフィロで覆い（各枚にバターを塗る）、端を整えるか折り込んでパイが完全に密封されるようにする。鋭いナイフでトップのフィロにダイヤモンドまたは正方形の切り込みを入れる — 後でシロップが浸透できるように、最後まで切る — 残りのバターを表面にたっぷり塗り、170℃ で 45〜55 分、上面が深い金茶色になるまで焼く。オーブンから出した瞬間、冷たいシロップを熱いパイの上に均等に注ぐ — ジューと音を立てて蒸気が立つ — 切り込み線に沿って切り、室温で供する前に少なくとも 4 時間、できれば一晩、落ち着かせる。",

'tr': "Şurubu çok önceden başlat — fırından çıkan sıcak böreğin üzerine dökülürken soğuk olmalı — küçük bir tencerede şeker, su, limon suyu, portakal kabuğu ve tarçını birleştir, kaynamaya getir, sonra 4 dakika kısık ateşte pişir, ocaktan al ve tamamen soğumaya bırak. Muhallebi için, geniş bir tencerede sütü şeker ve limon kabuğu rendesiyle yeni buhar çıkana dek ısıt (kaynatma), iriks (semolina) ince ve düzgün bir akıntı halinde sürekli çırparak ekle, sonra kısık ateşte 5–6 dakika daha çırpmaya devam et, gevşek bir puding kıvamına gelene dek; ocaktan aldıktan sonra yumurtaları birer birer ekle (karışım sıcak olmalı ama yumurtaları haşlayacak kadar sıcak değil) ve vanilyayı da ekle, sonra streç filmi yüzeye doğrudan bastırarak kabuk oluşmasını önle. 22×30 cm fırın kabını erimiş tereyağı ile fırçala, 7 yufka yaprağını alta yay, her birini bolca tereyağı ile fırçala, kenarları yan taraflardan sarkıt (bu kapaklar sonradan üste katlanacak), hâlâ ılık muhallebiyi dök, yüzeyini düzelt, sarkan kapakları içe katla ve tereyağı ile fırçala, ardından 7 yufka daha ile kapla (tekrar her birine tereyağı sür) ve kenarları kes veya içe tıka ki börek tamamen mühürlensin. Üst yufkayı keskin bir bıçakla baklava şeklinde veya kare dilimle — şurup sonradan içine sızabilsin diye sonuna kadar kes — yüzeyini son tereyağıyla bolca fırçala ve 170°C'de 45–55 dakika, üst kısmı koyu altın kahverengiye dönene dek pişir. Fırından çıktığı an, soğuk şurubu sıcak böreğin üzerine eşit şekilde dök — cızırdayıp buharı çıkacak — kesim çizgileri boyunca kesmeden ve oda sıcaklığında servis etmeden önce en az 4 saat, ideal olarak gece boyu otursun.",

'it': "Iniziate lo sciroppo con largo anticipo — deve essere freddo quando la torta calda esce dal forno — combinate lo zucchero, l'acqua, il succo di limone, la scorza d'arancia e la cannella in un pentolino, portate a ebollizione poi sobbollite 4 minuti, togliete dal fuoco e fate raffreddare completamente. Per la crema, scaldate il latte in un pentolino largo con lo zucchero e la scorza di limone fino a quando non fuma appena (non lasciate bollire), spolverate il semolino in un filo fine e regolare mentre sbattete costantemente, poi continuate a sbattere a fuoco basso per 5–6 minuti finché non si addensa in un budino morbido; fuori dal fuoco, incorporate le uova una alla volta (il composto deve essere caldo ma non così caldo da farle strapazzare) e la vaniglia, poi premete la pellicola direttamente sulla superficie per impedire la formazione di una pellicola. Spennellate una pirofila 22×30 cm con burro fuso, stendete 7 fogli di phyllo sul fondo spennellando ognuno generosamente con burro e lasciando che i bordi pendano dai lati (quelle alette si piegheranno sopra in seguito), versate la crema ancora calda, livellatela, piegate le alette pendenti verso l'interno e spennellatele con burro, poi coprite con altri 7 fogli di phyllo (spennellando di nuovo ognuno con burro) e rifilate o ripiegate i bordi così che la torta sia completamente sigillata. Incidete il phyllo superiore in rombi o quadrati con un coltello affilato — tagliate fino in fondo affinché lo sciroppo possa penetrare più tardi — spennellate la superficie abbondantemente con il burro rimasto, e infornate a 170°C per 45–55 minuti finché la superficie non è di un marrone dorato profondo. Nel momento in cui esce dal forno, versate lo sciroppo freddo uniformemente sulla torta calda — sfrigolerà e farà fumo — lasciate riposare almeno 4 ore, idealmente tutta la notte, prima di tagliare lungo i segni e servire a temperatura ambiente.",

'ko': "시럽을 미리 만들어 둔다 — 뜨거운 파이가 오븐에서 나올 때 차가워야 한다 — 작은 냄비에 설탕, 물, 레몬즙, 오렌지 껍질, 시나몬을 넣고 끓인 다음 4분간 졸이고, 불에서 내려 완전히 식힌다. 커스터드용으로, 넓은 냄비에 우유와 설탕과 레몬 제스트를 넣고 김이 막 오를 정도로 가열하고 (끓이지 말 것), 세몰리나를 가늘고 균일한 흐름으로 끊임없이 휘저으면서 뿌린 다음, 약불에서 5–6분 더 휘저어 묽은 푸딩 농도가 될 때까지 졸인다; 불에서 내려 달걀을 하나씩 넣고 (혼합물은 따뜻해야 하지만 달걀이 익을 정도로 뜨거우면 안 된다) 바닐라도 넣은 뒤, 표면에 랩을 직접 밀착시켜 막이 생기는 것을 막는다. 22×30 cm 베이킹 디시에 녹인 버터를 바르고, 필로 7장을 바닥에 깔되 각 장에 버터를 듬뿍 바르고 가장자리는 옆으로 늘어뜨려 두고 (그 부분은 나중에 위로 다시 접힌다), 아직 따뜻한 커스터드를 부어 평평하게 펴고, 늘어뜨린 가장자리를 안쪽으로 접고 버터를 발라, 다시 7장의 필로로 덮고 (각 장에 다시 버터 바르기) 가장자리를 잘라내거나 안으로 밀어 넣어 파이가 완전히 봉인되도록 한다. 위쪽 필로를 날카로운 칼로 다이아몬드나 정사각형 모양으로 칼집을 내되 — 시럽이 나중에 스며들 수 있도록 끝까지 자르고 — 표면에 남은 버터를 듬뿍 바르고, 170°C에서 45–55분, 윗면이 진한 황금색이 될 때까지 굽는다. 오븐에서 나오는 순간 차가운 시럽을 뜨거운 파이 위에 고르게 부으면 — 치익 소리와 김이 난다 — 칼집 선을 따라 자르고 실온에서 내기 전에 최소 4시간, 이상적으로는 하룻밤 정착시킨다.",

'hi': "चाशनी बहुत पहले से शुरू करें — गरम पाई जब ओवन से निकले तो वो ठंडी होनी चाहिए — एक छोटे बर्तन में चीनी, पानी, नीबू का रस, संतरे का छिलका और दालचीनी मिलाएँ, उबाल पर लाएँ फिर 4 मिनट तक उबालें, आँच से हटा कर पूरी तरह ठंडा करें। कस्टर्ड के लिए, एक चौड़े बर्तन में दूध, चीनी और नीबू के छिलके का बुरादा डाल कर बस-बस भाप उठने तक गरम करें (उबलने न दें), लगातार फेंटते हुए सूजी को एक पतले, एकसमान धार में डालें, फिर धीमी आँच पर 5–6 मिनट और फेंटते रहें जब तक एक ढीली पुडिंग जैसा गाढ़ापन न आ जाए; आँच से हटा कर अंडे एक-एक करके मिलाएँ (मिश्रण गुनगुना होना चाहिए पर इतना गरम नहीं कि अंडे फटें) और वनीला डालें, फिर ऊपर एक परत न बने इसलिए क्लिंगफ़िल्म को सीधे सतह पर दबाएँ। 22×30 सेमी बेकिंग डिश पर पिघले मक्खन से ब्रश करें, तले पर 7 phyllo शीट बिछाएँ, हर एक पर ख़ूब मक्खन ब्रश करें और किनारों को बग़ल से लटकने दें (ये फ़्लैप्स बाद में ऊपर मोड़े जाएँगे), अभी भी गुनगुना कस्टर्ड डालें, उसे एकसमान करें, लटकते फ़्लैप्स अंदर मोड़ें और मक्खन लगाएँ, फिर 7 और phyllo शीट से ढक दें (हर एक पर फिर से मक्खन ब्रश करते हुए) और किनारों को काटें या अंदर डाल दें ताकि पाई पूरी तरह सीलबंद हो। ऊपर वाले phyllo पर तेज़ चाक़ू से हीरे या चौकोर शेप में निशान लगाएँ — पूरा काटें ताकि चाशनी बाद में अंदर जा सके — सतह को बचे मक्खन से उदारता से ब्रश करें, और 170°C पर 45–55 मिनट तक तब तक बेक करें जब तक ऊपर का हिस्सा गहरा सुनहरा-भूरा न हो जाए। ओवन से निकलते ही ठंडी चाशनी को गरम पाई पर एकसमान डालें — वो छनछनाएगी और भाप उठाएगी — कम से कम 4 घंटे, बेहतर रात भर, बैठने दें, फिर निशान वाली रेखाओं के साथ काटें और कमरे के तापमान पर परोसें।",
}

FEATURE_CARDS = {
'en': '[{icon:"❄️", t:"Cold syrup, hot pie", d:"Syrup must be fully cold when the pie comes out of the oven"}, {icon:"🥛", t:"Semolina-thickened custard", d:"Streamed in while whisking — never lumps when poured slow"}, {icon:"📐", t:"7 sheets below + 7 above", d:"Phyllo brushed with butter, edges folded back over the top"}, {icon:"⏰", t:"Settle overnight before cutting", d:"Score lines deep enough for the syrup to find its way down"}]',
'ro': '[{icon:"❄️", t:"Sirop rece, plăcintă fierbinte", d:"Siropul trebuie să fie complet rece când plăcinta iese din cuptor"}, {icon:"🥛", t:"Cremă îngroșată cu griș", d:"Strecurat în fir subțire în timp ce bați — fără cocoloașe"}, {icon:"📐", t:"7 foi dedesubt + 7 deasupra", d:"Phyllo uns cu unt, marginile pliate înapoi peste partea de sus"}, {icon:"⏰", t:"Așezat peste noapte înainte de tăiat", d:"Crestături adânci pentru ca siropul să-și găsească drumul"}]',
'es': '[{icon:"❄️", t:"Almíbar frío, tarta caliente", d:"El almíbar debe estar completamente frío cuando la tarta sale del horno"}, {icon:"🥛", t:"Crema espesada con sémola", d:"Vertida en chorro fino mientras bates — sin grumos si vas despacio"}, {icon:"📐", t:"7 hojas abajo + 7 arriba", d:"Phyllo pintada con mantequilla, bordes plegados sobre el top"}, {icon:"⏰", t:"Asentar toda la noche antes de cortar", d:"Marcas profundas para que el almíbar encuentre su camino"}]',
'fr': '[{icon:"❄️", t:"Sirop froid, tarte chaude", d:"Le sirop doit être complètement froid quand la tarte sort du four"}, {icon:"🥛", t:"Crème épaissie à la semoule", d:"Versée en filet tout en fouettant — pas de grumeaux si lent"}, {icon:"📐", t:"7 feuilles en bas + 7 en haut", d:"Phyllo badigeonné de beurre, bords repliés sur le dessus"}, {icon:"⏰", t:"Reposer toute la nuit avant de couper", d:"Entailles profondes pour que le sirop trouve son chemin"}]',
'de': '[{icon:"❄️", t:"Kalter Sirup, heiße Pastete", d:"Der Sirup muss vollständig kalt sein, wenn die Pastete aus dem Ofen kommt"}, {icon:"🥛", t:"Grießverdickte Creme", d:"Im Strahl beim Schlagen eingerieselt — keine Klumpen wenn langsam"}, {icon:"📐", t:"7 Blätter unten + 7 oben", d:"Phyllo mit Butter bestrichen, Ränder über die Oberseite gefaltet"}, {icon:"⏰", t:"Über Nacht ruhen vor dem Schneiden", d:"Tiefe Schnitte, damit der Sirup seinen Weg findet"}]',
'pt': '[{icon:"❄️", t:"Calda fria, torta quente", d:"A calda deve estar completamente fria quando a torta sai do forno"}, {icon:"🥛", t:"Creme espessado com sêmola", d:"Adicionada em fio enquanto se bate — sem grumos se for devagar"}, {icon:"📐", t:"7 folhas em baixo + 7 em cima", d:"Phyllo pincelado com manteiga, bordas dobradas sobre o topo"}, {icon:"⏰", t:"Assentar de um dia para o outro antes de cortar", d:"Marcas profundas para a calda encontrar caminho"}]',
'ru': '[{icon:"❄️", t:"Холодный сироп, горячий пирог", d:"Сироп должен быть полностью холодным, когда пирог выходит из духовки"}, {icon:"🥛", t:"Крем загущённый манкой", d:"Тонкой струйкой при помешивании — без комков если медленно"}, {icon:"📐", t:"7 листов внизу + 7 наверху", d:"Фило смазано маслом, края загнуты обратно поверх"}, {icon:"⏰", t:"Дать отстояться на ночь до нарезки", d:"Глубокие надрезы, чтобы сироп нашёл путь вниз"}]',
'ar': '[{icon:"❄️", t:"قطر بارد، فطيرة ساخنة", d:"يجب أن يكون القطر بارداً تماماً عندما تخرج الفطيرة من الفرن"}, {icon:"🥛", t:"كاسترد مثخّن بالسميد", d:"يُرشّ بخيط أثناء الخفق — لا كتل إذا بطيئاً"}, {icon:"📐", t:"7 أوراق تحت + 7 فوق", d:"الفيلو مدهون بالزبدة، الحواف مطوية إلى الأعلى"}, {icon:"⏰", t:"الاستقرار طوال الليل قبل التقطيع", d:"خطوط تقطيع عميقة كي يجد القطر طريقه إلى الأسفل"}]',
'zh': '[{icon:"❄️", t:"冷糖浆，热派", d:"派出炉时糖浆必须完全冷掉"}, {icon:"🥛", t:"粗麦粉勾稠的卡仕达", d:"边搅打边细流撒入 — 慢慢加就不会结块"}, {icon:"📐", t:"底 7 张 + 上 7 张", d:"phyllo 刷黄油，边缘折回到顶部上来"}, {icon:"⏰", t:"切之前先静置一夜", d:"切痕够深，糖浆才能向下找到路径"}]',
'ja': '[{icon:"❄️", t:"冷たいシロップ、熱いパイ", d:"シロップはパイがオーブンから出る時点で完全に冷えていなければならない"}, {icon:"🥛", t:"セモリナでとろみをつけたカスタード", d:"泡立てながら細い筋で振り入れる — ゆっくりやればダマにならない"}, {icon:"📐", t:"下 7 枚 + 上 7 枚", d:"フィロにバターを塗り、端を上に折り返す"}, {icon:"⏰", t:"切る前に一晩落ち着かせる", d:"シロップが下まで到達できるように深く切り込む"}]',
'tr': '[{icon:"❄️", t:"Soğuk şurup, sıcak börek", d:"Börek fırından çıkarken şurup tamamen soğumuş olmalı"}, {icon:"🥛", t:"İriksle yoğunlaştırılmış muhallebi", d:"Çırparken ince bir akıntıyla — yavaş eklersen topaklanmaz"}, {icon:"📐", t:"7 alt + 7 üst yufka", d:"Yufkalara tereyağı fırçalanır, kenarlar üste katlanır"}, {icon:"⏰", t:"Kesmeden önce bir gece dinlenir", d:"Şurubun aşağıya ulaşması için derin kesim çizgileri"}]',
'it': '[{icon:"❄️", t:"Sciroppo freddo, torta calda", d:"Lo sciroppo deve essere completamente freddo quando la torta esce dal forno"}, {icon:"🥛", t:"Crema addensata col semolino", d:"Versato a filo mentre si sbatte — niente grumi se lento"}, {icon:"📐", t:"7 fogli sotto + 7 sopra", d:"Phyllo spennellato di burro, bordi ripiegati sopra"}, {icon:"⏰", t:"Riposo notturno prima di tagliare", d:"Incisioni profonde affinché lo sciroppo trovi la sua strada"}]',
'ko': '[{icon:"❄️", t:"차가운 시럽, 뜨거운 파이", d:"파이가 오븐에서 나올 때 시럽은 완전히 차가워야 한다"}, {icon:"🥛", t:"세몰리나로 농축한 커스터드", d:"휘저으며 가는 흐름으로 — 천천히 하면 덩어리 없다"}, {icon:"📐", t:"아래 7장 + 위 7장", d:"필로에 버터를 바르고, 가장자리를 위로 다시 접기"}, {icon:"⏰", t:"자르기 전 하룻밤 정착", d:"시럽이 아래로 길을 찾도록 깊은 칼집"}]',
'hi': '[{icon:"❄️", t:"ठंडी चाशनी, गरम पाई", d:"पाई जब ओवन से निकले तब चाशनी पूरी ठंडी होनी चाहिए"}, {icon:"🥛", t:"सूजी से गाढ़ी कस्टर्ड", d:"फेंटते हुए पतली धार में डालें — धीरे डालें तो गांठ नहीं बनती"}, {icon:"📐", t:"नीचे 7 + ऊपर 7 शीट", d:"phyllo पर मक्खन ब्रश, किनारे ऊपर मोड़ें"}, {icon:"⏰", t:"काटने से पहले रात भर बैठने दें", d:"गहरे निशान ताकि चाशनी नीचे तक रास्ता बना ले"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*198,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 198 (Galaktoboureko): {rec_end-rec_start} → {len(new_recipe_block)} chars")
