#!/usr/bin/env python3
"""Rewrite recipe 199 (Pizza Margherita): 12 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "For the dough, dissolve the yeast in the cold water then mix in the flour and salt until you have a shaggy mass, knead by hand for 10 minutes (or 6 minutes with a stand mixer and dough hook) until smooth and elastic, cover and rest at room temperature for an hour, then refrigerate for at least 24 hours and ideally 48 to 72 — the long cold proof is what gives Neapolitan dough its blistered char and airy structure. Two hours before baking, take the dough out, divide into four 210 g balls, dust with flour, cover with a damp cloth and let them come to room temperature, meanwhile heat the oven as hot as it goes (250°C or above) with a pizza stone or heavy steel sheet inside for at least 45 minutes; without serious heat under the pizza, the crust will never set in time. Hand-stretch one ball on a well-floured surface — press the centre flat with your fingertips leaving a raised lip, then gently pull and stretch the disc to about 28 cm across — never use a rolling pin, which collapses the gas pockets in the crust — and slide it onto a floured peel. Spoon 80 g of crushed tomato into the centre and spread it in a spiral with the back of the spoon stopping 2 cm from the edge, salt the tomato lightly, drizzle a little olive oil, and scatter the torn mozzarella over the top (not too much, or the pizza floods). Slide the pizza onto the stone and bake until the crust is puffed and charred in spots, the cheese has melted into pools and the rim is dark gold — 4 to 6 minutes in a domestic oven at full blast, 90 seconds in a wood-fired Neapolitan oven — pull it out, tear over the basil leaves (which would scorch in the oven), drizzle a final thread of olive oil, and eat immediately.",

'ro': "Pentru aluat, dizolvă drojdia în apa rece, apoi amestecă făina și sarea până obții o masă cu zdrențe, frământă manual 10 minute (sau 6 minute cu mixerul cu cârlig) până devine neted și elastic, acoperă și odihnește la temperatura camerei o oră, apoi refrigerează cel puțin 24 de ore, ideal 48 până la 72 — fermentarea lungă la rece este ce dă aluatului napolitan acea coajă cu blistere arse și structura aerată. Cu două ore înainte de coacere, scoate aluatul, împarte-l în patru bile de 210 g, pudrează cu făină, acoperă cu o cârpă umedă și las-le să ajungă la temperatura camerei, între timp încălzește cuptorul la maxim (250°C sau peste) cu o piatră de pizza sau o tavă grea de oțel înăuntru cel puțin 45 de minute; fără căldură serioasă sub pizza, coaja nu se va închega la timp. Întinde manual o bilă pe o suprafață bine pudrată — apasă centrul cu vârfurile degetelor lăsând o margine ridicată, apoi trage și întinde delicat discul până la circa 28 cm — niciodată un sucitor, care prăbușește buzunarele de gaz din coajă — și alunecă-l pe o lopată cu făină. Pune 80 g de roșii zdrobite în centru și întinde-le într-o spirală cu dosul lingurii, oprindu-te la 2 cm de margine, sărează ușor roșia, picură puțin ulei de măsline și presară mozzarella ruptă deasupra (nu prea multă, altfel pizza se inundă). Alunecă pizza pe piatră și coace până când coaja s-a umflat și are pete arse, brânza s-a topit în băltoace, iar marginea este aurie închis — 4 până la 6 minute într-un cuptor casnic la maxim, 90 de secunde într-un cuptor napolitan cu lemne — scoate-o, rupe deasupra frunzele de busuioc (care ar arde în cuptor), picură un ultim fir de ulei de măsline și mănâncă-o imediat.",

'es': "Para la masa, disuelve la levadura en el agua fría, luego mezcla la harina y la sal hasta obtener una masa rasposa, amasa a mano durante 10 minutos (o 6 minutos con batidora de pie con gancho) hasta que esté lisa y elástica, tapa y deja reposar a temperatura ambiente una hora, después refrigera al menos 24 horas, idealmente 48 a 72 — el largo fermentado en frío es lo que da a la masa napolitana esa corteza ampollada y estructura aireada. Dos horas antes de hornear, saca la masa, divide en cuatro bolas de 210 g, espolvorea con harina, tapa con un paño húmedo y déjalas atemperar, mientras tanto calienta el horno al máximo (250°C o más) con una piedra de pizza o una bandeja de acero pesada dentro al menos 45 minutos; sin calor serio bajo la pizza, la corteza nunca se asentará a tiempo. Estira una bola a mano sobre una superficie bien enharinada — presiona el centro plano con las yemas dejando un borde elevado, luego tira y estira el disco con suavidad hasta unos 28 cm — nunca uses rodillo, que aplasta los bolsillos de gas de la corteza — y deslízala a una pala enharinada. Pon 80 g de tomate triturado en el centro y extiéndelo en espiral con el dorso de la cuchara parando 2 cm del borde, sala ligeramente el tomate, riega un poco de aceite de oliva y esparce la mozzarella desgarrada por encima (no demasiada, o la pizza se inunda). Desliza la pizza sobre la piedra y hornea hasta que la corteza esté hinchada y con manchas chamuscadas, el queso se haya derretido en charcos y el borde sea dorado oscuro — 4 a 6 minutos en un horno doméstico al máximo, 90 segundos en un horno napolitano de leña — sácala, rasga las hojas de albahaca por encima (se quemarían en el horno), riega un último hilo de aceite de oliva y come al momento.",

'fr': "Pour la pâte, dissolvez la levure dans l'eau froide, puis mélangez la farine et le sel jusqu'à obtenir une masse grumeleuse, pétrissez à la main pendant 10 minutes (ou 6 minutes au robot avec crochet pétrisseur) jusqu'à ce que ce soit lisse et élastique, couvrez et faites reposer à température ambiante pendant une heure, puis réfrigérez au moins 24 heures et idéalement 48 à 72 — la longue fermentation à froid est ce qui donne à la pâte napolitaine cette croûte boursouflée et cette structure aérée. Deux heures avant la cuisson, sortez la pâte, divisez en quatre boules de 210 g, fariner, couvrez d'un linge humide et laissez revenir à température ambiante, pendant ce temps chauffez le four au maximum (250°C ou plus) avec une pierre à pizza ou une plaque d'acier épaisse à l'intérieur pendant au moins 45 minutes ; sans une chaleur sérieuse sous la pizza, la croûte ne prendra jamais à temps. Étirez une boule à la main sur une surface bien farinée — appuyez sur le centre avec le bout des doigts en laissant un bord surélevé, puis tirez et étirez délicatement le disque jusqu'à environ 28 cm — n'utilisez jamais de rouleau à pâtisserie, qui écrase les poches de gaz dans la croûte — et glissez-la sur une pelle farinée. Versez 80 g de tomate concassée au centre et étalez-la en spirale avec le dos de la cuillère en vous arrêtant à 2 cm du bord, salez légèrement la tomate, arrosez d'un filet d'huile d'olive, et parsemez la mozzarella déchirée sur le dessus (pas trop, sinon la pizza se noie). Faites glisser la pizza sur la pierre et faites cuire jusqu'à ce que la croûte soit gonflée et tachée de noir, que le fromage ait fondu en flaques et que le bord soit doré foncé — 4 à 6 minutes dans un four domestique à plein régime, 90 secondes dans un four napolitain à bois — sortez-la, déchirez les feuilles de basilic dessus (qui brûleraient au four), arrosez d'un dernier filet d'huile d'olive et mangez immédiatement.",

'de': "Für den Teig die Hefe im kalten Wasser auflösen, dann das Mehl und Salz untermischen, bis eine zottelige Masse entsteht, von Hand 10 Minuten kneten (oder 6 Minuten mit der Küchenmaschine und Knethaken), bis er glatt und elastisch ist, abdecken und bei Raumtemperatur eine Stunde ruhen lassen, dann mindestens 24 Stunden, idealerweise 48 bis 72 Stunden im Kühlschrank gehen lassen — die lange Kaltgare gibt neapolitanischem Teig diese blasige verkohlte Kruste und luftige Struktur. Zwei Stunden vor dem Backen den Teig herausnehmen, in vier 210-g-Kugeln teilen, mit Mehl bestäuben, mit einem feuchten Tuch abdecken und auf Raumtemperatur bringen, in der Zwischenzeit den Ofen so heiß wie möglich vorheizen (250°C oder höher) mit einem Pizzastein oder einer schweren Stahlplatte mindestens 45 Minuten innen; ohne richtige Hitze unter der Pizza wird die Kruste nie rechtzeitig fest. Eine Kugel von Hand auf einer gut bemehlten Fläche dehnen — die Mitte mit den Fingerspitzen flachdrücken und einen erhöhten Rand lassen, dann sanft ziehen und die Scheibe auf etwa 28 cm strecken — niemals ein Nudelholz verwenden, das die Gasblasen in der Kruste zerstört — und auf eine bemehlte Schaufel gleiten lassen. 80 g zerdrückte Tomaten in die Mitte geben und mit der Rückseite des Löffels in einer Spirale verteilen, 2 cm vor dem Rand stoppen, die Tomaten leicht salzen, ein wenig Olivenöl beträufeln und den zerrupften Mozzarella darüber streuen (nicht zu viel, sonst überflutet die Pizza). Die Pizza auf den Stein schieben und backen, bis die Kruste aufgegangen und stellenweise verkohlt ist, der Käse zu Pfützen geschmolzen und der Rand dunkelgolden ist — 4 bis 6 Minuten in einem Haushaltsofen bei voller Leistung, 90 Sekunden in einem holzbefeuerten neapolitanischen Ofen — herausnehmen, die Basilikumblätter darüberreißen (die im Ofen verbrennen würden), einen letzten Faden Olivenöl darüber träufeln und sofort essen.",

'pt': "Para a massa, dissolva o fermento na água fria, depois misture a farinha e o sal até obter uma massa irregular, sove à mão durante 10 minutos (ou 6 minutos com batedeira de pé com gancho) até estar lisa e elástica, tape e deixe descansar à temperatura ambiente uma hora, depois refrigere pelo menos 24 horas, idealmente 48 a 72 — a longa fermentação a frio é o que dá à massa napolitana aquela crosta empolada e estrutura arejada. Duas horas antes de assar, retire a massa, divida em quatro bolas de 210 g, polvilhe com farinha, tape com um pano húmido e deixe vir à temperatura ambiente, entretanto aqueça o forno no máximo (250°C ou mais) com uma pedra de pizza ou uma chapa de aço pesada dentro pelo menos 45 minutos; sem calor sério debaixo da pizza, a crosta nunca firmará a tempo. Estique uma bola à mão sobre uma superfície bem enfarinhada — pressione o centro com as pontas dos dedos deixando uma borda elevada, depois puxe e estique o disco suavemente até cerca de 28 cm — nunca use rolo, que esmaga as bolsas de gás na crosta — e deslize-a para uma pá enfarinhada. Coloque 80 g de tomate esmagado no centro e espalhe em espiral com as costas da colher parando a 2 cm da borda, salgue ligeiramente o tomate, regue com um pouco de azeite, e espalhe o mozzarella desfeito por cima (não em demasia, ou a pizza inunda). Deslize a pizza para a pedra e asse até a crosta estar inchada e com manchas chamuscadas, o queijo ter derretido em poças e a borda estar dourada escura — 4 a 6 minutos num forno doméstico no máximo, 90 segundos num forno napolitano a lenha — retire, rasgue as folhas de manjericão por cima (que se queimariam no forno), regue com um último fio de azeite e coma de imediato.",

'ru': "Для теста растворите дрожжи в холодной воде, затем вмешайте муку и соль до образования лохматой массы, замесите вручную 10 минут (или 6 минут стационарным миксером с крюком) до гладкости и эластичности, накройте и оставьте при комнатной температуре на час, затем поставьте в холодильник минимум на 24 часа, идеально на 48–72 — долгая холодная расстойка даёт неаполитанскому тесту эту пузырчатую обугленную корку и воздушную структуру. За два часа до выпечки достаньте тесто, разделите на четыре шара по 210 г, посыпьте мукой, накройте влажным полотенцем и дайте дойти до комнатной температуры, тем временем разогрейте духовку до максимума (250°C или выше) с камнем для пиццы или тяжёлым стальным листом внутри минимум 45 минут; без серьёзного жара под пиццей корка никогда не успеет схватиться. Растяните один шар руками на хорошо посыпанной мукой поверхности — кончиками пальцев придавите центр плоско, оставляя приподнятый бортик, затем мягко потяните и растяните диск примерно до 28 см — никогда не используйте скалку, она разрушает газовые карманы в корке — и переложите на присыпанную мукой лопату. Положите 80 г раздавленных томатов в центр и распределите спиралью обратной стороной ложки, остановившись в 2 см от края, слегка посолите томаты, сбрызните оливковым маслом и разложите сверху разорванную моцареллу (не слишком много, иначе пицца зальётся). Сдвиньте пиццу на камень и пеките, пока корка не станет вздутой и обугленной местами, сыр не растает в лужицы, а бортик не станет тёмно-золотистым — 4–6 минут в домашней духовке на полную, 90 секунд в дровяной неаполитанской печи — вытащите, разорвите сверху листья базилика (которые сгорели бы в духовке), сбрызните последней нитью оливкового масла и ешьте немедленно.",

'ar': "للعجين، أذِب الخميرة في الماء البارد، ثم اخلط الدقيق والملح حتى تحصل على كتلة خشنة، اعجن باليد لمدة 10 دقائق (أو 6 دقائق بخلاط ثابت مع شفرة العجن) حتى يصبح ناعماً ومرناً، غطّ ودعه يرتاح في درجة حرارة الغرفة لمدة ساعة، ثم برّده في الثلاجة 24 ساعة على الأقل، ويفضل 48 إلى 72 — التخمير البارد الطويل هو ما يمنح العجين النابولي تلك القشرة المتفقعة المتفحمة والبنية الهوائية. قبل الخبز بساعتين، أخرج العجين، قسّمه إلى أربع كرات بوزن 210 جم، رشّ بالطحين، غطّ بقماشة مبللة، ودعها تعود إلى حرارة الغرفة، في هذه الأثناء سخّن الفرن إلى أقصى درجة (250°م أو أعلى) مع حجر بيتزا أو صفيحة فولاذية ثقيلة بالداخل لمدة 45 دقيقة على الأقل؛ بدون حرارة جدية تحت البيتزا، لن تثبت القشرة في الوقت المناسب. ابسط كرة باليد على سطح مرشوش بالطحين بوفرة — اضغط على المركز بأطراف الأصابع تاركاً حافة مرتفعة، ثم اسحب وامدد القرص بلطف إلى نحو 28 سم — لا تستخدم أبداً مرر العجين، فهو يهدم جيوب الغاز في القشرة — وادفعها على مجرفة مرشوشة بالطحين. ضع 80 جم من الطماطم المهروسة في المركز وافردها بشكل حلزوني بظهر الملعقة متوقفاً على بُعد 2 سم من الحافة، رشّ الطماطم بقليل من الملح، رشّ القليل من زيت الزيتون، وانثر الموزاريلا الممزقة فوقها (ليس كثيراً، وإلا فاضت البيتزا). ادفع البيتزا على الحجر واخبزها حتى تنتفخ القشرة وتظهر بقع متفحمة، يذوب الجبن في برك، وتصبح الحافة ذهبية داكنة — 4 إلى 6 دقائق في فرن منزلي على أقصاه، و 90 ثانية في فرن نابولي يعمل بالحطب — أخرجها، مزّق أوراق الريحان فوقها (التي ستحترق في الفرن)، رشّ خيطاً أخيراً من زيت الزيتون، وتناولها فوراً.",

'zh': "做面团：把酵母溶于冷水中，再混入面粉和盐，揉成一团粗糙的面团，手揉 10 分钟（或用厨师机带勾揉 6 分钟）至光滑有弹性，盖好在室温下醒发一小时，再放冰箱冷藏至少 24 小时，最好 48–72 小时——这种长时间的冷发酵正是给那不勒斯面团带来那种起泡焦化的边缘和蓬松结构的关键。烤之前两小时，把面团拿出来，分成四个 210 g 的小球，撒上面粉，盖湿布让它们回到室温；同时把烤箱开到最高档（250°C 或更高），里面放一块披萨石或厚钢板预热至少 45 分钟；没有真正的高温从下面顶住披萨，面饼就来不及成型。在撒了大量面粉的台面上手工拉一个面球——用指尖压平中心，留出隆起的边，然后轻轻把面饼拉伸到约 28 cm——千万不要用擀面杖，那会压碎面边里的气孔——把它移到撒了面粉的披萨铲上。在中心放上 80 g 压碎的番茄，用勺子背面以螺旋状抹开，留出离边 2 cm 的边缘不抹，番茄上撒一点盐，淋一点橄榄油，再把撕碎的莫扎瑞拉撒在上面（不要太多，否则披萨会被淹没）。把披萨滑到石板上烤，直到面边鼓起、有焦黑斑点，奶酪化成一汪汪，边缘呈深金色——家用烤箱满火 4 到 6 分钟，那不勒斯柴火炉 90 秒——拿出来，把罗勒叶撕碎撒上去（放进烤箱会被烤焦），最后再淋一线橄榄油，立刻趁热吃。",

'ja': "生地：冷水でイーストを溶かし、小麦粉と塩を混ぜてざらついた塊にし、手で 10 分（またはスタンドミキサーのドゥフックで 6 分）滑らかで弾力が出るまでこね、覆って室温で 1 時間休ませてから、冷蔵庫で最低 24 時間、理想は 48〜72 時間寝かせる — この長時間の低温発酵こそ、ナポリの生地にあの気泡だらけの焦げた縁と空気を含んだ構造を与えるものだ。焼く 2 時間前に生地を冷蔵庫から出し、210 g のボール 4 個に分け、粉をふって湿った布で覆い、室温に戻す；同時にオーブンを最高温度（250℃ 以上）に予熱し、ピザストーンまたは厚い鋼板を中に入れて最低 45 分予熱する；ピザの下にきちんとした熱がなければ、生地は時間内に固まらない。1 個のボールを粉をふった台で手で伸ばす — 指先で中心を平らに押さえ、縁を盛り上げて残し、ディスクを優しく引っ張って約 28 cm に広げる — 麺棒は絶対に使わない、それは生地の気泡を潰してしまう — そして粉をふったパドルに移す。中心に 80 g の砕いたトマトを置き、スプーンの背で螺旋状に広げ、縁から 2 cm のところで止め、トマトに軽く塩を振り、少量のオリーブオイルを回しかけ、ちぎったモッツァレラを上に散らす（多すぎないように、さもないとピザが浸水する）。ピザを石の上に滑り込ませ、生地が膨らんで所々黒く焦げ、チーズが水たまり状に溶け、縁が濃い金色になるまで焼く — 家庭オーブンの全開で 4〜6 分、薪窯のナポリピザ窯で 90 秒 — 取り出し、バジルの葉をちぎって上に散らし（オーブンに入れると焦げる）、最後のオリーブオイルをひとすじ回しかけ、すぐに食べる。",

'tr': "Hamur için, mayayı soğuk suda erit, sonra unu ve tuzu içine karıştır ve tutarsız bir kütle elde edene dek karıştır, elle 10 dakika (veya hamur kancalı standart mikserle 6 dakika) yoğur — düz ve esnek olana dek — örtüp oda sıcaklığında bir saat dinlendir, sonra en az 24 saat, ideal olarak 48 ila 72 saat buzdolabında tut — uzun soğuk mayalanma, Napoli hamuruna o kabarcıklı kömürleşmiş kabuğu ve havadar yapıyı verir. Pişirmeden iki saat önce, hamuru çıkar, dört adet 210 g'lık top halinde böl, una bula, nemli bir bezle örtüp oda sıcaklığına gelmesini bekle, bu arada fırını gidebileceği kadar yüksek ısıt (250°C veya üzeri) içinde pizza taşı veya ağır çelik levhayla en az 45 dakika; pizzanın altında ciddi ısı olmadan, kabuk asla zamanında oturmaz. Bir topu iyice unlanmış bir yüzeyde elle aç — parmak uçlarıyla merkezi düzleştir, yükseltilmiş bir kenar bırakarak, ardından diski nazikçe çekerek yaklaşık 28 cm'ye kadar genişlet — asla oklava kullanma, kabuktaki gaz ceplerini ezer — ve unlu bir kürek üzerine kaydır. 80 g ezilmiş domatesi merkeze koy ve kaşığın arkasıyla spiral şeklinde yayıp kenardan 2 cm uzakta dur, domatesi hafifçe tuzla, biraz zeytinyağı gezdir, ve parçalanmış mozzarella'yı üstüne serp (çok fazla değil, yoksa pizza taşkın olur). Pizzayı taşın üzerine kaydır ve kabuk kabarıp yer yer kömürleşene, peynir göletler halinde eriyene ve kenar koyu altın olana dek pişir — ev fırınında en yüksek ayarda 4 ila 6 dakika, odun ateşli Napoli fırınında 90 saniye — çıkar, üstüne fesleğen yapraklarını parçala (fırında kavrulurlardı), son bir zeytinyağı ipliği gezdir, ve hemen ye.",

'it': "Per l'impasto, sciogliete il lievito nell'acqua fredda, poi mescolate la farina e il sale fino a ottenere una massa irregolare, impastate a mano per 10 minuti (o 6 minuti con planetaria e gancio) finché non è liscia ed elastica, coprite e fate riposare a temperatura ambiente per un'ora, poi mettete in frigo per almeno 24 ore e idealmente 48 a 72 — la lunga lievitazione a freddo è ciò che dà all'impasto napoletano quella crosta bollita e bruciacchiata e quella struttura ariosa. Due ore prima di infornare, tirate fuori l'impasto, dividete in quattro palline da 210 g, infarinate, coprite con un panno umido e lasciate venire a temperatura ambiente, nel frattempo scaldate il forno al massimo (250°C o oltre) con una pietra refrattaria o una piastra in acciaio dentro per almeno 45 minuti; senza un calore serio sotto la pizza, la crosta non si rapprenderà mai in tempo. Stendete una pallina a mano su una superficie ben infarinata — premete il centro piatto con la punta delle dita lasciando un bordo rialzato, poi tirate e stendete delicatamente il disco fino a circa 28 cm — non usate mai un mattarello, che schiaccia le bolle di gas nella crosta — e fatela scivolare su una pala infarinata. Mettete 80 g di pomodoro schiacciato al centro e stendetelo a spirale con il dorso del cucchiaio fermandovi a 2 cm dal bordo, salate leggermente il pomodoro, condite con un filo d'olio d'oliva, e cospargete la mozzarella spezzata in cima (non troppa, o la pizza si allaga). Fate scivolare la pizza sulla pietra e cuocete fino a quando la crosta non è gonfia e maculata di nero, il formaggio non si è sciolto in pozze e il bordo non è dorato scuro — 4 a 6 minuti in forno domestico al massimo, 90 secondi in un forno napoletano a legna — tirate fuori, spezzettate le foglie di basilico sopra (che si brucerebbero in forno), fate un ultimo filo d'olio d'oliva, e mangiate subito.",

'ko': "반죽: 차가운 물에 이스트를 녹이고, 밀가루와 소금을 섞어 거친 덩어리가 될 때까지 섞은 다음, 손으로 10분(또는 스탠드 믹서의 도우 후크로 6분) 부드럽고 탄력 있게 반죽하고, 덮어 실온에서 1시간 휴지시킨 뒤, 냉장고에서 최소 24시간, 이상적으로는 48–72시간 발효한다 — 긴 저온 발효가 나폴리 도우에 그 거품진 그을린 가장자리와 공기를 머금은 구조를 준다. 굽기 2시간 전, 반죽을 꺼내 210 g씩 네 개의 공으로 나누고, 밀가루를 뿌리고, 젖은 천으로 덮어 실온에 가져오고, 그 사이 오븐을 가능한 한 최고 온도로 (250°C 이상) 안에 피자 스톤이나 두꺼운 스틸 시트를 넣고 최소 45분간 예열한다; 피자 아래에 진지한 열이 없으면, 반죽은 제시간에 굳지 않는다. 한 공을 잘 밀가루를 묻힌 표면에서 손으로 늘린다 — 손가락 끝으로 중앙을 평평하게 누르고 가장자리는 솟아오르게 두고, 디스크를 부드럽게 당겨 약 28 cm까지 펴기 — 절대 밀대를 사용하지 말라, 반죽의 기포를 무너뜨린다 — 그리고 밀가루를 묻힌 페일(주걱)에 옮긴다. 으깬 토마토 80 g을 중앙에 놓고 숟가락 뒷면으로 나선형으로 펴 가장자리에서 2 cm 떨어진 곳에서 멈추고, 토마토에 약간 소금을 뿌리고, 올리브유를 약간 두르고, 찢은 모차렐라를 위에 뿌린다 (너무 많지 않게, 그렇지 않으면 피자가 물에 잠긴다). 피자를 스톤 위로 미끄러뜨려 가장자리가 부풀고 군데군데 그을리고, 치즈가 웅덩이로 녹고, 가장자리가 짙은 황금색이 될 때까지 굽는다 — 가정용 오븐 최대치에서 4–6분, 장작 나폴리 가마에서 90초 — 꺼내고, 위에 바질 잎을 찢어 올리고 (오븐에서는 탄다), 마지막으로 올리브유 한 줄을 두르고, 즉시 먹는다.",

'hi': "आटे के लिए, ख़मीर को ठंडे पानी में घोलें, फिर आटा और नमक मिलाएँ जब तक एक रूखी सी गुठली न बने, हाथ से 10 मिनट तक (या स्टैंड मिक्सर के dough hook से 6 मिनट) तब तक गूँधें जब तक चिकना और लचीला न हो जाए, ढक कर कमरे के तापमान पर एक घंटा आराम दें, फिर कम से कम 24 घंटे, बेहतर 48 से 72 घंटे फ्रिज में रखें — यह लंबा ठंडा फ़र्मेंटेशन ही नियापोलिटन आटे को वह बबल वाला, जला हुआ किनारा और हवादार बनावट देता है। बेकिंग से दो घंटे पहले, आटा निकालें, 210 g के चार गोले बनाएँ, आटा छिड़कें, गीले कपड़े से ढक कर कमरे के तापमान तक आने दें, इस बीच ओवन को जितना गरम हो सके (250°C या ऊपर) करें, अंदर पिज़्ज़ा स्टोन या भारी स्टील शीट रख कर कम से कम 45 मिनट गरम करें; पिज़्ज़ा के नीचे गंभीर गर्मी के बिना crust समय पर नहीं जमेगा। एक गोले को अच्छे से आटा छिड़की सतह पर हाथ से फैलाएँ — उँगलियों से बीच को दबाएँ, उठा हुआ किनारा छोड़ें, फिर डिस्क को धीरे से खींच कर लगभग 28 सेमी तक फैलाएँ — कभी बेलन का इस्तेमाल न करें, वह crust की गैस की जेबें कुचल देता है — और आटा छिड़की पैडल पर सरकाएँ। 80 g कुचले टमाटर को बीच में रखें और चम्मच के पीछे से spiral में फैलाएँ, किनारे से 2 सेमी पहले रुकें, टमाटर पर हलका नमक छिड़कें, थोड़ा ओलिव ऑयल डालें, और टुकड़े-टुकड़े मोज़रेला ऊपर बिखेर दें (बहुत ज़्यादा नहीं, वर्ना पिज़्ज़ा डूब जाएगा)। पिज़्ज़ा को स्टोन पर सरकाएँ और तब तक बेक करें जब तक crust फूल जाए और कहीं-कहीं काली पड़ जाए, चीज़ पिघल कर पोखर बना ले और किनारा गहरा सुनहरा हो जाए — घरेलू ओवन में पूरी आँच पर 4 से 6 मिनट, लकड़ी से जलने वाले नियापोलिटन ओवन में 90 सेकंड — निकालें, ऊपर तुलसी के पत्ते तोड़ कर डालें (ओवन में जल जाते), अंत में ओलिव ऑयल की एक धार डालें, और तुरंत खाएँ।",
}

FEATURE_CARDS = {
'en': '[{icon:"⏰", t:"48–72h cold proof", d:"What gives Neapolitan dough its char and airy structure"}, {icon:"🔥", t:"Stone heated 45+ min", d:"Without serious heat under the pizza, the crust never sets"}, {icon:"✋", t:"Hand-stretch, never roll", d:"Rolling pin collapses the gas pockets in the crust"}, {icon:"🌿", t:"Basil after the oven", d:"Leaves added after baking — heat would scorch them"}]',
'ro': '[{icon:"⏰", t:"Fermentare 48–72h la rece", d:"Ce dă aluatului napolitan culoarea arsă și structura aerată"}, {icon:"🔥", t:"Piatră încălzită 45+ min", d:"Fără căldură serioasă sub pizza, coaja nu se închega niciodată"}, {icon:"✋", t:"Întins manual, niciodată cu sucitor", d:"Sucitorul prăbușește buzunarele de gaz din coajă"}, {icon:"🌿", t:"Busuiocul după cuptor", d:"Frunzele se adaugă după coacere — căldura le-ar arde"}]',
'es': '[{icon:"⏰", t:"Fermentación en frío 48–72h", d:"Lo que da a la masa napolitana su carbonizado y estructura aireada"}, {icon:"🔥", t:"Piedra calentada 45+ min", d:"Sin calor serio bajo la pizza, la corteza nunca se asienta"}, {icon:"✋", t:"Estirar a mano, nunca con rodillo", d:"El rodillo aplasta los bolsillos de gas en la corteza"}, {icon:"🌿", t:"Albahaca después del horno", d:"Las hojas se añaden tras hornear — el calor las quemaría"}]',
'fr': '[{icon:"⏰", t:"Fermentation à froid 48–72h", d:"Ce qui donne à la pâte napolitaine son charbon et sa structure aérée"}, {icon:"🔥", t:"Pierre chauffée 45+ min", d:"Sans chaleur sérieuse sous la pizza, la croûte ne prend jamais"}, {icon:"✋", t:"Étirer à la main, jamais au rouleau", d:"Le rouleau écrase les poches de gaz dans la croûte"}, {icon:"🌿", t:"Basilic après le four", d:"Les feuilles ajoutées après cuisson — la chaleur les brûlerait"}]',
'de': '[{icon:"⏰", t:"48–72h Kaltgare", d:"Was dem neapolitanischen Teig den Char und die luftige Struktur gibt"}, {icon:"🔥", t:"Stein 45+ Min vorgeheizt", d:"Ohne ernsthafte Hitze unter der Pizza wird die Kruste nie fest"}, {icon:"✋", t:"Mit der Hand strecken, nie rollen", d:"Das Nudelholz zerstört die Gasblasen in der Kruste"}, {icon:"🌿", t:"Basilikum nach dem Ofen", d:"Blätter nach dem Backen hinzugefügt — Hitze würde sie verbrennen"}]',
'pt': '[{icon:"⏰", t:"Fermentação fria 48–72h", d:"O que dá à massa napolitana o tostado e estrutura arejada"}, {icon:"🔥", t:"Pedra aquecida 45+ min", d:"Sem calor sério sob a pizza, a crosta nunca firma"}, {icon:"✋", t:"Esticar à mão, nunca rolar", d:"O rolo esmaga as bolsas de gás na crosta"}, {icon:"🌿", t:"Manjericão depois do forno", d:"As folhas adicionadas após assar — o calor as queimaria"}]',
'ru': '[{icon:"⏰", t:"Холодная расстойка 48–72ч", d:"Что даёт неаполитанскому тесту обугливание и воздушную структуру"}, {icon:"🔥", t:"Камень нагрет 45+ мин", d:"Без серьёзного жара под пиццей корка никогда не схватится"}, {icon:"✋", t:"Растягивать руками, не скалкой", d:"Скалка разрушает газовые карманы в корке"}, {icon:"🌿", t:"Базилик после духовки", d:"Листья добавляются после выпечки — жар их сжёг бы"}]',
'ar': '[{icon:"⏰", t:"تخمير بارد 48–72 ساعة", d:"ما يمنح العجين النابولي تفحّمه وبنيته الهوائية"}, {icon:"🔥", t:"حجر مسخّن 45+ دقيقة", d:"بدون حرارة جدية تحت البيتزا، لن تثبت القشرة أبداً"}, {icon:"✋", t:"بسط باليد، أبداً بمرر", d:"المرر يهدم جيوب الغاز في القشرة"}, {icon:"🌿", t:"الريحان بعد الفرن", d:"تُضاف الأوراق بعد الخبز — الحرارة ستحرقها"}]',
'zh': '[{icon:"⏰", t:"48–72 小时低温发酵", d:"那不勒斯面团焦化和蓬松结构的来源"}, {icon:"🔥", t:"石板预热 45+ 分钟", d:"披萨下没有真正的高温，面边永远不会成型"}, {icon:"✋", t:"手工拉伸，绝不擀面", d:"擀面杖会压碎面边里的气孔"}, {icon:"🌿", t:"罗勒在出炉后加", d:"叶子是烤后加的——高温会把它们烤焦"}]',
'ja': '[{icon:"⏰", t:"48〜72 時間の低温発酵", d:"ナポリ生地のチャーと空気の構造を与えるもの"}, {icon:"🔥", t:"石板を 45 分以上予熱", d:"ピザの下に本気の熱がなければ、生地は時間内に固まらない"}, {icon:"✋", t:"手で伸ばす、麺棒は絶対不可", d:"麺棒は生地のガス気泡を潰す"}, {icon:"🌿", t:"バジルはオーブンの後", d:"焼いた後に葉を加える — 熱で焦げてしまう"}]',
'tr': '[{icon:"⏰", t:"48–72 saat soğuk mayalanma", d:"Napoli hamuruna kömürleşmesini ve havadar yapısını veren şey"}, {icon:"🔥", t:"Taş 45+ dakika ısıtılır", d:"Pizzanın altında ciddi ısı olmadan, kabuk asla oturmaz"}, {icon:"✋", t:"Elle aç, asla oklavayla değil", d:"Oklava kabuktaki gaz ceplerini ezer"}, {icon:"🌿", t:"Fesleğen fırın sonrası", d:"Yapraklar pişirmeden sonra eklenir — ısı onları yakar"}]',
'it': '[{icon:"⏰", t:"Lievitazione fredda 48–72h", d:"Ciò che dà all\'impasto napoletano la bruciacchiatura e la struttura ariosa"}, {icon:"🔥", t:"Pietra preriscaldata 45+ min", d:"Senza calore serio sotto la pizza, la crosta non si rapprende"}, {icon:"✋", t:"Stendere a mano, mai col mattarello", d:"Il mattarello schiaccia le bolle di gas nella crosta"}, {icon:"🌿", t:"Basilico dopo il forno", d:"Foglie aggiunte dopo la cottura — il calore le brucerebbe"}]',
'ko': '[{icon:"⏰", t:"48–72시간 저온 발효", d:"나폴리 도우에 그을림과 공기 구조를 주는 것"}, {icon:"🔥", t:"스톤 45분 이상 예열", d:"피자 아래에 진지한 열이 없으면 반죽이 굳지 않는다"}, {icon:"✋", t:"손으로 늘리기, 절대 밀대 금지", d:"밀대는 반죽의 가스 기포를 무너뜨린다"}, {icon:"🌿", t:"오븐 후 바질", d:"잎은 굽고 나서 — 열에 그을릴 수 있음"}]',
'hi': '[{icon:"⏰", t:"48–72 घंटे ठंडा फ़र्मेंटेशन", d:"नियापोलिटन आटे को जला किनारा और हवादार बनावट देता है"}, {icon:"🔥", t:"पत्थर 45+ मिनट गरम", d:"पिज़्ज़ा के नीचे गंभीर गर्मी के बिना crust नहीं जमेगा"}, {icon:"✋", t:"हाथ से फैलाएँ, बेलन कभी नहीं", d:"बेलन crust की गैस की जेबें कुचल देता है"}, {icon:"🌿", t:"तुलसी ओवन के बाद", d:"पत्तियाँ बेकिंग के बाद डाली जाती हैं — गर्मी उन्हें जला देगी"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*199,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 199 (Pizza Margherita): {rec_end-rec_start} → {len(new_recipe_block)} chars")
