#!/usr/bin/env python3
"""Rewrite recipe 208 (Samosa): howIsMade 18 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Rub the ghee into the flour, ajwain and salt with your fingertips until the mixture resembles coarse breadcrumbs — the amount of fat is what gives samosa pastry its blistered, biscuit-crisp shell — then add the cold water a tablespoon at a time, mixing into a stiff smooth dough (softer than chapati but firmer than bread dough) and rest it covered for 30 minutes. Boil the potatoes in their skins until just tender, drain, peel and crush coarsely with the back of a fork (you want texture, not mash); heat the oil in a wide pan, add the cumin seeds and let them sizzle, then the ginger and green chilli for 30 seconds, stir in the dry spices and fry briefly, tip in the potato, peas, salt, amchur and coriander, and cook 4–5 minutes turning everything until the spices coat every piece — cool to room temperature before shaping. Divide the dough into 8 balls, roll one into a thin oval about 18 cm long and cut across the middle to make two half-circles; take one half, brush a thin line of water along the straight edge, and fold into a cone by bringing the two corners of the straight edge together so they overlap by 1 cm, pinching the seam tightly to seal. Hold the cone in one hand, fill it three-quarters with potato, then pleat the open edge by folding a small tuck on one side and sealing the rim shut with a damp finger — the tucked pleat creates the samosa's signature side ridge and helps it sit upright while cooking — and repeat with the rest. Heat the frying oil to 150°C (lower than you might expect, but the slow climb is what gives the shell its blisters), slip in the samosas in batches of 3 or 4 and fry 6–7 minutes turning gently until pale gold, then raise the heat to 180°C and fry another 3–4 minutes until deep golden and properly crisp, draining on a rack and serving hot with tamarind and mint chutneys.",

'ro': "Freacă ghee-ul în făină, ajwain și sare cu buricele degetelor până când amestecul seamănă cu pesmet grosier — cantitatea de grăsime este ceea ce dă cojii de samosa textura ei băltită și de biscuit crocant — apoi adaugă apa rece lingură cu lingură, frământând până obții un aluat ferm și neted (mai moale decât pentru chapati, mai dens decât pentru pâine) și odihnește-l acoperit 30 de minute. Fierbe cartofii în coajă până sunt abia moi, scurge-i, curăță-i și strivește-i grosier cu dosul furculiței (vrei textură, nu piure); încălzește uleiul într-o tigaie largă, adaugă semințele de chimion și las-le să sfârâie, apoi ghimbirul și ardeiul verde pentru 30 de secunde, adaugă mirodeniile uscate și prăjește-le scurt, pune cartofii, mazărea, sarea, amchur-ul și coriandrul și gătește 4–5 minute, întorcând totul împreună până când mirodeniile învelesc fiecare bucată — răcește la temperatura camerei înainte de modelat. Împarte aluatul în 8 bile, întinde una într-un oval subțire de aproximativ 18 cm lungime și taie-o pe mijloc pentru două semicercuri; ia o jumătate, pensulează o linie subțire de apă pe muchia dreaptă și pliază-l într-un con aducând cele două colțuri ale muchiei drepte împreună cu suprapunere de 1 cm, strângând bine cusătura ca să o sigilezi. Ține conul într-o mână, umple-l cu cartof până la trei sferturi, apoi pliază marginea deschisă printr-o cută mică pe o parte și sigilează gura cu un deget umed — cuta strânsă creează nervura laterală caracteristică a samosa-ului și o ajută să stea în picioare la prăjit — repetă cu restul. Încălzește uleiul pentru prăjit la 150°C (mai jos decât te-ai aștepta, dar urcatul lent este cel care dă coajii băltirea ei), pune samosa-urile în reprize de 3 sau 4 și prăjește-le 6–7 minute, întorcându-le ușor, până devin auriu palid, apoi ridică temperatura la 180°C și mai prăjește-le 3–4 minute, până devin aurii adânc și crocante, scurgând pe un grătar și servind calde cu chutney de tamarind și chutney de mentă.",

'es': "Frota el ghee con la harina, el ajowán y la sal con las yemas hasta que la mezcla recuerde a migas gruesas — la cantidad de grasa es lo que da a la masa de samosa esa cáscara abullonada y crujiente como bizcocho — después añade el agua fría cucharada a cucharada, hasta una masa firme y lisa (más blanda que la de chapati pero más firme que la de pan) y déjala reposar tapada 30 minutos. Cuece las patatas con piel hasta que estén apenas tiernas, escúrrelas, pélalas y rómpelas con el revés del tenedor (quieres textura, no puré); calienta el aceite en una sartén ancha, añade las semillas de comino y deja que chisporroteen, después el jengibre y el chile verde durante 30 segundos, incorpora las especias secas y fríelas brevemente, vuelca la patata, los guisantes, la sal, el amchur y el cilantro, y cocina 4–5 minutos, girando todo hasta que las especias cubran cada trozo — enfría a temperatura ambiente antes de formar. Divide la masa en 8 bolas, estira una en un óvalo fino de unos 18 cm y córtala por la mitad para hacer dos semicírculos; toma una mitad, pinta una línea fina de agua a lo largo del borde recto y pliega en cono uniendo las dos esquinas del borde recto de modo que se superpongan 1 cm, apretando la unión con fuerza para sellarla. Sujeta el cono en una mano, rellénalo de patata hasta tres cuartos, después pliega el borde abierto haciendo un pequeño pliegue en un lado y cerrando el borde con un dedo húmedo — ese pliegue crea la cresta lateral característica de la samosa y la ayuda a quedar en pie al freírse — repite con el resto. Calienta el aceite a 150°C (más bajo de lo que esperarías, pero la subida lenta es lo que da a la cáscara sus burbujas), echa las samosas en tandas de 3 o 4 y fríe 6–7 minutos, girándolas con suavidad, hasta que estén pálidamente doradas, después sube a 180°C y fríe otros 3–4 minutos hasta un dorado profundo y crujientes de verdad, escurriendo sobre rejilla y sirviendo calientes con chutneys de tamarindo y de menta.",

'fr': "Sablez le ghee dans la farine, l'ajowan et le sel du bout des doigts jusqu'à obtenir une chapelure grossière — la quantité de gras est ce qui donne à la pâte des samoussas son enveloppe boursouflée et croustillante — puis ajoutez l'eau froide cuillère par cuillère, en pétrissant jusqu'à une pâte ferme et lisse (plus souple qu'une pâte à chapati mais plus ferme qu'une pâte à pain) et faites-la reposer couverte 30 minutes. Faites cuire les pommes de terre en robe des champs jusqu'à ce qu'elles soient juste tendres, égouttez, pelez et écrasez-les grossièrement au dos de la fourchette (on veut de la texture, pas de la purée) ; faites chauffer l'huile dans une grande poêle, ajoutez les graines de cumin et laissez-les crépiter, puis le gingembre et le piment vert pendant 30 secondes, incorporez les épices sèches et faites-les frire un instant, versez les pommes de terre, les petits pois, le sel, l'amchur et la coriandre, et faites cuire 4 à 5 minutes en mélangeant tout jusqu'à ce que les épices enrobent chaque morceau — laissez refroidir à température ambiante avant de façonner. Divisez la pâte en 8 boules, étalez-en une en un ovale fin d'environ 18 cm et coupez-la en deux pour obtenir deux demi-cercles ; prenez une demi-lune, badigeonnez d'un filet d'eau le bord droit et pliez en cône en réunissant les deux coins du bord droit qui se chevauchent sur 1 cm, en pinçant la couture fermement pour sceller. Tenez le cône dans une main, garnissez-le de pommes de terre aux trois quarts, puis plissez le bord ouvert en repliant un petit pli sur un côté et en scellant l'ouverture avec un doigt humide — ce pli crée l'arête latérale caractéristique du samoussa et lui permet de tenir debout pendant la cuisson — répétez pour le reste. Chauffez l'huile à 150°C (plus bas qu'on ne le penserait, mais la montée lente est ce qui donne à la coque ses cloques), plongez-y les samoussas par 3 ou 4 et faites-les frire 6 à 7 minutes en les retournant doucement, jusqu'à un blond pâle, puis montez la température à 180°C et faites frire encore 3 à 4 minutes jusqu'à un blond foncé et bien croustillants, en égouttant sur grille et en servant chauds avec un chutney de tamarin et un chutney à la menthe.",

'de': "Reiben Sie das Ghee mit Mehl, Ajwain und Salz mit den Fingerspitzen, bis die Mischung grobe Brösel ergibt — die Menge Fett ist es, die der Samosa-Hülle ihre blasige, biscuitartige Knusprigkeit gibt — geben Sie dann das kalte Wasser löffelweise dazu und kneten Sie zu einem festen, glatten Teig (weicher als Chapati-Teig, aber fester als Brotteig) und lassen Sie ihn abgedeckt 30 Minuten ruhen. Kochen Sie die Kartoffeln in der Schale bis sie gerade weich sind, abgießen, schälen und mit dem Gabelrücken grob zerdrücken (Sie wollen Textur, kein Püree); erhitzen Sie das Öl in einer breiten Pfanne, geben Sie die Kreuzkümmelsamen hinein und lassen Sie sie aufzischen, dann den Ingwer und die grüne Chili für 30 Sekunden, rühren Sie die trockenen Gewürze ein und braten Sie sie kurz an, geben Sie die Kartoffel, Erbsen, Salz, Amchur und Koriander dazu und braten Sie 4–5 Minuten unter Wenden, bis die Gewürze jedes Stück überziehen — auf Zimmertemperatur abkühlen lassen, bevor Sie formen. Teilen Sie den Teig in 8 Kugeln, rollen Sie eine zu einem dünnen Oval von etwa 18 cm aus und schneiden Sie sie in der Mitte in zwei Halbkreise; bestreichen Sie an einer Halbmondhälfte die gerade Kante mit einem dünnen Wasserstreifen und falten Sie sie zu einem Kegel, indem Sie die beiden Ecken der geraden Kante zusammenführen und 1 cm überlappen lassen, drücken Sie die Naht fest zusammen, damit sie hält. Halten Sie den Kegel in einer Hand, füllen Sie ihn zu drei Vierteln mit Kartoffel, dann falten Sie die offene Kante mit einer kleinen Falte auf einer Seite und verschließen Sie den Rand mit feuchtem Finger — diese Falte erzeugt die charakteristische Kante an der Samosa und hilft ihr, beim Frittieren aufrecht zu stehen — wiederholen Sie das mit dem Rest. Erhitzen Sie das Frittieröl auf 150°C (niedriger als man denkt, aber der langsame Aufstieg ist es, der die Blasen erzeugt), geben Sie die Samosas in Portionen von 3 oder 4 hinein und frittieren Sie sie 6–7 Minuten, dabei sanft wenden, bis sie hellgelb sind, erhöhen Sie auf 180°C und frittieren Sie weitere 3–4 Minuten, bis sie tief goldbraun und richtig knusprig sind, auf einem Gitter abtropfen lassen und heiß mit Tamarinden- und Minz-Chutney servieren.",

'pt': "Esfregue o ghee na farinha, ajwain e sal com as pontas dos dedos até a mistura parecer farelo grosseiro — a quantidade de gordura é o que dá à massa de samosa a sua casca empolada e crocante como biscoito — adicione depois a água fria colher a colher, amassando até obter uma massa firme e lisa (mais macia que a do chapati, mais firme que a do pão) e deixe descansar tapada 30 minutos. Cozinhe as batatas com pele até estarem mal cozidas, escorra, descasque e esmague grosseiramente com o dorso do garfo (quer-se textura, não puré); aqueça o óleo numa frigideira larga, junte as sementes de cominho e deixe estalar, depois o gengibre e o piri-piri verde durante 30 segundos, junte as especiarias secas e frite-as brevemente, deite as batatas, ervilhas, sal, amchur e coentros, e cozinhe 4–5 minutos, envolvendo tudo até as especiarias cobrirem cada pedaço — arrefeça à temperatura ambiente antes de moldar. Divida a massa em 8 bolas, estenda uma num oval fino de cerca de 18 cm e corte ao meio para fazer duas meias-luas; pegue numa, pincele uma linha fina de água ao longo do lado reto e dobre em cone juntando as duas pontas do lado reto sobrepondo 1 cm, apertando a costura com força para selar. Segure o cone numa mão, recheie até três quartos com batata, depois pregueia o bordo aberto dobrando uma pequena prega de um lado e selando a borda com um dedo húmido — essa prega cria a nervura lateral característica da samosa e ajuda-a a ficar de pé enquanto frita — repita com o resto. Aqueça o óleo a 150°C (mais baixo do que se esperaria, mas a subida lenta é o que dá à casca as suas bolhas), coloque as samosas em lotes de 3 ou 4 e frite 6–7 minutos, virando suavemente, até estarem amarelo-pálido, aumente para 180°C e frite mais 3–4 minutos, até um dourado profundo e bem crocantes, escorrendo sobre uma grelha e servindo quentes com chutney de tamarindo e chutney de hortelã-coentros.",

'ru': "Втирайте ги в муку, аджвайн и соль кончиками пальцев, пока смесь не станет похожа на грубую крошку — именно количество жира даёт оболочке самосы её пузырчатую, бисквитную хрусткость — добавляйте затем холодную воду по ложке, замешивая плотное гладкое тесто (мягче чапати, но плотнее хлебного) и оставьте под крышкой на 30 минут. Отварите картофель в кожуре до едва мягкости, слейте, очистите и крупно разомните вилкой (вам нужна текстура, а не пюре); разогрейте масло в широкой сковороде, добавьте семена зиры и дайте им подсиплеть, затем имбирь и зелёный перец на 30 секунд, вмешайте сухие специи и обжарьте коротко, добавьте картофель, горошек, соль, амчур и кинзу и готовьте 4–5 минут, переворачивая всё вместе, пока специи не покроют каждый кусок — остудите до комнатной температуры перед формовкой. Разделите тесто на 8 шаров, раскатайте один в тонкий овал длиной около 18 см и разрежьте поперёк пополам, две половинки; возьмите одну, проведите тонкую полоску воды по прямому краю и сверните в конус, соединив два угла прямого края с нахлёстом в 1 см, сильно прижмите шов для герметичности. Держите конус в одной руке, наполните его картофелем на три четверти, затем сложите открытый край маленькой складкой на одной стороне и запечатайте кромку влажным пальцем — эта складка создаёт характерное боковое ребро самосы и помогает ей стоять при жарке — повторите с остальными. Разогрейте масло до 150°C (ниже, чем ожидаешь, но именно медленный подъём даёт оболочке её пузыри), опускайте самосы партиями по 3–4 и жарьте 6–7 минут, аккуратно переворачивая, до бледно-золотистого, поднимите температуру до 180°C и жарьте ещё 3–4 минуты до глубокого золотистого и настоящей хрусткости, откиньте на решётку и подавайте горячими с тамариндовым и мятным чатни.",

'ar': "افرك السمن في الدقيق والأجوين والملح بأطراف الأصابع حتى يصبح المزيج كفتات الخبز الخشن — كمية الدهن هي ما يعطي قشرة السمبوسة قرمشتها الفقاعية كالبسكويت — أضف الماء البارد ملعقةً ملعقة، واعجن حتى تصبح عجينة متماسكة وناعمة (أطرى من عجين الشاباتي وأشد من عجين الخبز)، وأرحها مغطاة 30 دقيقة. اسلق البطاطس بقشرها حتى تطرى للتو، صفّها وقشّرها واهرسها بظهر الشوكة بشكل خشن (نريد قواماً لا بوريه)؛ سخّن الزيت في مقلاة واسعة، أضف بذور الكمون واتركها تطقطق، ثم الزنجبيل والفلفل الأخضر لمدة 30 ثانية، أضف البهارات الناعمة وقلّبها لحظة، ثم ادفع البطاطس والبازلاء والملح والأمشور والكزبرة، واطبخها 4–5 دقائق مع التقليب حتى تغلف البهارات كل قطعة — برّدها إلى حرارة الغرفة قبل التشكيل. قسّم العجين إلى 8 كرات، افرد واحدة على شكل بيضاوي رفيع بطول نحو 18 سم واقطعها في الوسط لتحصل على نصفي دائرة؛ خذ نصفاً، ادهن خطاً رفيعاً من الماء على الحافة المستقيمة، وأطوه على شكل مخروط بأن تجمع زاويتي الحافة المستقيمة مع تداخل 1 سم، اضغط على اللحام بإحكام لتثبيته. أمسك المخروط بيد، املأه بالحشوة حتى ثلاثة أرباع، ثم قسّم الحافة المفتوحة بثنية صغيرة من جهة واحدة وأحكم الإغلاق بإصبع مبلل — هذه الثنية تخلق الحافة الجانبية المميّزة للسمبوسة وتساعدها على الوقوف عند القلي — كرّر مع البقية. سخّن زيت القلي إلى 150°م (أقل مما تتوقّع، لكن التسخين البطيء هو ما يمنح القشرة فقاعاتها)، أنزل السمبوسات بدفعات من 3 أو 4 واقلِها 6–7 دقائق مع التقليب اللطيف حتى تصبح ذهبية شاحبة، ارفع الحرارة إلى 180°م واقلِها 3–4 دقائق إضافية حتى تصير ذهبية غامقة ومقرمشة فعلاً، صفّها على شبكة وقدّمها ساخنة مع شطنة التمر الهندي وشطنة النعناع-الكزبرة.",

'zh': "用指尖把酥油搓进面粉、ajwain 和盐里，直到混合物像粗面包屑——这层油脂的份量正是给 samosa 外壳那种带气泡、像饼干一样酥脆的关键——冷水一汤匙一汤匙地加，揉成一团硬而光滑的面团（比 chapati 软、比面包面团硬），盖好醒 30 分钟。带皮把土豆煮到刚熟，捞出剥皮，用叉背粗略地碾碎（要的是颗粒，不是泥）；在宽锅中热油，下孜然籽爆香，再下姜和青辣椒炒 30 秒，加入干性香料快速炒一下，倒入土豆、豌豆、盐、amchur 和切碎的香菜，翻拌 4–5 分钟，让每一块都裹上香料——冷却到室温再开始包。面团分成 8 个小球，把一个擀成一个长约 18 厘米的薄椭圆，再从中间一切两半得到两个半圆；取一个半圆，在直边上刷一条细水线，将直边的两个角合到一起、交叠 1 厘米折成一个圆锥，把接缝用力捏紧封死。一只手托住圆锥，把土豆馅填到三分之二满，再把开口处的一边折一个小褶，用湿手指把口完全封死——这一小折就是 samosa 标志性的侧棱，也让它在油里能立得住——其余照做。把油加热到 150°C（比想象中低，但慢慢升温正是外壳起泡的关键），每次下 3–4 个 samosa 炸 6–7 分钟，轻轻翻动，让它呈淡金色，然后把油温升到 180°C 再炸 3–4 分钟，直到呈深金色、真正酥脆，沥在网架上，趁热配上罗望子和薄荷-香菜 chutney 享用。",

'ja': "ギーを薄力粉、アジョワン、塩の中に指先ですり込み、粗いパン粉のような状態にする — この脂の量こそが、サモサの皮にあのビスケットのような波打つカリッとした食感を与える — 冷水を大さじ 1 ずつ加え、しっかりしてなめらかな生地にこねる（チャパティより少し柔らかく、パンよりは硬い）、覆って 30 分休ませる。じゃがいもを皮ごとちょうど火が通るまで茹で、湯切りして皮を剥き、フォークの背で粗くつぶす（マッシュではなく食感を残す）；広めの鍋で油を熱し、クミンシードを入れて香りを立たせ、しょうがと青唐辛子を 30 秒、乾燥スパイスを加えてさっと炒め、じゃがいも、グリーンピース、塩、アムチュール、コリアンダーを入れ、全体を返しながら 4〜5 分、スパイスが一切れ一切れにまとうまで炒める — 成形する前に常温まで冷ます。生地を 8 個の球に分け、1 つを長さ約 18 cm の薄い楕円形に伸ばし、中央でカットして半円を 2 つ作る；半円を 1 枚取り、直線の縁に細い水のラインを刷毛で塗り、直線の角どうしが 1 cm 重なるようにコーン状に巻く、継ぎ目をしっかりつまんで閉じる。片手でコーンを持ち、4 分の 3 までじゃがいもの具を詰め、開いた縁を片側に小さなひだを折り込みながら閉じ、湿らせた指で縁を完全に密着させる — この折り込みがサモサ特有の側面の稜線を作り、揚げるときに自立する助けにもなる — 残りも同じ手順で。揚げ油を 150℃ に熱する（思うより低めだが、このゆっくりした温度上昇こそが皮にあの気泡を作る）、サモサを 3〜4 個ずつ落とし入れて優しく返しながら 6〜7 分、淡い黄金色になるまで揚げ、温度を 180℃ に上げてさらに 3〜4 分、深い黄金色とちゃんとした歯ごたえになるまで揚げる、網にあげて油を切り、温かいうちにタマリンドとミントのチャツネを添えて供する。",

'tr': "Ghee'yi un, ajwain ve tuza parmak uçlarınla ovalayarak iri ekmek kırıntısı kıvamına getir — bu yağ miktarı, samosa kabuğuna o kabarcıklı, bisküvi gibi çıtır dokuyu veren şeydir — soğuk suyu birer yemek kaşığı şeklinde ekle ve sıkı ama pürüzsüz bir hamur olana dek yoğur (chapati'den daha yumuşak, ekmek hamurundan daha sert), üzerini örtüp 30 dakika dinlendir. Patatesleri kabuklarıyla tam yumuşayana kadar haşla, süz, soy ve çatal arkasıyla kabaca ez (istediğin doku, ezme değil); geniş bir tavada yağı ısıt, kimyon tohumlarını ekle ve cızırdatmasını izle, sonra zencefil ve yeşil acı biberi 30 saniye, toz baharatları ekle ve kısa süre kavur, sonra patates, bezelye, tuz, amchur ve kişnişi ekle, baharatlar her parçayı kaplayana dek 4–5 dakika çevirerek pişir — şekillendirmeden önce oda sıcaklığına gelmesini bekle. Hamuru 8 topa böl, birini yaklaşık 18 cm uzunluğunda ince bir oval şeklinde aç, ortadan keserek iki yarım daire elde et; bir yarım daireyi al, düz kenara ince bir su çizgisi sür ve düz kenarın iki ucunu 1 cm üst üste binecek şekilde getirerek koni biçimine getir, birleştirme yerini sıkıca tutarak mühürle. Koniyi bir elle tut, patates harcıyla dörtte üçüne kadar doldur, sonra açık kenarı bir yandan küçük bir kıvrım yaparak ve nemli parmağınla kenarı kapatarak kapat — bu kıvrım, samosanın kendine has yan sırtını yaratır ve kızartılırken dik durmasına yardımcı olur — geri kalanı aynı şekilde yap. Kızartma yağını 150°C'ye ısıt (beklediğinden düşük, ama yavaş tırmanış kabuğa o kabarcıkları veren şeydir), samosaları 3 veya 4'lü gruplar halinde yağa indir ve 6–7 dakika nazikçe çevirerek soluk altın olana dek kızart, sıcaklığı 180°C'ye yükselt ve 3–4 dakika daha, derin altın rengine ve gerçek bir çıtırlığa ulaşana dek kızart, telli bir ızgaraya alıp süz ve sıcakken demirhindi ile nane-kişniş soslarıyla servis et.",

'it': "Sfregate il ghee con la farina, l'ajwain e il sale con la punta delle dita finché il composto non somiglia a una panatura grossolana — la quantità di grasso è ciò che dà alla pasta della samosa quella crosta increspata e croccante come un biscotto — aggiungete l'acqua fredda un cucchiaio alla volta, impastando fino a un impasto sodo e liscio (più morbido di quello del chapati ma più fermo di quello del pane) e fatelo riposare coperto 30 minuti. Lessate le patate con la buccia finché non sono appena tenere, scolatele, pelatele e schiacciatele grossolanamente con il dorso della forchetta (volete consistenza, non purè); scaldate l'olio in una padella ampia, aggiungete i semi di cumino e lasciateli sfrigolare, poi lo zenzero e il peperoncino verde per 30 secondi, unite le spezie in polvere e fatele saltare brevemente, versate le patate, i piselli, il sale, l'amchur e il coriandolo, e fate cuocere 4–5 minuti rigirando il tutto finché le spezie non rivestono ogni pezzo — lasciate raffreddare a temperatura ambiente prima di formare. Dividete l'impasto in 8 palline, stendetene una in un ovale sottile di circa 18 cm e tagliatela a metà per ottenere due semicerchi; prendete un semicerchio, spennellate una linea sottile d'acqua lungo il lato dritto e piegatelo a cono unendo i due angoli del lato dritto sovrapponendoli di 1 cm, pizzicate la cucitura con forza per sigillarla. Reggete il cono in una mano, riempitelo per tre quarti di patata, poi pieghettate il bordo aperto facendo una piccola piega da un lato e sigillando l'apertura con un dito umido — quella piega crea la nervatura laterale tipica della samosa e l'aiuta a stare in piedi durante la frittura — ripetete con il resto. Scaldate l'olio per friggere a 150°C (più basso di quanto vi aspettiate, ma la salita lenta è ciò che dà alla crosta le sue bolle), tuffate le samose in lotti di 3 o 4 e friggete 6–7 minuti rigirandole con delicatezza, finché non sono di un giallo pallido, alzate la temperatura a 180°C e friggete altri 3–4 minuti fino a un dorato profondo e una vera croccantezza, scolando su griglia e servendo calde con chutney di tamarindo e di menta.",

'ko': "기를 박력분, 아즈완 씨, 소금에 손가락 끝으로 비벼 거친 빵가루 같은 상태가 될 때까지 섞는다 — 이 지방의 양이 사모사 껍질에 그 거품지고 비스킷처럼 바삭한 식감을 준다 — 찬물을 1큰술씩 더하며, 차파티보다 부드럽고 빵 반죽보다 단단한, 매끄럽고 단단한 반죽이 될 때까지 치댄 다음 덮어 30분 휴지시킨다. 감자는 껍질째 막 익을 정도까지 삶고, 물기 빼서 껍질을 벗기고, 포크 뒷면으로 거칠게 으깬다 (매끈한 매시드가 아니라 식감이 살아있어야 한다); 넓은 팬에 기름을 데우고 쿠민 씨를 넣어 향을 일으키고, 생강과 청양고추를 30초 볶은 다음, 마른 향신료들을 넣고 짧게 볶고, 감자, 완두, 소금, 암추르, 고수를 넣고 4–5분간 향신료가 모든 조각에 잘 묻도록 뒤집어가며 익힌다 — 빚기 전에 실온까지 식힌다. 반죽을 8개의 공으로 나누고, 하나를 약 18 cm 길이의 얇은 타원으로 밀고, 가운데를 잘라 반원 두 개를 만든다; 반원 하나를 가져와 직선 가장자리에 가는 물선을 그리고, 직선의 두 꼭짓점을 1 cm 겹치게 모아 원뿔로 접은 다음 이음매를 단단히 꼬집어 봉한다. 원뿔을 한 손에 잡고 감자 속을 3/4까지 채운 다음, 열린 가장자리를 한쪽에서 작은 주름을 만들어 접고 젖은 손가락으로 가장자리를 완전히 봉한다 — 이 작은 주름이 사모사 특유의 옆선 능선을 만들고, 튀길 때 사모사를 곧추 세우는 역할도 한다 — 나머지도 같은 방식으로 만든다. 튀김유를 150°C로 가열한다 (생각보다 낮지만, 이 느린 온도 상승이 껍질에 그 거품 같은 무늬를 만들어준다), 사모사를 3~4개씩 기름에 넣고 부드럽게 뒤집으며 6–7분 옅은 황금색이 될 때까지 튀긴 다음, 온도를 180°C로 올려 3–4분 더 짙은 황금색이 나고 제대로 바삭해질 때까지 튀기고, 망에 건져 기름을 빼고 따뜻한 채로 타마린드 처트니와 민트-고수 처트니와 함께 낸다.",

'hi': "उँगलियों के पोरों से घी को मैदा, अजवायन और नमक के साथ इस तरह रगड़ें कि मिश्रण मोटे ब्रेडक्रंब जैसा हो जाए — यह जो वसा है, यही समोसे की पपड़ी को वो बबल-दार, बिस्कुट जैसी कुरकुरी सूरत देती है — ठंडा पानी एक-एक बड़ा चम्मच डाल कर सख़्त और चिकना आटा गूँधें (चपाती से नर्म पर ब्रेड के आटे से सख़्त), और ढक कर 30 मिनट आराम दें। आलू को छिलके सहित बस-बस गलने तक उबालें, छान कर छिलका उतारें, फिर काँटे की पीठ से मोटे-मोटे चूरें (आपको texture चाहिए, mash नहीं); एक चौड़े पैन में तेल गरम करें, जीरा डालें और चटकने दें, फिर अदरक और हरी मिर्च 30 सेकंड के लिए डालें, सूखे मसाले डाल कर हलका भूनें, फिर आलू, मटर, नमक, अमचूर और धनिया डाल कर 4–5 मिनट चलाते रहें जब तक मसाला हर टुकड़े पर चढ़ न जाए — शेप करने से पहले कमरे के तापमान पर ठंडा करें। आटे को 8 गोले बनाएँ, एक गोला लगभग 18 सेमी लंबे पतले अंडाकार में बेलें, फिर बीच से काट कर दो अर्धवृत्त बनाएँ; एक अर्धवृत्त लें, सीधी धार पर पानी की एक पतली रेखा ब्रश करें, और सीधी धार के दो कोनों को 1 सेमी ओवरलैप करते हुए जोड़ कर एक कोन बनाएँ, जोड़ को कस कर दबा कर सील करें। एक हाथ में कोन पकड़ें, आलू को तीन-चौथाई तक भरें, फिर खुली धार को एक तरफ़ छोटी सी प्लीट डाल कर मोड़ें और गीली उँगली से किनारा पूरी तरह बंद कर दें — यही छोटी प्लीट समोसे को उसकी पहचान वाली साइड रेज देती है और तलते वक़्त उसे खड़ा रहने में मदद करती है — बाक़ी भी इसी तरह बनाएँ। तलने का तेल 150°C तक गरम करें (आपकी अपेक्षा से कम, पर यही धीमी चढ़ाई पपड़ी पर बबल लाती है), समोसे को 3 या 4 के बैचों में तेल में डालें और हलके से पलटते हुए 6–7 मिनट तक हलका सुनहरा रंग आने तक तलें, आँच को 180°C तक बढ़ाएँ और 3–4 मिनट और तलें, जब तक गहरा सुनहरा और सही मायने में कुरकुरे न हो जाएँ, जाली पर निकाल कर तेल छानें और गरम-गरम इमली की चटनी और पुदीना-धनिया चटनी के साथ परोसें।",
}

FEATURE_CARDS = {
'en': '[{icon:"🌾", t:"Fat = blistered shell", d:"The amount of ghee is what gives samosa its biscuit crunch"}, {icon:"🥔", t:"Crush, don\'t mash", d:"Forked coarse texture — never a smooth puree"}, {icon:"📐", t:"Cone, then pleat", d:"Half-circle → cone → tucked pleat = the signature side ridge"}, {icon:"🔥", t:"Two-stage frying", d:"150°C for the blisters; 180°C for the colour"}]',
'ro': '[{icon:"🌾", t:"Grăsime = coajă băltită", d:"Cantitatea de ghee este ce dă samosa-ului crocantul de biscuit"}, {icon:"🥔", t:"Strivește, nu pasează", d:"Textură grosieră de furculiță — niciodată piure"}, {icon:"📐", t:"Con, apoi cută", d:"Semicerc → con → cută = nervura laterală caracteristică"}, {icon:"🔥", t:"Prăjire în două etape", d:"150°C pentru băltire; 180°C pentru culoare"}]',
'es': '[{icon:"🌾", t:"Grasa = cáscara abullonada", d:"La cantidad de ghee da a la samosa su crujiente de bizcocho"}, {icon:"🥔", t:"Romper, no aplastar", d:"Textura gruesa con tenedor — nunca puré liso"}, {icon:"📐", t:"Cono, después pliegue", d:"Semicírculo → cono → pliegue = la cresta lateral"}, {icon:"🔥", t:"Fritura en dos etapas", d:"150°C para las burbujas; 180°C para el color"}]',
'fr': '[{icon:"🌾", t:"Gras = coque boursouflée", d:"La quantité de ghee donne au samoussa sa croustillance de biscuit"}, {icon:"🥔", t:"Écraser, pas réduire", d:"Texture grossière à la fourchette — jamais en purée"}, {icon:"📐", t:"Cône, puis pli", d:"Demi-cercle → cône → pli = l\'arête latérale signature"}, {icon:"🔥", t:"Friture en deux temps", d:"150°C pour les cloques ; 180°C pour la couleur"}]',
'de': '[{icon:"🌾", t:"Fett = blasige Hülle", d:"Die Menge Ghee gibt der Samosa ihre Keks-Knusprigkeit"}, {icon:"🥔", t:"Zerdrücken, nicht pürieren", d:"Grobe Gabel-Textur — niemals ein glattes Püree"}, {icon:"📐", t:"Kegel, dann Falte", d:"Halbkreis → Kegel → Falte = die typische Seitenkante"}, {icon:"🔥", t:"Frittieren in zwei Stufen", d:"150°C für die Blasen; 180°C für die Farbe"}]',
'pt': '[{icon:"🌾", t:"Gordura = casca empolada", d:"A quantidade de ghee dá à samosa o seu estaladiço de biscoito"}, {icon:"🥔", t:"Esmagar, não passar", d:"Textura grosseira de garfo — nunca puré liso"}, {icon:"📐", t:"Cone, depois prega", d:"Meia-lua → cone → prega = a nervura lateral característica"}, {icon:"🔥", t:"Fritura em duas etapas", d:"150°C para as bolhas; 180°C para a cor"}]',
'ru': '[{icon:"🌾", t:"Жир = пузырчатая оболочка", d:"Количество ги даёт самосе её бисквитную хрусткость"}, {icon:"🥔", t:"Размять, а не пюрировать", d:"Грубая текстура вилкой — никогда гладкое пюре"}, {icon:"📐", t:"Конус, потом складка", d:"Полукруг → конус → складка = характерное боковое ребро"}, {icon:"🔥", t:"Жарка в два этапа", d:"150°C для пузырей; 180°C для цвета"}]',
'ar': '[{icon:"🌾", t:"الدهن = قشرة فقاعية", d:"كمية السمن هي ما تعطي السمبوسة قرمشتها كالبسكويت"}, {icon:"🥔", t:"اهرس بخشونة لا تنعّم", d:"قوام شوكة خشن — أبداً ليس بوريه ناعم"}, {icon:"📐", t:"مخروط ثم طية", d:"نصف دائرة → مخروط → طية = الحافة الجانبية المميّزة"}, {icon:"🔥", t:"قلي على مرحلتين", d:"150°م للفقاعات؛ 180°م للون"}]',
'zh': '[{icon:"🌾", t:"油 = 起泡的外壳", d:"酥油的份量给 samosa 那种饼干般的酥脆"}, {icon:"🥔", t:"压碎，别打成泥", d:"叉背粗碎口感 — 不能是光滑的土豆泥"}, {icon:"📐", t:"先成锥，再打褶", d:"半圆 → 圆锥 → 褶 = 标志性的侧棱"}, {icon:"🔥", t:"两段式油炸", d:"150°C 起泡；180°C 上色"}]',
'ja': '[{icon:"🌾", t:"油 = 波打つ皮", d:"ギーの量こそが、サモサにビスケットのような歯ごたえを与える"}, {icon:"🥔", t:"潰すが、ピューレにしない", d:"フォーク粗目の食感 — 決して滑らかなマッシュではない"}, {icon:"📐", t:"コーン、そして折り込み", d:"半円 → コーン → 折り込み = 特徴的な側面の稜線"}, {icon:"🔥", t:"二段階の揚げ", d:"150℃ で気泡、180℃ で色"}]',
'tr': '[{icon:"🌾", t:"Yağ = kabarcıklı kabuk", d:"Ghee miktarı samosaya bisküvi gibi çıtırlık verir"}, {icon:"🥔", t:"Ez, püre yapma", d:"Çatal arkasıyla iri doku — asla pürüzsüz püre değil"}, {icon:"📐", t:"Önce koni, sonra kıvrım", d:"Yarım daire → koni → kıvrım = imza yan sırt"}, {icon:"🔥", t:"İki aşamalı kızartma", d:"150°C kabarcıklar için; 180°C renk için"}]',
'it': '[{icon:"🌾", t:"Grasso = guscio increspato", d:"La quantità di ghee dà alla samosa la croccantezza da biscotto"}, {icon:"🥔", t:"Schiacciare, non frullare", d:"Texture grossolana con la forchetta — mai purè liscio"}, {icon:"📐", t:"Cono, poi piega", d:"Semicerchio → cono → piega = la nervatura laterale tipica"}, {icon:"🔥", t:"Frittura in due tempi", d:"150°C per le bolle; 180°C per il colore"}]',
'ko': '[{icon:"🌾", t:"지방 = 거품 진 껍질", d:"기의 양이 사모사에 비스킷 같은 바삭함을 준다"}, {icon:"🥔", t:"으깨되, 매시는 아니게", d:"포크로 거친 식감 — 매끈한 퓌레 아님"}, {icon:"📐", t:"콘 먼저, 그다음 주름", d:"반원 → 콘 → 주름 = 시그니처 옆 능선"}, {icon:"🔥", t:"두 단계 튀기기", d:"150°C 거품을 위해; 180°C 색을 위해"}]',
'hi': '[{icon:"🌾", t:"वसा = बबल वाली परत", d:"घी की मात्रा ही समोसे को बिस्कुट जैसा कुरकुरापन देती है"}, {icon:"🥔", t:"चूरें, मसलें नहीं", d:"काँटे से मोटा texture — कभी भी चिकना mash नहीं"}, {icon:"📐", t:"पहले कोन, फिर प्लीट", d:"अर्धवृत्त → कोन → प्लीट = पहचान वाली साइड रेज"}, {icon:"🔥", t:"दो चरण की तलाई", d:"150°C बबल के लिए; 180°C रंग के लिए"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*208,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 208 (Samosa): {rec_end-rec_start} → {len(new_recipe_block)} chars (was 18 → 5 steps)")
