#!/usr/bin/env python3
"""Rewrite recipe 200 (Lasagne alla Bolognese): 14 → 5 steps; add 4 featureCards."""
import re

LANGS = ['ro','en','es','fr','de','pt','ru','ar','zh','ja','tr','it','ko','hi']

HOWISMADE = {
'en': "Render the pancetta gently in a heavy pot with a splash of olive oil over medium-low heat for 5 minutes until the fat runs clear, add the chopped soffritto (onion, carrot, celery) and cook 10 minutes until soft and just gilded at the edges, then crumble in both meats and brown them properly — patience: do not stir for the first 3 minutes, then break them up and cook 10 more minutes until the pan bottom is deeply caramelised. Pour in the wine, scrape the fond from the pan with a wooden spoon and reduce by half, then add the tomatoes, the milk (the Bolognese signature — it rounds the acid and tightens the texture), the bay leaf and a teaspoon of salt; bring to a bare simmer, partially cover, and cook on the lowest possible heat for at least 2 hours and ideally 3, stirring occasionally and adding a splash of water if it threatens to dry — the finished ragù should be glossy, deep brown-red and almost a paste, never a soup. While the ragù finishes, make the béchamel: melt the butter, whisk in the flour for 2 minutes without colour, pour in the warm milk in a slow stream while whisking and simmer 5 minutes until thick, then season with salt and a generous grating of nutmeg. If using dried lasagne sheets blanch them in salted boiling water for a minute and lay on damp tea towels — fresh sheets go in raw — heat the oven to 180°C and butter a 25×35 cm baking dish, then spread a thin layer of béchamel on the bottom, then a layer of pasta, then ragù, then béchamel, then a snowy dusting of Parmigiano, and repeat until you have used everything (six to seven layers is the Bolognese target), finishing with béchamel and a heavier shower of Parmigiano. Bake 35–40 minutes until the top is bronzed and bubbling, then rest 20 minutes before cutting — lasagne sliced hot slides apart, lasagne rested holds its layers.",

'ro': "Topește pancetta blând într-o oală groasă cu un strop de ulei de măsline pe foc mediu-mic 5 minute până când grăsimea iese limpede, adaugă soffritto tocat (ceapă, morcov, țelină) și gătește 10 minute până e moale și abia aurit la margini, apoi sfărâmă ambele cărnuri și rumenește-le bine — răbdare: nu amesteca în primele 3 minute, apoi sparge-le și gătește încă 10 minute până când fundul tigăii este adânc caramelizat. Toarnă vinul, răzui glazura de pe fundul tigăii cu o lingură de lemn și redu la jumătate, apoi adaugă roșiile, laptele (semnătura bologneză — rotunjește aciditatea și strânge textura), foaia de dafin și o linguriță de sare; adu la o fierbere abia perceptibilă, acoperă parțial și gătește pe focul cel mai mic posibil cel puțin 2 ore, ideal 3, amestecând ocazional și adăugând un strop de apă dacă amenință să se usuce — ragù-ul finalizat trebuie să fie lucios, brun-roșu profund și aproape o pastă, niciodată o supă. Cât se termină ragù-ul, fă béchamel-ul: topește untul, bate făina 2 minute fără culoare, toarnă laptele cald într-un fir lent în timp ce bați și fierbe 5 minute până se îngroașă, apoi asezonează cu sare și o rașpă generoasă de nucșoară. Dacă folosești foi uscate de lasagne, opărește-le în apă fiartă cu sare un minut și pune-le pe prosoape umede — foile proaspete intră crude — încălzește cuptorul la 180°C și unge cu unt un vas de copt 25×35 cm, apoi întinde un strat subțire de béchamel pe fund, apoi un strat de paste, apoi ragù, apoi béchamel, apoi o pulbere de nea de Parmigiano, și repetă până folosești totul (șase-șapte straturi este ținta bologneză), terminând cu béchamel și o ploaie mai abundentă de Parmigiano. Coace 35–40 minute până când partea de sus este bronzată și bolborosește, apoi odihnește 20 de minute înainte de tăiere — lasagna tăiată fierbinte se desface, lasagna odihnită își ține straturile.",

'es': "Renderiza la pancetta suavemente en una olla pesada con un chorrito de aceite de oliva a fuego medio-bajo durante 5 minutos hasta que la grasa salga clara, añade el sofrito picado (cebolla, zanahoria, apio) y cocina 10 minutos hasta que esté blando y apenas dorado en los bordes, después desmenuza ambas carnes y dóralas bien — paciencia: no remuevas durante los primeros 3 minutos, después rómpelas y cocina 10 minutos más hasta que el fondo de la sartén esté profundamente caramelizado. Vierte el vino, raspa la película del fondo con una cuchara de madera y reduce a la mitad, después añade los tomates, la leche (la firma boloñesa — redondea el ácido y aprieta la textura), la hoja de laurel y una cucharadita de sal; lleva a un hervor apenas perceptible, tapa parcialmente y cocina al fuego más bajo posible durante al menos 2 horas, idealmente 3, removiendo de vez en cuando y añadiendo un chorrito de agua si amenaza con secarse — el ragù terminado debe ser brillante, marrón-rojo profundo y casi una pasta, nunca una sopa. Mientras el ragù termina, haz la bechamel: derrite la mantequilla, bate la harina durante 2 minutos sin color, vierte la leche caliente en un hilo lento mientras bates y cuece 5 minutos hasta que esté espesa, después sazona con sal y una ralladura generosa de nuez moscada. Si usas láminas secas de lasaña, escáldalas en agua hirviendo salada un minuto y colócalas en paños húmedos — las láminas frescas van crudas — calienta el horno a 180°C y unta un molde de 25×35 cm con mantequilla, después extiende una capa fina de bechamel en el fondo, después una capa de pasta, después ragù, después bechamel, después una nevada de Parmigiano, y repite hasta que hayas usado todo (seis a siete capas es el objetivo boloñés), terminando con bechamel y una lluvia más abundante de Parmigiano. Hornea 35–40 minutos hasta que la parte de arriba esté bronceada y burbujeante, después reposa 20 minutos antes de cortar — la lasaña cortada caliente se desliza, la lasaña reposada mantiene sus capas.",

'fr': "Faites fondre la pancetta doucement dans une cocotte épaisse avec un filet d'huile d'olive à feu doux-moyen pendant 5 minutes jusqu'à ce que la graisse coule claire, ajoutez le soffritto haché (oignon, carotte, céleri) et faites cuire 10 minutes jusqu'à ce que ce soit fondant et tout juste doré sur les bords, puis émiettez les deux viandes et faites-les bien dorer — patience : ne remuez pas pendant les 3 premières minutes, puis cassez-les et faites cuire 10 minutes de plus jusqu'à ce que le fond de la cocotte soit profondément caramélisé. Versez le vin, grattez les sucs du fond avec une cuillère en bois et faites réduire de moitié, puis ajoutez les tomates, le lait (la signature bolognaise — il arrondit l'acide et tend la texture), la feuille de laurier et une cuillère à café de sel ; portez à frémissement à peine perceptible, couvrez à moitié, et faites cuire au feu le plus doux possible pendant au moins 2 heures, idéalement 3, en remuant de temps en temps et en ajoutant un filet d'eau si ça menace de sécher — le ragù terminé doit être brillant, brun-rouge profond et presque une pâte, jamais une soupe. Pendant que le ragù finit, faites la béchamel : faites fondre le beurre, fouettez la farine pendant 2 minutes sans coloration, versez le lait chaud en filet lent tout en fouettant et faites frémir 5 minutes jusqu'à épaississement, puis assaisonnez de sel et d'une râpée généreuse de muscade. Si vous utilisez des feuilles de lasagne sèches, blanchissez-les dans de l'eau bouillante salée pendant une minute et posez-les sur des torchons humides — les feuilles fraîches vont crues — chauffez le four à 180°C et beurrez un plat de 25×35 cm, puis étalez une fine couche de béchamel au fond, puis une couche de pâte, puis du ragù, puis de la béchamel, puis une neige de Parmigiano, et répétez jusqu'à ce que vous ayez tout utilisé (six à sept couches est l'objectif bolognais), en terminant par de la béchamel et une averse plus généreuse de Parmigiano. Cuisez 35 à 40 minutes jusqu'à ce que le dessus soit bronzé et bouillonne, puis laissez reposer 20 minutes avant de couper — la lasagne coupée chaude glisse à part, la lasagne reposée tient ses couches.",

'de': "Lassen Sie die Pancetta sanft in einem schweren Topf mit einem Schuss Olivenöl bei mittlerer bis niedriger Hitze 5 Minuten auslassen, bis das Fett klar wird, geben Sie das gehackte Soffritto (Zwiebel, Karotte, Sellerie) hinein und garen Sie 10 Minuten, bis es weich und an den Rändern gerade vergoldet ist, dann krümeln Sie beide Sorten Fleisch hinein und bräunen Sie sie richtig — Geduld: in den ersten 3 Minuten nicht rühren, dann zerteilen und 10 weitere Minuten garen, bis der Pfannenboden tief karamellisiert ist. Gießen Sie den Wein an, kratzen Sie die Bratrückstände mit einem Holzlöffel ab und reduzieren Sie auf die Hälfte, dann fügen Sie die Tomaten, die Milch (die Bologneser Signatur — sie rundet die Säure ab und strafft die Textur), das Lorbeerblatt und einen Teelöffel Salz hinzu; bringen Sie alles zum sanften Köcheln, decken Sie teilweise zu und garen Sie bei niedrigster möglicher Hitze mindestens 2 Stunden, idealerweise 3, gelegentlich umrühren und einen Spritzer Wasser hinzufügen, wenn es zu trocken zu werden droht — das fertige Ragù sollte glänzend, tief braun-rot und fast eine Paste sein, nie eine Suppe. Während das Ragù fertiggart, machen Sie die Béchamel: die Butter schmelzen, das Mehl 2 Minuten ohne Farbe einrühren, die warme Milch in einem dünnen Strahl unter Rühren angießen und 5 Minuten köcheln bis es dick ist, dann mit Salz und einer großzügigen Prise Muskatnuss würzen. Wenn Sie getrocknete Lasagneblätter verwenden, blanchieren Sie sie in gesalzenem kochendem Wasser eine Minute und legen Sie sie auf feuchte Tücher — frische Blätter kommen roh hinein — heizen Sie den Ofen auf 180°C und buttern Sie eine 25×35 cm Form, dann verteilen Sie eine dünne Schicht Béchamel auf den Boden, dann eine Schicht Pasta, dann Ragù, dann Béchamel, dann eine schneeige Schicht Parmigiano, und wiederholen Sie das, bis Sie alles aufgebraucht haben (sechs bis sieben Schichten ist das Bologneser Ziel), abschließend mit Béchamel und einem reichlicheren Schauer Parmigiano. 35–40 Minuten backen, bis die Oberseite bronziert und blubbernd ist, dann 20 Minuten ruhen lassen vor dem Schneiden — heiß geschnittene Lasagne rutscht auseinander, geruhte Lasagne behält ihre Schichten.",

'pt': "Derreta a pancetta suavemente numa panela pesada com um fio de azeite em lume médio-baixo durante 5 minutos até a gordura sair clara, junte o sofrito picado (cebola, cenoura, aipo) e cozinhe 10 minutos até estar macio e mal dourado nas bordas, depois esmigalhe ambas as carnes e doure-as bem — paciência: não mexa nos primeiros 3 minutos, depois separe-as e cozinhe mais 10 minutos até o fundo da panela estar profundamente caramelizado. Verta o vinho, raspe o fundo com uma colher de pau e reduza a metade, depois junte os tomates, o leite (a assinatura bolonhesa — arredonda a acidez e aperta a textura), a folha de louro e uma colher de chá de sal; leve a uma fervura quase imperceptível, tape parcialmente, e cozinhe no lume mais baixo possível pelo menos 2 horas, idealmente 3, mexendo ocasionalmente e juntando um fio de água se ameaçar secar — o ragù terminado deve ser brilhante, castanho-vermelho profundo e quase uma pasta, nunca uma sopa. Enquanto o ragù termina, faça a béchamel: derreta a manteiga, mexa a farinha durante 2 minutos sem cor, verta o leite morno num fio lento enquanto mexe e ferva 5 minutos até estar espesso, depois tempere com sal e uma raspagem generosa de noz-moscada. Se usar folhas secas de lasanha, escalde-as em água a ferver salgada um minuto e coloque-as em panos húmidos — as folhas frescas vão cruas — aqueça o forno a 180°C e unte uma forma de 25×35 cm, depois espalhe uma camada fina de béchamel no fundo, depois uma camada de massa, depois ragù, depois béchamel, depois um polvilho nevado de Parmigiano, e repita até ter usado tudo (seis a sete camadas é o alvo bolonhês), terminando com béchamel e uma chuva mais abundante de Parmigiano. Asse 35–40 minutos até o topo estar bronzeado e a borbulhar, depois deixe descansar 20 minutos antes de cortar — a lasanha cortada quente desliza, a lasanha repousada mantém as suas camadas.",

'ru': "Вытопите панчетту мягко в тяжёлой кастрюле с каплей оливкового масла на среднем-низком огне 5 минут, пока жир не станет прозрачным, добавьте нарубленное софритто (лук, морковь, сельдерей) и готовьте 10 минут, пока не размягчится и края не подзолотятся, затем раскрошите оба вида мяса и хорошо подрумяньте — терпение: первые 3 минуты не мешайте, затем разломайте и готовьте ещё 10 минут, пока дно сковороды глубоко не карамелизуется. Влейте вино, соскребите осадок с дна деревянной ложкой и уварите вдвое, затем добавьте помидоры, молоко (фирменная нота Болоньи — округляет кислоту и стягивает текстуру), лавровый лист и чайную ложку соли; доведите до едва заметного кипения, частично накройте, и варите на самом слабом возможном огне минимум 2 часа, идеально 3, изредка помешивая и добавляя каплю воды, если грозит высохнуть — готовый рагу должен быть глянцевым, глубокого коричнево-красного цвета и почти пастой, никогда не супом. Пока рагу заканчивается, сделайте бешамель: растопите масло, вмешайте муку на 2 минуты без цвета, влейте тёплое молоко тонкой струйкой при помешивании и варите 5 минут до густоты, затем приправьте солью и щедрой щепоткой мускатного ореха. Если используете сухие листы лазаньи, бланшируйте их в подсоленной кипящей воде минуту и выложите на влажные полотенца — свежие листы идут сырыми — нагрейте духовку до 180°C и смажьте маслом форму 25×35 см, затем распределите тонкий слой бешамеля на дне, затем слой пасты, затем рагу, затем бешамель, затем снежную пыль пармезана, и повторите, пока не используете всё (шесть-семь слоёв — это болонская цель), завершите бешамелем и более обильным душем пармезана. Запекайте 35–40 минут, пока верх не станет бронзовым и не забулькает, затем дайте отдохнуть 20 минут перед нарезкой — горячая нарезанная лазанья расползается, отдохнувшая держит слои.",

'ar': "أذِب البانشيتا برفق في قدر ثقيل مع رشة زيت الزيتون على نار متوسطة-منخفضة لمدة 5 دقائق حتى تخرج الدهون صافية، أضف الصوفريتو المفروم (بصل، جزر، كرفس) واطبخ 10 دقائق حتى يصبح طرياً ومذهباً عند الحواف، ثم فتت اللحمين وحمّرهما بشكل صحيح — صبر: لا تحرّك خلال أول 3 دقائق، ثم فتت واطبخ 10 دقائق إضافية حتى يصبح قعر القدر متكرملاً بعمق. اسكب النبيذ، اكشط طبقة الفوند من القعر بملعقة خشبية وقلّل إلى النصف، ثم أضف الطماطم، الحليب (توقيع بولوني — يدوّر الحمضية ويشدّ القوام)، ورقة الغار وملعقة صغيرة من الملح؛ أوصلها إلى غليان بالكاد محسوس، غطّ جزئياً، واطبخ على أهدأ نار ممكنة لمدة لا تقل عن ساعتين، ويفضل 3 ساعات، مع التقليب من حين لآخر وإضافة رشة ماء إذا هددت بالجفاف — الراغو الجاهز يجب أن يكون لامعاً، أحمر-بنياً عميقاً وشبه عجين، ليس شوربة. أثناء انتهاء الراغو، حضّر البشاميل: أذِب الزبدة، اخفق الطحين لمدة دقيقتين بدون لون، اسكب الحليب الدافئ بخيط بطيء أثناء الخفق واطهُ 5 دقائق حتى يثخن، ثم تبّل بالملح وبرشة سخية من جوزة الطيب. إذا استخدمت ألواح اللازانيا الجافة، اسلقها في ماء مغلي مملح لمدة دقيقة وضعها على مناشف مبللة — الألواح الطازجة تذهب نيئة — سخّن الفرن إلى 180°م وادهن صحن خبز 25×35 سم بالزبدة، ثم افرد طبقة رقيقة من البشاميل في القاع، ثم طبقة من الباستا، ثم راغو، ثم بشاميل، ثم رشة بيضاء من البارميجيانو، وكرّر حتى تستخدم كل شيء (ست إلى سبع طبقات هو الهدف البولوني)، منتهياً ببشاميل وبشاميل أكثر سخاء من البارميجيانو. اخبز 35–40 دقيقة حتى يصبح السطح برونزياً ويفور، ثم أرحه 20 دقيقة قبل التقطيع — اللازانيا المقطعة وهي ساخنة تنزلق، أما المرتاحة فتحافظ على طبقاتها.",

'zh': "把意式咸猪肉（pancetta）在厚锅里加一点橄榄油，以中小火慢慢出油 5 分钟，直到油变清，加入切碎的 soffritto（洋葱、胡萝卜、芹菜），煮 10 分钟，直到变软、边缘微微发金，再把两种肉都掰碎放进去煎香——耐心：前 3 分钟不要动它，再用铲子把肉打散，再煎 10 分钟，直到锅底深深焦化。倒入葡萄酒，用木勺把锅底的 fond 刮起来，收汁到一半，然后加入番茄、牛奶（这就是 Bolognese 的标志——它能圆润酸度、收紧口感）、月桂叶和 1 茶匙盐；煮到刚冒泡的程度，半盖，以最小可能的火炖至少 2 小时，最好 3 小时，时不时搅一下，如果有干掉的迹象就加一点水——成品 ragù 应当是有光泽的、深红棕色的，几乎像一团酱，绝不是汤。ragù 快好的时候做 béchamel：把黄油融化，加入面粉打 2 分钟但不要让它上色，倒入温热的牛奶，一边慢慢倒一边打，煮 5 分钟到变稠，最后用盐和大量现磨肉豆蔻调味。如果用干的千层面皮，在加盐的沸水里焯 1 分钟，然后摊在湿的茶巾上——鲜面皮直接生用——把烤箱加热到 180°C，给一只 25×35 cm 的烤盘抹上黄油，在底部铺一层薄薄的 béchamel，然后一层面皮、一层 ragù、一层 béchamel、再撒一层雪一样的 Parmigiano，重复这个动作直到所有材料用完（6–7 层是 Bolognese 的目标），最上面以 béchamel 收尾，再撒上更厚的一层 Parmigiano。烤 35–40 分钟，直到表面变得古铜色并冒泡，然后静置 20 分钟再切——刚出炉就切的千层面会散开，静置过的能保持层次。",

'ja': "パンチェッタを厚手の鍋にオリーブ油を少々加えて中弱火で 5 分、脂が透き通るまでゆっくり脂を引き出し、刻んだソフリット（玉ねぎ、にんじん、セロリ）を加えて 10 分、しんなりして縁が金色に色付くまで炒め、それから 2 種の肉をほぐし入れてきちんと焼き色を付ける — 忍耐：最初の 3 分は触らない、それから崩してさらに 10 分、鍋底が深くキャラメル化するまで炒める。ワインを注いで、木べらで鍋底のフォンを溶かし、半量まで煮詰めたら、トマト、牛乳（これがボロネーゼの署名 — 酸を丸くし、テクスチャーを引き締める）、ベイリーフ、塩小さじ 1 を加える；ぎりぎり沸騰しない火加減にし、半蓋で、可能な限り弱火で最低 2 時間、できれば 3 時間煮込み、時々かき混ぜながら、乾きそうなら水を少々足す — 完成したラグーは艶があり、深い茶赤色で、ほぼペースト状、決してスープではない。ラグーが仕上がっている間にベシャメルを作る：バターを溶かし、小麦粉を 2 分間、色を付けずに混ぜ、温めた牛乳をゆっくりと注ぎながら泡立て器で混ぜ、5 分間煮詰めて濃度をつけ、塩とたっぷりすりおろしたナツメグで味付け。乾燥ラザニアシートを使うなら、塩を入れた湯で 1 分茹で、湿らせた布巾に並べる — フレッシュなシートはそのままで使う — オーブンを 180℃ に予熱し、25×35 cm の耐熱皿にバターを塗り、底に薄くベシャメル、次にパスタ、次にラグー、次にベシャメル、次に雪のようにパルミジャーノを振り、すべてを使い切るまで繰り返す（6〜7 層がボローニャの目標）、最後はベシャメルとさらに多めのパルミジャーノで仕上げ。35〜40 分焼き、表面が褐色になり、ふつふつと泡立つまで、その後 20 分休ませてから切る — 熱いまま切るとラザニアは崩れ、休ませると層を保つ。",

'tr': "Pancettayı zeytinyağı serpiştirilmiş ağır bir tencerede orta-düşük ateşte 5 dakika boyunca yağı berraklaşana dek yavaşça erit, doğranmış sofrito'yu (soğan, havuç, kereviz sapı) ekle ve 10 dakika boyunca yumuşayıp kenarları altın renge dönene dek pişir, sonra her iki kıymayı da içine ufalayıp düzgünce kahverengileştir — sabır: ilk 3 dakika karıştırma, sonra parçala ve 10 dakika daha, tava dibi derin karamel rengini alana dek pişir. Şarabı dök, ahşap kaşıkla tava dibindeki fondu kazı ve yarıya kadar uçur, sonra domatesleri, sütü (Bolonya'nın imzası — asidi yuvarlar ve dokuyu sıkar), defne yaprağını ve 1 çay kaşığı tuzu ekle; neredeyse algılanamayan bir kaynamaya getir, yarı örtülü olarak, mümkün olan en düşük ateşte en az 2 saat, ideal olarak 3 saat pişir, arada karıştırarak ve kurumaya yüz tutarsa biraz su ekleyerek — biten ragù parlak, derin kahverengi-kırmızı ve neredeyse bir macun olmalı, asla bir çorba değil. Ragù tamamlanırken beşameli hazırla: tereyağını erit, unu 2 dakika boyunca renk almadan çırp, ılık sütü ince bir akıntı halinde dökerken çırp ve 5 dakika koyulaşana dek kaynat, sonra tuz ve cömert bir muskat rendesiyle tatlandır. Kuru lazanya yaprakları kullanıyorsan tuzlu kaynar suda bir dakika haşla ve nemli mutfak bezlerine yerleştir — taze yapraklar çiğ olarak girer — fırını 180°C'ye ısıt ve 25×35 cm bir fırın kabını tereyağı ile yağla, sonra dibe ince bir beşamel katmanı yay, sonra bir kat hamur, sonra ragù, sonra beşamel, sonra karlı bir Parmigiano serpiştirme, ve her şeyi kullanana dek tekrarla (altı-yedi kat Bologna hedefidir), beşamel ve daha bol Parmigiano serpiştirmesiyle bitir. 35–40 dakika, üstü bronzlaşıp kabarana dek pişir, sonra kesmeden önce 20 dakika dinlendir — sıcakken kesilen lazanya dağılır, dinlenmiş olan katmanlarını tutar.",

'it': "Fate rendere la pancetta delicatamente in una pentola pesante con un filo di olio extravergine a fuoco medio-basso per 5 minuti finché il grasso non scorre chiaro, aggiungete il soffritto tritato (cipolla, carota, sedano) e cuocete 10 minuti finché non è morbido e appena dorato sui bordi, poi sbriciolate entrambe le carni e rosolatele come si deve — pazienza: non mescolate per i primi 3 minuti, poi spezzettatele e cuocete altri 10 minuti finché il fondo della pentola non è profondamente caramellato. Versate il vino, raschiate il fondo con un cucchiaio di legno e fate ridurre della metà, poi aggiungete i pomodori, il latte (la firma bolognese — arrotonda l'acidità e stringe la consistenza), l'alloro e un cucchiaino di sale; portate a un sobbollire appena percettibile, coprite parzialmente, e cuocete sul fuoco più basso possibile per almeno 2 ore, idealmente 3, mescolando ogni tanto e aggiungendo un filo d'acqua se minaccia di seccarsi — il ragù finito deve essere lucido, di un bruno-rosso profondo e quasi una pasta, mai una zuppa. Mentre il ragù finisce, preparate la besciamella: sciogliete il burro, sbattete la farina per 2 minuti senza colorire, versate il latte caldo a filo lento mentre sbattete e fate sobbollire 5 minuti finché non si addensa, poi condite con sale e una generosa grattata di noce moscata. Se usate sfoglie di lasagna secche sbollentatele in acqua bollente salata per un minuto e stendetele su strofinacci umidi — le sfoglie fresche vanno crude — scaldate il forno a 180°C e imburrate una pirofila 25×35 cm, poi stendete uno strato sottile di besciamella sul fondo, poi uno strato di pasta, poi ragù, poi besciamella, poi una spolverata nevosa di Parmigiano, e ripetete finché non avete usato tutto (sei-sette strati è l'obiettivo bolognese), terminando con besciamella e una più abbondante doccia di Parmigiano. Cuocete 35–40 minuti finché la superficie non è bronzata e gorgogliante, poi fate riposare 20 minuti prima di tagliare — la lasagna tagliata calda scivola via, la lasagna riposata tiene i suoi strati.",

'ko': "두꺼운 냄비에 올리브유 약간을 더해 중-약불에서 판체타를 5분간 천천히 기름이 맑게 빠질 때까지 렌더링하고, 다진 소프리토(양파, 당근, 셀러리)를 넣어 10분간 부드럽고 가장자리가 살짝 황금색이 될 때까지 익힌 다음, 두 가지 고기를 모두 부수어 넣고 제대로 갈색이 되게 굽는다 — 인내: 처음 3분간은 건드리지 말고, 그다음 부수어 10분 더, 팬 바닥이 깊이 캐러멜화될 때까지 굽는다. 와인을 붓고, 나무 주걱으로 팬 바닥의 폰드를 긁어 반으로 졸인 다음, 토마토, 우유(볼로녜제의 시그니처 — 산을 둥글게 하고 식감을 조여준다), 월계수잎, 소금 1작은술을 더한다; 거의 느껴지지 않는 약한 끓음으로 가져가고, 반쯤 뚜껑을 덮고, 가능한 가장 약한 불에서 최소 2시간, 이상적으로는 3시간 동안 가끔 저으며, 마르려고 하면 물을 약간 더하며 익힌다 — 완성된 라구는 윤기 있는, 진한 갈색-빨강이며 거의 페이스트 같은 상태여야 하지, 결코 수프가 아니다. 라구가 마무리되는 동안 베샤멜을 만든다: 버터를 녹이고, 밀가루를 2분간 색이 나지 않게 휘저은 뒤, 따뜻한 우유를 천천히 부으면서 휘젓고 5분간 진하게 졸인 다음, 소금과 넉넉한 너트맥 가루로 간한다. 마른 라자냐 시트를 사용하면 소금물 끓는 물에 1분 데쳐 젖은 행주에 펴 놓고 — 생 시트는 그대로 사용 — 오븐을 180°C로 예열하고 25×35 cm 베이킹 디시에 버터를 바른 다음, 바닥에 베샤멜을 얇게 펴고, 그다음 파스타 한 층, 그다음 라구, 그다음 베샤멜, 그다음 파르미지아노를 눈처럼 뿌리고, 모든 재료를 다 사용할 때까지 반복한다 (6–7층이 볼로녜제의 목표), 베샤멜로 마무리하고 파르미지아노를 더 넉넉히 뿌린다. 35–40분간 윗면이 청동색이 되고 거품이 일 때까지 굽고, 자르기 전에 20분 휴지한다 — 뜨거울 때 자른 라자냐는 흩어지고, 휴지한 라자냐는 층을 유지한다.",

'hi': "पैनसेटा को एक भारी बर्तन में ओलिव ऑयल की एक छिड़काव के साथ मध्यम-धीमी आँच पर 5 मिनट तक धीरे-धीरे रेंडर करें जब तक चर्बी साफ़ निकलने न लगे, कटा soffritto (प्याज़, गाजर, अजवाइन डंठल) डालें और 10 मिनट तक तब तक पकाएँ जब तक नर्म हो जाए और किनारे ज़रा सुनहरे हो जाएँ, फिर दोनों कीमे को कुचल कर डालें और अच्छी तरह भूनें — धैर्य: पहले 3 मिनट तक न चलाएँ, फिर तोड़ें और 10 मिनट और पकाएँ जब तक पैन का तला गहराई से कैरेमलाइज़ न हो जाए। शराब डालें, लकड़ी के चम्मच से तले की पपड़ी खुरचें और आधी तक रिड्यूस करें, फिर टमाटर, दूध (बोलोनीज़ की पहचान — यह खटास को गोल करता है और बनावट को कसता है), तेज़पत्ता और 1 छोटा चम्मच नमक डालें; बेहद हलकी उबाल पर लाएँ, आधी ढक कर, और सबसे संभव धीमी आँच पर कम से कम 2 घंटे, बेहतर 3 घंटे पकाएँ, बीच-बीच में चलाते रहें और अगर सूखने का खतरा हो तो थोड़ा पानी डालें — तैयार ragù चमकदार, गहरे भूरे-लाल और लगभग पेस्ट जैसा होना चाहिए, कभी सूप जैसा नहीं। ragù ख़त्म होते-होते béchamel बनाएँ: मक्खन पिघलाएँ, आटे को 2 मिनट तक बिना रंग के फेंटें, गरम दूध को एक धीमी धारा में डालते हुए फेंटें और 5 मिनट तक तब तक उबालें जब तक गाढ़ा न हो जाए, फिर नमक और एक उदार जायफल कद्दूकस से सीज़न करें। अगर सूखी lasagne शीट इस्तेमाल कर रहे हैं तो नमकीन उबलते पानी में 1 मिनट blanch करें और नम कपड़ों पर रखें — ताज़ी शीट कच्ची ही जाती हैं — ओवन को 180°C तक गरम करें और 25×35 सेमी बेकिंग डिश पर मक्खन लगाएँ, फिर तले पर béchamel की एक पतली परत, फिर पास्ता की एक परत, फिर ragù, फिर béchamel, फिर Parmigiano की बर्फ़-जैसी छिड़काव, और तब तक दोहराते रहें जब तक सब ख़त्म न हो जाए (छह-सात परतें बोलोनीज़ का लक्ष्य है), अंत में béchamel और Parmigiano की एक भारी बौछार। 35–40 मिनट तक तब तक बेक करें जब तक ऊपरी भाग कांस्य रंग का और बुलबुलाता हुआ न हो जाए, फिर काटने से पहले 20 मिनट आराम दें — गरम-गरम काटी लसैन्या बिखर जाती है, आराम दी हुई अपनी परतें संभाले रखती है।",
}

FEATURE_CARDS = {
'en': '[{icon:"⏰", t:"2–3 hour ragù", d:"Glossy, deep brown-red, almost a paste — never a soup"}, {icon:"🥛", t:"Milk in the ragù", d:"The Bolognese signature — rounds acid, tightens texture"}, {icon:"📚", t:"6–7 layers, no more", d:"The classic count from the Bologna canon"}, {icon:"🍴", t:"20-min rest before cutting", d:"Hot slices slide apart; rested slices hold"}]',
'ro': '[{icon:"⏰", t:"Ragù de 2–3 ore", d:"Lucios, brun-roșu profund, aproape o pastă — niciodată o supă"}, {icon:"🥛", t:"Lapte în ragù", d:"Semnătura bologneză — rotunjește aciditatea, strânge textura"}, {icon:"📚", t:"6–7 straturi, nu mai mult", d:"Numărul clasic din canonul Bolognei"}, {icon:"🍴", t:"20 min odihnit înainte de tăiat", d:"Feliile fierbinți se desfac; cele odihnite își țin forma"}]',
'es': '[{icon:"⏰", t:"Ragù de 2–3 horas", d:"Brillante, marrón-rojo profundo, casi una pasta — nunca una sopa"}, {icon:"🥛", t:"Leche en el ragù", d:"La firma boloñesa — redondea el ácido, aprieta la textura"}, {icon:"📚", t:"6–7 capas, no más", d:"El número clásico del canon de Bolonia"}, {icon:"🍴", t:"20 min de reposo antes de cortar", d:"Las porciones calientes se deslizan; las reposadas mantienen"}]',
'fr': '[{icon:"⏰", t:"Ragù de 2–3 heures", d:"Brillant, brun-rouge profond, presque une pâte — jamais une soupe"}, {icon:"🥛", t:"Du lait dans le ragù", d:"La signature bolognaise — arrondit l\'acide, tend la texture"}, {icon:"📚", t:"6–7 couches, pas plus", d:"Le décompte classique du canon bolognais"}, {icon:"🍴", t:"20 min de repos avant de couper", d:"Les tranches chaudes glissent ; reposées elles tiennent"}]',
'de': '[{icon:"⏰", t:"2–3 Stunden Ragù", d:"Glänzend, tief braun-rot, fast eine Paste — nie eine Suppe"}, {icon:"🥛", t:"Milch im Ragù", d:"Die Bologneser Signatur — rundet Säure ab, strafft die Textur"}, {icon:"📚", t:"6–7 Schichten, nicht mehr", d:"Die klassische Zahl aus dem Bologneser Kanon"}, {icon:"🍴", t:"20 Min Ruhe vor dem Schneiden", d:"Heiße Scheiben rutschen; geruhte halten ihre Form"}]',
'pt': '[{icon:"⏰", t:"Ragù de 2–3 horas", d:"Brilhante, castanho-vermelho profundo, quase uma pasta — nunca sopa"}, {icon:"🥛", t:"Leite no ragù", d:"A assinatura bolonhesa — arredonda o ácido, aperta a textura"}, {icon:"📚", t:"6–7 camadas, não mais", d:"A contagem clássica do cânone bolonhês"}, {icon:"🍴", t:"20 min de repouso antes de cortar", d:"Fatias quentes deslizam; repousadas mantêm forma"}]',
'ru': '[{icon:"⏰", t:"Рагу 2–3 часа", d:"Глянцевое, глубокое коричнево-красное, почти паста — никогда суп"}, {icon:"🥛", t:"Молоко в рагу", d:"Болонский фирменный приём — округляет кислоту, стягивает текстуру"}, {icon:"📚", t:"6–7 слоёв, не больше", d:"Классический счёт болонского канона"}, {icon:"🍴", t:"20 мин отдыха до нарезки", d:"Горячие куски расползаются; отдохнувшие держат форму"}]',
'ar': '[{icon:"⏰", t:"راغو لـ 2–3 ساعات", d:"لامع، أحمر-بنّي عميق، شبه عجين — أبداً ليس شوربة"}, {icon:"🥛", t:"حليب في الراغو", d:"توقيع بولوني — يدوّر الحمضية ويشدّ القوام"}, {icon:"📚", t:"6–7 طبقات، لا أكثر", d:"العد الكلاسيكي من قانون بولونيا"}, {icon:"🍴", t:"20 دقيقة راحة قبل التقطيع", d:"الشرائح الساخنة تنزلق؛ المرتاحة تحافظ على شكلها"}]',
'zh': '[{icon:"⏰", t:"2–3 小时 ragù", d:"有光泽，深红棕色，几乎像酱——绝不是汤"}, {icon:"🥛", t:"ragù 里要加牛奶", d:"Bolognese 的标志——圆润酸度，收紧口感"}, {icon:"📚", t:"6–7 层，不多不少", d:"Bologna 经典传统的层数"}, {icon:"🍴", t:"切前静置 20 分钟", d:"热的切散开；静置的能保持层次"}]',
'ja': '[{icon:"⏰", t:"2〜3 時間のラグー", d:"艶のある深い茶赤、ほぼペースト — 決してスープではない"}, {icon:"🥛", t:"ラグーに牛乳", d:"ボロネーゼの署名 — 酸を丸くしテクスチャーを引き締める"}, {icon:"📚", t:"6〜7 層、それ以上は無し", d:"ボローニャの古典的な層数"}, {icon:"🍴", t:"切る前 20 分の休ませ", d:"熱いまま切ると崩れる、休ませると層を保つ"}]',
'tr': '[{icon:"⏰", t:"2–3 saat ragù", d:"Parlak, derin kahverengi-kırmızı, neredeyse macun — asla çorba değil"}, {icon:"🥛", t:"Ragù\'da süt", d:"Bolonya imzası — asidi yuvarlar, dokuyu sıkar"}, {icon:"📚", t:"6–7 kat, daha fazla değil", d:"Bologna kanonunun klasik sayısı"}, {icon:"🍴", t:"Kesmeden önce 20 dk dinlenme", d:"Sıcakken kesilirse dağılır; dinlenmiş şeklini korur"}]',
'it': '[{icon:"⏰", t:"Ragù da 2–3 ore", d:"Lucido, bruno-rosso profondo, quasi una pasta — mai una zuppa"}, {icon:"🥛", t:"Latte nel ragù", d:"La firma bolognese — arrotonda l\'acido, stringe la consistenza"}, {icon:"📚", t:"6–7 strati, non di più", d:"Il conteggio classico del canone bolognese"}, {icon:"🍴", t:"20 min di riposo prima di tagliare", d:"Calda si sfila; riposata tiene i suoi strati"}]',
'ko': '[{icon:"⏰", t:"2–3시간 라구", d:"윤기 있고 진한 갈색-빨강, 거의 페이스트 — 결코 수프가 아님"}, {icon:"🥛", t:"라구에 우유", d:"볼로녜제의 시그니처 — 산을 둥글게, 식감을 조여준다"}, {icon:"📚", t:"6–7층, 더 이상은 안 됨", d:"볼로냐 정통의 고전 층수"}, {icon:"🍴", t:"자르기 전 20분 휴지", d:"뜨거운 슬라이스는 흩어지고, 휴지한 것은 층을 유지"}]',
'hi': '[{icon:"⏰", t:"2–3 घंटे का ragù", d:"चमकदार, गहरा भूरा-लाल, लगभग पेस्ट — कभी सूप नहीं"}, {icon:"🥛", t:"ragù में दूध", d:"बोलोनीज़ की पहचान — खटास को गोल करता है, बनावट को कसता है"}, {icon:"📚", t:"6–7 परतें, इससे ज़्यादा नहीं", d:"बोलोग्ना के क्लासिक कैनन की गिनती"}, {icon:"🍴", t:"काटने से पहले 20 मिनट आराम", d:"गरम स्लाइस बिखरते हैं; आराम दिए हुए परतें संभाले रखते हैं"}]',
}

src = open('public/js/recipes.js', encoding='utf-8').read()
m = re.search(r'^\s*\{\s*\n\s*id:\s*200,', src, re.M)
rec_start = m.start()
depth = 0; i = rec_start
while i < len(src):
    if src[i] == '{': depth += 1
    elif src[i] == '}':
        depth -= 1
        if depth == 0: rec_end = i + 1; break
    i += 1
recipe_block = src[rec_start:rec_end]
hm_match = re.search(r'(\s*)howIsMade:\s*\{', recipe_block)
hm_start = hm_match.start()

def js_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

how_lines = ['howIsMade: {']
for lc in LANGS: how_lines.append(f'      {lc}: {js_str(HOWISMADE[lc])},')
how_lines.append('    }')
new_howismade = '\n'.join(how_lines)
fc_lines = ['featureCards: {']
for lc in LANGS: fc_lines.append(f'      {lc}: {FEATURE_CARDS[lc]},')
fc_lines.append('    }')
new_featurecards = '\n'.join(fc_lines)

before_hm = recipe_block[:hm_start].rstrip()
new_recipe_block = before_hm + '\n    ' + new_howismade + ',\n    ' + new_featurecards + '\n  }'
new_src = src[:rec_start] + new_recipe_block + src[rec_end:]
open('public/js/recipes.js', 'w', encoding='utf-8').write(new_src)
print(f"Recipe 200 (Lasagne): {rec_end-rec_start} → {len(new_recipe_block)} chars")
